force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/Engagement_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Counterparties</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Joint_Counterparty__c.field-meta.xml
<CustomField>
    <fullName>Joint_Counterparty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Joint Counterparty</label>
    <referenceTo>Engagement_Counterparty__c</referenceTo>
    <relationshipLabel>Joint Bidders</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_CustomLookupLwcController.cls
public class HL_CustomLookupLwcController {
   // Method to fetch lookup search result   
    @AuraEnabled(cacheable=true)
    public static list<sObject> fetchLookupData(string searchKey , string sObjectApiName , String whereClauseFieldName) {    
        List < sObject > returnList = new List < sObject > ();

        string sWildCardText = '%' + searchKey + '%';
        string sQuery ;
        if(String.isNotBlank(whereClauseFieldName))
            sQuery = 'Select Id,Name,'+whereClauseFieldName+ (sObjectApiName == 'Engagement__c' ? ',(Select id from Engagement_Counterparties__r)':'') +' From ' + sObjectApiName + ' Where Name Like : sWildCardText or '+whereClauseFieldName+' like :sWildCardText order by createdDate DESC LIMIT 10';
        else
            sQuery = 'Select Id,Name '+(sObjectApiName == 'Engagement__c' ? ',(Select id from Engagement_Counterparties__r)':'') +' From ' + sObjectApiName + ' Where Name Like : sWildCardText order by createdDate DESC LIMIT 10';

        
        System.debug('sQuery'+sQuery);
        for (sObject obj: database.query(sQuery)) {
            if(sObjectApiName == 'Engagement__c'){
                Engagement__c inx = (Engagement__c)obj;
               // System.debug('inx.Engagement_Counterparties__r.size()'+inx.Engagement_Counterparties__r.size());
                /*if(inx.Engagement_Counterparties__r.size()>0){
                    returnList.add(obj);
                }*/
                boolean moreThanOne = false;
                for(Engagement_Counterparty__c ind: inx.Engagement_Counterparties__r){
                    moreThanOne = true;
                    break;
                }
                if(moreThanOne){
                    returnList.add(obj);
                }
            }else{
                returnList.add(obj);
            }
            
        }
        system.debug(returnList.size());
        return returnList;
    }
    
    // Method to fetch lookup default value 
    @AuraEnabled
    public static sObject fetchDefaultRecord(string recordId , string sObjectApiName ,  String whereClauseFieldName) {
        string sRecId = recordId;    
        string sQuery;
        if(String.isNotBlank(whereClauseFieldName))
            sQuery = 'Select Id,Name,'+whereClauseFieldName+' From ' + sObjectApiName + ' Where Id = : sRecId LIMIT 1';
        else
            sQuery = 'Select Id,Name  From ' + sObjectApiName + ' Where Id = : sRecId LIMIT 1';
        for (sObject obj: database.query(sQuery)) {
            return obj;
        }
        return null;
    }
    
    
    
}