force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Projected_Monthly_Fee__c.field-meta.xml
<CustomField>
    <fullName>Projected_Monthly_Fee__c</fullName>
    <label>Projected Monthly Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Projected_Transaction_Fee__c.field-meta.xml
<CustomField>
    <fullName>Projected_Transaction_Fee__c</fullName>
    <label>Projected Transaction Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Projection__c/Revenue_Projection__c.object-meta.xml
<CustomObject>
    <label>Revenue Projection</label>
    <nameField>
        <displayFormat>PROJ-REV{000000}</displayFormat>
        <label>Revenue Projection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Projections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Projection__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Projection__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Revenue Projections</relationshipLabel>
    <relationshipName>Revenue_Projections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Projection__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Projected_Monthly_Fee__c +  Projected_Transaction_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HL_RevenueProjectionRLVController.cls
public with sharing class HL_RevenueProjectionRLVController {
    private id EngId;
    public boolean CurrentOnly{get;set;}
    public ApexPages.StandardController stdCtrl;
    public ApexPages.StandardSetController setCon {get{
        if(setCon==null){
            setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                'SELECT Month__c, Year__c, Projected_Monthly_Fee__c, Projected_Transaction_Fee__c, Total__c, Archive__c, CurrencyIsoCode FROM Revenue_Projection__c WHERE Engagement__C =:EngId' + (CurrentOnly ? ' AND Archive__c = false ' : '') + ' ORDER BY Year__c, Month__c ASC'));
            setCon.setPageSize(5);
        }
        return setCon;
    }set;}
    
    public HL_RevenueProjectionRLVController(ApexPages.StandardController stdController){
        EngId = stdController.getrecord().id;
        CurrentOnly=true;
        stdCtrl = stdController;
    }
    
    public List<Revenue_Projection__c> getRevenueProjectionList(){
        return filterCurrentDate(setCon.getRecords());
    }
    
    public PageReference getRedirectToPage() {
        PageReference redirect = new PageReference('/apex/HL_RevenueProjectionEditView?id=' + EngId);
        redirect.setRedirect(true);
        return redirect;
    }
    
    public void Filter(){
        
        setCon = null;
    }
    
    public boolean hasNext{
        get{
            return setCon.getHasNext();
        }
        set;
    }
    
    public boolean hasPrevious{
        get{
            return setCon.getHasPrevious();
        }
        set;
    }
    
    public integer pageNumber {
        get{
            return setCon.getPageNumber();
        }
        set;
    }
    
    public void first(){
        setCon.first();
    }
    
    public void last(){
        setCon.last();
    } 
    
    public void previous(){
        setCon.previous();
    }
    
    public void next(){
        setCon.next();
    }
    
    public pageReference cancel(){
        return stdCtrl.cancel();
    }
    
    public List<Revenue_Projection__c> filterCurrentDate(List<Revenue_Projection__c> revenueProjections) {
        if (CurrentOnly) {
            integer year = System.Today().year();
            integer month = System.Today().month();
    
            List<Revenue_Projection__c> returnProjections = new List<Revenue_Projection__c>();
    
            for(Revenue_Projection__c p: revenueProjections) {
                if (Integer.valueof(p.Month__c.trim()) >= month && Integer.valueof(p.Year__c.trim()) >= year) {
                    returnProjections.add(p);
                }
            }  
            
            return returnProjections;
        }
        else {
            return revenueProjections;
        }
	}
}