force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Cash_Component__c.field-meta.xml
<CustomField>
    <fullName>Cash_Component__c</fullName>
    <label>Cash Component</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>Deposit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/Sale_Transaction__c.object-meta.xml
<CustomObject>
    <description>Custom object to track asset sales as part of a restructuring transaction.</description>
    <label>Sale Transaction</label>
    <nameField>
        <label>Asset Sold</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale_Transaction__c/fields/Break_Up_Fee__c.field-meta.xml
<CustomField>
    <fullName>Break_Up_Fee__c</fullName>
    <label>Break Up Fee (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Cash_Component__c.field-meta.xml
<CustomField>
    <fullName>Cash_Component__c</fullName>
    <label>Cash Component (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Claim_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Claim_Conversion__c</fullName>
    <label>Claim Conversion (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Date_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Sale__c</fullName>
    <label>Date of Sale</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>Deposit (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Sale Transactions</relationshipLabel>
    <relationshipName>Sale_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Incremental_Overbid__c.field-meta.xml
<CustomField>
    <fullName>Incremental_Overbid__c</fullName>
    <label>Incremental Overbid (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Liability_Assumed__c.field-meta.xml
<CustomField>
    <fullName>Liability_Assumed__c</fullName>
    <label>Liability Assumed (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Minimum_Overbid__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Overbid__c</fullName>
    <label>Minimum Overbid (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Stock_Component__c.field-meta.xml
<CustomField>
    <fullName>Stock_Component__c</fullName>
    <label>Stock Component (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sale_Transaction__c/fields/Total_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Price__c</fullName>
    <formula>BLANKVALUE(Cash_Component__c,0) + BlANKVALUE(Stock_Component__c,0) + BLANKVALUE(Liability_Assumed__c,0) + BLANKVALUE(Claim_Conversion__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Sales Price (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HL_SaleTransactionController.cls
public with sharing class HL_SaleTransactionController {
    public Id RecordId {get; set;}
    public Id EngagementId {get; set;}
   
    public Sale_Transaction__c SaleTransaction {get{
        if(saleTransaction == null){
            if(RecordId <> null)
                saleTransaction = [SELECT Name, Break_Up_Fee__c, Cash_Component__c, Claim_Conversion__c, Date_of_Sale__c, Deposit__c, Engagement__c, Incremental_Overbid__c, Liability_Assumed__c, Minimum_Overbid__c, Stock_Component__c, Total_Sales_Price__c FROM Sale_Transaction__c WHERE Id =: RecordId LIMIT 1];
            else
                saleTransaction = new Sale_Transaction__c(Engagement__c = EngagementId);
        }
        return saleTransaction;
    } set;}

	public HL_SaleTransactionController(){
        Map<String, String> q = ApexPages.currentPage().getParameters();
        if(q.containsKey('id'))
        	RecordId = q.get('id');
        EngagementId = q.get('eng');
    }
    
    
    public void Save(){
        try{        
            upsert SaleTransaction;
            RecordId = SaleTransaction.Id;
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, 'Record Saved'));
        }
        catch(DmlException ex){
            ApexPages.addMessages(ex);
        }
    }
}