force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/recordTypes/Litigation.recordType-meta.xml
<RecordType>
    <fullName>Litigation</fullName>
    <active>true</active>
    <label>Litigation</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record__c/Time_Record__c.object-meta.xml
<CustomObject>
    <description>Used to track time records</description>
    <label>Time Record</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Time Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date of Activity/Work.  For Weekly Recordings (FR), this will just be the Create Date</description>
    <label>Activity Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <description>Type of Activity for Time Being Tracked</description>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Audit Review Time</fullName>
            </value>
            <value>
                <fullName>Closing/Bring Down</fullName>
            </value>
            <value>
                <fullName>Conduct Analysis</fullName>
            </value>
            <value>
                <fullName>Conduct Research</fullName>
            </value>
            <value>
                <fullName>Counsel/Client Communications</fullName>
            </value>
            <value>
                <fullName>CS - Admin</fullName>
            </value>
            <value>
                <fullName>CS - Audit support</fullName>
            </value>
            <value>
                <fullName>CS - Initial Analysis</fullName>
            </value>
            <value>
                <fullName>CS - Iterations</fullName>
            </value>
            <value>
                <fullName>CS - Quality Review</fullName>
            </value>
            <value>
                <fullName>Deposition (including preparation for)</fullName>
            </value>
            <value>
                <fullName>Develop Work Product</fullName>
            </value>
            <value>
                <fullName>Diligence Discussion with Client</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>OOS</fullName>
            </value>
            <value>
                <fullName>Scoping / Admin</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Fieldwork</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Internal Admin/Planning</fullName>
            </value>
            <value>
                <fullName>Marketing - NB</fullName>
            </value>
            <value>
                <fullName>Non-Billable - NB</fullName>
            </value>
            <value>
                <fullName>Outsourced</fullName>
            </value>
            <value>
                <fullName>Pre-Engagement</fullName>
            </value>
            <value>
                <fullName>Receive/Catalogue/Review Data</fullName>
            </value>
            <value>
                <fullName>Report Writing</fullName>
            </value>
            <value>
                <fullName>Review of Work Product</fullName>
            </value>
            <value>
                <fullName>Strategic Consulting</fullName>
            </value>
            <value>
                <fullName>Testimony (including preparation for)</fullName>
            </value>
            <value>
                <fullName>Workstream 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Hourly Rate</description>
    <label>Hourly Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Hours_Worked__c.field-meta.xml
<CustomField>
    <fullName>Hours_Worked__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Hours Worked Value</description>
    <label>Hours Worked</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Time_Record_Period_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period_Staff_Member__c</fullName>
    <description>Related time record period staff member record</description>
    <label>Time Record Period Staff Member</label>
    <referenceTo>Time_Record_Period_Staff_Member__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Timer_Status__c.field-meta.xml
<CustomField>
    <fullName>Timer_Status__c</fullName>
    <label>Timer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Reset</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record__c/recordTypes/Beta.recordType-meta.xml
<RecordType>
    <fullName>Beta</fullName>
    <active>true</active>
    <label>Beta</label>
</RecordType>

force-app/main/default/objects/Time_Record__c/recordTypes/Litigation.recordType-meta.xml
<RecordType>
    <fullName>Litigation</fullName>
    <active>true</active>
    <description>Litigation Time Tracking Record</description>
    <label>Litigation</label>
</RecordType>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/Time_Record_Period_Staff_Member__c.object-meta.xml
<CustomObject>
    <label>Time Record Period Staff Member</label>
    <nameField>
        <displayFormat>TRPSM-{00000000}</displayFormat>
        <label>Time Record Period Staff Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Period Staff Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Rollup_Day__c/Time_Record_Rollup_Day__c.object-meta.xml
<CustomObject>
    <description>Used to aggregate the time record data to a single day.
The largest activity for the day is how all the time for the day will be categorized.
Should only have one record/client/user for each day</description>
    <label>Time Record Rollup Day</label>
    <nameField>
        <displayFormat>TRRD-{00000000}</displayFormat>
        <label>Time Record Rollup Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Rollup Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <label>Activity Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Receive/Catalogue/Review Data</fullName>
            </value>
            <value>
                <fullName>Conduct Research</fullName>
            </value>
            <value>
                <fullName>Conduct Analysis</fullName>
            </value>
            <value>
                <fullName>Develop Work Product</fullName>
            </value>
            <value>
                <fullName>Deposition (including preparation for)</fullName>
            </value>
            <value>
                <fullName>Testimony (including preparation for)</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Counsel/Client Communications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <label>Hourly Rate</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Hours_Worked__c.field-meta.xml
<CustomField>
    <fullName>Hours_Worked__c</fullName>
    <label>Hours Worked</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Time_Record_Period_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period_Staff_Member__c</fullName>
    <description>Related time record period staff member record</description>
    <label>Time Record Period Staff Member</label>
    <referenceTo>Time_Record_Period_Staff_Member__c</referenceTo>
    <relationshipLabel>Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Days</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_HL_TimeRecordHandler.cls
@isTest private class Test_HL_TimeRecordHandler {
    @isTest
    private static void TestAfterInsertRecordCreation() {
        final integer RECORDS_TO_INSERT = 10;
        
        Test.startTest();
        
        List<Time_Record__c> timeRecordList = SL_TestSetupUtils.CreateTimeRecordsWithRelated(RECORDS_TO_INSERT, 'Litigation');
        
        Test.stopTest();
        
        //Validate the time records were created
        System.assert([SELECT Id FROM Time_Record__c].size() == RECORDS_TO_INSERT);
        //Validate the the Time Record Rollup Day records were created
        System.assert([SELECT Id FROM Time_Record_Rollup_Day__c].size() > 0);
    }
    
    @isTest
    private static void TestAfterRecordUpdate() {
        final integer RECORDS_TO_INSERT = 10;
        final integer HOURS_WORKED = 2;
        
        List<Time_Record__c> timeRecordList = SL_TestSetupUtils.CreateTimeRecordsWithRelated(RECORDS_TO_INSERT, 'Litigation');
        timeRecordList[0].Timer_Status__c='Start';
        update timeRecordList[0];
        for (Time_Record__c tr : timeRecordList){
            tr.Hours_Worked__c = HOURS_WORKED;
            tr.Timer_Status__c='Pause';
        }
        Test.startTest();
        
        update timeRecordList;
        
        Test.stopTest();
        
        //Validate the rollup record was adjusted
        AggregateResult ar = [SELECT SUM(Hours_Worked__c) hours FROM Time_Record_Rollup_Day__c];
        //System.assertEquals(RECORDS_TO_INSERT * HOURS_WORKED, ar.get('hours'));
    }
    
    @isTest
    private static void TestAfterProjectUpdate() {
        final integer RECORDS_TO_INSERT = 10;
        List<Time_Record__c> timeRecordList = SL_TestSetupUtils.CreateTimeRecordsWithRelated(RECORDS_TO_INSERT, 'Litigation');
        Opportunity__c opp = SL_TestSetupUtils.CreateOpp('', 1)[0];
        opp.Beneficial_Owner_Control_Person_form__c = 'No';
        insert opp;
        
        for (Time_Record__c tr : timeRecordList) {
            tr.Activity_Date__c = Date.today();
            tr.Opportunity__c = opp.Id;
            tr.Hours_Worked__c = 1;
        }
        
        Test.startTest();
        
        update timeRecordList;
        
        Test.stopTest();
        
        //Validate there is only one rollup record
        System.assertEquals(1, [SELECT Id FROM Time_Record_Rollup_Day__c].size());
    }
    
    @isTest
    private static void TestAfterRecordDelete() {
        final integer RECORDS_TO_INSERT = 10;
        final integer HOURS_WORKED = 2;
        
        List<Time_Record__c> timeRecordList = SL_TestSetupUtils.CreateTimeRecordsWithRelated(RECORDS_TO_INSERT, 'Litigation');
        for (Time_Record__c tr : timeRecordList) 
            tr.Hours_Worked__c = HOURS_WORKED;
        update timeRecordList;
        
        Test.startTest();
        
        delete timeRecordList;
        
        Test.stopTest();
        
        //Validate the rollup record was adjusted
        AggregateResult ar = [SELECT SUM(Hours_Worked__c) hours FROM Time_Record_Rollup_Day__c];
        System.assertEquals(NULL, ar.get('hours'));
    }
    
    @isTest
    public static void testTimeRecordUpdate(){
        Integer recordCount = 2;
        List<Time_Record__c> timeRecordList = SL_TestSetupUtils.CreateTimeRecordsWithRelated(recordCount, 'Beta');
        Integer  count = 1;
        for(Time_Record__c tr : timeRecordList){
            if(count == 1){
                tr.Activity_Type__c = 'FieldWork';
                tr.Hourly_Rate__c = 100;
                tr.Hours_Worked__c = 5;
            }else{
                tr.Activity_Type__c = 'Marketing';  
                tr.Hourly_Rate__c = 100;
                tr.Hours_Worked__c = 5;
            }
            count++;
        }
        update timeRecordList;
    }
    
    @isTest
    public static void testTimeRecord(){
        Date startDate = Date.today();
        Date endDate = Date.today().addYears(1);
        Id userId = UserInfo.getUserId();
        Id recordTypeId = Schema.SObjectType.Time_Record__c.getRecordTypeInfosByName().get('Beta').getRecordTypeId();
        Set<Date> activityDateSet = new Set<Date>();
        activityDateSet.add(startDate);
        Set<String> relatedObjectIdSet = new Set<String>();
        relatedObjectIdSet.add('Opportunity__c');
        relatedObjectIdSet.add('Engagement__c');
        List<Time_Record__c> timeRecordList = SL_TestSetupUtils.CreateTimeRecordsWithRelated(2, 'Beta');
        List<Time_Record__c> listToUpdate = new List<Time_Record__c>();
        List<Opportunity__c> oppList = SL_TestSetupUtils.CreateOpp('Test',1);
        Set<Id> engagementIdSet = new Set<Id>();
        for(Time_Record__c tr : timeRecordList){
            engagementIdSet.add(tr.Engagement__c);
            tr.Opportunity__c = oppList[0].Id;
            listToUpdate.add(tr);
        }
        update listToUpdate;
        Set<Id> smIdSet = new Set<Id>();
        for(Time_Record__c tr : timeRecordList){
            smIdSet.add(tr.Time_Record_Period_Staff_Member__c);
        }
        Test.startTest();
        HL_TimeRecord.GetByUser(userId, startDate, endDate);
        HL_TimeRecord.GetByEngagements(recordTypeId, engagementIdSet);
        HL_TimeRecord.GetByEngagementsOpportunities(recordTypeId, engagementIdSet);
        HL_TimeRecord.GetAggregatedTimeRecordsByDate(activityDateSet, relatedObjectIdSet, smIdSet);
        Test.stopTest();
        
    }
    
}