force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Comment__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Comment__c</fullName>
    <label>Engagement Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Last_Engagement_Comment_Any__c.field-meta.xml
<CustomField>
    <fullName>Last_Engagement_Comment_Any__c</fullName>
    <description>Last Engagement Comment of Any Type (Including Admin)</description>
    <formula>Last_Engagement_Comment_Any_Part_1__c + Last_Engagement_Comment_Any_Part_2__c + Last_Engagement_Comment_Any_Part_3__c + Last_Engagement_Comment_Any_Part_4__c</formula>
    <label>Last Engagement Comment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Last_Engagement_Comment_PIPELINE__c.field-meta.xml
<CustomField>
    <fullName>Last_Engagement_Comment_PIPELINE__c</fullName>
    <formula>Last_Engagement_Comment_Part_1__c +  Last_Engagement_Comment_Part_2__c + Last_Engagement_Comment_Part_3__c  +  Last_Engagement_Comment_Part_4__c</formula>
    <label>Last Engagement Comment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Comment__c/Engagement_Comment__c.object-meta.xml
<CustomObject>
    <label>Engagement Comment</label>
    <nameField>
        <displayFormat>ENOP-{0000}</displayFormat>
        <label>Engagement Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Comment__c/fields/Comment_Type__c.field-meta.xml
<CustomField>
    <fullName>Comment_Type__c</fullName>
    <inlineHelpText>Administrative - For LOB administrators
Internal - Internal reporting</inlineHelpText>
    <label>Comment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
                <default>true</default>
                <label>Internal</label>
            </value>
            <value>
                <fullName>Next Step</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Comment__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Engagement_Comments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_EngagementCommentHandler.cls
@isTest
private class Test_HL_EngagementCommentHandler {
    @isTest
    private static void TestOnAfterEngagementCommentInsert(){
        Engagement__c e = HL_TestFactory.CreateEngagement(false);
        insert e;
        Engagement_Comment__c ec = new Engagement_Comment__c(Engagement__c = e.Id, Comment_Type__c = 'Internal', Comment__c = 'Test');

        Test.startTest();

        HL_EngagementCommentHandler handler = new HL_EngagementCommentHandler(false, 1);
        insert ec;

        Test.stopTest();

        //Verify the engagement has been updated with the latest comment
        e = [SELECT Last_Engagement_Comment_Any__c, Last_Engagement_Comment_PIPELINE__c FROM Engagement__c WHERE Id =: e.Id];
        System.assert(!String.isBlank(e.Last_Engagement_Comment_Any__c));
        System.assert(!String.isBlank(e.Last_Engagement_Comment_PIPELINE__c));
    }
}