force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staffing_Details__c/Staffing_Details__c.object-meta.xml
<CustomObject>
    <description>Stores the staffing details records per month</description>
    <label>Staffing Detail</label>
    <nameField>
        <displayFormat>SD-{YYYY}{MM}-{0}</displayFormat>
        <label>Staffing Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staffing_Details__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Staffing Details</relationshipLabel>
    <relationshipName>Staffing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_RecalculateLOBSplitBatch.cls
global class HL_RecalculateLOBSplitBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    String query;
    Date previousMonthDate =System.Today().toStartOfMonth().addDays(-1); 
    global HL_RecalculateLOBSplitBatch(String queryString) {
        query = queryString;
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc,  List<Staffing_Details__c> lstStaffingDetail){
        Set<Id> engagementIds = new Set<Id>();

        if(!lstStaffingDetail.isEmpty()){
            for(Staffing_Details__c sd : lstStaffingDetail)
            engagementIds.add(sd.Engagement__c);
            }
    HL_PercentageSplitHandler handler = new HL_PercentageSplitHandler();
    handler.RecalculateLOBSplits(engagementIds);  
    }

    global void finish(Database.BatchableContext bc){

    }
}