force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/Time_Record__c.object-meta.xml
<CustomObject>
    <description>Used to track time records</description>
    <label>Time Record</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Time Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record__c/fields/Day_Rollup_Key__c.field-meta.xml
<CustomField>
    <fullName>Day_Rollup_Key__c</fullName>
    <formula>TEXT(YEAR(Activity_Date__c)) + &apos;_&apos; + TEXT(MONTH(Activity_Date__c)) + &apos;_&apos; + TEXT(DAY(Activity_Date__c)) + &apos;_&apos; + Time_Record_Period_Staff_Member__r.User__c + &apos;_&apos; +  BLANKVALUE(Engagement__c , BLANKVALUE(Opportunity__c, Special_Project__c))</formula>
    <label>Day Rollup Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/recordTypes/FR.recordType-meta.xml
<RecordType>
    <fullName>FR</fullName>
    <active>true</active>
    <description>FR Time Tracking Record Type</description>
    <label>FR</label>
</RecordType>

force-app/main/default/objects/Time_Record_Rollup_Day__c/Time_Record_Rollup_Day__c.object-meta.xml
<CustomObject>
    <description>Used to aggregate the time record data to a single day.
The largest activity for the day is how all the time for the day will be categorized.
Should only have one record/client/user for each day</description>
    <label>Time Record Rollup Day</label>
    <nameField>
        <displayFormat>TRRD-{00000000}</displayFormat>
        <label>Time Record Rollup Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Rollup Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_TimeRecordRollupDay.cls
@isTest
private class Test_HL_TimeRecordRollupDay {
    @isTest private static void TestRetrievalMethods(){
        final integer TEST_RECORDS_CREATED = 10;
        List<Time_Record__c> trList = SL_TestSetupUtils.CreateTimeRecordsWithRelated(TEST_RECORDS_CREATED, 'FR');
        Date startDate = Date.today();
        Date endDate = Date.today().addYears(1);
        List<Id> engagementIdList = new List<Id>();
        for(Time_Record__c tr : trList){
            engagementIdList.add(tr.Engagement__c);
        }
        
        Test.startTest();
        	HL_TimeRecordRollupDay trrd = new HL_TimeRecordRollupDay();
        	List<Time_Record_Rollup_Day__c> trrdGetByUserResult = HL_TimeRecordRollupDay.GetByUser(UserInfo.getUserId(), startDate, endDate);
        	List<Time_Record_Rollup_Day__c> trrdGetByKeysResult = HL_TimeRecordRollupDay.GetByKeys(new Set<String>{trList[0].Day_Rollup_Key__c});
        	List<AggregateResult> trrdGetGroupedByDayAndProject = HL_TimeRecordRollupDay.GetGroupedByDayAndProject(UserInfo.getUserId(), startDate, endDate);
			List<AggregateResult> trrdGetGroupedByEngagement = HL_TimeRecordRollupDay.GetGroupedByEngagement('FR', startDate, endDate);
        	List<AggregateResult> trrdGetGroupedByEngagement1 = HL_TimeRecordRollupDay.GetGroupedByEngagement('FR', startDate, endDate,engagementIdList);
        	List<AggregateResult> trrdGetGroupedByDay = HL_TimeRecordRollupDay.GetGroupedByDay(UserInfo.getUserId(), startDate, endDate);
        	List<Time_Record_Rollup_Day__c> trrdGetEngagementsLoggedForUser = HL_TimeRecordRollupDay.GetEngagementsLoggedForUser(UserInfo.getUserId(), startDate, endDate);

        Test.stopTest();
        
        //Validate the user results were retured
        System.assertEquals(1,trrdGetByUserResult.size());
    }
}