force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements (Billing Contact)</relationshipLabel>
    <relationshipName>Engagements6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/Engagement_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for an engaged deal/project.</description>
    <label>Engagement Contact</label>
    <nameField>
        <displayFormat>EET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_External_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Invalid Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Engagement_Working_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Engagement_Working_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Accountant to Official Creditors Committee</fullName>
            </value>
            <value>
                <fullName>Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Adverse Party</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Attorney (Acquirer)</fullName>
            </value>
            <value>
                <fullName>Attorney (Target)</fullName>
            </value>
            <value>
                <fullName>Attorney Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Houlihan Lokey</fullName>
            </value>
            <value>
                <fullName>Audit Partner</fullName>
            </value>
            <value>
                <fullName>Balloting/Solicitation Agent</fullName>
            </value>
            <value>
                <fullName>Banker Advising Acquirer</fullName>
            </value>
            <value>
                <fullName>Banker Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Banker Advising Target</fullName>
            </value>
            <value>
                <fullName>Bank Group</fullName>
            </value>
            <value>
                <fullName>Bank Group - First Lien</fullName>
            </value>
            <value>
                <fullName>Bank Group - Second Lien</fullName>
            </value>
            <value>
                <fullName>Bank Lender</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Clerk</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Bank Group</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Board of Directors</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to DIP Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Sub_Role__c.field-meta.xml
<CustomField>
    <fullName>Sub_Role__c</fullName>
    <inlineHelpText>Applicable to FR only.</inlineHelpText>
    <label>Sub Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Judge</fullName>
            </value>
            <value>
                <fullName>Potential Buyer</fullName>
            </value>
            <value>
                <fullName>Restricted Group</fullName>
            </value>
            <value>
                <fullName>Steering Committee</fullName>
            </value>
            <value>
                <fullName>Subcommittee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>External</fullName>
                <default>true</default>
                <label>External</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/Opportunity_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for a prospective engagement.</description>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>OET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Invalid Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Opportunity_Client_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>FVA TO, FMV, Fairness, Solvency and BAS  roles: 
-Adverse Party 
-Attorney 
-Banker 
-BoD 
-CEO 
-CFO 
-Company Mgmt 
-Fin Advisor 
-Independent Director 
-Majority Owner 
-Mgmt Contact
-Independent Director</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Accountant to Official Creditors Committee</fullName>
            </value>
            <value>
                <fullName>Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Adverse Party</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Attorney (Acquirer)</fullName>
            </value>
            <value>
                <fullName>Attorney (Target)</fullName>
            </value>
            <value>
                <fullName>Attorney Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Houlihan Lokey</fullName>
            </value>
            <value>
                <fullName>Audit Partner</fullName>
            </value>
            <value>
                <fullName>Balloting/Solicitation Agent</fullName>
            </value>
            <value>
                <fullName>Banker Advising Acquirer</fullName>
            </value>
            <value>
                <fullName>Banker Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Banker Advising Target</fullName>
            </value>
            <value>
                <fullName>Bank Group</fullName>
            </value>
            <value>
                <fullName>Bank Group - First Lien</fullName>
            </value>
            <value>
                <fullName>Bank Group - Second Lien</fullName>
            </value>
            <value>
                <fullName>Bank Lender</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Clerk</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Bank Group</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Board of Directors</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to DIP Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Sub_Role__c.field-meta.xml
<CustomField>
    <fullName>Sub_Role__c</fullName>
    <inlineHelpText>Applicable to FR only.</inlineHelpText>
    <label>Sub Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Judge</fullName>
            </value>
            <value>
                <fullName>Potential Buyer</fullName>
            </value>
            <value>
                <fullName>Restricted Group</fullName>
            </value>
            <value>
                <fullName>Steering Committee</fullName>
            </value>
            <value>
                <fullName>Subcommittee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SL_Convert_EngagementQueueableClass.cls
public class SL_Convert_EngagementQueueableClass implements Queueable{
    private Id opportunityId;
    
    public SL_Convert_EngagementQueueableClass(ID idToOpp){
        this.opportunityId = idToOpp;
    }
    public void execute(QueueableContext context){
        system.debug('opportunityId-- '+opportunityId);
        list<Engagement_External_Team__c> engETList = new list<Engagement_External_Team__c>();
        List<Engagement__c>  engList = [SELECT Id, Opportunity__c FROM Engagement__c WHERE Opportunity__c =:opportunityId];
        system.debug('engList-- '+engList.size());
        list<Opportunity_External_Team__c> oppETList = [SELECT Contact__c, Opportunity__c, Type__c, Role__c, Sub_Role__c, 
                                                        Description__c, Billing_Contact__c, Acknowledge_Billing_Contact__c, 
                                                        Billing_Contact_Notes__c,  
                                                        Exclude_from_Working_Party__c, Primary__c, Id 
         												FROM Opportunity_External_Team__c WHERE Opportunity__c =:  opportunityId];
        system.debug('oppETList-- '+oppETList.size());
        for(Engagement__c e : engList ){
            for(Opportunity_External_Team__c oet : oppETList){
                Engagement_External_Team__c et = new Engagement_External_Team__c();
                et.Contact__c = oet.Contact__c;
                et.Type__c = oet.Type__c;
                et.Role__c = oet.Role__c;
                et.Sub_Role__c = oet.Sub_Role__c;
                et.Description__c = oet.Description__c;
                et.Billing_Contact__c = oet.Billing_Contact__c;
                et.Acknowledge_Billing_Contact__c = oet.Acknowledge_Billing_Contact__c;
                et.Billing_Contact_Notes__c = oet.Billing_Contact_Notes__c;
                et.Exclude_from_Working_Party__c = oet.Exclude_from_Working_Party__c ;
                et.Primary__c = oet.Primary__c;
                et.Engagement__c = e.Id;
                engETList.add(et);
            }
        }
        system.debug('engETList-- '+engETList.size());
        if(engETList.size() > 0)
        insert engETList;
    }
}