force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Summary__c/Engagement_Summary__c.object-meta.xml
<CustomObject>
    <description>Stored the Engagement Closing Data</description>
    <label>Engagement Summary</label>
    <nameField>
        <label>Engagement Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Summary__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Summaries</relationshipLabel>
    <relationshipName>Engagement_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/Opportunity_Approval__c.object-meta.xml
<CustomObject>
    <description>These records are related to Opportunities and are required for submission before attaining committee approval and engagement.</description>
    <label>Opportunity Review</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Opportunity Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <description>Used for approval processes and to identify records between FEIS and NBC</description>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FEIS</fullName>
            </value>
            <value>
                <fullName>NBC</fullName>
            </value>
            <value>
                <fullName>CNBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <inlineHelpText>Please indicate the related Opportunity record.</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Reviews</relationshipLabel>
    <relationshipName>Opportunity_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HL_PagePreProcess.cls
//This class is used to create/evaluate a record prior to redirecting to the destination page.
public with sharing class HL_PagePreProcess {
    public static PageReference PreProcess()
    {
        PageReference dest;
        List<SObject> existingRecords;
        SObject destRecord;
        string action = HL_PageUtility.GetParameter('action');
        string parentcurrency = HL_PageUtility.GetParameter('parentcurrency');
        if(action == 'feis'||action =='nbc' || action == 'cnbc'){ 
            string oppId = HL_PageUtility.GetParameter('opp');
            existingRecords = [SELECT Id FROM Opportunity_Approval__c WHERE Related_Opportunity__c =:oppId LIMIT 1];
            if(existingRecords.size() == 0){
                destRecord = new Opportunity_Approval__c(Related_Opportunity__c = oppID,Form_Type__c = action.toUpperCase(), CurrencyIsoCode = parentcurrency);
                insert destRecord;
            }
            else
                destRecord = existingRecords[0];

            dest = new PageReference('/apex/HL_' + action.toUpperCase() + '?id=' + destRecord.Id);
        }
        else
        {
            if(action == 'summary_cf'){
                string engId = HL_PageUtility.GetParameter('eng');
                existingRecords = [SELECT Id FROM Engagement_Summary__c WHERE Engagement__c =:engId LIMIT 1];
                if(existingRecords.size() == 0){
                    destRecord = new Engagement_Summary__c(Engagement__c = engId);
                    insert destRecord;
                }
                else
                    destRecord = existingRecords[0];
                
                dest = New PageReference('/apex/HL_CF_EngagementSummary?id=' + destRecord.Id);
            }
            else
                dest = new PageReference('/');
        }
        
        return dest;
    }
}