force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Recalculate_Deal_Percentages__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Deal_Percentages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Records with this field checked, will be picked by the batch job to recalculate the Splits</description>
    <label>Recalculate Deal Percentages</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/Engagement_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that are staffed on an engaged deal/project.</description>
    <label>Engagement Internal Team</label>
    <nameField>
        <displayFormat>EIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Staff_Revenue_Split__c.field-meta.xml
<CustomField>
    <fullName>Staff_Revenue_Split__c</fullName>
    <description>Saves the Staff Split Calculation.</description>
    <label>Staff Revenue Split</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/SL_Batch_PercentageSplit.cls
/**
* \arg ClassName      : SL_Batch_PercentageSplit
* \arg JIRATicket     : HL-43
* \arg CreatedOn      : 12/JAN/2015
* \arg LastModifiedOn : 12/JAN/2015
* \arg CreatededBy    : GM
* \arg ModifiedBy     : GM
* \arg Description    : Batch class to recalculate Percent Staff/Role split on engagement.
*/
global class SL_Batch_PercentageSplit implements Database.Batchable<sObject> {

    String query;

    global SL_Batch_PercentageSplit(String query) {
        this.query = query;
    }
    global SL_Batch_PercentageSplit() {
        this('Select Id FROM Engagement__c WHERE (ID in (select engagement__c FROM engagement_internal_team__c where (End_Date__c <= TODAY AND Staff_Revenue_Split__c != 0) OR Engagement__r.Recalculate_Deal_Percentages__c=true))');
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    /*
        @MethodName : execute.
        @param      : Database.BatchableContext and List of Event.
        @Description: This method recalculates engagements
    */
    global void execute(Database.BatchableContext BC, List<Engagement__c> lstEngagement) {        
        HL_PercentageSplitHandler handler = new HL_PercentageSplitHandler();
        Set<Id> stIds = new Set<Id>();
        for (Engagement__c e : lstEngagement)
            stIds.add(e.Id);
        //Collect all the Engagement Ids and pass it to the Handler class
        handler.Recalculate(stIds);
        handler.RecalculateLOBSplits(stIds);

    }
    /*
        @MethodName : finish.
        @param      : Database.BatchableContext .
        @Description: do nothing
    */
    global void finish(Database.BatchableContext BC) {
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob WHERE Id = 
                              :BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion if there is an error in any of the batches.
        if (a.NumberOfErrors > 0) {
            HL_Email.SendEmail(new List<String> {a.CreatedBy.Email}, null, null, 'Engagement Staff Split Calculations: ' + a.Status, 'The batch Apex job processed ' + a.TotalJobItems +
             ' batches with ' + a.NumberOfErrors + ' failures.', false);         
        }
    }

}