force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/Engagement_Office_Split__c.object-meta.xml
<CustomObject>
    <description>Stores the calculated office splits per Engagement</description>
    <label>Engagement Office Split</label>
    <nameField>
        <displayFormat>EOS-{00000000}</displayFormat>
        <label>Engagement Office Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Office Splits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Engagement Record</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Office Splits</relationshipLabel>
    <relationshipName>Engagement_Office_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Office of the Split Calculation</description>
    <label>Office</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Office_Split__c.field-meta.xml
<CustomField>
    <fullName>Office_Split__c</fullName>
    <description>Office Revenue Split Percentage</description>
    <label>Office Split</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Office_Split_Override_Percent__c.field-meta.xml
<CustomField>
    <fullName>Office_Split_Override_Percent__c</fullName>
    <description>Override Office Split Percentage Value</description>
    <inlineHelpText>If override value is no longer needed, be sure to clear the value and do not set to 0</inlineHelpText>
    <label>Office Split Override Percent</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Test_HL_EngagementOfficeSplitEditCon.cls
@isTest
private class Test_HL_EngagementOfficeSplitEditCon {
    @testSetup
    private static void CreateData() {
        Engagement__c e = SL_TestSetupUtils.CreateEngagement('', 1)[0];
        insert e;
        
        List<Engagement_Office_Split__c> elsList = new List<Engagement_Office_Split__c> {new Engagement_Office_Split__c(Engagement__c = e.Id, Office__c = 'CF', Office_Split__c = 80.0),
            new Engagement_Office_Split__c(Engagement__c = e.Id, Office__c = 'FVA', Office_Split__c = 20.0)
            };
                insert elsList;
    }
    
    @isTest
    private static void TestOfficeSplitOverrideSave() {
        Engagement_Office_Split__c els = [SELECT Engagement__c FROM Engagement_Office_Split__c LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(els);
        Test.setCurrentPage(new PageReference('/apex/HL_EngagementOfficeSplitEdit?Id=' + els.id));
        
        HL_EngagementOfficeSplitEditController con = new HL_EngagementOfficeSplitEditController(sc);
        
        List<String> SplitTypeList = con.SplitTypeList;
        
        //Override both to 50%
        con.OverrideOfficeSplitList[0].Percent = 50.0;
        con.OverrideOfficeSplitList[1].Percent = 50.0;
        
        con.SaveRecords();
        
        Test.stopTest();
        
        //Verify the Properties were Updated
        System.assertEquals(els.Engagement__c, con.EngagementId);
        System.assertEquals(2, con.EngagementOfficeSplitList.size());
        System.assertEquals(2, con.OfficeSplitList.size());
        System.assertEquals(2, con.OverrideOfficeSplitList.size());
        
        //Verify the Save was Successful
        for (Engagement_Office_Split__c split : [SELECT Office_Split_Override_Percent__c
                                                 FROM Engagement_Office_Split__c]) {
                                                     System.assertEquals(50.0, split.Office_Split_Override_Percent__c);
                                                 }
    }
    
    @isTest
    private static void TestOfficeSplitOverrideSaveBackToNull() {
        Engagement_Office_Split__c els = [SELECT Engagement__c FROM Engagement_Office_Split__c LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(els);
        Test.setCurrentPage(new PageReference('/apex/HL_EngagementOfficeSplitEdit?Id=' + els.id));
        
        HL_EngagementOfficeSplitEditController con = new HL_EngagementOfficeSplitEditController(sc);
        
        List<String> SplitTypeList = con.SplitTypeList;
        
        //Override both to 50%
        con.OverrideOfficeSplitList[0].Percent = 50.0;
        con.OverrideOfficeSplitList[1].Percent = 50.0;
        
        con.SaveRecords();
        
        con.OverrideOfficeSplitList[0].Percent = null;
        con.OverrideOfficeSplitList[1].Percent = null;
        
        con.SaveRecords();
        
        Test.stopTest();
        
        //Verify the Save was Successful and Override Results are Back to 0
        for (Engagement_Office_Split__c split : [SELECT Office_Split_Override_Percent__c
                                                 FROM Engagement_Office_Split__c]) {
                                                     System.assertEquals(0, split.Office_Split_Override_Percent__c);
                                                 }
    }
    
    @isTest
    private static void TestOfficeSplitOverrideSaveErrorDMLException() {
        Engagement_Office_Split__c els = [SELECT Engagement__c FROM Engagement_Office_Split__c LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(els);
        Test.setCurrentPage(new PageReference('/apex/HL_EngagementOfficeSplitEdit?Id=' + els.id));
        
        HL_EngagementOfficeSplitEditController con = new HL_EngagementOfficeSplitEditController(sc);
        
        //Override both to 50%
        con.OverrideOfficeSplitList[0].Percent = 50.0;
        con.OverrideOfficeSplitList[1].Percent = 50.0;
        
        //Delete the Records Before Save
        delete [SELECT Id FROM Engagement_Office_Split__c];
        
        con.SaveRecords();
        
        Test.stopTest();
        
        //Verify an Error is Displayed
        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
    }
    
    @isTest
    private static void TestOfficeSplitOverrideSaveErrorAbove100() {
        Engagement_Office_Split__c els = [SELECT Engagement__c FROM Engagement_Office_Split__c LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(els);
        Test.setCurrentPage(new PageReference('/apex/HL_EngagementOfficeSplitEdit?Id=' + els.id));
        
        HL_EngagementOfficeSplitEditController con = new HL_EngagementOfficeSplitEditController(sc);
        
        //Override both to 75%
        con.OverrideOfficeSplitList[0].Percent = 75.0;
        con.OverrideOfficeSplitList[1].Percent = 75.0;
        
        con.SaveRecords();
        
        Test.stopTest();
        
        //Verify an Error is Displayed
        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
        
        //Verify the Save was not Successful
        for (Engagement_Office_Split__c split : [SELECT Office_Split_Override_Percent__c
                                                 FROM Engagement_Office_Split__c]) {
                                                     System.assertNotEquals(75.0, split.Office_Split_Override_Percent__c);
                                                 }
    }
    
    @isTest
    private static void TestOfficeSplitOverrideCancel() {
        Engagement_Office_Split__c els = [SELECT Engagement__c FROM Engagement_Office_Split__c LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(els);
        Test.setCurrentPage(new PageReference('/apex/HL_EngagementOfficeSplitEdit?Id=' + els.id));
        
        HL_EngagementOfficeSplitEditController con = new HL_EngagementOfficeSplitEditController(sc);
        
        //Override both to 50%
        con.OverrideOfficeSplitList[0].Percent = 50.0;
        con.OverrideOfficeSplitList[1].Percent = 50.0;
        
        con.CancelAndReturn();
        
        Test.stopTest();
        
        //Verify the Properties were Updated
        System.assertEquals(els.Engagement__c, con.EngagementId);
        System.assertEquals(2, con.EngagementOfficeSplitList.size());
        System.assertEquals(2, con.OfficeSplitList.size());
        System.assertEquals(2, con.OverrideOfficeSplitList.size());
        
        //Verify the Save did not happen
        for (Engagement_Office_Split__c split : [SELECT Office_Split_Override_Percent__c
                                                 FROM Engagement_Office_Split__c]) {
            System.assertNotEquals(50.0, split.Office_Split_Override_Percent__c);
        }
        
    }
}