force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/Engagement_Office_Split__c.object-meta.xml
<CustomObject>
    <description>Stores the calculated office splits per Engagement</description>
    <label>Engagement Office Split</label>
    <nameField>
        <displayFormat>EOS-{00000000}</displayFormat>
        <label>Engagement Office Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Office Splits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Engagement Record</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Office Splits</relationshipLabel>
    <relationshipName>Engagement_Office_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Office of the Split Calculation</description>
    <label>Office</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Office_Split__c.field-meta.xml
<CustomField>
    <fullName>Office_Split__c</fullName>
    <description>Office Revenue Split Percentage</description>
    <label>Office Split</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Engagement_Office_Split__c/fields/Office_Split_Override_Percent__c.field-meta.xml
<CustomField>
    <fullName>Office_Split_Override_Percent__c</fullName>
    <description>Override Office Split Percentage Value</description>
    <inlineHelpText>If override value is no longer needed, be sure to clear the value and do not set to 0</inlineHelpText>
    <label>Office Split Override Percent</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/HL_EngagementOfficeSplitEditController.cls
public with sharing class HL_EngagementOfficeSplitEditController {
    public Id EngagementId {get; set;}
    public List<Engagement_Office_Split__c> EngagementOfficeSplitList {get; set;}
    public List<String> SplitTypeList {get {return new List<String>{'','Office Split', 'Office Split Override'};}}
    public List<OfficeSplit> OfficeSplitList {get; set;}
    public List<OfficeSplit> OverrideOfficeSplitList {get; set;}
    
    
    public HL_EngagementOfficeSplitEditController(ApexPages.StandardController controller) {
        Engagement_Office_Split__c record = (Engagement_Office_Split__c)controller.getRecord();
        this.EngagementId = record.Engagement__c;
        this.EngagementOfficeSplitList = [SELECT Office__c,
                                          Office_Split__c,
                                          Office_Split_Override_Percent__c
                                          FROM Engagement_Office_Split__c
                                          WHERE Engagement__c = : this.EngagementId
                                          ORDER BY Office__c];
        
        this.OfficeSplitList = new List<OfficeSplit>();
        this.OverrideOfficeSplitList = new List<OfficeSplit>();
        
        for (Engagement_Office_Split__c els : this.EngagementOfficeSplitList){
            this.OfficeSplitList.add(new OfficeSplit(els.Office__c, els.Office_Split__c  * 100.0));
            this.OverrideOfficeSplitList.add(new OfficeSplit(els.Office__c, els.Office_Split_Override_Percent__c));
        }
    }
    
    public PageReference SaveRecords() {
        PageReference pf = ApexPages.currentPage();
        String errorMsg = this.Validate();
        
        if (String.isBlank(errorMsg)) {
            try {
                this.Save();
                pf = new PageReference('/' + this.EngagementId);
            }
            catch (DmlException ex) {
                ApexPages.addMessages(ex);
            }
        }
        else
            HL_PageUtility.ShowError(errorMsg);
        
        return pf;
    }
    
    public PageReference CancelAndReturn() {
        return new PageReference('/' + this.EngagementId);
    }
    
    private string Validate() {
        decimal overrideTotal = 0;
        
        for (OfficeSplit ls : this.OverrideOfficeSplitList) {
            if (ls.Percent != null)
                overrideTotal += ls.Percent;
        }
        
        //Verify if an Override was Specified the Totals must Equal 100.0
        return overrideTotal > 0 ? overrideTotal != 100 ? 'Override Values Must Equal 100.0' : '' : '';
    }
    
    private List<Engagement_Office_Split__c> Save() {
        Map<String, Decimal> overrideSplitMap = new Map<String, Decimal>();
        
        for(OfficeSplit ls : this.OverrideOfficeSplitList)
            overrideSplitMap.put(ls.Office, ls.Percent);
        
        for (Engagement_Office_Split__c els : this.EngagementOfficeSplitList) {
            Decimal overridePercent = overrideSplitMap.get(els.Office__c);
            if (overridePercent != null)
                els.Office_Split_Override_Percent__c = overridePercent;
            else
                els.Office_Split_Override_Percent__c = 0;
        }
        
        update this.EngagementOfficeSplitList;
        
        return this.EngagementOfficeSplitList;
    }
    
    public class OfficeSplit {
        public String Office {get; set;}
        public Decimal Percent {get; set;}
        
        public OfficeSplit(string Office, decimal percent){
            this.Office = Office;
            this.Percent = percent;
        }
    }
}