force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Special_Project__c.field-meta.xml
<CustomField>
    <fullName>Special_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Projects labeled as the special project will need to go through a separate scoping committee</description>
    <label>Special Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Project__c/Special_Project__c.object-meta.xml
<CustomObject>
    <description>Used to store non-billable or non-case related special projects.</description>
    <label>Special Project</label>
    <nameField>
        <label>Special Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record__c/Time_Record__c.object-meta.xml
<CustomObject>
    <description>Used to track time records</description>
    <label>Time Record</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Time Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record__c/fields/Add_Minute__c.field-meta.xml
<CustomField>
    <fullName>Add_Minute__c</fullName>
    <label>Add Minute</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Add_Minute_Change__c.field-meta.xml
<CustomField>
    <fullName>Add_Minute_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Minute Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Hours_Change__c.field-meta.xml
<CustomField>
    <fullName>Hours_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hours Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Hours_Worked__c.field-meta.xml
<CustomField>
    <fullName>Hours_Worked__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Hours Worked Value</description>
    <label>Hours Worked</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Minutes_Worked__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Worked__c</fullName>
    <label>Minutes Worked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Recording_Status__c.field-meta.xml
<CustomField>
    <fullName>Recording_Status__c</fullName>
    <description>Used to monitor whether the user completed the time record</description>
    <label>Recording Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Seconds_Worked__c.field-meta.xml
<CustomField>
    <fullName>Seconds_Worked__c</fullName>
    <label>Seconds Worked</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Special_Project__c.field-meta.xml
<CustomField>
    <fullName>Special_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related special project record</description>
    <label>Special Project</label>
    <referenceTo>Special_Project__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Stop_Time__c.field-meta.xml
<CustomField>
    <fullName>Stop_Time__c</fullName>
    <label>Stop Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Timer_Status__c.field-meta.xml
<CustomField>
    <fullName>Timer_Status__c</fullName>
    <label>Timer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Reset</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/Time_Record_Rollup_Day__c.object-meta.xml
<CustomObject>
    <description>Used to aggregate the time record data to a single day.
The largest activity for the day is how all the time for the day will be categorized.
Should only have one record/client/user for each day</description>
    <label>Time Record Rollup Day</label>
    <nameField>
        <displayFormat>TRRD-{00000000}</displayFormat>
        <label>Time Record Rollup Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Rollup Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Hours_Worked__c.field-meta.xml
<CustomField>
    <fullName>Hours_Worked__c</fullName>
    <label>Hours Worked</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Day__c/fields/Special_Project__c.field-meta.xml
<CustomField>
    <fullName>Special_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Project</label>
    <referenceTo>Special_Project__c</referenceTo>
    <relationshipLabel>Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Time_Record_Rollup_Day__c/Time_Record_Time_Record_Rollup_Day__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Time Records to Time Record Rollup Day Records</description>
    <label>Time Record Time Record Rollup Day</label>
    <nameField>
        <displayFormat>TRTRRD-{00000000}</displayFormat>
        <label>Time Record Time Record Rollup Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Time Record Rollup Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Time_Record_Rollup_Day__c/fields/Time_Record__c.field-meta.xml
<CustomField>
    <fullName>Time_Record__c</fullName>
    <label>Time Record</label>
    <referenceTo>Time_Record__c</referenceTo>
    <relationshipLabel>Time Record Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Time_Record_Rollup_Days</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record_Time_Record_Rollup_Day__c/fields/Time_Record_Rollup_Day__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Rollup_Day__c</fullName>
    <label>Time Record Rollup Day</label>
    <referenceTo>Time_Record_Rollup_Day__c</referenceTo>
    <relationshipLabel>Time Record Time Record Rollup Days</relationshipLabel>
    <relationshipName>Time_Record_Time_Record_Rollup_Days</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HL_TimeRecordHandler.cls
public class HL_TimeRecordHandler {
    public boolean IsTriggerContext {get{ return isExecuting;}}

    private boolean isExecuting = false;
    private integer batchSize = 0;
    public static Boolean isAfterInsertFlag = false;
    public static Boolean isAfterUpdateFlag = false;
    public static Boolean isAfterDeleteFlag = false;

    public HL_TimeRecordHandler(boolean isExecuting, integer size) {
        isExecuting = isExecuting;
        batchSize = size;
    }

    public void OnAfterInsert(List<Time_Record__c> timeRecordList) {
        if (!isAfterInsertFlag) {
            List<Time_Record__c> completedTimeRecordList = new List<Time_Record__c>();

            for (Time_Record__c t : timeRecordList) {
                if (t.Recording_Status__c == 'Complete') {
                    completedTimeRecordList.add(t);
                }  
               
            }

            isAfterInsertFlag = true;
            HL_TimeRecordRollupDayHandler rollupHandler = new HL_TimeRecordRollupDayHandler(completedTimeRecordList);
            rollupHandler.RollupRecords();
        }
    }
    public void OnBeforeInsert(List<Time_Record__c> timeRecordList){
        for(Time_Record__c t: timeRecordList){
            if(t.Timer_Status__c=='Start'){
                t.Start_Time__c=System.Now();
            }
            system.debug('ggg....'+ t.Start_Time__c);
        }
    }
     public void OnBeforeUpdate(List<Time_Record__c> timeRecordList,Map<Id,Time_Record__c> oldMap){
        for(Time_Record__c t: timeRecordList){
            system.debug('t.Hours_Change__c...'+t.Hours_Change__c);
            system.debug('oldMap.get(t.Id).Hours_Change__c...'+oldMap.get(t.Id).Hours_Change__c);
            Decimal houresChanged;
            if(t.Timer_Status__c=='Stop' && oldMap.get(t.Id).Timer_Status__c=='Stop'&& oldMap.get(t.Id).Hours_Worked__c!=t.Hours_Worked__c){
         houresChanged=t.Hours_Worked__c;
        } 
              if(!t.Hours_Change__c && !String.isBlank(t.Timer_Status__c)){
               if( t.Minutes_Worked__c==null) t.Minutes_Worked__c=0;
                if(t.Add_Minute__c!=null && oldMap.get(t.Id).Add_Minute_Change__c!=t.Add_Minute_Change__c && t.Add_Minute_Change__c){
                system.debug(t.Add_Minute_Change__c+'min change'+t.Add_Minute__c+'Before...'+ t.Minutes_Worked__c);
                       t.Minutes_Worked__c= t.Minutes_Worked__c + t.Add_Minute__c;
                      
                system.debug(t.Add_Minute_Change__c+'min change'+t.Add_Minute__c+'Before...'+ t.Minutes_Worked__c);
                }
               if((t.Timer_Status__c=='Pause' || t.Timer_Status__c=='Stop') && oldMap.get(t.Id).Timer_Status__c=='Start' && oldMap.get(t.Id).Timer_Status__c!=t.Timer_Status__c ){
              
               t.Stop_Time__c=System.Now();
                Long dt1Long = t.Start_Time__c.getTime();
                Long dt2Long = DateTime.now().getTime();
                Decimal milliseconds = dt2Long - dt1Long;
                Decimal seconds = milliseconds / 1000;
                Decimal minutes = seconds / 60;
                //t.Seconds_Worked__c=seconds;
                if(t.Minutes_Worked__c==null)t.Minutes_Worked__c=0;
                t.Minutes_Worked__c= t.Minutes_Worked__c+minutes.setScale(1);
                system.debug('min change'+minutes+'minutes...'+ t.Minutes_Worked__c);
               
        }
        if(t.Timer_Status__c=='Start' && oldMap.get(t.Id).Timer_Status__c!=t.Timer_Status__c){
               t.Start_Time__c=System.Now();
                system.debug('ggg....'+ t.Start_Time__c);
               }
            if(oldMap.get(t.Id).Timer_Status__c!='Stop'){   
         Decimal hours =  t.Minutes_Worked__c/ 60;
        t.Hours_Worked__c=hours.setscale(1);
        t.Seconds_Worked__c=hours.setscale(2);
        }
        }
        system.debug(t.Timer_Status__c+'t.Minutes_Worked__c...'+t.Minutes_Worked__c);
        if(t.Minutes_Worked__c!=null && t.Timer_Status__c=='Stop' && t.Minutes_Worked__c<6&& oldMap.get(t.Id).Timer_Status__c!='Stop'){
             t.Hours_Worked__c=0.1;
                }  
         if(t.Timer_Status__c=='Stop' && oldMap.get(t.Id).Timer_Status__c=='Stop'&& oldMap.get(t.Id).Hours_Worked__c!=houresChanged && houresChanged!=null){
                 t.Hours_Worked__c=houresChanged;
        }          
            
      }  
    }
    public void OnAfterUpdate(List<Time_Record__c> timeRecordList, Map<Id, Time_Record__c> oldTimeRecordMap, Map<Id, Time_Record__c> newTimeRecordMap) {
        if (!isAfterUpdateFlag) {
            List<Time_Record__c> completedTimeRecordList = new List<Time_Record__c>();
            for (Time_Record__c t : timeRecordList) {
                if (t.Recording_Status__c == 'Complete') {
                    completedTimeRecordList.add(t);
                }
                 
            }

            isAfterUpdateFlag = true;
            this.HandleProjectUpdates(oldTimeRecordMap, newTimeRecordMap);
            HL_TimeRecordRollupDayHandler rollupHandler = new HL_TimeRecordRollupDayHandler(completedTimeRecordList);
            rollupHandler.RollupRecords();
           
        }
    }

    public void OnAfterDelete(List<Time_Record__c> timeRecordList) {
        if (!isAfterDeleteFlag) {
            isAfterDeleteFlag = true;
            HL_TimeRecordRollupDayHandler rollupHandler = new HL_TimeRecordRollupDayHandler(timeRecordList);
            rollupHandler.RollupRecords();
        }
    }

    private List<Time_Record__c> HandleProjectUpdates(Map<Id, Time_Record__c> oldTimeRecordMap, Map<Id, Time_Record__c> newTimeRecordMap) {
        List<Time_Record__c> projectUpdateList = new List<Time_Record__c>();
        Map<Id, Time_Record_Rollup_Day__c> rollupUpdateMap = new Map<Id, Time_Record_Rollup_Day__c>();
        Map<Id, Time_Record_Rollup_Day__c> rollupDeleteMap = new Map<Id, Time_Record_Rollup_Day__c>();
        List<Time_Record_Time_Record_Rollup_Day__c> junctionDeleteList = new List<Time_Record_Time_Record_Rollup_Day__c>();
        for (Time_Record__c newTimeRecord : newTimeRecordMap.values()) {
            Time_Record__c oldTimeRecord = oldTimeRecordMap.get(newTimeRecord.Id);
            //Determine if the Project has Changed
            if (!(oldTimeRecord.Opportunity__c == newTimeRecord.Opportunity__c
                    && oldTimeRecord.Engagement__c == newTimeRecord.Engagement__c
                    && oldTimeRecord.Special_Project__c == newTimeRecord.Special_Project__c)) {
                projectUpdateList.add(oldTimeRecord);
            }
        }

        for (Time_Record_Time_Record_Rollup_Day__c j : [SELECT Time_Record_Rollup_Day__c,
                Time_Record__c,
                Time_Record_Rollup_Day__r.Opportunity__c,
                Time_Record__r.Opportunity__c,
                Time_Record_Rollup_Day__r.Engagement__c,
                Time_Record__r.Engagement__c,
                Time_Record_Rollup_Day__r.Special_Project__c,
                Time_Record__r.Special_Project__c,
                Time_Record_Rollup_Day__r.Hours_Worked__c,
                Time_Record__r.Hours_Worked__c
                FROM Time_Record_Time_Record_Rollup_Day__c
                WHERE Time_Record__c IN: projectUpdateList]) {
            if ( (j.Time_Record_Rollup_Day__r.Opportunity__c != null && j.Time_Record_Rollup_Day__r.Opportunity__c != j.Time_Record__r.Opportunity__c) ||
                    (j.Time_Record_Rollup_Day__r.Engagement__c != null && j.Time_Record_Rollup_Day__r.Engagement__c != j.Time_Record__r.Engagement__c) ||
                    (j.Time_Record_Rollup_Day__r.Special_Project__c != null && j.Time_Record_Rollup_Day__r.Special_Project__c != j.Time_Record__r.Special_Project__c)) {
                if (rollupDeleteMap.get(j.Time_Record_Rollup_Day__c) == null) {
                    //Update the Hours Worked or Remove the Record if it is 0
                    Time_Record_Rollup_Day__c trrd = rollupUpdateMap.get(j.Time_Record_Rollup_Day__c);
                    boolean inUpdate = false;

                    if (trrd == null)
                        trrd = j.Time_Record_Rollup_Day__r;
                    else
                        inUpdate = true;

                    trrd.Hours_Worked__c = trrd.Hours_Worked__c - j.Time_Record__r.Hours_Worked__c;

                    if (trrd.Hours_Worked__c > 0)
                        rollupUpdateMap.put(trrd.Id, trrd);
                    else {
                        if (inUpdate)
                            rollupUpdateMap.remove(trrd.Id);

                        rollupDeleteMap.put(trrd.Id, trrd);
                    }
                }
                //Delete the Junction Record
                junctionDeleteList.add(j);
            }
        }

        if (junctionDeleteList.size() > 0)
            delete junctionDeleteList;

        if (rollupDeleteMap.size() > 0)
            delete rollupDeleteMap.values();

        if (rollupUpdateMap.size() > 0)
            update rollupUpdateMap.values();

        return projectUpdateList;
    }


}