force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/recordTypes/FR.recordType-meta.xml
<RecordType>
    <fullName>FR</fullName>
    <active>true</active>
    <description>Financial Restructuring</description>
    <label>FR</label>
</RecordType>

force-app/main/default/objects/Time_Record__c/Time_Record__c.object-meta.xml
<CustomObject>
    <description>Used to track time records</description>
    <label>Time Record</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Time Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Time_Record_Period_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period_Staff_Member__c</fullName>
    <description>Related time record period staff member record</description>
    <label>Time Record Period Staff Member</label>
    <referenceTo>Time_Record_Period_Staff_Member__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/recordTypes/FR.recordType-meta.xml
<RecordType>
    <fullName>FR</fullName>
    <active>true</active>
    <description>FR Time Tracking Record Type</description>
    <label>FR</label>
</RecordType>

force-app/main/default/objects/Time_Record_Period__c/Time_Record_Period__c.object-meta.xml
<CustomObject>
    <description>Time record periods</description>
    <label>Time Record Period</label>
    <nameField>
        <displayFormat>TRP-{00000000}</displayFormat>
        <label>Time Record Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period__c/fields/Period_Category__c.field-meta.xml
<CustomField>
    <fullName>Period_Category__c</fullName>
    <description>Used to categorize the period to allow for multiple functionalities</description>
    <label>Period Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beta</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Litigation</fullName>
                <default>true</default>
                <label>Litigation</label>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>TFR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/Time_Record_Period_Staff_Member__c.object-meta.xml
<CustomObject>
    <label>Time Record Period Staff Member</label>
    <nameField>
        <displayFormat>TRPSM-{00000000}</displayFormat>
        <label>Time Record Period Staff Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Period Staff Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Record Period Staff Members</relationshipLabel>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Time_Record_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period__c</fullName>
    <description>Related time record period record</description>
    <label>Time Record Period</label>
    <referenceTo>Time_Record_Period__c</referenceTo>
    <relationshipLabel>Time Record Period Staff Members</relationshipLabel>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related user record</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/Time_Record_Rollup_Week__c.object-meta.xml
<CustomObject>
    <description>Time record weekly record time, used by the FR Group</description>
    <label>Time Record Rollup Week</label>
    <nameField>
        <displayFormat>TRRW-{00000000}</displayFormat>
        <label>Time Record Rollup Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Rollup Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related engagement</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Record Rollup Weeks</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Time Record Rollup Weeks</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Time_Record_Period_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period_Staff_Member__c</fullName>
    <label>Time Record Period Staff Member</label>
    <referenceTo>Time_Record_Period_Staff_Member__c</referenceTo>
    <relationshipLabel>Time Record Rollup Weeks</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Weeks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HL_TimeRecordRollupWeekHandler.cls
public with sharing class HL_TimeRecordRollupWeekHandler {
	private Time_Record_Period__c TimeRecordPeriod {get; set;}
    private List<Time_Record_Period_Staff_Member__c> StaffMembers {get{
        if(staffMembers == null)
            staffMembers = HL_TimeRecordPeriodStaffMember.GetByPeriod(TimeRecordPeriod.Id);
        
        return staffMembers;
    } set;}

	public HL_TimeRecordRollupWeekHandler(Time_Record_Period__c timeRecordPeriod, List<Time_Record_Period_Staff_Member__c> staffMembers) {
		this.TimeRecordPeriod = timeRecordPeriod;
		this.StaffMembers = staffMembers;
	}

	//Inserts the default Time_Record_Period_Staff_Member__c records based on the period category
    //FR - Inserts the Time_Record__c records for their deals
    public void InsertDefaultRecords(){
        if(TimeRecordPeriod.Period_Category__c == 'FR'){
            Map<Id,Id> contactToUserMap = new Map<Id, Id>();
            Map<Id,Time_Record_Period_Staff_Member__c> contactToStaffMemberMap = new Map<Id,Time_Record_Period_Staff_Member__c>();

            for(Time_Record_Period_Staff_Member__c sm : StaffMembers){
                contactToUserMap.put(sm.Contact__c, sm.User__c);
                contactToStaffMemberMap.put(sm.Contact__c, sm);
            }

            InsertDefaultFRRecords(contactToUserMap, contactToStaffMemberMap);
        }
    }

    //Inserts the default records for FR Staff members for the deals they are staffed on
    private List<Time_Record_Rollup_Week__c> InsertDefaultFRRecords(Map<Id,Id> contactToUserMap, Map<Id, Time_Record_Period_Staff_Member__c> contactToStaffMemberMap){
        Set<String> dealStatuses = new Set<String>{'Active','Hold'};  //Status of deals to insert records for
        Map<Id, Set<Id>> contactToOppMap = HL_Opportunity.GetOpportunityMapByContacts(contactToUserMap.keySet(), dealStatuses);
        Map<Id, Set<Id>> contactToEngMap = HL_Engagement.GetEngagementMapByContacts(contactToUserMap.keySet(), dealStatuses);
        List<Time_Record_Rollup_Week__c> trToInsert = new List<Time_Record_Rollup_Week__c>();
        
        for(Id c : contactToEngMap.keySet()){
            Set<Id> idSet = contactToOppMap.get(c);
            if(idSet != null)
            {
                for(Id o : idSet)
                    trToInsert.add(new Time_Record_Rollup_Week__c(Opportunity__c = o, Time_Record_Period_Staff_Member__c = contactToStaffMemberMap.get(c).Id));
            }
            
            idSet = contactToEngMap.get(c);
            if(idSet != null){
                for(Id e : idSet)
                    trToInsert.add(new Time_Record_Rollup_Week__c(Engagement__c = e, Time_Record_Period_Staff_Member__c = contactToStaffMemberMap.get(c).Id));
            }
           }

        if(trToInsert.size() > 0)
            insert trToInsert;

        return trToInsert;
    }
}