force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Client_Subject__c/Engagement_Client_Subject__c.object-meta.xml
<CustomObject>
    <description>JUNCTION OBJECT: Custom object to track additional clients and subjects for an engagement.</description>
    <label>Engagement Client/Subject</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Clients/Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Client_Subject__c/fields/Client_Subject__c.field-meta.xml
<CustomField>
    <fullName>Client_Subject__c</fullName>
    <inlineHelpText>Client: parties which signed/acceded to HL&apos;s EL (or are anticipated to do so). 
Subject: underlying company</inlineHelpText>
    <label>Client/Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Clients/Subjects</relationshipLabel>
    <relationshipName>Engagement_Clients_Subjects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_Client_Subject__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Additional Clients/Subjects</relationshipLabel>
    <relationshipName>Engagement_Clients_Subjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_Client_Subject__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The primary client or subject defined on the engagement level.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement_Client_Subject__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Key Creditor: (i) creditor-side HL client, (ii) AHG member, (iii) other creditor with meaningful negotiation with the debtor, or (iv) lender holding &gt;10% of total debt or &gt;$50m</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Counterparty</fullName>
            </value>
            <value>
                <fullName>Equity Holder</fullName>
            </value>
            <value>
                <fullName>Key Creditor</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PE Firm</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Client_Subject__c/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Engagement_Client_Subject__c/recordTypes/Subject.recordType-meta.xml
<RecordType>
    <fullName>Subject</fullName>
    <active>true</active>
    <label>Subject</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_C1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SL_RelatedOppEgmtHelper.cls
public with sharing class SL_RelatedOppEgmtHelper {
    public static Boolean ALREADY_UPDATED = false;

    /*
        * MethodName        : createInitialRelatedJoiners
        * param             : Map<id, SObject> newOppsEgmts, String oppOrEgmt
        * Description       : This function is called after inserting Opportunity or Engagement records
                              It creates Related Opportunity/Engagement Joiner object records.
    */
    public static void createInitialRelatedJoiners (Map<Id, SObject> newOppsEgmts, String oppOrEgmt){
        Schema.SObjectType joinerType = Schema.getGlobalDescribe().get(oppOrEgmt);
        String parentAPI = oppOrEgmt == 'Engagement_Client_Subject__c' ? 'Engagement__c' : 'Opportunity__c';
 
        // Map used to store filter Engagements which have either client__c or Subject__c field populated to create Joiner Object records.
        // Z.Engman: Prevent this from continuing for engagements converted from opportunities since the conversion handler already mapps the joiner object separately
        Map<Id,SObject> filteredNewOppsEgmts = new Map<Id,SObject>(); 
        for(SObject newOppEng : newOppsEgmts.values()){
            if(!(parentAPI == 'Engagement__c' && newOppEng.get('Engagement__c') == null) && (newOppEng.get('Client__c') != null || newOppEng.get('Subject__c') != null))
                filteredNewOppsEgmts.put((Id)newOppEng.get('Id'),newOppEng);
        }
        // Method Called to insert Joiner Object records for newly inserted Opportunities having either Client or Subject Field Populated.
        if(filteredNewOppsEgmts.isEmpty()){
            return;
        }
        List<SObject> joinersToInsert = new List<SObject>(); 
    
        for(SObject oppOrEng: filteredNewOppsEgmts.values()){
            if(oppOrEng.get('Client__c') != null){                                                                        
                // Adding in a List to insert Joiner object record                                                                    
                joinersToInsert.add(createJoinerRecord(parentAPI, (String) oppOrEng.get('Id'), (String) oppOrEng.get('Client__c'), 'Client', joinerType));                                             
            } //&& oppOrEng.get('Subject__c') != oppOrEng.get('Client__c')
            if(oppOrEng.get('Subject__c') != null){
                joinersToInsert.add(createJoinerRecord(parentAPI, (String) oppOrEng.get('Id'), (String) oppOrEng.get('Subject__c'), 'Subject', joinerType));    
            }
        }
        if(!joinersToInsert.IsEmpty())
            Database.insert(joinersToInsert,false);
    }

    private static SObject createJoinerRecord(String parentAPI, String parentId, String clientSubject, String type, Schema.SObjectType joinerType){
        SObject joinerRecord = joinerType.newSObject();
        joinerRecord.put(parentAPI, parentId);
        joinerRecord.put('Client_Subject__c', clientSubject);
        joinerRecord.put('Primary__c', true);
        joinerRecord.put('Type__c', type);     
        return joinerRecord;
    }

    /*
        * MethodName        : updateRelatedJoiners
        * param             : Map<Id, SObject> newOppsEgmts, Map<Id, SObject> oldOppsEgmts
        * Description       : This function is called after updating an opportunity or engagement Records(either Client__c or Subject__c field) to 
                              Create/Update/Delete Related Opportunity/Engagement Joiner object records.
    */
    public static void updateRelatedJoiners (Map<Id, SObject> newOppsEgmts, Map<Id, SObject> oldOppsEgmts, String oppOrEgmt)  {
        if (ALREADY_UPDATED) {
            return;
        }

        ALREADY_UPDATED = true;
        
        Schema.SObjectType joinerType = Schema.getGlobalDescribe().get(oppOrEgmt);
        String parentAPI = oppOrEgmt == 'Engagement_Client_Subject__c' ? 'Engagement__c' : 'Opportunity__c';
        // List used to store Joiner records which will be deleted when Client__c Or Subject__c field is nullified.
        List<SObject> joinerRecordsToDelete = new List<SObject>(); 
        // List used to store Joiner records which will be inserted when Client__c Or Subject__c field is Populated.
        List<SObject> joinerRecordsToCreate = new List<SObject>(); 

        //Set of AccountIds that have tobe deleted from the joiner object
        Set<Id> accountIds = new Set<Id>();

        //Map to store all the updated client or Subject values
        Map<String, Id> clientOrSubjectToOppOrEng = new Map<String, Id>();
        Set<String> deletionCodes = new Set<String>();
        for(SObject opportunityorEngagement : newOppsEgmts.values()){
            if(opportunityorEngagement.get('Client__c') !=  oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Client__c')){
                //Put the Client value into the map, insert a new record of type 'Client' 
                clientOrSubjectToOppOrEng.put(opportunityorEngagement.get('Client__c') + '_' + opportunityorEngagement.get('Id') + '_' + 'Client', (Id)opportunityorEngagement.get('Client__c'));
                // if the client and subject are now the same
                //if (opportunityorEngagement.get('Client__c')==opportunityorEngagement.get('Subject__c')){
                    // delete the 'Subject' record
                     //Id idAccount = (Id) oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Subject__c');
                     //deletionCodes.add(idAccount + '_' + opportunityorEngagement.get('Id') + '_' + 'Subject');
                     //accountIds.add(idAccount);
                //}
                // if the client and subject were the same, and the subject has not changed
                //if (oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Client__c') == oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Subject__c') && opportunityorEngagement.get('Subject__c') == oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Subject__c')){
                    //Put the Subject value into the map, insert a new record of type 'Subject'
                    //clientOrSubjectToOppOrEng.put(opportunityorEngagement.get('Subject__c') + '_' + opportunityorEngagement.get('Id') + '_' + 'Subject', (Id)opportunityorEngagement.get('Subject__c'));
                //}
                // delete the old 'Client' record associated with this Engagement
                Id idAccount = (Id)oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Client__c');
                deletionCodes.add(idAccount + '_' + opportunityorEngagement.get('Id') + '_' + 'Client');
                accountIds.add(idAccount);
            }
            if(opportunityorEngagement.get('Subject__c') != oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Subject__c')){
                // if the client and subject are not the same
                //if(opportunityorEngagement.get('Client__c') != opportunityorEngagement.get('Subject__c')){
                    //Put the Subject value into the Map, insert a new record of type 'Subject'  
                    clientOrSubjectToOppOrEng.put(opportunityorEngagement.get('Subject__c') + '_' + opportunityorEngagement.get('Id') + '_'  + 'Subject', (Id)opportunityorEngagement.get('Subject__c'));
               //}
                // delete the old 'Subject' record associated with this Engagement
                Id idAccount = (Id)oldOppsEgmts.get((Id)opportunityorEngagement.get('Id')).get('Subject__c');
                deletionCodes.add(idAccount + '_' + opportunityorEngagement.get('Id') + '_' + 'Subject');
                accountIds.add(idAccount);
            }
        }
        String query = 'SELECT Id, Client_Subject__c,Type__c, '+ parentAPI  
                       +' FROM '+oppOrEgmt+' WHERE Client_Subject__c IN :accountIds';
        //collect all the Engagement Client subject to be deleted
        for(SObject objOpportuntiyClientSub : Database.query(query)){            
            if(deletionCodes.Contains(objOpportuntiyClientSub.get('Client_Subject__c') + '_' + objOpportuntiyClientSub.get(parentAPI) + '_' + objOpportuntiyClientSub.get('Type__c')))
                joinerRecordsToDelete.add(objOpportuntiyClientSub);
        }
        //iterate the clientOrSubjectToOppOrEng to create new EngagementClientSubject records
        for(String strAccountEngagementType : clientOrSubjectToOppOrEng.keyset()){
            if(strAccountEngagementType.split('_')[2] == 'Subject'){
                 // Adding in a List to insert Joiner object record   
                 joinerRecordsToCreate.add(createJoinerRecord(parentAPI, strAccountEngagementType.split('_')[1], clientOrSubjectToOppOrEng.get(strAccountEngagementType), 'Subject', joinerType));    
         
            }
            else if(strAccountEngagementType.split('_')[2] == 'Client'){
                 // Adding in a List to insert Joiner object record                                                                
                 joinerRecordsToCreate.add(createJoinerRecord(parentAPI, strAccountEngagementType.split('_')[1], clientOrSubjectToOppOrEng.get(strAccountEngagementType), 'Client', joinerType));  
            }
        }
        //Delete the Records
        if(!joinerRecordsToDelete.IsEmpty()) {
            // Added by Sandeep (SF-507 Date 17th March 2017) Purpose: To stop deleting opportunity client Subject record In trigger 'HL_OpportunityClientSubjectTrigger'
            HL_ConstantsUtil.StopValidation = true;
            Database.delete(joinerRecordsToDelete,false);
            // Added by Sandeep (SF-507 Date 17th March 2017)
            HL_ConstantsUtil.StopValidation = false;
        }
        //Create new records
        if(!joinerRecordsToCreate.IsEmpty())
          // Database.insert(joinerRecordsToCreate,false);
          // Added by Harsh (SF-400 Date 23th March 2017) Purpose: To stop duplicate opportunity client or opportunity Subject on opportunity client Subject record in trigger 'HL_OpportunityClientSubjectTrigger'
            insert joinerRecordsToCreate ;
    }
}