force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/Opp_VP__c.object-meta.xml
<CustomObject>
    <label>Opportunity Valuation Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Valuation Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_VP__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Opportunity record</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity_Portfolio_Valuations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/HL_RedirectingToPVController.cls
public class HL_RedirectingToPVController {

public boolean IsPVConversionCompeleted {get;set;}
public boolean isError{get;set;}
String EngRecordId;
String OppRecordId;   

Public String ErrorMessage{get;set;}

public HL_RedirectingToPVController()
{
    IsPVConversionCompeleted = false;
    isError = false;
    EngRecordId = apexpages.currentpage().getparameters().get('id');
    OppRecordId = apexpages.currentpage().getparameters().get('Oppid');
}
private List<Engagement__c> newEngagement;

Public Pagereference calculate(){
    Savepoint sp = Database.setSavepoint();
    try
    {            
        List<Opp_Vp__C> listofVP = new List<Opp_VP__c>();
        listofVP = [Select id From Opp_VP__c Where Isconverted__C = false AND Opportunity__c = : OppRecordId];    
        if(listofVP.size() > 0){ 
            // To stop un-necessary operations related to PV while converting opportunity in to engagement
            
            HL_ConstantsUtil.stopExecutionForPVConversion = true;
            PVConversion();              
            HL_ConstantsUtil.stopExecutionForPVConversion = false;            
            return null;  
        }
        else
        {
            IsPVConversionCompeleted = true;
            return new Pagereference('/apex/HL_Related_PortfolioValuations?id='+EngRecordId  +'&relatedObjType=EngVP');
        }       
    }
    catch(exception e)
    {
        Database.rollback( sp );
        isError = true;
        IsPVConversionCompeleted = true; 
        ErrorMessage  = e.getmessage();
        ApexPages.addmessages(e);
        return null;            
    }   
}

private void PVConversion(){
        try{
            system.debug('----'+limits.getQueries());            
            if(EngRecordId != null && Label.Allow_Portfolio_Valuation_Conversion == 'True')
                SL_EngagementConversionHelper.ConvertOppVPs(EngRecordId,OppRecordId);
            system.debug('----'+limits.getQueries());         
        }
        catch(Exception e){
            throw e;
        }
    }
public PageReference BackToEnagement() {
        return new PageReference('/'+EngRecordId);
    } 

}