force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Projected_Monthly_Fee__c.field-meta.xml
<CustomField>
    <fullName>Projected_Monthly_Fee__c</fullName>
    <label>Projected Monthly Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Projected_Transaction_Fee__c.field-meta.xml
<CustomField>
    <fullName>Projected_Transaction_Fee__c</fullName>
    <label>Projected Transaction Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Projection__c/Revenue_Projection__c.object-meta.xml
<CustomObject>
    <label>Revenue Projection</label>
    <nameField>
        <displayFormat>PROJ-REV{000000}</displayFormat>
        <label>Revenue Projection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Projections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Projection__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Projection__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Revenue Projections</relationshipLabel>
    <relationshipName>Revenue_Projections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_RevenueProjectionViewController.cls
public class HL_RevenueProjectionViewController {
    
    private Id EngId;
    public List<Revenue_Projection__c> revenueProjectionList {get;set;}
    
    public HL_RevenueProjectionViewController (ApexPages.StandardController stdController){
        EngId = stdController.getRecord().Id;
        revenueProjectionList = [SELECT Year__c, Month__c, Projected_Transaction_Fee__c, Projected_Monthly_Fee__C, Archive__c FROM Revenue_Projection__c WHERE Engagement__c =: EngId ORDER BY Year__c,Month__C ASC LIMIT 13];                
    }

    public PageReference getRedirectToPage() {
        PageReference redirect = new PageReference('/apex/HL_RP?id=' + EngId);
        redirect.setRedirect(true);
        return redirect;
    }
    
    public PageReference getRedirectToPageView() {
        PageReference redirect = new PageReference('/apex/HL_RevenueProjectionRelatedListView?id=' + EngId);
        redirect.setRedirect(true);
        return redirect;
    }
}