force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/recordTypes/Sellside.recordType-meta.xml
<RecordType>
    <fullName>Sellside</fullName>
    <active>true</active>
    <label>Sellside</label>
</RecordType>

force-app/main/default/classes/Test_hlUniversalLookupController.cls
@isTest
private class Test_hlUniversalLookupController {
    @isTest static void hlBasicTest(){
        Account a = SL_TestSetupUtils.CreateAccount('Test_Houlihan', 1)[0];
        a.Ownership = 'Private';
        insert a;
        Engagement__c e = SL_TestSetupUtils.CreateEngagement('Test_Houlihan', 1)[0];
        e.RecordTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Sellside').getRecordTypeId();
        e.Client__c = a.Id;
        e.Subject__c = a.Id;
        insert e;
        system.debug('Engagement__c-e' + e);
        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = e.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        Test.startTest();
            String objectApi = 'Engagement__c'; 
            String filter = 'Test_Houlihan0'; 
            List<String> fields = new List<String>{'Id','Name'};
            String sortField = 'Name';
            String sortDirection = 'ASC';
            List<SObject> lookupData = hlUniversalLookupController.getLookupSearch(objectApi,filter,fields,sortField,sortDirection,'5');
            system.debug('lookupData1' + lookupData.size());
        Test.stopTest();
        //System.assert(lookupData.size() > 0);
    }
}