force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Special_Project__c.field-meta.xml
<CustomField>
    <fullName>Special_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Projects labeled as the special project will need to go through a separate scoping committee</description>
    <label>Special Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/FR.recordType-meta.xml
<RecordType>
    <fullName>FR</fullName>
    <active>true</active>
    <description>Financial Restructuring</description>
    <label>FR</label>
</RecordType>

force-app/main/default/objects/Special_Project__c/Special_Project__c.object-meta.xml
<CustomObject>
    <description>Used to store non-billable or non-case related special projects.</description>
    <label>Special Project</label>
    <nameField>
        <label>Special Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Project__c/recordTypes/FR.recordType-meta.xml
<RecordType>
    <fullName>FR</fullName>
    <active>true</active>
    <description>FR Special Projects for Time Tracking</description>
    <label>FR</label>
</RecordType>

force-app/main/default/objects/Time_Record_Period__c/Time_Record_Period__c.object-meta.xml
<CustomObject>
    <description>Time record periods</description>
    <label>Time Record Period</label>
    <nameField>
        <displayFormat>TRP-{00000000}</displayFormat>
        <label>Time Record Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/Time_Record_Period_Staff_Member__c.object-meta.xml
<CustomObject>
    <label>Time Record Period Staff Member</label>
    <nameField>
        <displayFormat>TRPSM-{00000000}</displayFormat>
        <label>Time Record Period Staff Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Period Staff Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Time_Record_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period__c</fullName>
    <description>Related time record period record</description>
    <label>Time Record Period</label>
    <referenceTo>Time_Record_Period__c</referenceTo>
    <relationshipLabel>Time Record Period Staff Members</relationshipLabel>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/Time_Record_Rollup_Week__c.object-meta.xml
<CustomObject>
    <description>Time record weekly record time, used by the FR Group</description>
    <label>Time Record Rollup Week</label>
    <nameField>
        <displayFormat>TRRW-{00000000}</displayFormat>
        <label>Time Record Rollup Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Rollup Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related engagement</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Record Rollup Weeks</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Hours_Worked_Weekday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Worked_Weekday__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Hours worked for the week for the project. Used in FR Time Tracking</description>
    <label>Hours Worked Weekday</label>
    <precision>5</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Hours_Worked_Weekend__c.field-meta.xml
<CustomField>
    <fullName>Hours_Worked_Weekend__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Hours worked for the week on the weekend. Used for FR Time Tracking</description>
    <label>Hours Worked Weekend</label>
    <precision>5</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Time Record Rollup Weeks</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Special_Project__c.field-meta.xml
<CustomField>
    <fullName>Special_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Project</label>
    <referenceTo>Special_Project__c</referenceTo>
    <relationshipLabel>Time Record Rollup Weeks</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Rollup_Week__c/fields/Time_Record_Period_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period_Staff_Member__c</fullName>
    <label>Time Record Period Staff Member</label>
    <referenceTo>Time_Record_Period_Staff_Member__c</referenceTo>
    <relationshipLabel>Time Record Rollup Weeks</relationshipLabel>
    <relationshipName>Time_Record_Rollup_Weeks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HL_TimeRecordRollupWeekController.cls
public with sharing class HL_TimeRecordRollupWeekController extends HL_TimeRecordControllerBase {
    @AuraEnabled
    public static List<Time_Record_Rollup_Week__c> GetTimeRecordWeekRollups(Id timeRecordPeriodStaffMemberId){
        return HL_TimeRecordRollupWeek.GetByTimeRecordPeriodStaffMember(timeRecordPeriodStaffMemberId);
    }

    @AuraEnabled
    public static List<Time_Record_Period_Staff_Member__c> GetTimeRecordPeriodStaffMemberByPeriodAndUser(Id timeRecordPeriodId, Id userId){
        return HL_TimeRecordPeriodStaffMember.GetByPeriodAndUser(timeRecordPeriodId, userId);
    }

    @AuraEnabled
    public static Time_Record_Period__c GetCurrentPeriod(string category){
        return HL_TimeRecordControllerBase.GetCurrentPeriod(category);
    }

    @AuraEnabled
    public static Time_Record_Period_Staff_Member__c GetCurrentTimeRecordPeriodStaffMemberRecord(string category){
        return HL_TimeRecordControllerBase.GetCurrentTimeRecordPeriodStaffMemberRecord(category);
    }

    @AuraEnabled
    public static String GetCategory(){
        return HL_Group.GetTimeTrackingGroup();
    }

    @AuraEnabled
    public static Time_Record_Rollup_Week__c UpdateHoursWorkedWeekday(Id recordId, decimal value){
        Time_Record_Rollup_Week__c tr = new Time_Record_Rollup_Week__c(Id = recordId, Hours_Worked_Weekday__c = value);
        update tr;
        return tr;
    }

    @AuraEnabled
    public static Time_Record_Rollup_Week__c UpdateHoursWorkedWeekend(Id recordId, decimal value){
        Time_Record_Rollup_Week__c tr = new Time_Record_Rollup_Week__c(Id = recordId, Hours_Worked_Weekend__c = value);
        update tr;
        return tr;
    }

    @AuraEnabled
    public static Time_Record_Rollup_Week__c UpdateComments(Id recordId, string value){
        Time_Record_Rollup_Week__c tr = new Time_Record_Rollup_Week__c(Id = recordId, Comments__c = value);
        update tr;
        return tr;
    }

    @AuraEnabled
    public static Time_Record_Rollup_Week__c InsertRollupWeekRecord(Time_Record_Rollup_Week__c tr){
        //Insert the time record rollup week
        HL_TimeRecordRollupWeek rollupWeek = new HL_TimeRecordRollupWeek(tr);
        return rollupWeek.InsertRecord();
    }

    @AuraEnabled
    public static Time_Record_Rollup_Week__c DeleteRecord(Id recordId){
        Time_Record_Rollup_Week__c tr = new Time_Record_Rollup_Week__c(Id = recordId);
        delete tr;
        return tr;
    }

    //Determines if the user is in the supervisor group
    @AuraEnabled
    public static Boolean IsSupervisor(string category){
        return HL_TimeRecordControllerBase.IsSupervisor(category);
    }

    @AuraEnabled
    public static List<Opportunity__c> GetOpportunities(string category, string userId){
        return HL_TimeRecordControllerBase.GetOpportunities(category, userId);
    }

    @AuraEnabled
    public static List<Special_Project__c> GetSpecialProjects(){
        string category = GetCategory();
        if(String.isBlank(category))
            category = 'FR';
        Id spRecordTypeId = Schema.sObjectType.Special_Project__c.getRecordTypeInfosByName().get(category).getRecordTypeId();
        return HL_TimeRecordControllerBase.GetSpecialProjects(spRecordTypeId);
    }

    @AuraEnabled
    public static List<Engagement__c> GetEngagements(string category, string userId){
        return HL_TimeRecordControllerBase.GetEngagements(category, userId);
    }

}