force-app/main/default/objects/Campaign/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Engagement__c.Stage__c</field>
            <operation>equals</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Closed engagements shown by default.  &quot;Show All Results&quot; will display all matching engagements.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <formula>Engagement__r.Engagement_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <inlineHelpText>Case Number</inlineHelpText>
    <label>Engagement Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c, &quot;Closed&quot;), &quot;Closed&quot;,
IF(ISPICKVAL(Stage__c, &quot;Hold&quot;), &quot;Hold&quot;,
IF(ISPICKVAL(Stage__c, &quot;Dead&quot;), &quot;Dead&quot;,
&quot;Active&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_TestFactory.cls
public with sharing class HL_TestFactory extends SmartFactory {
    public Enum ContactRecordType{Houlihan_Employee, External_Contact}
    
    public static boolean SetFillAllFields(boolean fillAllFields){
        SmartFactory.FillAllFields = fillAllFields;
        return SmartFactory.FillAllFields;
    }
    
    public static Map<String, Set<String>> AddIncludedField(string objectType, Set<String> fieldSet){
        SmartFactory.IncludedFields.put(objectType, fieldSet);
        return SmartFactory.IncludedFields;
    }
    
    public static Map<String, Set<String>> AddExcludedField(string objectType, Set<String> fieldSet){
        SmartFactory.ExcludedFields.put(objectType, fieldSet);
        return SmartFactory.ExcludedFields;
    }
    
    public static SObject CreateSObject(string objectType, boolean cascade) {
        return SmartFactory.CreateSObject(objectType, cascade, 1);
    }
    
    public static List<SObject> CreateSObjectList(string objectType, boolean cascade, integer numberOfObjects) {
        return SmartFactory.CreateSObjectList(objectType, cascade, numberOfObjects);
    }
    
    public static Campaign CreateCampaign(boolean cascade){
        return CreateCampaignList(cascade, 1)[0];
    }
    
    public static List<Campaign> CreateCampaignList(boolean cascade, integer numberOfObjects){
        List<Campaign> campaignList = (List<Campaign>)SmartFactory.CreateSObjectList('Campaign', cascade, numberOfObjects);
        
        for(integer i = 0; i < campaignList.size(); i++)
            campaignList[i].Name = 'Test_' + String.valueOf(i);
        
        return campaignList;
    }
    
    public static Contact CreateContact(ContactRecordType recordType, boolean cascade){
        return CreateContactList(recordType, cascade, 1)[0];
    }
    
    public static List<Contact> CreateContactList(ContactRecordType recordType, boolean cascade, integer numberOfObjects){
        List<Contact> contactList = (List<Contact>)SmartFactory.CreateSObjectList('Contact', cascade, numberOfObjects);
        string recordTypeDeveloperName = recordType == ContactRecordType.Houlihan_Employee ? 'Houlihan_Employee' : 'External_Contact';
        Id recordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' AND RecordType.DeveloperName =: recordTypeDeveloperName].Id;
        
        for(integer i = 0; i < contactList.size(); i++){
            contactList[i].FirstName = 'Test_' + String.valueOf(i);
            contactList[i].LastName = 'Test_' + String.valueOf(i);
            contactList[i].Status__c = 'Active';
            contactList[i].RecordTypeId = recordTypeId;
        }
        
        return contactList;
    }
    
    public static Engagement__c CreateEngagement(boolean cascade){
        return CreateEngagementList(cascade, 1)[0];
    }
    
    public static List<Engagement__c> CreateEngagementList(boolean cascade, integer numberOfObjects){
        List<Engagement__c> engagementList = (List<Engagement__c>)SmartFactory.CreateSObjectList('Engagement__c', cascade, numberOfObjects);
        
        for(integer i = 0; i < engagementList.size(); i++){
            engagementList[i].Name = String.valueOf(i);
            engagementList[i].Engagement_Number__c = String.valueOf(i);
        }
        
        return engagementList;
    }
    
}