force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_C1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/Opportunity_Client_Subject__c.object-meta.xml
<CustomObject>
    <description>Custom object to track additional clients and subjects for an opportunity.</description>
    <label>Opportunity Client/Subject</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Clients/Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Client_Subject__c.field-meta.xml
<CustomField>
    <fullName>Client_Subject__c</fullName>
    <inlineHelpText>Client: parties which signed/acceded to HL&apos;s EL (or are anticipated to do so). 
Subject: underlying company</inlineHelpText>
    <label>Client/Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Additional Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Public_Or_Private__c.field-meta.xml
<CustomField>
    <fullName>Public_Or_Private__c</fullName>
    <description>Used on the FEIS form, required by legal for the user to specify the ownership of the company</description>
    <label>Public Or Private</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Key Creditor: (i) creditor-side HL client, (ii) AHG member, (iii) other creditor with meaningful negotiation with the debtor, or (iv) lender holding &gt;10% of total debt or &gt;$50m</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Key Creditor</fullName>
            </value>
            <value>
                <fullName>PE Firm</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Type = &quot;Client&quot;</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Subject.recordType-meta.xml
<RecordType>
    <fullName>Subject</fullName>
    <active>true</active>
    <description>Type = &quot;Subject&quot;</description>
    <label>Subject</label>
</RecordType>

force-app/main/default/classes/Test_HL_OpportunityClientSubjectHandler.cls
@isTest
private class Test_HL_OpportunityClientSubjectHandler {
   @isTest private static void TestBasicFunctionality(){
        //Setup Test Data
        Opportunity__c opp = SL_TestSetupUtils.CreateOpp('',1)[0];
        opp.Beneficial_Owner_Control_Person_form__c = 'No';
        insert opp;
        //Create a Public Ownership and Private Ownership Account
        List<Account> aList = SL_TestSetupUtils.CreateAccount('', 2);
        aList[0].Ownership = 'Private Equity';
        aList[1].Ownership = 'Public Debt';
        insert aList;
        
        //Test Public or Private Field Trigger Updates
        //Insert a Private Company OCS record
        Opportunity_Client_Subject__c ocs = new Opportunity_Client_Subject__c(Opportunity__c = opp.Id, Client_Subject__c = aList[0].Id);
        insert ocs;

        //Verify the PublicOrPrivate field is now Private
        opp = [SELECT Client__c, Subject__c, Public_Or_Private__c FROM Opportunity__c WHERE Id =: opp.Id];
        System.assert(opp.Public_Or_Private__c == 'Private');
        
        //Insert a Public Company OCS record
        ocs = new Opportunity_Client_Subject__c(Opportunity__c = opp.Id, Client_Subject__c = aList[1].Id);
        insert ocs;
                
        //Verify the PublicOrPrivate field is now Public
        opp = [SELECT Client__c, Subject__c, Public_Or_Private__c FROM Opportunity__c WHERE Id =: opp.Id];
        System.assert(opp.Public_Or_Private__c == 'Public');  
    }
    
    @isTest private static void TestBasicFunctionalityToUpdate(){
        //Setup Test Data
        Opportunity__c opp = SL_TestSetupUtils.CreateOpp('',1)[0];
        opp.Beneficial_Owner_Control_Person_form__c = 'No';
        insert opp;
        //Create a Public Ownership and Private Ownership Account
        List<Account> aList = SL_TestSetupUtils.CreateAccount('', 2);
        aList[0].Ownership = 'Private Equity';
        aList[1].Ownership = 'Public Debt';
        insert aList;
        
        //Test Public or Private Field Trigger Updates
        //Insert a Private Company OCS record
        Opportunity_Client_Subject__c ocs1 = new Opportunity_Client_Subject__c(Opportunity__c = opp.Id,type__c = 'Client', Client_Subject__c = aList[0].Id);
        Opportunity_Client_Subject__c ocs2 = new Opportunity_Client_Subject__c(Opportunity__c = opp.Id,type__c = 'Subject', Client_Subject__c = aList[1].Id);
        List<Opportunity_Client_Subject__c > OCSList = new List<Opportunity_Client_Subject__c >();
        OCSList.add(ocs1);
        OCSList.add(ocs2);        
        insert OCSList ;

        ocs1.type__c = 'Subject'; 
        update ocs1;
        
    }
    
     @isTest private static void TestBasicFunctionalityToDelete(){
        //Setup Test Data
        Opportunity__c opp = SL_TestSetupUtils.CreateOpp('',1)[0];
        opp.Beneficial_Owner_Control_Person_form__c = 'No';
        insert opp;
        //Create a Public Ownership and Private Ownership Account
        List<Account> aList = SL_TestSetupUtils.CreateAccount('', 2);
        aList[0].Ownership = 'Private Equity';
        aList[1].Ownership = 'Public Debt';
        insert aList;
        
        //Test Public or Private Field Trigger Updates
        //Insert a Private Company OCS record
        Opportunity_Client_Subject__c ocs1 = new Opportunity_Client_Subject__c(Opportunity__c = opp.Id,type__c = 'Client', Client_Subject__c = aList[0].Id);
        Opportunity_Client_Subject__c ocs2 = new Opportunity_Client_Subject__c(Opportunity__c = opp.Id,type__c = 'Subject', Client_Subject__c = aList[1].Id);
        List<Opportunity_Client_Subject__c > OCSList = new List<Opportunity_Client_Subject__c >();
        OCSList.add(ocs1);
        OCSList.add(ocs2);        
        insert OCSList ;

       // ocs1.type__c = 'Subject'; 
      //  update ocs1;
        Delete ocs1;
        
        
    }
    
}