force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/Opportunity_Approval__c.object-meta.xml
<CustomObject>
    <description>These records are related to Opportunities and are required for submission before attaining committee approval and engagement.</description>
    <label>Opportunity Review</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Opportunity Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <inlineHelpText>Please indicate the related Opportunity record.</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Reviews</relationshipLabel>
    <relationshipName>Opportunity_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HL_OpportunityApproval.cls
public with sharing class HL_OpportunityApproval {
      public static Opportunity_Approval__c GetById(string Id){
        List<Opportunity_Approval__c> oa = Database.Query(GetFullSelect() + 
                                                          'FROM Opportunity_Approval__c ' + 
                                                          'WHERE Id =: Id');
        return oa.size() > 0 ? oa[0] : null;
    }
    
    public static string GetFullSelect(){
        Map<String, Schema.SObjectField> fldObjMap = schema.SObjectType.Opportunity_Approval__c.fields.getMap();
		List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
        String q = 'SELECT Related_Opportunity__r.Name, ';
        // Build dynamic query string
        for(Schema.SObjectField s : fldObjMapValues)
           q += s.getDescribe().getName() + ',';
        // Trim last comma
		q = q.subString(0, q.length() - 1);
        return q + ' ';
    }
}