force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/DND_Status__c.field-meta.xml
<CustomField>
    <fullName>DND_Status__c</fullName>
    <label>DND Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add Requested</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>Removal Requested</fullName>
            </value>
            <value>
                <fullName>RELEASED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/DND_Submitter_Email__c.field-meta.xml
<CustomField>
    <fullName>DND_Submitter_Email__c</fullName>
    <label>DND Submitter Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opp_Name_Store__c.field-meta.xml
<CustomField>
    <fullName>Opp_Name_Store__c</fullName>
    <label>Opp Name Store</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/TAS_DND__c.field-meta.xml
<CustomField>
    <fullName>TAS_DND__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates deal as TAS DND</description>
    <inlineHelpText>Indicates deal as TAS DND</inlineHelpText>
    <label>TAS DND</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/z_Principal_Aggregate_CHECK__c.field-meta.xml
<CustomField>
    <fullName>z_Principal_Aggregate_CHECK__c</fullName>
    <description>TO CHECK FOR ID CURRENT USER</description>
    <formula>CONTAINS(z_Principal_Aggregate__c,$User.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>z_Principal_Aggregate_CHECK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TAS_DNDController.cls
Global class TAS_DNDController {
   
    Webservice static string DnDOnOff(Id recordId){ 
        
        System.debug('recordId'+recordId);
        
       
        Opportunity__c opptyRecord = [Select id,TAS_DND__c, DND_Status__c, Opp_Name_Store__c,z_Principal_Aggregate_CHECK__c , Name, DND_Submitter_Email__c From Opportunity__c where id =:recordId];
        
        try{
            
            return updateOpportunity(opptyRecord);
            //return 'Successfully completed the operation';
           
        }
        catch(DMLException dmlEx){return dmlEx.getDMLMessage(0);}catch(Exception ex){return ex.getMessage();}
        

    
    }
    
    public static String updateOpportunity(Opportunity__c opptyRecord){
        if(opptyRecord.DND_Status__c != 'APPROVED'){
            opptyRecord.DND_Submitter_Email__c  = UserInfo.getUserEmail();
            opptyRecord.Opp_Name_Store__c = opptyRecord.Name;
            opptyRecord.Name = 'DND – '+opptyRecord.Id;
            opptyRecord.DND_Status__c = 'APPROVED';
            opptyRecord.TAS_DND__c = true;
            update opptyRecord;
            return System.label.HL_TASDNDON ;
        }else{
            opptyRecord.DND_Submitter_Email__c  = UserInfo.getUserEmail();
            opptyRecord.Name = opptyRecord.Opp_Name_Store__c;
            opptyRecord.DND_Status__c = 'RELEASED'; 
            opptyRecord.TAS_DND__c = false;
            update opptyRecord;
            return System.label.HL_TASDNDOFF  ;
        }
        
        
    }
    
    
}