force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/SC.recordType-meta.xml
<RecordType>
    <fullName>SC</fullName>
    <active>true</active>
    <description>Strategic Consulting</description>
    <label>SC</label>
</RecordType>

force-app/main/default/objects/Opportunity_Client_Subject__c/Opportunity_Client_Subject__c.object-meta.xml
<CustomObject>
    <description>Custom object to track additional clients and subjects for an opportunity.</description>
    <label>Opportunity Client/Subject</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Clients/Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Client_Subject__c.field-meta.xml
<CustomField>
    <fullName>Client_Subject__c</fullName>
    <inlineHelpText>Client: parties which signed/acceded to HL&apos;s EL (or are anticipated to do so). 
Subject: underlying company</inlineHelpText>
    <label>Client/Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Additional Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The primary client or subject defined on the opportunity level.</inlineHelpText>
    <label>Primary?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Key Creditor: (i) creditor-side HL client, (ii) AHG member, (iii) other creditor with meaningful negotiation with the debtor, or (iv) lender holding &gt;10% of total debt or &gt;$50m</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Key Creditor</fullName>
            </value>
            <value>
                <fullName>PE Firm</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Contra.recordType-meta.xml
<RecordType>
    <fullName>Contra</fullName>
    <active>true</active>
    <description>Type = &quot;Contra&quot;</description>
    <label>Contra</label>
</RecordType>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Subject.recordType-meta.xml
<RecordType>
    <fullName>Subject</fullName>
    <active>true</active>
    <description>Type = &quot;Subject&quot;</description>
    <label>Subject</label>
</RecordType>

force-app/main/default/classes/HLClientSubOppButtonControllerTest.cls
@isTest
public class HLClientSubOppButtonControllerTest {
    @isTest
    public static void testMethodFoOppClientSub (){
        Account newClient = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newClient;
        Account newSubject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newSubject;
        
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('', 1)[0];
        o.Beneficial_Owner_Control_Person_form__c = 'No';
        insert o;
        Opportunity_Client_Subject__c addClient = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Client_Subject__c = newClient.Id, Type__c = 'Contra');
        insert addClient;
        Opportunity_Client_Subject__c addSubject = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Primary__c = false, Client_Subject__c = newSubject.Id, Type__c = 'Subject');
        insert addSubject;
        Test.startTest();
        
        
        PageReference pageRef = Page.HLClientSubOppButton; // Add your VF page Name here
        pageRef.getParameters().put('opportunityId', String.valueOf(o.Id));
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(o);
        HLClientSubOppButtonController testAccPlan = new HLClientSubOppButtonController(sc);
        testAccPlan.redirect();
        HLClientSubEngButtonController.findCustomFieldsid('Account');
        Test.stopTest();
    }
}