force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Any_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Any_Part_1__c</fullName>
    <description>Last Opportunity Comment of Any Type (Including Admin Comments)</description>
    <label>Last Opportunity Comment Any Part 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Any_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Any_Part_2__c</fullName>
    <description>Last Opportunity Comment of Any Type (Including Admin)</description>
    <label>Last Opportunity Comment Any Part 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Any_Part_3__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Any_Part_3__c</fullName>
    <description>Last Opportunity Comment of Any Type (Including Admin)</description>
    <label>Last Opportunity Comment Any Part 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Any_Part_4__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Any_Part_4__c</fullName>
    <description>Last Opportunity Comment of Any Type (Including Admin)</description>
    <label>Last Opportunity Comment Any Part 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Part_1__c</fullName>
    <label>Last Opportunity Comment Part 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Part_2__c</fullName>
    <label>Last Opportunity Comment Part 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Part_3__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Part_3__c</fullName>
    <label>Last Opportunity Comment Part 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Opportunity_Comment_Part_4__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Comment_Part_4__c</fullName>
    <label>Last Opportunity Comment Part 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Comments__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Comments__c</fullName>
    <label>Opportunity Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Comment__c/Opportunity_Comment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Comment</label>
    <nameField>
        <displayFormat>OPCOM-{0000}</displayFormat>
        <label>Opportunity Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Comment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Comment__c/fields/Include_In_Latest_Comment__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Latest_Comment__c</fullName>
    <formula>TEXT(Comment_Type__c) = &apos;Administrative&apos; || TEXT(Comment_Type__c) = &apos;Internal&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Include In Latest Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Comment__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Opportunity_Comments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_OpportunityCommentHandler.cls
public with sharing class HL_OpportunityCommentHandler {
	 /* start - global variables*/
    public static boolean isTest = false;
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    /* stop - global variables*/
    
    /* start - constructor */     
    public HL_OpportunityCommentHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }

    public void onAfterUpdate(Map<Id, Opportunity_Comment__c> oldMap, Map<Id, Opportunity_Comment__c> newMap){
        Set<Id> oppIds = new Set<Id>();
        //Only handle comments where the comment or comment type has changed
        for(Id ocId : newMap.keySet())
        {
          if(oldMap.get(ocId).Comment__c != newMap.get(ocId).Comment__c || oldMap.get(ocId).Comment_Type__c != newMap.get(ocId).Comment_Type__c)
             oppIds.add(newMap.get(ocId).Related_Opportunity__c);
        }
        UpdateLastComments(oppIds);
    }

    public void onAfterInsert(Map<Id, Opportunity_Comment__c> mapNewOppComments){
    	//We want Non-Administrative Comments for Sharing Rules
    	List<Opportunity_Comment__c> nonAdminComments = new List<Opportunity_Comment__c>();
        Set<Id> oppIds = new Set<Id>();
        for(Opportunity_Comment__c oc : mapNewOppComments.values())
    	{
            oppIds.add(oc.Related_Opportunity__c);
    		if(oc.Comment_Type__c <> 'Administrative' && oc.Comment_Type__c <> 'Compliance')
    			nonAdminComments.add(oc);
    	}
        SL_ManageSharingRules.manageRevAccrualsCounterpartySharingRules(nonAdminComments, 'Opportunity_Comment__c'); 
        UpdateLastComments(oppIds);
    }

    //Update the last comment fields back on the opportunity, if needed, when records are deleted
    public void onAfterDelete(Map<Id, Opportunity_Comment__c> oldMap){
        Set<Id> oppIds = new Set<Id>();
        for(Opportunity_Comment__c oc : oldMap.values())
            oppIds.add(oc.Related_Opportunity__c);
        UpdateLastComments(oppIds);
    }

    //Update the last comment fields back on the opportunity
    private void UpdateLastComments(Set<Id> oppIdSet)
    {
        List<Opportunity__c> oppsToUpdate = new List<Opportunity__c>();
        Integer nonAdminIndex;
        for(Opportunity__c o : [SELECT Opportunity_Comments__c, Last_Opportunity_Comment_Part_1__c, Last_Opportunity_Comment_Part_2__c, Last_Opportunity_Comment_Part_3__c, Last_Opportunity_Comment_Part_4__c, Last_Opportunity_Comment_Any_Part_1__c, Last_Opportunity_Comment_Any_Part_2__c, Last_Opportunity_Comment_Any_Part_3__c, Last_Opportunity_Comment_Any_Part_4__c, (SELECT Comment__c, Comment_Type__c, CreatedDate, CreatedBy.FirstName, CreatedBy.LastName FROM Opportunity_Comments__r WHERE Include_In_Latest_Comment__c =: true ORDER BY CreatedDate DESC) FROM Opportunity__c WHERE Id IN: oppIdSet])
        {
            if(o.Opportunity_Comments__r.size() != 0)
            {
                //Our Goal Here is To Find the Earliest Non Admin Comment
                //Because we need to be sure both the Last Comment field sets (4 each) are updated properly
                nonAdminIndex = -1;
                for(Integer i = 0; i < o.Opportunity_Comments__r.size(); i++)
                {
                    if(o.Opportunity_Comments__r[i].Comment_Type__c != 'Administrative' && o.Opportunity_Comments__r[i].Comment_Type__c != 'Compliance'){
                        nonAdminIndex = i;
                        break;
                    }
                }

                if(nonAdminIndex > 0)
                    HL_OpportunityHandler.FormatLastComment(o, o.Opportunity_Comments__r[nonAdminIndex], true);
                
                HL_OpportunityHandler.FormatLastComment(o, o.Opportunity_Comments__r[0], nonAdminIndex == 0);
                if(nonAdminIndex == -1)
                    o.Last_Opportunity_Comment_Part_1__c = o.Last_Opportunity_Comment_Part_2__c = o.Last_Opportunity_Comment_Part_3__c = o.Last_Opportunity_Comment_Part_4__c = '';
            }
            else //Clear the Last Comment Fields
                o.Last_Opportunity_Comment_Part_1__c = o.Last_Opportunity_Comment_Part_2__c = o.Last_Opportunity_Comment_Part_3__c = o.Last_Opportunity_Comment_Part_4__c = o.Last_Opportunity_Comment_Any_Part_1__c = o.Last_Opportunity_Comment_Any_Part_2__c = o.Last_Opportunity_Comment_Any_Part_3__c = o.Last_Opportunity_Comment_Any_Part_4__c = '';
            
            oppsToUpdate.add(o);          
        }

        if(oppsToUpdate.size() > 0 && HL_TriggerContextUtility.isFirstRun())
            update oppsToUpdate;
    }
}