force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Additional_Client__c.field-meta.xml
<CustomField>
    <fullName>Additional_Client__c</fullName>
    <inlineHelpText>Is there more than one Client? If &apos;Yes,&apos; you will be prompted to add Additional Clients.</inlineHelpText>
    <label>Additional Client</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Additional_Subject__c.field-meta.xml
<CustomField>
    <fullName>Additional_Subject__c</fullName>
    <inlineHelpText>Is there more than one Subject? If &apos;Yes,&apos; you will be prompted to add Additional Subjects.</inlineHelpText>
    <label>Additional Subject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Completed_Additional_Client__c.field-meta.xml
<CustomField>
    <fullName>Completed_Additional_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed Additional Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Completed_Additional_Subject__c.field-meta.xml
<CustomField>
    <fullName>Completed_Additional_Subject__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed Additional Subject</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_C1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/Opportunity_Client_Subject__c.object-meta.xml
<CustomObject>
    <description>Custom object to track additional clients and subjects for an opportunity.</description>
    <label>Opportunity Client/Subject</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Clients/Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Client_Subject__c.field-meta.xml
<CustomField>
    <fullName>Client_Subject__c</fullName>
    <inlineHelpText>Client: parties which signed/acceded to HL&apos;s EL (or are anticipated to do so). 
Subject: underlying company</inlineHelpText>
    <label>Client/Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Additional Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Key Creditor: (i) creditor-side HL client, (ii) AHG member, (iii) other creditor with meaningful negotiation with the debtor, or (iv) lender holding &gt;10% of total debt or &gt;$50m</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Key Creditor</fullName>
            </value>
            <value>
                <fullName>PE Firm</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Type = &quot;Client&quot;</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Subject.recordType-meta.xml
<RecordType>
    <fullName>Subject</fullName>
    <active>true</active>
    <description>Type = &quot;Subject&quot;</description>
    <label>Subject</label>
</RecordType>

force-app/main/default/classes/Test_HL_AddClientsSubjectsController.cls
@isTest
private class Test_HL_AddClientsSubjectsController {
    @isTest private static void TestBasicFunctionality(){
        //Setup Test Data
        Account client = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert client;
        Account subject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert subject;
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('',1)[0];
        o.Additional_Client__c = 'No';
        o.Additional_Subject__c = 'No';
        o.Client__c = client.Id;
        o.Subject__c = subject.Id;
		o.Beneficial_Owner_Control_Person_form__c = 'No';
        insert o;
        //Insert Additional Clients/Subjects
        Account newClient = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newClient;
        Account newSubject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newSubject;
        Opportunity_Client_Subject__c addClient = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Client_Subject__c = newClient.Id, Type__c = 'Client');
        insert addClient;
        Opportunity_Client_Subject__c addSubject = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Client_Subject__c = newSubject.Id, Type__c = 'Subject');
        insert addSubject;
        
        ApexPages.currentPage().getParameters().put('Id',o.Id);
        
        Test.startTest();
            //Test Controller Functionality
            HL_AdditionalClientsSubjectsController con = new HL_AdditionalClientsSubjectsController();
            Opportunity__c opp = con.Opp;
            System.assert(opp.Id == o.Id);
            List<Opportunity_Client_Subject__c> additionalClients = con.AdditionalClients;
            //Should now have two (one from trigger on opp and another we added above)
            System.assert(additionalClients.size() == 2);
            List<Opportunity_Client_Subject__c> additionalSubjects = con.AdditionalSubjects;
            //Should now have two (one from trigger on opp and another we added above)
            System.assert(additionalSubjects.size() == 2);
            con.Opp.Completed_Additional_Client__c = false;
            con.RefreshAdditionalClients();
            con.ClientToRemove = addClient.Id;
            con.RemoveClient();     
            //Should now have one after removal
            System.assert(con.AdditionalClients.size() == 1);
            con.Opp.Completed_Additional_Subject__c = false;
            con.RefreshAdditionalSubjects();
            con.SubjectToRemove = addSubject.Id;
            con.RemoveSubject();
            //Should now have one after removal
            System.assert(con.AdditionalSubjects.size() == 1);
            con.SaveOpp();
        Test.stopTest();
    }
}