force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Estimated_Transaction_Size_MM__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Transaction_Size_MM__c</fullName>
    <inlineHelpText>If Public, insert the Market Cap of the company.</inlineHelpText>
    <label>Est. Transaction Size / Market Cap (MM)</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/SC.recordType-meta.xml
<RecordType>
    <fullName>SC</fullName>
    <active>true</active>
    <description>Strategic Consulting</description>
    <label>SC</label>
</RecordType>

force-app/main/default/objects/Opportunity_Approval__c/Opportunity_Approval__c.object-meta.xml
<CustomObject>
    <description>These records are related to Opportunities and are required for submission before attaining committee approval and engagement.</description>
    <label>Opportunity Review</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Opportunity Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/fields/Conflicts_3a_Related_to_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Conflicts_3a_Related_to_Transaction__c</fullName>
    <description>Do any of the deal team members or, to the extent any of the deal team members are aware, does Houlihan Lokey or any other employee of Houlihan Lokey, have any business, employment, family or other relationships with or any direct or indirect financial interests in or exposures to the contemplated transaction, any related transactions, the potential client or, if known, the likely counterparty(ies), or their respective affiliates or management teams?</description>
    <label>Yes/No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Fairness_Additional_Officers__c.field-meta.xml
<CustomField>
    <fullName>Fairness_Additional_Officers__c</fullName>
    <label>Fairness Additional Officers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Fairness_Disclosure_Document__c.field-meta.xml
<CustomField>
    <fullName>Fairness_Disclosure_Document__c</fullName>
    <label>Fairness Disclosure Document</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>14A/14C</fullName>
            </value>
            <value>
                <fullName>S-4/F-4</fullName>
            </value>
            <value>
                <fullName>13E-3</fullName>
            </value>
            <value>
                <fullName>14D-9</fullName>
            </value>
            <value>
                <fullName>State Proxy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Fairness_In_Addition__c.field-meta.xml
<CustomField>
    <fullName>Fairness_In_Addition__c</fullName>
    <label>Fairness In Addition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Fairness_Opinion_Publicly_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>Fairness_Opinion_Publicly_Disclosed__c</fullName>
    <label>Fairness Opinion Publicly Disclosed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/FEIS_Opine_Option_6__c.field-meta.xml
<CustomField>
    <fullName>FEIS_Opine_Option_6__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check if applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/FEIS_Other_Job_Type_Desc__c.field-meta.xml
<CustomField>
    <fullName>FEIS_Other_Job_Type_Desc__c</fullName>
    <label>FEIS - Other Job Type Desc</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/FEIS_Other_Legal_Structure_Desc__c.field-meta.xml
<CustomField>
    <fullName>FEIS_Other_Legal_Structure_Desc__c</fullName>
    <label>FEIS - Other Legal Structure Desc</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Form_of_Consideration__c.field-meta.xml
<CustomField>
    <fullName>Form_of_Consideration__c</fullName>
    <label>Form of Consideration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Stock</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Has_Other_Shareholders__c.field-meta.xml
<CustomField>
    <fullName>Has_Other_Shareholders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Other Shareholders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Legal_Structure__c.field-meta.xml
<CustomField>
    <fullName>Legal_Structure__c</fullName>
    <label>Legal Structure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Merger</fullName>
            </value>
            <value>
                <fullName>Purchase/Sale of Assets</fullName>
            </value>
            <value>
                <fullName>Tender Offer/Merger</fullName>
            </value>
            <value>
                <fullName>Exchange Offer/Merger</fullName>
            </value>
            <value>
                <fullName>Recap</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Opinion_Parties_Affiliated__c.field-meta.xml
<CustomField>
    <fullName>Opinion_Parties_Affiliated__c</fullName>
    <label>Opinion Parties Affiliated</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Other_Shareholders__c.field-meta.xml
<CustomField>
    <fullName>Other_Shareholders__c</fullName>
    <label>Other Shareholders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <inlineHelpText>Please indicate the related Opportunity record.</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Reviews</relationshipLabel>
    <relationshipName>Opportunity_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Shareholder_Vote__c.field-meta.xml
<CustomField>
    <fullName>Shareholder_Vote__c</fullName>
    <label>Shareholder Vote?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Transaction_Overview__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Overview__c</fullName>
    <inlineHelpText>Include information pertaining to potential Fairness option</inlineHelpText>
    <label>Transaction Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Buy Side</fullName>
            </value>
            <value>
                <fullName>Concurrent Sale/Rollup</fullName>
            </value>
            <value>
                <fullName>ESOP</fullName>
            </value>
            <value>
                <fullName>Going Private</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Merger of Equals</fullName>
            </value>
            <value>
                <fullName>Minority Investment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PIPE</fullName>
            </value>
            <value>
                <fullName>Sell Side (company)</fullName>
            </value>
            <value>
                <fullName>Sell Side (divestiture)</fullName>
            </value>
            <value>
                <fullName>Spin-off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/Opportunity_Client_Subject__c.object-meta.xml
<CustomObject>
    <description>Custom object to track additional clients and subjects for an opportunity.</description>
    <label>Opportunity Client/Subject</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Clients/Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Client_Subject__c.field-meta.xml
<CustomField>
    <fullName>Client_Subject__c</fullName>
    <inlineHelpText>Client: parties which signed/acceded to HL&apos;s EL (or are anticipated to do so). 
Subject: underlying company</inlineHelpText>
    <label>Client/Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Additional Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The primary client or subject defined on the opportunity level.</inlineHelpText>
    <label>Primary?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Shareholder_Vote__c.field-meta.xml
<CustomField>
    <fullName>Shareholder_Vote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shareholder vote in connection with the transaction</description>
    <label>Shareholder Vote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Key Creditor: (i) creditor-side HL client, (ii) AHG member, (iii) other creditor with meaningful negotiation with the debtor, or (iv) lender holding &gt;10% of total debt or &gt;$50m</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Key Creditor</fullName>
            </value>
            <value>
                <fullName>PE Firm</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Contra.recordType-meta.xml
<RecordType>
    <fullName>Contra</fullName>
    <active>true</active>
    <description>Type = &quot;Contra&quot;</description>
    <label>Contra</label>
</RecordType>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Type = &quot;Other&quot; A &quot;Type (Other)&quot;  text field has been provided if the &quot;Other&quot; specific name needs to be saved.</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Subject.recordType-meta.xml
<RecordType>
    <fullName>Subject</fullName>
    <active>true</active>
    <description>Type = &quot;Subject&quot;</description>
    <label>Subject</label>
</RecordType>

force-app/main/default/classes/Test_HL_FEISController.cls
@isTest
private class Test_HL_FEISController {
    @isTest private static void TestBasicFunctionality() {
        //Setup Test Data
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('', 1)[0];
        o.Beneficial_Owner_Control_Person_form__c = 'No';
        insert o;
        
        Opportunity_Approval__c oa = SL_TestSetupUtils.CreateOA('', 1)[0];
        oa.Related_Opportunity__c = o.Id;
        insert oa;
        
        Test.startTest();
        //Setup Standard Controller
        ApexPages.StandardController sc = new ApexPages.StandardController(oa);
        //Test Controller Properties/Methods
        HL_FEISController con = new HL_FEISController(sc);
        List < Opportunity_Client_Subject__c > csList = con.ClientsSubjects;
        List < Opportunity_Client_Subject__c > cpList = con.Counterparties;
        List < Opportunity_Client_Subject__c > shList = con.ShareholderCompanies;
        
        con.RefreshClientsSubjects();
        con.RefreshCounterparties();
        con.SaveRecord();
        con.SaveAndReturn();
        con.SubmitForm();
        Test.stopTest();
        
    }
    
    @isTest private static void Test2() {
        //Setup Test Data
        //Insert Additional Clients/Subjects
        Account newClient = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newClient;
        Account newSubject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newSubject;
        
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('', 1)[0];
        o.Beneficial_Owner_Control_Person_form__c = 'No';
        insert o;
        Opportunity_Approval__c oa = SL_TestSetupUtils.CreateOA('', 1)[0];
        oa.Related_Opportunity__c = o.Id;
        oa.Transaction_Type__c = 'Other';
        oa.Legal_Structure__c = 'Other';
        oa.Form_of_Consideration__c = 'Other';
        oa.Opinion_Parties_Affiliated__c = 'Yes';
        oa.FEIS_Opine_Option_6__c = True;
        oa.Fairness_Opinion_Publicly_Disclosed__c = 'Yes';
        oa.Fairness_In_Addition__c = 'Yes';
        oa.Fairness_Additional_Officers__c = 'Yes';
        oa.Conflicts_3a_Related_to_Transaction__c = 'Yes';
        oa.Shareholder_Vote__c = 'Yes';
        oa.Other_Shareholders__c = 'Test';
        oa.Has_Other_Shareholders__c = true;
        oa.Fairness_Disclosure_Document__c = 'Other';
        insert oa;
        
        Opportunity_Client_Subject__c addClient = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Client_Subject__c = newClient.Id, Type__c = 'Contra');
        insert addClient;
        Opportunity_Client_Subject__c addSubject = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Primary__c = false, Client_Subject__c = newSubject.Id, Type__c = 'Subject');
        insert addSubject;
        
        Test.startTest();
        //Setup Standard Controller
        ApexPages.StandardController sc = new ApexPages.StandardController(oa);
        //Test Controller Properties/Methods
        HL_FEISController con = new HL_FEISController(sc);
        List < Opportunity_Client_Subject__c > csList = con.ClientsSubjects;
        List < Opportunity_Client_Subject__c > cpList = con.Counterparties;
        List < Opportunity_Client_Subject__c > shList = con.ShareholderCompanies;
        con.RefreshClientsSubjects();
        con.RefreshCounterparties();
        con.SaveRecord();
        con.SaveAndReturn();
        con.DelId = csList[0].Id;
        Boolean OnOIT = con.OnOIT;
        PageReference objPf = con.TriggerValidation();
        con.SubmitForm();   
        con.CancelSubmission();
        con.DeleteClientSubject();
        con.DelId = cpList[0].Id;
        con.DeleteCounterparty();
        con.FairnessAdditionalOfficers();
        Test.stopTest();
       }
    
    @isTest private static void Test3() {
        //Setup Test Data
        //Insert Additional Clients/Subjects
        Account newClient = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newClient;
        Account newSubject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert newSubject;
        
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('', 1)[0];
        o.Beneficial_Owner_Control_Person_form__c = 'No';
        insert o;
        
        Opportunity_Approval__c oa = SL_TestSetupUtils.CreateOA('', 1)[0];
        oa.Related_Opportunity__c = o.Id;
        oa.Transaction_Overview__c = 'This transaction overview';
        oa.Transaction_Type__c = 'Other';
        oa.FEIS_Other_Job_Type_Desc__c = 'This is text area';
        oa.Legal_Structure__c = 'Other';
        oa.FEIS_Other_Legal_Structure_Desc__c = 'This is legal structure desc';
        oa.Estimated_Transaction_Size_MM__c = 100;
        oa.Form_of_Consideration__c = 'Cash';
        oa.Opinion_Parties_Affiliated__c = 'No';
        oa.FEIS_Opine_Option_6__c = False; 
        oa.Fairness_Opinion_Publicly_Disclosed__c = 'No';
        oa.Fairness_In_Addition__c = 'No';
        oa.Fairness_Additional_Officers__c = 'No';
        oa.Fairness_Relative_Fairness__c = 'No';
        oa.Fairness_Fairness_or_Terms__c = 'No';
        oa.Fairness_Multiple_Conclusions__c = 'No';
        oa.Fairness_Committee_or_Trustee__c = 'No';
        oa.Fairness_Unusual_Opinion__c = 'No';
        oa.Conflicts_3a_Related_to_Transaction__c = 'No';
        oa.Conflicts_35a_Related_to_Client__c = 'No';
        oa.Conflicts_4a_Conflict_of_Interest__c = 'No';
        oa.Conflicts_5a_Other_Conflicts__c = 'No';
        oa.Shareholder_Vote__c = 'No';
        oa.Has_Other_Shareholders__c = false;
        oa.Opinion_Special_Committee__c = 'No';
        insert oa;
        
        Opportunity_Client_Subject__c addClient = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Client_Subject__c = newClient.Id, Type__c = 'Contra');
        insert addClient;
        Opportunity_Client_Subject__c addSubject = new Opportunity_Client_Subject__c(Opportunity__c = o.Id, Primary__c = false, Client_Subject__c = newSubject.Id, Type__c = 'Subject');
        insert addSubject;
        
        Test.startTest();
        //Setup Standard Controller
        ApexPages.StandardController sc = new ApexPages.StandardController(oa);
        //Test Controller Properties/Methods
        HL_FEISController con = new HL_FEISController(sc);
        List < Opportunity_Client_Subject__c > csList = con.ClientsSubjects;
        List < Opportunity_Client_Subject__c > cpList = con.Counterparties;
        List < Opportunity_Client_Subject__c > shList = con.ShareholderCompanies;
      
        con.SubmitForm();  
        
        o.Line_of_Business__c = 'FVA';
        update o;
        
        con.SubmitForm();
       
        Test.stopTest();
       }

}