force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M&amp;A</fullName>
            </value>
            <value>
                <fullName>Capital Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/Opportunity_Approval__c.object-meta.xml
<CustomObject>
    <description>These records are related to Opportunities and are required for submission before attaining committee approval and engagement.</description>
    <label>Opportunity Review</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Opportunity Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/fields/Client_Company__c.field-meta.xml
<CustomField>
    <fullName>Client_Company__c</fullName>
    <formula>Related_Opportunity__r.Client__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Client_Country__c.field-meta.xml
<CustomField>
    <fullName>Client_Country__c</fullName>
    <formula>Related_Opportunity__r.Client__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Client_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Client_Ownership__c</fullName>
    <formula>TEXT(Related_Opportunity__r.Client_Ownership__c)</formula>
    <label>Client Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Company_Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Ownership_Type__c</fullName>
    <formula>TEXT(Related_Opportunity__r.Subject_Company_Ownership__c)</formula>
    <label>Subject Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <description>Used for approval processes and to identify records between FEIS and NBC</description>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FEIS</fullName>
            </value>
            <value>
                <fullName>NBC</fullName>
            </value>
            <value>
                <fullName>CNBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Head_Approval__c.field-meta.xml
<CustomField>
    <fullName>Head_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Please confirm that a group head has approved prior to submitting to the committee.</description>
    <label>Group Head Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Is_Client_EU__c.field-meta.xml
<CustomField>
    <fullName>Is_Client_EU__c</fullName>
    <formula>IF(Related_Opportunity__r.Client__r.Is_Client_EU_CF__c ||  EU_Override__c, &quot;TRUE&quot;, &quot;FALSE&quot;)</formula>
    <label>Is Client EU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Is_Majority_Sale__c.field-meta.xml
<CustomField>
    <fullName>Is_Majority_Sale__c</fullName>
    <label>Is Majority Sale?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Locked__c.field-meta.xml
<CustomField>
    <fullName>Locked__c</fullName>
    <formula>NOT(BLANKVALUE(TEXT(Grade__c),&apos;F&apos;) == &apos;F&apos;) ||  Reviewed__c</formula>
    <label>Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>Related_Opportunity__r.Opportunity_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/PDF_View__c.field-meta.xml
<CustomField>
    <fullName>PDF_View__c</fullName>
    <formula>$Setup.HL_General__c.Cognos_Protocol__c + $Setup.HL_General__c.Cognos_Domain__c +
CASE(Form_Type__c, &apos;NBC&apos;, &quot;/ibmcognos/bi/v1/disp?b_action=cognosViewer&amp;run.outputFormat=PDF&amp;run.prompt=false&amp;ui.object=storeID%28%22i7499382846124884B3C472FD334A907F%22%29&amp;ui.action=run&amp;cv.header=true&amp;cv.toolbar=false&amp;ui_appbar=true&amp;p_p_OpportunityId=&quot;, &apos;FEIS&apos;, &quot;/ibmcognos/bi/v1/disp?b_action=cognosViewer&amp;run.outputFormat=PDF&amp;run.prompt=false&amp;ui.object=storeID%28%22iD6E596CC881741878AFF2CEEBDCEE79A%22%29&amp;ui.action=run&amp;cv.header=false&amp;cv.toolbar=true&amp;ui_appbar=true&amp;p_p_OpportunityId=&quot;,&apos;CNBC&apos;,&quot;/ibmcognos/bi/v1/disp?b_action=cognosViewer&amp;run.outputFormat=PDF&amp;run.prompt=false&amp;ui.object=storeID%28%22i2DA41AC49BB04B8F9596F5C417E1CF40%22%29&amp;ui.action=run&amp;cv.header=false&amp;cv.toolbar=true&amp;ui_appbar=true&amp;p_p_OpportunityId=&quot;,&quot;INVALID FORM&quot;) + Related_Opportunity_Case_Safe__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PDF View</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <inlineHelpText>Please indicate the related Opportunity record.</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Reviews</relationshipLabel>
    <relationshipName>Opportunity_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Secondary_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Job_Type__c</fullName>
    <label>Secondary Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activist Advisory</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Buyside &amp; Financing Advisory</fullName>
            </value>
            <value>
                <fullName>Corporate Alliances</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Advisors</fullName>
            </value>
            <value>
                <fullName>Discretionary Advisory</fullName>
            </value>
            <value>
                <fullName>Equity Capital Markets</fullName>
            </value>
            <value>
                <fullName>ESOP Corporate Finance</fullName>
            </value>
            <value>
                <fullName>General Financial Advisory</fullName>
            </value>
            <value>
                <fullName>Going Private</fullName>
            </value>
            <value>
                <fullName>Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>Liability Management</fullName>
            </value>
            <value>
                <fullName>Merger</fullName>
            </value>
            <value>
                <fullName>Negotiated Fairness</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Post Merger Integration</fullName>
            </value>
            <value>
                <fullName>Private Funds: GP Advisory</fullName>
            </value>
            <value>
                <fullName>Private Funds: GP Stake Sale</fullName>
            </value>
            <value>
                <fullName>Private Funds: Primary Advisory</fullName>
            </value>
            <value>
                <fullName>Private Funds: Secondary Advisory</fullName>
            </value>
            <value>
                <fullName>Real Estate Brokerage</fullName>
            </value>
            <value>
                <fullName>Sellside</fullName>
            </value>
            <value>
                <fullName>Special Committee Advisory</fullName>
            </value>
            <value>
                <fullName>Special Situations Buyside</fullName>
            </value>
            <value>
                <fullName>Special Situations Sellside</fullName>
            </value>
            <value>
                <fullName>Strategic Alternatives Study</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Syndicated Finance</fullName>
            </value>
            <value>
                <fullName>Take Over Defense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Subject_Company__c.field-meta.xml
<CustomField>
    <fullName>Subject_Company__c</fullName>
    <formula>Related_Opportunity__r.Subject__r.Name</formula>
    <label>Subject Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Subject_Country__c.field-meta.xml
<CustomField>
    <fullName>Subject_Country__c</fullName>
    <formula>Related_Opportunity__r.Subject__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HlNCBFormController.cls
public class HlNCBFormController {
    @AuraEnabled(cacheable=true)
    public static String checkOpportunityReview(String oppId,String action,String parentcurrency){
        String oppreviewId;
        try{
            List<Opportunity_Approval__c> oppLst =  [SELECT Id, Form_Type__c FROM Opportunity_Approval__c WHERE Related_Opportunity__c =: oppId];
            if(oppLst.size()>0){
                oppreviewId = oppLst[0].Id;
            }
            else{
                Opportunity_Approval__c destRecord = new Opportunity_Approval__c(Related_Opportunity__c = oppId,Form_Type__c = action.toUpperCase(), CurrencyIsoCode = parentcurrency);
                insert destRecord;
                oppreviewId = destRecord.id;
            }
            return oppreviewId;
        }catch(Exception e){
            system.debug('Exception in checkOpportunityReview'+e.getMessage());
            return null;
            
        }
        
    }
     @AuraEnabled
    public static Opportunity_Approval__c getOpportunityReview(String oppReviewId){
        return [Select id,Related_Opportunity__c,Related_Opportunity__r.Name,Locked__c,PDF_View__c,Opportunity_Number__c,Client_Company__c,
        Subject_Company__c,Client_Ownership__c,Company_Ownership_Type__c,Client_Country__c,Subject_Country__c,Secondary_Job_Type__c,Is_Majority_Sale__c,Head_Approval__c,Is_Client_EU__c 
         FROM Opportunity_Approval__c where id=: oppReviewId];
    }
}