force-app/main/default/objects/Eng_VP_Position__c/Eng_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Engagement Valuation Period Positions linked with Engagement and Companies</description>
    <label>Eng Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eng Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP_Position__c/fields/Revenue_Month__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Month__c</fullName>
    <description>Select the Current Month for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Month for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Revenue Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Revenue_Year__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Year__c</fullName>
    <description>Select the Current Year for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Year for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Revenue Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed, Generate Accrual</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_TeamMember__c/Eng_VP_TeamMember__c.object-meta.xml
<CustomObject>
    <description>This is related with Engagement Valuation Period Position and HL Internal Team Members</description>
    <label>Eng Valuation Period TeamMember</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eng Valuation Period TeamMembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP_TeamMember__c/fields/Engagement_VP_Position__c.field-meta.xml
<CustomField>
    <fullName>Engagement_VP_Position__c</fullName>
    <label>Engagement Valuation Period Position</label>
    <referenceTo>Eng_VP_Position__c</referenceTo>
    <relationshipLabel>Eng Valuation Period TeamMembers</relationshipLabel>
    <relationshipName>Eng_VP_TeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Eng_VP_TeamMember__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_TeamMember__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eng_PV_TeamMembers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP_TeamMember__c/fields/Team_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Status__c</fullName>
    <formula>IF( End_Date__c &lt;=  TODAY()  , &apos;Inactive&apos;, &apos;Active&apos;)</formula>
    <label>Team Member Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/Monthly_Revenue_Process_Control__c.object-meta.xml
<CustomObject>
    <description>Kick off and track each step of the Monthly Revenue Process in JDE</description>
    <label>Monthly Revenue Process Control</label>
    <nameField>
        <label>Monthly Revenue Process Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Revenue Process Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Currently Running Process</description>
    <inlineHelpText>Status of the Currently Running Process</inlineHelpText>
    <label>Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HL_Eng_VP_TeamMemberTriggerHelper.cls
public without sharing class HL_Eng_VP_TeamMemberTriggerHelper {
    
    public static void beforeInsert(List<Eng_VP_TeamMember__c> newEngVpTeamMemberList, Map<Id, Eng_VP_TeamMember__c> newEngVpTeamMemberMap, List<Eng_VP_TeamMember__c> oldEngVPTeamMemberList , Map<Id, Eng_VP_TeamMember__c> oldEngVPTeamMemberMap) {
       
    }
        
    public static void afterInsert(List<Eng_VP_TeamMember__c> newEngVpTeamMemberList, Map<Id, Eng_VP_TeamMember__c> newEngVpTeamMemberMap, List<Eng_VP_TeamMember__c> oldEngVPTeamMemberList , Map<Id, Eng_VP_TeamMember__c> oldEngVPTeamMemberMap) { 


        if(!HL_ConstantsUtil.stopExecutionForPVConversion){
            validateDuplicate(newEngVpTeamMemberList, oldEngVPTeamMemberMap);   
            stopModificationTM_Basedon_MRPC_onDelete('AfterInsert', newEngVpTeamMemberList);
        }     
    }
    
    public static void beforeUpdate(List<Eng_VP_TeamMember__c> newEngVpTeamMemberList, Map<Id, Eng_VP_TeamMember__c> newEngVpTeamMemberMap, List<Eng_VP_TeamMember__c> oldEngVPTeamMemberList , Map<Id, Eng_VP_TeamMember__c> oldEngVPTeamMemberMap) {
        if(!HL_ConstantsUtil.stopExecutionForPVConversion){
            stopModificationTM_Basedon_MRPC_onDelete('BeforeUpdate', newEngVpTeamMemberList);
        }
    }
    
    public static void afterUpdate(List<Eng_VP_TeamMember__c> newEngVpTeamMemberList, Map<Id, Eng_VP_TeamMember__c> newEngVpTeamMemberMap, List<Eng_VP_TeamMember__c> oldEngVPTeamMemberList , Map<Id, Eng_VP_TeamMember__c> oldEngVPTeamMemberMap) {
        if(!HL_ConstantsUtil.stopExecutionForPVConversion){
            validateDuplicate(newEngVpTeamMemberList, oldEngVPTeamMemberMap);           
        }
    }
    
    public static void beforeDelete(List<Eng_VP_TeamMember__c> newEngVpTeamMemberList, Map<Id, Eng_VP_TeamMember__c> newEngVpTeamMemberMap, List<Eng_VP_TeamMember__c> oldEngVPTeamMemberList , Map<Id, Eng_VP_TeamMember__c> oldEngVPTeamMemberMap) {
        
        if(!HL_ConstantsUtil.IsSupervisorOrAdmin() && oldEngVPTeamMemberList != null && oldEngVPTeamMemberList.size() > 0 ) {
                oldEngVPTeamMemberList[0].addError(Label.HL_No_Delete_Privilige_VP_Team_Member);                       
        }
        if(!HL_ConstantsUtil.stopExecutionForPVConversion){ 
            stopModificationTM_Basedon_MRPC_onDelete('BeforeDelete',oldEngVPTeamMemberList);
        }                  
    }
    
    public static void afterDelete(List<Eng_VP_TeamMember__c> newEngVpTeamMemberList, Map<Id, Eng_VP_TeamMember__c> newEngVpTeamMemberMap, List<Eng_VP_TeamMember__c> oldEngVPTeamMemberList , Map<Id, Eng_VP_TeamMember__c> oldEngVPTeamMemberMap) {
        
    }

    
    public static void stopModificationTM_Basedon_MRPC_onDelete(String eventType, List<Eng_VP_TeamMember__c> oldEngVpTeamMemberList){
        Monthly_Revenue_Process_Control__c  MRPC = new Monthly_Revenue_Process_Control__c();
        MRPC = HL_Eng_VP_PositionTriggerHelper.fetchMRPC();  
        
          
          User getUserProInfo = [SELECT Id,Name, Profile.Name from User Where Id =: userinfo.getUserId()];
          
            for(Eng_VP_TeamMember__c EngVPTM : [Select id,Engagement_VP_Position__r.Revenue_Month__c, Engagement_VP_Position__r.Revenue_Year__c from Eng_VP_TeamMember__c Where ID in: oldEngVpTeamMemberList AND Engagement_VP_Position__r.Status__c =: System.Label.HL_Eng_VP_Status_Completed])
            {     
             if(MRPC == null){
                 if (eventType == 'BeforeDelete'){                    
                        ((Eng_VP_TeamMember__c)Trigger.oldMap.get(EngVPTM.Id)).addError(System.Label.HL_MRPC_Not_Exists); 
                 }
                 else{                     
                        ((Eng_VP_TeamMember__c)Trigger.newMap.get(EngVPTM.Id)).addError(System.Label.HL_MRPC_Not_Exists); 
                 }
             }
             else
             {
            
                if(HL_Eng_VP_PositionTriggerHelper.isRevenueMonthYearPassed(EngVPTM.Engagement_VP_Position__r.Revenue_Month__c, EngVPTM.Engagement_VP_Position__r.Revenue_Year__c,MRPC) && !(HL_Eng_VP_PositionTriggerHelper.isSuperUserOrSysAdmin()))
                    {
                        if(Trigger.IsInsert)
                            ((Eng_VP_TeamMember__c)Trigger.NewMap.get(EngVPTM.Id)).adderror(System.Label.HL_VP_TeamMember_StopChange);
                        else
                            ((Eng_VP_TeamMember__c)Trigger.oldMap.get(EngVPTM.Id)).adderror(System.Label.HL_VP_TeamMember_StopChange);
                    }
             }
            }
    }

    private static void validateDuplicate(List < Eng_VP_TeamMember__c > teamMemberNewList, Map < Id, Eng_VP_TeamMember__c > teamMemberOldMap) {
    Map < String, Eng_VP_TeamMember__c > teamMemberUniqueMap = new Map < String, Eng_VP_TeamMember__c > ();
    set < string > userSet = new Set < string > ();
    set < string > roles = new Set < string > ();
    set < Id > parentposition = new Set < Id > ();
    List < Eng_VP_TeamMember__c > teamMemberstoIgnore = new List < Eng_VP_TeamMember__c > ();
    for (Eng_VP_TeamMember__c teamMember: teamMemberNewList) 
    {
        if (trigger.isinsert || ((teamMember.Role__c != (teamMemberOldMap.get(teamMember.Id).Role__c)) ||
            (teamMember.Start_Date__c != (teamMemberOldMap.get(teamMember.Id).Start_Date__c)) ||
            (teamMember.End_Date__c != (teamMemberOldMap.get(teamMember.Id).End_Date__c))))
        {
                teamMemberUniqueMap.put((teamMember.Staff__c + '' + teamMember.Role__c + '' + teamMember.Engagement_VP_Position__c), teamMember);
                userSet.add(teamMember.Staff__c);
                roles.add(teamMember.Role__c);
                parentposition.add(teamMember.Engagement_VP_Position__c);
                teamMemberstoIgnore.add(teamMember);
        }
    }   
    for (Eng_VP_TeamMember__c teamMember: [ SELECT Staff__c, Role__c, Start_Date__c, End_Date__c, Engagement_VP_Position__c, Team_Member_Status__c 
                                            FROM Eng_VP_TeamMember__c
                                            WHERE Staff__c IN: userSet and Role__c IN: roles and Engagement_VP_Position__c 
                                                IN: parentposition  limit: Limits.getLimitQueryRows()])
    {
        
        if (teamMemberUniqueMap.containsKey(teamMember.Staff__c + '' + teamMember.Role__c + '' + teamMember.Engagement_VP_Position__c)) 
        {
            Eng_VP_TeamMember__c duplicateRecord = teamMemberUniqueMap.get(teamMember.Staff__c + '' + teamMember.Role__c + '' + teamMember.Engagement_VP_Position__c);
               if(teamMember.Id != duplicateRecord.id){               
                 
                 if (((duplicateRecord.Start_Date__c <= teamMember.Start_Date__c || duplicateRecord.Start_Date__c <= teamMember.End_Date__c)&& teamMember.Team_Member_Status__c != 'Inactive' ) || 
                    ((duplicateRecord.Start_Date__c < teamMember.Start_Date__c || duplicateRecord.Start_Date__c < teamMember.End_Date__c)&& teamMember.Team_Member_Status__c == 'Inactive' ) ||
                    (duplicateRecord.Start_Date__c > teamMember.Start_Date__c && teamMember.End_Date__c == null ))
                    {
                        
                        duplicateRecord.addError(System.Label.HL_Date_Overlapping_Error);
                        
                    }
               }
        }       
    }
}    
       
   
}