force-app/main/default/objects/Eng_VP_Position__c/Eng_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Engagement Valuation Period Positions linked with Engagement and Companies</description>
    <label>Eng Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eng Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP_Position__c/fields/Engagement_VP__c.field-meta.xml
<CustomField>
    <fullName>Engagement_VP__c</fullName>
    <label>Engagement Valuation Period</label>
    <referenceTo>Eng_VP__c</referenceTo>
    <relationshipName>Eng_VP_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed, Generate Accrual</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/recordTypes/Cancelled.recordType-meta.xml
<RecordType>
    <fullName>Cancelled</fullName>
    <active>true</active>
    <description>Record type for cancelled Positions</description>
    <label>Cancelled</label>
</RecordType>

force-app/main/default/classes/HL_ValuationPeriodPositionCancel.cls
public class HL_ValuationPeriodPositionCancel {
    private Id PositionId ;  
    public Eng_VP_Position__c EngVpPosition{get;set;}   
    public boolean isError{get;set;}
    
    // constructor
    public HL_ValuationPeriodPositionCancel(ApexPages.StandardController controller) {
        isError = false;
        PositionId = ApexPages.currentPage().getParameters().get('id');
        EngVpPosition = new Eng_VP_Position__c() ;
        for(Eng_VP_Position__c pos : [Select id,status__c,Engagement_VP__c from Eng_VP_Position__c where id =: PositionId]){
            EngVpPosition  = pos;                       
        }
    }
        
    Public PageReference CancelAccural(){
        PageReference pageRef = new PageReference('/'+PositionId);
        try{
            // To avoid validation (to avoid chaging status to cancelled on position directly)
            HL_ConstantsUtil.ToStopChangesStatusToCancelled = false;
            if(EngVpPosition.Status__c == System.Label.HL_Eng_VP_Status_Completed || EngVpPosition.Status__c == 'In Progress'){
                EngVpPosition.Status__c = 'Cancelled';
                update EngVpPosition;
            HL_ConstantsUtil.ToStopChangesStatusToCancelled = true;
            }               
        }
        catch(Exception e){
            isError = true;
            ApexPages.addMessages(e); 
            return null;
        }
        return pageRef;
  
  } 
  Public PageReference Back(){
    if(EngVpPosition.Engagement_VP__c != null)
        return new PageReference('/'+EngVpPosition.Engagement_VP__c);
    else 
        return null;
  }
  
   Public PageReference No(){
    if(PositionId != null)
        return new PageReference('/'+PositionId );
    else 
        return null;
  }

}