force-app/main/default/objects/Coverage_Sector_Dependency__c/Coverage_Sector_Dependency__c.object-meta.xml
<CustomObject>
    <label>Coverage Sector Dependency</label>
    <nameField>
        <displayFormat>CSDN-{0000000000}</displayFormat>
        <label>Coverage Sector Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Sector Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/CoverageType__c.field-meta.xml
<CustomField>
    <fullName>CoverageType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Coverage Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies</relationshipLabel>
    <relationshipName>CoverageSectorDependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/PrimarySector__c.field-meta.xml
<CustomField>
    <fullName>PrimarySector__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Sector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Primary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies (Primary Sector)</relationshipLabel>
    <relationshipName>CoverageSectorDependencies2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/SecondarySector__c.field-meta.xml
<CustomField>
    <fullName>SecondarySector__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Secondary Sector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Secondary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies (Secondary Sector)</relationshipLabel>
    <relationshipName>CoverageSectorDependencies3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/TertiarySector__c.field-meta.xml
<CustomField>
    <fullName>TertiarySector__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tertiary Sector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Tertiary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies (Tertiary Sector)</relationshipLabel>
    <relationshipName>CoverageSectorDependencies4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SectorValue__c/SectorValue__c.object-meta.xml
<CustomObject>
    <description>This object houses all the Coverage Types and Primary, Secondary, and Tertiary Sector values.  These records are used in the Coverage Dependency object for the dependent picklists.</description>
    <label>Sector Value</label>
    <nameField>
        <label>Sector Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sector Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HLSectorDependentPicklist.cls
public with sharing class HLSectorDependentPicklist {
    
    @AuraEnabled(cacheable=true)
    public static List<wrapper> getCoverageType(){
        List<wrapper> wList = new List<wrapper>();
        for(AggregateResult ar : [SELECT CoverageType__c,CoverageType__r.Name ctName FROM Coverage_Sector_Dependency__c group by CoverageType__c,CoverageType__r.Name order by CoverageType__r.Name]){
            wList.add(new wrapper((String)ar.get('CoverageType__c'),(String)ar.get('ctName')));
        }        
        return wList;        
    }

    @AuraEnabled(cacheable=true)
    public static List<wrapper> getPrimaryCoverage(Id coverageTypeId){
        List<wrapper> wList = new List<wrapper>();
        for(AggregateResult ar : [SELECT PrimarySector__c,PrimarySector__r.Name psName FROM Coverage_Sector_Dependency__c WHERE CoverageType__c=:coverageTypeId AND PrimarySector__c!='' group by PrimarySector__c,PrimarySector__r.Name order by PrimarySector__r.Name]){
            wList.add(new wrapper((String)ar.get('PrimarySector__c'),(String)ar.get('psName')));
        }        
        return wList;        
    }

    @AuraEnabled(cacheable=true)
    public static List<wrapper> getSecondaryCoverage(Id coverageTypeId, Id primarySectorId){
        List<wrapper> wList = new List<wrapper>();
        for(AggregateResult ar : [SELECT SecondarySector__c,SecondarySector__r.Name ssName FROM Coverage_Sector_Dependency__c WHERE CoverageType__c=:coverageTypeId AND PrimarySector__c=:primarySectorId AND SecondarySector__c!='' group by SecondarySector__c,SecondarySector__r.Name order by SecondarySector__r.Name]){
            wList.add(new wrapper((String)ar.get('SecondarySector__c'),(String)ar.get('ssName')));
        }        
        return wList;
    }

    @AuraEnabled(cacheable=true)
    public static List<wrapper> getTertiaryCoverage(Id coverageTypeId, Id primarySectorId,Id secondarySectorId){
        List<wrapper> wList = new List<wrapper>();
        for(AggregateResult ar : [SELECT TertiarySector__c,TertiarySector__r.Name tsName FROM Coverage_Sector_Dependency__c WHERE CoverageType__c=:coverageTypeId AND PrimarySector__c=:primarySectorId AND SecondarySector__c=:secondarySectorId AND TertiarySector__c!='' group by TertiarySector__c,TertiarySector__r.Name order by TertiarySector__r.Name]){            
            wList.add(new wrapper((String)ar.get('TertiarySector__c'),(String)ar.get('tsName')));            
        }
        return wList;   
    }

    public class wrapper{
        public wrapper(String value,String label){
            this.label=label;
            this.value=value;
        }
        @AuraEnabled        
        public String label {get;set;}

        @AuraEnabled
        public String value {get;set;}
    }
}