force-app/main/default/objects/Coverage_Sector_Dependency__c/Coverage_Sector_Dependency__c.object-meta.xml
<CustomObject>
    <label>Coverage Sector Dependency</label>
    <nameField>
        <displayFormat>CSDN-{0000000000}</displayFormat>
        <label>Coverage Sector Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Sector Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/CoverageType__c.field-meta.xml
<CustomField>
    <fullName>CoverageType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Coverage Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies</relationshipLabel>
    <relationshipName>CoverageSectorDependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/PrimarySector__c.field-meta.xml
<CustomField>
    <fullName>PrimarySector__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Sector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Primary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies (Primary Sector)</relationshipLabel>
    <relationshipName>CoverageSectorDependencies2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/SecondarySector__c.field-meta.xml
<CustomField>
    <fullName>SecondarySector__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Secondary Sector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Secondary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies (Secondary Sector)</relationshipLabel>
    <relationshipName>CoverageSectorDependencies3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Sector_Dependency__c/fields/TertiarySector__c.field-meta.xml
<CustomField>
    <fullName>TertiarySector__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tertiary Sector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Tertiary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Sector Dependencies (Tertiary Sector)</relationshipLabel>
    <relationshipName>CoverageSectorDependencies4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SectorValue__c/SectorValue__c.object-meta.xml
<CustomObject>
    <description>This object houses all the Coverage Types and Primary, Secondary, and Tertiary Sector values.  These records are used in the Coverage Dependency object for the dependent picklists.</description>
    <label>Sector Value</label>
    <nameField>
        <label>Sector Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sector Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SectorValue__c/fields/DependencyValue__c.field-meta.xml
<CustomField>
    <fullName>DependencyValue__c</fullName>
    <label>Dependency Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Type</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Tertiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SectorValue__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SectorValue__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HLSectorDependentPicklistTest.cls
@IsTest
private class HLSectorDependentPicklistTest {
    @IsTest
    static void myUnitTest(){
        List<HLSectorDependentPicklist.wrapper> ctList = HLSectorDependentPicklist.getCoverageType();
        
        List<HLSectorDependentPicklist.wrapper> primaryList = HLSectorDependentPicklist.getPrimaryCoverage(ctList.get(0).value);
        
        List<HLSectorDependentPicklist.wrapper> secondaryList = HLSectorDependentPicklist.getSecondaryCoverage(ctList.get(0).value,primaryList.get(0).value);
        
        List<HLSectorDependentPicklist.wrapper> tertiaryList = HLSectorDependentPicklist.getTertiaryCoverage(ctList.get(0).value,primaryList.get(0).value,secondaryList.get(0).value);
    }
    @TestSetup
    static void setupData(){
        List<SectorValue__c> svList = new List<SectorValue__c>();
        svList.add(new SectorValue__c(Active__c=true,Value__c='A',UniqueKey__c='A',DependencyValue__c='Type'));
        svList.add(new SectorValue__c(Active__c=true,Value__c='B',UniqueKey__c='B',DependencyValue__c='Primary'));
        svList.add(new SectorValue__c(Active__c=true,Value__c='C',UniqueKey__c='C',DependencyValue__c='Secondary'));
        svList.add(new SectorValue__c(Active__c=true,Value__c='D',UniqueKey__c='D',DependencyValue__c='Tertiary'));
        
        svList.add(new SectorValue__c(Active__c=true,Value__c='E',UniqueKey__c='E',DependencyValue__c='Type'));
        svList.add(new SectorValue__c(Active__c=true,Value__c='F',UniqueKey__c='F',DependencyValue__c='Primary'));
        svList.add(new SectorValue__c(Active__c=true,Value__c='G',UniqueKey__c='G',DependencyValue__c='Secondary'));
        svList.add(new SectorValue__c(Active__c=true,Value__c='H',UniqueKey__c='H',DependencyValue__c='Tertiary'));
        insert svList;
        List<Coverage_Sector_Dependency__c> csdList = new List<Coverage_Sector_Dependency__c>();
        csdList.add(new Coverage_Sector_Dependency__c(Active__c=true,CoverageType__c=svList.get(0).Id,PrimarySector__c=svList.get(1).Id,
                                                                             SecondarySector__c=svList.get(2).Id,TertiarySector__c=svList.get(3).Id));
        csdList.add(new Coverage_Sector_Dependency__c(Active__c=true,CoverageType__c=svList.get(4).Id,PrimarySector__c=svList.get(5).Id,
                                                                             SecondarySector__c=svList.get(6).Id,TertiarySector__c=svList.get(7).Id));
        insert csdList;
    }
}