force-app/main/default/objects/Debt_Structure__c/Debt_Structure__c.object-meta.xml
<CustomObject>
    <description>Custom object to track debt structures for restructuring engagements.</description>
    <label>Debt Structure</label>
    <nameField>
        <displayFormat>EDS-{000000}</displayFormat>
        <label>Debt Structure #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debt_Structure__c/fields/Amoritization__c.field-meta.xml
<CustomField>
    <fullName>Amoritization__c</fullName>
    <label>Amortization</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Call_Provisions_Prepayment_Premiums__c.field-meta.xml
<CustomField>
    <fullName>Call_Provisions_Prepayment_Premiums__c</fullName>
    <label>Call Provisions / Prepayment Premiums</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Constituent_Debt__c.field-meta.xml
<CustomField>
    <fullName>Constituent_Debt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Constituent Debt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Covenants__c.field-meta.xml
<CustomField>
    <fullName>Covenants__c</fullName>
    <label>Covenants</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Debt Structures</relationshipLabel>
    <relationshipName>Debt_Structures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Facility_Balance_MM__c.field-meta.xml
<CustomField>
    <fullName>Facility_Balance_MM__c</fullName>
    <label>Facility Balance (MM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Fees_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expenses__c</fullName>
    <label>Fees &amp; Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Mandatory_Prepayments_ECF_Sweep__c.field-meta.xml
<CustomField>
    <fullName>Mandatory_Prepayments_ECF_Sweep__c</fullName>
    <label>Mandatory Prepayments / ECF Sweep</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date__c</fullName>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/OID_Percent__c.field-meta.xml
<CustomField>
    <fullName>OID_Percent__c</fullName>
    <label>OID Percent</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Pre_Post_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Pre_Post_Transaction__c</fullName>
    <label>Pre / Post Transaction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Transaction</fullName>
            </value>
            <value>
                <fullName>Post-Transaction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Debt_Structure__c/fields/Security_Type__c.field-meta.xml
<CustomField>
    <fullName>Security_Type__c</fullName>
    <label>Security Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Debt (First Lien) - Revolver</fullName>
            </value>
            <value>
                <fullName>Bank Debt (First Lien) - Term Loan A</fullName>
            </value>
            <value>
                <fullName>Bank Debt (First Lien) - Term Loan B</fullName>
            </value>
            <value>
                <fullName>Bank Debt (First Lien) - Synthetic LC Facility</fullName>
            </value>
            <value>
                <fullName>ABL/ABS Facility - First Lien</fullName>
            </value>
            <value>
                <fullName>LC Facility</fullName>
            </value>
            <value>
                <fullName>Bank Debt (Second Lien)</fullName>
            </value>
            <value>
                <fullName>ABL/ABS Facility - Second Lien</fullName>
            </value>
            <value>
                <fullName>Convertible Notes (Secured)</fullName>
            </value>
            <value>
                <fullName>Senior Secured Notes</fullName>
            </value>
            <value>
                <fullName>Capital Leases</fullName>
            </value>
            <value>
                <fullName>Other Secured Debt</fullName>
            </value>
            <value>
                <fullName>Mezzanine Debt</fullName>
            </value>
            <value>
                <fullName>Senior Notes (Unsecured)</fullName>
            </value>
            <value>
                <fullName>Senior Subordinated Notes (Unsecured)</fullName>
            </value>
            <value>
                <fullName>Substantially All Assets</fullName>
            </value>
            <value>
                <fullName>Convertible Notes (Unsecured)</fullName>
            </value>
            <value>
                <fullName>Other Unsecured Debt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_DebtStructure.cls
public with sharing class HL_DebtStructure {
    public static List<Debt_Structure__c> GetByPrePostTransaction(id engagementId, string tran){
        return [SELECT Amoritization__c, Call_Provisions_Prepayment_Premiums__c, Constituent_Debt__c, Covenants__c, Facility_Balance_MM__c, Fees_Expenses__c, Interest__c, Mandatory_Prepayments_ECF_Sweep__c, Maturity_Date__c, OID_Percent__c, Security_Type__c FROM Debt_Structure__c WHERE Pre_Post_Transaction__c =: tran AND Engagement__c =: engagementId ORDER BY Security_Type__c];
    }
}