force-app/main/default/objects/Time_Record_Period__c/Time_Record_Period__c.object-meta.xml
<CustomObject>
    <description>Time record periods</description>
    <label>Time Record Period</label>
    <nameField>
        <displayFormat>TRP-{00000000}</displayFormat>
        <label>Time Record Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/Time_Record_Period_Staff_Member__c.object-meta.xml
<CustomObject>
    <label>Time Record Period Staff Member</label>
    <nameField>
        <displayFormat>TRPSM-{00000000}</displayFormat>
        <label>Time Record Period Staff Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Period Staff Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Time_Record_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period__c</fullName>
    <description>Related time record period record</description>
    <label>Time Record Period</label>
    <referenceTo>Time_Record_Period__c</referenceTo>
    <relationshipLabel>Time Record Period Staff Members</relationshipLabel>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HL_TimeRecordPeriodHandler.cls
public with sharing class HL_TimeRecordPeriodHandler {
    private boolean isExecuting = false;
    private integer batchSize = 0;
    public static Boolean isAfterInsertFlag = false;

    //Trigger Constructor
    public HL_TimeRecordPeriodHandler(boolean isExecuting, integer size){
        isExecuting = isExecuting;
        batchSize = size;
    }
    
    //Trigger Methods
    public void OnAfterInsert(List<Time_Record_Period__c> periods){
        if(!isAfterInsertFlag){            
            isAfterInsertFlag = true;

            for(Time_Record_Period__c trp : periods){
                //Insert the default staff records
                HL_TimeRecordPeriodStaffMemberHandler smHandler = new HL_TimeRecordPeriodStaffMemberHandler(trp);
                List<Time_Record_Period_Staff_Member__c> staffMembers = smHandler.InsertRecords();
                
                //Insert the default time records
                //HL_TimeRecordRollupWeekHandler trHandler = new HL_TimeRecordRollupWeekHandler(trp, staffMembers);
                //trHandler.InsertDefaultRecords();
            }
        }
    }


}