force-app/main/default/objects/Time_Record_Period__c/Time_Record_Period__c.object-meta.xml
<CustomObject>
    <description>Time record periods</description>
    <label>Time Record Period</label>
    <nameField>
        <displayFormat>TRP-{00000000}</displayFormat>
        <label>Time Record Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date for the Period</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period__c/fields/Period_Category__c.field-meta.xml
<CustomField>
    <fullName>Period_Category__c</fullName>
    <description>Used to categorize the period to allow for multiple functionalities</description>
    <label>Period Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beta</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Litigation</fullName>
                <default>true</default>
                <label>Litigation</label>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>TFR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record_Period__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <description>The time tracking public group name</description>
    <formula>CASE(TEXT(Period_Category__c), &quot;PV&quot;, &quot;Time_Tracking_PV&quot;, &quot;FR&quot;, &quot;Time_Tracking_FR&quot;, &quot;Beta&quot;, &quot;Time_Tracking_Beta&quot;, &quot;Litigation&quot;, &quot;Time_Tracking_Litigation&quot;, &quot;TFR&quot;, &quot;Time_Tracking_TFR&quot;, &quot;SC&quot;, &quot;Time_Tracking_SC&quot;, null)</formula>
    <label>Public Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Period Start date</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/Time_Record_Period_Staff_Member__c.object-meta.xml
<CustomObject>
    <label>Time Record Period Staff Member</label>
    <nameField>
        <displayFormat>TRPSM-{00000000}</displayFormat>
        <label>Time Record Period Staff Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Period Staff Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Time_Record_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period__c</fullName>
    <description>Related time record period record</description>
    <label>Time Record Period</label>
    <referenceTo>Time_Record_Period__c</referenceTo>
    <relationshipLabel>Time Record Period Staff Members</relationshipLabel>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_HL_TimeRecordPeriodHandler.cls
@isTest
private class Test_HL_TimeRecordPeriodHandler {
    @isTest 
    private static void TestAfterInsertCreationOfTimeRecordPeriodStaffMemberRecords(){
        Time_Record_Period__c periodRecord = (Time_Record_Period__c)HL_TestFactory.CreateSObject('Time_Record_Period__c', false);
        periodRecord.Start_Date__c = Date.today();
        periodRecord.End_Date__c = Date.today().addDays(6);
        periodRecord.Period_Category__c = 'Litigation';

        Test.startTest();

        insert periodRecord;

        Test.stopTest();

        //Validate the any staff members in the group now have a time record period staff member record
        Time_Record_Period__c periodResult = [SELECT Public_Group__c FROM Time_Record_Period__c WHERE Id=:periodRecord.Id];
        HL_Group groupRecord = new HL_Group(periodResult.Public_Group__c);
		List<Contact> staffMemberList = groupRecord.GetContacts();
        List<Time_Record_Period_Staff_Member__c> periodStaffMemberList = [SELECT Id FROM Time_Record_Period_Staff_Member__c WHERE Time_Record_Period__c =: periodResult.Id];
        System.assertEquals(staffMemberList.size(), periodStaffMemberList.size());
    }
}