force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CapIQ_Company__c/fields/Most_Recent_Fund_Size_MM__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Fund_Size_MM__c</fullName>
    <label>Most Recent Fund Size (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Custom object to track a capital provider&apos;s funds.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size (MM)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HL_FundHandler.cls
public class HL_FundHandler {
    public static void HandleLatestFlag(List<Fund__c> funds){
        //Create a Set of IDs for the Latest Flags
        Set<Id> lFunds = new Set<Id>();
        //Create a Map of Companies to the New/Update Size
        Map<Id,Decimal> companies = new Map<Id,Decimal>();
        for(Fund__c f:funds)
        {
            if(f.Latest__c){
                lFunds.add(f.Id);
                companies.put(f.CapIQ_Company__c,f.Size__c);        
            }         
        }

        //Remove the latest from any records that are marked as latest
        for(List<Fund__c> fToUpdate : [SELECT Id, Latest__c FROM Fund__c WHERE CapIQ_Company__c <> null AND CapIQ_Company__c IN:companies.keyset() AND Latest__c =:true And Id NOT IN:lFunds])
        {
            for(Fund__c f:fToUpdate)
                f.Latest__c = false;
            update fToUpdate;
        }
        //Get the Cap IQ Companies to Update the Most Recent Fund Size Field
        if(companies.size() > 0)
        {
        	for(List<CapIQ_Company__c> ccs : [SELECT Most_Recent_Fund_Size_MM__c FROM CapIQ_Company__c WHERE Id IN:companies.keySet()])
            {
                for(CapIQ_Company__c c: ccs)
                    c.Most_Recent_Fund_Size_MM__c = companies.get(c.Id);  
                
                if(ccs.size() > 0)
                    update ccs;
            }
        }
    }
}