force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CapIQ_Company__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Custom object to track a capital provider&apos;s funds.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry__c/Industry__c.object-meta.xml
<CustomObject>
    <description>Store the Industries</description>
    <label>Industry</label>
    <nameField>
        <label>Industry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASC - Augmenting Sector Coverage</fullName>
            </value>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>BUS - Facilities Management</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>CM - Capital Markets</fullName>
            </value>
            <value>
                <fullName>CMG - Capital Markets</fullName>
            </value>
            <value>
                <fullName>CORP - Corporate</fullName>
            </value>
            <value>
                <fullName>CVAS - Corporate Valuation Advisory Services</fullName>
            </value>
            <value>
                <fullName>DDS - Due Diligence Services</fullName>
            </value>
            <value>
                <fullName>Dist - Distribution</fullName>
            </value>
            <value>
                <fullName>DR - Dispute Resolution</fullName>
            </value>
            <value>
                <fullName>Eur - Europe</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>FRG - FRG</fullName>
            </value>
            <value>
                <fullName>FS - Financial Sponsors</fullName>
            </value>
            <value>
                <fullName>FVA - FVA</fullName>
            </value>
            <value>
                <fullName>GEN - General</fullName>
            </value>
            <value>
                <fullName>GER - Generalist/REVS</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IFA - Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>M&amp;A - Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>PFG - Private Funds Group</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>PV - Portfolio Valuation</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TAG - Tangible Asset Group</fullName>
            </value>
            <value>
                <fullName>TAS - Transaction Advisory Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Industry__c/fields/Industry_Sector__c.field-meta.xml
<CustomField>
    <fullName>Industry_Sector__c</fullName>
    <formula>Industry_Group_REPORTING__c + &quot; - &quot; +  Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry Sector</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track portfolio companies related to a fund.</description>
    <label>Investment</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Investment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Actual_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Actual_Relationship_Type__c</fullName>
    <label>Actual Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled Acquisition/Investment</fullName>
            </value>
            <value>
                <fullName>Current Investment</fullName>
            </value>
            <value>
                <fullName>Current Investment Arm</fullName>
            </value>
            <value>
                <fullName>Current Subsidiary/Operating Unit</fullName>
            </value>
            <value>
                <fullName>Merged Entity</fullName>
            </value>
            <value>
                <fullName>Pending Acquisition/Investment</fullName>
            </value>
            <value>
                <fullName>Prior Investment</fullName>
            </value>
            <value>
                <fullName>Prior Investment Arm</fullName>
            </value>
            <value>
                <fullName>Prior Subsidiary/Operating Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Amount_of_Investment__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Investment__c</fullName>
    <label>Amount of Investment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Date_Sold__c.field-meta.xml
<CustomField>
    <fullName>Date_Sold__c</fullName>
    <label>Date Sold</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>HL Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/EBITDA_CapIQ__c.field-meta.xml
<CustomField>
    <fullName>EBITDA_CapIQ__c</fullName>
    <label>CapIQ EBITDA (MM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/EBITDA_HL__c.field-meta.xml
<CustomField>
    <fullName>EBITDA_HL__c</fullName>
    <label>HL EBITDA (MM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Expected_Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Exit_Date__c</fullName>
    <label>Expected Exit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/HL_Industry_LK__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry_LK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>HL&apos;s perspective on the selected Investment&apos;s Industry</inlineHelpText>
    <label>HL Industry LK</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only FSC Industries are allowed.</errorMessage>
        <filterItems>
            <field>Industry__c.FSC__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>Investment</relationshipLabel>
    <relationshipName>Investment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/HL_Industry_Sector__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry_Sector__c</fullName>
    <description>it pulls the industry name because name = sector in this case. the help text is worded that way to minimize confusion - ayu</description>
    <formula>(IF(FIND(&quot; - &quot;, HL_Portfolio_Co_HL_Industry__c) &gt; 0, LEFT(HL_Portfolio_Co_HL_Industry__c, FIND( &quot; - &quot;, HL_Portfolio_Co_HL_Industry__c) - 1), HL_Portfolio_Co_HL_Industry__c)) + &quot; - &quot; + HL_Portfolio_Co_HL_Sector__c</formula>
    <inlineHelpText>Combines Industry reporting group and the selected HL Industry&apos;s sector</inlineHelpText>
    <label>HL Industry Sector</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>Portfolio_CapIQ_Company__r.Industry__c</formula>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Investment_Date__c.field-meta.xml
<CustomField>
    <fullName>Investment_Date__c</fullName>
    <label>Investment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Portfolio_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Portfolio Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Sponsor</relationshipLabel>
    <relationshipName>Investment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Related_Fund__c.field-meta.xml
<CustomField>
    <fullName>Related_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Fund</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Fund__c.CapIQ_Company__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Sponsor_CapIQ_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Revenue_CapIQ__c.field-meta.xml
<CustomField>
    <fullName>Revenue_CapIQ__c</fullName>
    <label>CapIQ Revenue (MM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Revenue_HL__c.field-meta.xml
<CustomField>
    <fullName>Revenue_HL__c</fullName>
    <label>HL Revenue (MM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Sponsor_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Sponsor Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Company</relationshipLabel>
    <relationshipName>Investment_Sponsor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Prior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_Investment.cls
public with sharing class HL_Investment {
    public HL_Investment() {}

    public static List<Investment__c> GetBySponsors(Set<Id> sponsors){
        return [SELECT Name, Amount_of_Investment__c, Date_Sold__c, Description__c, EBITDA_CapIQ__c, EBITDA_HL__c,  HL_Industry_Sector__c,
                       HL_Industry_LK__c, HL_Industry_LK__r.Industry_Group__c, HL_Industry_LK__r.Industry_Sector__c, Industry__c, Investment_Date__c, Portfolio_CapIQ_Company__r.Name, 
                       Expected_Exit_Date__c, Related_Fund__r.Name, Revenue_CapIQ__c, Revenue_HL__c, Status__c, Sponsor_CapIQ_Company__c, Sponsor_CapIQ_Company__r.Name, Actual_Relationship_Type__c 
                FROM Investment__c 
                WHERE Sponsor_CapIQ_Company__c <> null AND Sponsor_CapIQ_Company__c IN:sponsors];
    }
}