force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CapIQ_Company__c/fields/HL_Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry_Group__c</fullName>
    <label>HL Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food  &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CapIQ_Company__c/fields/HL_Sector__c.field-meta.xml
<CustomField>
    <fullName>HL_Sector__c</fullName>
    <label>HL Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HL_Industry_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Academic Research &amp; IP</fullName>
            </value>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Airlines/Air Cargo</fullName>
            </value>
            <value>
                <fullName>Ambulatory Surgical Centers</fullName>
            </value>
            <value>
                <fullName>Analytics &amp; Big Data</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automotive &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Autonomous Systems</fullName>
            </value>
            <value>
                <fullName>Behavioral &amp; Labs</fullName>
            </value>
            <value>
                <fullName>Broker Dealers</fullName>
            </value>
            <value>
                <fullName>Building Products</fullName>
            </value>
            <value>
                <fullName>Business Management Software</fullName>
            </value>
            <value>
                <fullName>Capital Goods</fullName>
            </value>
            <value>
                <fullName>CBD/Cannabis</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Commercial Financial Co.</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Infrastructure Components</fullName>
            </value>
            <value>
                <fullName>Communications Solutions</fullName>
            </value>
            <value>
                <fullName>Company &amp; Market Intelligence</fullName>
            </value>
            <value>
                <fullName>Consumer/Non-Mortgate Finance Co.</fullName>
            </value>
            <value>
                <fullName>Consumer Products</fullName>
            </value>
            <value>
                <fullName>Customer Information Management</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Data &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>Data Centers</fullName>
            </value>
            <value>
                <fullName>Dealership &amp; Rental Services</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track portfolio companies related to a fund.</description>
    <label>Investment</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Investment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/HL_Portfolio_Co_HL_Industry__c.field-meta.xml
<CustomField>
    <fullName>HL_Portfolio_Co_HL_Industry__c</fullName>
    <label>Portfolio Co. HL Industry</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/HL_Portfolio_Co_HL_Sector__c.field-meta.xml
<CustomField>
    <fullName>HL_Portfolio_Co_HL_Sector__c</fullName>
    <label>Portfolio Co. HL Sector</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Portfolio_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Portfolio Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Sponsor</relationshipLabel>
    <relationshipName>Investment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_CapIQ_Company_Handler.cls
/*
* Name: HL_CapIQ_Company_Handler
* Created Date: 2/22/2020
* Description: Apex Handler class for CapIQ Company object
*/ 
public with sharing class HL_CapIQ_Company_Handler {
    public static boolean ExecuteOnce = true;
    public static boolean IsTest = false;
    private boolean IsExecuting = false;
    private integer BatchSize = 0;
    
    public HL_CapIQ_Company_Handler (boolean executing, integer size)
    {
        IsExecuting = executing;
        BatchSize = size;
    }

    public void OnAfterUpdate(List<CapIQ_Company__c> newCapIQs, List<CapIQ_Company__c> oldCapIQs, Map<Id, CapIQ_Company__c> newCapIQMap, Map<Id, CapIQ_Company__c> oldCapIQMap)
    {
        if(ExecuteOnce){

            //Set stores All modified CapIQCompany record Ids
            Set<Id> CapIQCompanyIds=new Set<Id>();
            for(CapIQ_Company__c capIQ : newCapIQMap.values()){
                if((oldCapIQMap.get(capIQ.Id).HL_Industry_Group__c != newCapIQMap.get(capIQ.Id).HL_Industry_Group__c) || (oldCapIQMap.get(capIQ.Id).HL_Sector__c != newCapIQMap.get(capIQ.Id).HL_Sector__c)){
                   CapIQCompanyIds.add(capIQ.Id);
                }
            }
            
            if(CapIQCompanyIds.size() > 0){
                UpdateInvestmentFields(CapIQCompanyIds);
            }        
            ExecuteOnce = false;
        }
    }
    
    private void UpdateInvestmentFields(Set<Id> CapIQIds){
        List<Investment__c> InvestmentList = new List<Investment__c>();
        for(Investment__c InvList : [SELECT Id, HL_Portfolio_Co_HL_Industry__c, HL_Portfolio_Co_HL_Sector__c, Portfolio_CapIQ_Company__r.HL_Industry_Group__c, Portfolio_CapIQ_Company__r.HL_Sector__c 
                                    FROM Investment__c WHERE Portfolio_CapIQ_Company__c IN :CapIQIds]){
            InvList.HL_Portfolio_Co_HL_Industry__c = InvList.Portfolio_CapIQ_Company__r.HL_Industry_Group__c;                   
            InvList.HL_Portfolio_Co_HL_Sector__c = InvList.Portfolio_CapIQ_Company__r.HL_Sector__c;
            InvestmentList.add(InvList); 
        }
        
        if(InvestmentList.size() > 0){
            Database.SaveResult[] saveResults =   Database.update(InvestmentList, true);
        }
    }
}