force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CapIQ_Company__c/fields/Most_Recent_Fund_Size_MM__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Fund_Size_MM__c</fullName>
    <label>Most Recent Fund Size (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Custom object to track a capital provider&apos;s funds.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size (MM)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_HL_Fund_Handler.cls
@isTest
private class Test_HL_Fund_Handler {
    @isTest private static void TestInsertOneFundToOpportunity(){
         //TODO: Move into SL_TestSetupUtils once we create appropriate functions
         CapIQ_Company__c cc = new CapIQ_Company__c();
         insert cc;    
         Fund__c existingFund = new Fund__c(CapIQ_Company__c = cc.Id);
         insert existingFund;
         List<Fund__c> funds = new List<Fund__c>();
         for(Integer i=0; i<5; i++)
            funds.add(New Fund__c(CapIQ_Company__c = cc.Id));
         insert funds;
         //Create an existing fund to fully test logic
         existingFund.Latest__c = true;
         update existingFund;
        
         for(Integer i=0; i<funds.size(); i++){
            funds[i].Size__c = i;
            if(i==4)
            	funds[i].Latest__c = true;  
        }
        
        update funds;
        cc = [SELECT Id, Most_Recent_Fund_Size_MM__c FROM CapIQ_Company__c WHERE Id =:cc.Id];
        
        //Validate the Most Recent Fund Size has been updated appropriately
        System.assert(cc.Most_Recent_Fund_Size_MM__c == funds.size() - 1);
        System.assert(funds[0].Latest__c == false);
        System.assert(funds[funds.size() - 1].Latest__c == true);
    }
}