force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CapIQ_Company__c/fields/HL_Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry_Group__c</fullName>
    <label>HL Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food  &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CapIQ_Company__c/fields/HL_Sector__c.field-meta.xml
<CustomField>
    <fullName>HL_Sector__c</fullName>
    <label>HL Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HL_Industry_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Academic Research &amp; IP</fullName>
            </value>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Airlines/Air Cargo</fullName>
            </value>
            <value>
                <fullName>Ambulatory Surgical Centers</fullName>
            </value>
            <value>
                <fullName>Analytics &amp; Big Data</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automotive &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Autonomous Systems</fullName>
            </value>
            <value>
                <fullName>Behavioral &amp; Labs</fullName>
            </value>
            <value>
                <fullName>Broker Dealers</fullName>
            </value>
            <value>
                <fullName>Building Products</fullName>
            </value>
            <value>
                <fullName>Business Management Software</fullName>
            </value>
            <value>
                <fullName>Capital Goods</fullName>
            </value>
            <value>
                <fullName>CBD/Cannabis</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Commercial Financial Co.</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Infrastructure Components</fullName>
            </value>
            <value>
                <fullName>Communications Solutions</fullName>
            </value>
            <value>
                <fullName>Company &amp; Market Intelligence</fullName>
            </value>
            <value>
                <fullName>Consumer/Non-Mortgate Finance Co.</fullName>
            </value>
            <value>
                <fullName>Consumer Products</fullName>
            </value>
            <value>
                <fullName>Customer Information Management</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Data &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>Data Centers</fullName>
            </value>
            <value>
                <fullName>Dealership &amp; Rental Services</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track portfolio companies related to a fund.</description>
    <label>Investment</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Investment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/HL_Portfolio_Co_HL_Industry__c.field-meta.xml
<CustomField>
    <fullName>HL_Portfolio_Co_HL_Industry__c</fullName>
    <label>Portfolio Co. HL Industry</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/HL_Portfolio_Co_HL_Sector__c.field-meta.xml
<CustomField>
    <fullName>HL_Portfolio_Co_HL_Sector__c</fullName>
    <label>Portfolio Co. HL Sector</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Portfolio_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Portfolio Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Sponsor</relationshipLabel>
    <relationshipName>Investment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_InvestmentHandler.cls
/*
* Name: HL_InvestmentHandler  
* Created Date: 2/22/2020
* Description: handler class for Investment object
*/ 
public with sharing class HL_InvestmentHandler {
    private boolean isExecuting = false;
    private integer batchSize = 0;
    public boolean IsTriggerContext{get{ return isExecuting;}}
    public static Boolean isBeforeInsertFlag = false;
    public static Boolean isAfterInsertFlag = false;
    public static Boolean isBeforeUpdateFlag = false;

    public HL_InvestmentHandler(boolean isExecuting, integer size){
        isExecuting = isExecuting;
        batchSize = size;
    }

    public void OnBeforeInsert(List<Investment__c> newInvestmentList){
        if(!isBeforeInsertFlag){
            isBeforeInsertFlag = true;
            createIndustrySectorFields(newInvestmentList);
        }
    }
        
    public void OnAfterInsert(Map<Id, Investment__c> insertedMap){
        if(!isAfterInsertFlag){            
            isAfterInsertFlag = true;
            HL_OffsiteTemplate.HandleInsertedInvestmentRecords(insertedMap);
        }
    }

    public void OnBeforeUpdate(List<Investment__c> newInvestmentList , List<Investment__c> oldInvestmentList,  Map<Id, Investment__c> newInvestmentMap, Map<Id, Investment__c> oldInvestmentMap){
        if(!isBeforeUpdateFlag){
            isBeforeUpdateFlag = true;
            updateIndustrySectorFields(newInvestmentList, newInvestmentMap, oldInvestmentMap);
        }    
    }
    
    private void createIndustrySectorFields(List<Investment__c> newInvList){
        Set<Id> setInvIds = new Set<Id>();
   
        for(Investment__c InvList : newInvList){
            if(InvList.Portfolio_CapIQ_Company__c != null){
                setInvIds.add(InvList.Portfolio_CapIQ_Company__c);
            }
        }
        if(setInvIds != null && setInvIds.size() > 0){
            setIndustrySectorFields(newInvList, setInvIds);        
        }
    }
        
    private void updateIndustrySectorFields(List<Investment__c> newInvList, Map<Id, Investment__c> newInvMap, Map<Id, Investment__c> oldInvMap){
        Set<Id> setInvIds = new Set<Id>();
   
        for(Investment__c InvList : newInvMap.values()){
            if(newInvMap.get(InvList.Id).Portfolio_CapIQ_Company__c != null && oldInvMap.get(InvList.Id).Portfolio_CapIQ_Company__c != newInvMap.get(InvList.Id).Portfolio_CapIQ_Company__c){
                setInvIds.add(InvList.Portfolio_CapIQ_Company__c);
            }else if (newInvMap.get(InvList.Id).Portfolio_CapIQ_Company__c == null) {
                InvList.HL_Portfolio_Co_HL_Industry__c = '';
                InvList.HL_Portfolio_Co_HL_Sector__c = '';
            }
        }
        if(setInvIds != null && setInvIds.size() > 0){
            setIndustrySectorFields(newInvList, setInvIds);
        }
    }
    
    private void setIndustrySectorFields(List<Investment__c> newInvestmentsList, Set<Id> setInvestmentIds){
        
        Map<Id, CapIQ_Company__c> mapOfCapIQIdWithObject = new Map<Id, CapIQ_Company__c>();    
        
        for(CapIQ_Company__c objCapIQ : [SELECT id, Name, HL_Industry_Group__c, HL_Sector__c from CapIQ_Company__c WHERE Id IN :setInvestmentIds]){
            mapOfCapIQIdWithObject.put(objCapIQ.Id, objCapIQ);
        }
            
        for(Investment__c InvList : newInvestmentsList){
            if(InvList.Portfolio_CapIQ_Company__c != null && mapOfCapIQIdWithObject.containsKey(InvList.Portfolio_CapIQ_Company__c)){
                InvList.HL_Portfolio_Co_HL_Industry__c = mapOfCapIQIdWithObject.get(InvList.Portfolio_CapIQ_Company__c).HL_Industry_Group__c;
                InvList.HL_Portfolio_Co_HL_Sector__c = mapOfCapIQIdWithObject.get(InvList.Portfolio_CapIQ_Company__c).HL_Sector__c;
            }
        }
    }

}