force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>This is an HL Contract object. Stores information from Engagement or Opportunity and integrates with Oracle Contract object.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Contract</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <description>Business Unit in ERP

Maps to /createContract/contractHeader/OrgName/OwningOrgName</description>
    <inlineHelpText>Please select a business unit of this contract</inlineHelpText>
    <label>ERP Business Unit</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ERP_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contract_Type__c</fullName>
    <description>Contract Type for Oracle

Maps to /createContract/contractHeader/ContractTypeName</description>
    <inlineHelpText>Please select Engagement for a customer contract, or ICO for an intercompany ontract</inlineHelpText>
    <label>ERP Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Engagement</fullName>
                <default>true</default>
                <label>Engagement</label>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ERP_Legal_Entity_Lookup__c.field-meta.xml
<CustomField>
    <fullName>ERP_Legal_Entity_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERP Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Contract</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ERP_TAX_Classification_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_TAX_Classification_Code__c</fullName>
    <label>ERP TAX Classification Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <description>Business Unit, or Ledger, in ERP. Should come from Legal Entity.</description>
    <label>ERP Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/ERP_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_Entity_Code__c</fullName>
    <description>ERP Entity Code - Code from Legal Entity lookup value and populating value through Process builder</description>
    <label>ERP Entity Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Legal Entity</description>
    <label>Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Legal_Entity__c.Available_for_Project__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Tax_Classification_Code_Eng_VAT_Treatmnt__c.field-meta.xml
<CustomField>
    <fullName>Tax_Classification_Code_Eng_VAT_Treatmnt__c</fullName>
    <description>Engagement Vat Treatment, Latest Effective date records &quot;Tax Classification Code&quot; value</description>
    <label>Tax Classification Code Eng VAT Treatmnt</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_VAT_Treatment__c/Engagement_VAT_Treatment__c.object-meta.xml
<CustomObject>
    <label>Engagement VAT Treatment</label>
    <nameField>
        <displayFormat>EVT-{000000}</displayFormat>
        <label>Engagement VAT Treatment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement VAT Treatments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_VAT_Treatment__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Engagement_VAT_Treatements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_VAT_Treatment__c/fields/HL_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>HL_Entity_Code__c</fullName>
    <formula>Engagement__r.ERP_Entity_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HL Entity Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_VAT_Treatment__c/fields/Tax_Classification_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Classification_Code__c</fullName>
    <label>Tax Classification Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_VAT_Treatment__c/fields/Treatment__c.field-meta.xml
<CustomField>
    <fullName>Treatment__c</fullName>
    <label>Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard Rated</fullName>
            </value>
            <value>
                <fullName>Zero Rated</fullName>
            </value>
            <value>
                <fullName>Exempt with Credit</fullName>
            </value>
            <value>
                <fullName>Exempt without Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <description>Maintains the legal entities of Houlihan Lokey</description>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Entity__c/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <description>The business unit of the entity in ERP</description>
    <label>ERP Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/fields/ERP_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_Entity_Code__c</fullName>
    <description>The code of the legal entity in ERP</description>
    <label>ERP Entity Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Billing_Event__c/Revenue_Billing_Event__c.object-meta.xml
<CustomObject>
    <label>Revenue Billing Event</label>
    <nameField>
        <label>Revenue Billing Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Billing Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Billing_Event__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Revenue Billing Events</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/Tax_Classification_Code__mdt.object-meta.xml
<CustomObject>
    <description>Stores the Tax Classification Code assigned to Opportunity VAT Treatments and Engagement VAT Treatments.
Tax Classification Code is determined based on specified Legal Entity &apos;Entity Code&apos; and VAT Treatment.</description>
    <label>Tax Classification Code</label>
    <pluralLabel>Tax Classification Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <label>ERP Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/ERP_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_Entity_Code__c</fullName>
    <label>ERP Entity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/Tax_Classification_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Classification_Code__c</fullName>
    <label>Tax Classification Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/Treatment__c.field-meta.xml
<CustomField>
    <fullName>Treatment__c</fullName>
    <label>Treatment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_EngagementVatTreatmentHandler.cls
/*
* Name: HL_EngagementVatTreatmentHandler 
* Created Date: 10/03/2019
* Created By: Publicis Sapient
* Functionality : Handler class to implement logic for Engagement_VAT_Treatment__c object
*/

public with sharing class HL_EngagementVatTreatmentHandler {
    private boolean IsExecuting = false;
    private integer BatchSize = 0;
    public static final string CLASS_NAME = 'HL_EngagementVATTreatmentHandler';
    
    public HL_EngagementVatTreatmentHandler(boolean executing, integer size){
        IsExecuting = executing;
        BatchSize = size;
    }
    
    //Update VAT Treatment records when the 'Legal Entity' of the parent engagement changes
    public static void updateTaxClassificationCode(Set<Id> vatTreatmentIdSet, Map<Id,Engagement_VAT_Treatment__c> oldEngVATTreatmentMap, Boolean listPassedFromParent){
        try{
            List<Engagement_VAT_Treatment__c> engagementVATTreatmentList = [SELECT Id, Treatment__c, Engagement__c, Engagement__r.Legal_Entity__c, Engagement__r.Legal_Entity__r.ERP_Entity_Code__c FROM Engagement_VAT_Treatment__c WHERE Id IN: vatTreatmentIdSet];
            List<Tax_Classification_Code__mdt> taxClassificationList = [SELECT MasterLabel,ERP_Business_Unit__c,ERP_Entity_Code__c,Tax_Classification_Code__c,Treatment__c FROM Tax_Classification_Code__mdt];
            Map<String,Tax_Classification_Code__mdt> taxClassificationMap = new Map<String,Tax_Classification_Code__mdt>();
            for(Tax_Classification_Code__mdt taxClassification :taxClassificationList){
                taxClassificationMap.put(taxClassification.MasterLabel.trim().toLowercase(), taxClassification);
            }     
            system.debug('Tax_Classification_Code__mdt: ' + taxClassificationMap);
            
            List<Engagement_VAT_Treatment__c> engagementVATTreatmentUpdateList = new List<Engagement_VAT_Treatment__c>();
            for(Engagement_VAT_Treatment__c engVATTreatment : engagementVATTreatmentList){                
                if(listPassedFromParent
                   || Trigger.isInsert
                   || (Trigger.isUpdate 
                       && (engVATTreatment.Treatment__c !=  oldEngVATTreatmentMap.get(engVATTreatment.Id).Treatment__c 
                           || engVATTreatment.Engagement__c != oldEngVATTreatmentMap.get(engVATTreatment.Id).Engagement__c))){
                               String entityCodeTreatment = (engVATTreatment.Engagement__r.Legal_Entity__r.ERP_Entity_Code__c + '-' + engVATTreatment.Treatment__c).trim().toLowercase();
                               Engagement_VAT_Treatment__c EngagementVATTreatment = new Engagement_VAT_Treatment__c();
                               if(taxClassificationMap.containsKey(entityCodeTreatment)){
                                   EngagementVATTreatment.Tax_Classification_Code__c = taxClassificationMap.get(entityCodeTreatment).Tax_Classification_Code__c;
                               }
                               else{
                                   EngagementVATTreatment.Tax_Classification_Code__c = '';
                               }
                               EngagementVATTreatment.Id = engVATTreatment.Id;
                               engagementVATTreatmentUpdateList.add(EngagementVATTreatment);
                           }
            }
            
            if(engagementVATTreatmentUpdateList.size() > 0){
                Database.SaveResult[] saveResultList = Database.update(engagementVATTreatmentUpdateList,false);
                ErrorHandlingUtility.handleDatabaseSaveResults(saveResultList, CLASS_NAME);
            }
        }catch(exception ex){
            ErrorHandlingUtility.logException(null, ex);
        }
    }
    
    //Check for duplicate engagement VAT treatments based on Effective Date
    public static void checkForDuplicateVATTreatments(List<Engagement_VAT_Treatment__c> engagementVATTreatmentList){
        Set<Id> engIds= new Set<Id>();
        Map<String, Engagement_VAT_Treatment__c> engVATMap = new Map<String, Engagement_VAT_Treatment__c>();
        
        for(Engagement_VAT_Treatment__c eVAT : engagementVATTreatmentList){
            engIds.add(eVAT.Engagement__c);
        }
        
        for(Engagement_VAT_Treatment__c eVAT : [SELECT Id, Engagement__c, Effective_Date__c FROM Engagement_VAT_Treatment__c WHERE Engagement__c IN :engIds]){
            engVATMap.put(eVAT.Engagement__c + '-' + eVAT.Effective_Date__c.format(), eVAT);
        }
        
        for(Engagement_VAT_Treatment__c eVAT: engagementVATTreatmentList){
            Engagement_VAT_Treatment__c engVATRecord = engVATMap.get(eVAT.Engagement__c + '-' + eVAT.Effective_Date__c.format());
            if(engVATRecord != null && eVAT.Id != engVATRecord.Id)
                eVAT.addError('A duplicate VAT Treatment record with Effective Date \'' + engVATRecord.Effective_Date__c.format() + '\' '  + 'already exist for this engagement.');
        }
    }
    
    //Assign VAT Treatment Classification Codes
    public static void getVATTaxClassificationCode(List<Engagement_VAT_Treatment__c > engagementVATTreatmentList, Map<Id,Engagement_VAT_Treatment__c> oldEngVATTreatmentMap){
        List<Tax_Classification_Code__mdt> taxClassificationList = [SELECT MasterLabel,ERP_Business_Unit__c,ERP_Entity_Code__c,Tax_Classification_Code__c,Treatment__c FROM Tax_Classification_Code__mdt];
        Map<String,Tax_Classification_Code__mdt> taxClassificationMap = new Map<String,Tax_Classification_Code__mdt>();
        
        for(Tax_Classification_Code__mdt taxClassification :taxClassificationList){
            taxClassificationMap.put(taxClassification.MasterLabel.trim().toLowercase(), taxClassification);
        }     
        system.debug('Tax_Classification_Code__mdt: ' + taxClassificationMap);
        
        for(Engagement_VAT_Treatment__c engVAT : engagementVATTreatmentList){
            if(Trigger.isInsert
               || (Trigger.isUpdate 
                   && (engVAT.Treatment__c !=  oldEngVATTreatmentMap.get(engVAT.Id).Treatment__c 
                       || engVAT.Engagement__c != oldEngVATTreatmentMap.get(engVAT.Id).Engagement__c))){
                           String entityCodeTreatment = (engVAT.HL_Entity_Code__c + '-' + engVAT.Treatment__c).trim().toLowercase();
                           system.debug('entityCodeTreatment:  ' + entityCodeTreatment);
                           
                           if(taxClassificationMap.containsKey(entityCodeTreatment)){
                               engVAT.Tax_Classification_Code__c = taxClassificationMap.get(entityCodeTreatment).Tax_Classification_Code__c;
                           }
                           else{
                               engVAT.Tax_Classification_Code__c = '';
                           }
            }
        }
    }
    
    //Check for modified VAT Treatment records
    public static void checkForUpdatedVATTreatments(List<Engagement_VAT_Treatment__c > engVATTreatmentList, Map<Id,Engagement_VAT_Treatment__c> oldEngVATTreatmentMap){
        Set<Id> engIdSet = new Set<Id>(); 
        if(Trigger.isInsert || Trigger.isUpdate){
            for(Engagement_VAT_Treatment__c engVAT : engVATTreatmentList){
                if(Trigger.isInsert
                   || (Trigger.isUpdate 
                       && (engVAT.Tax_Classification_Code__c != oldEngVATTreatmentMap.get(engVAT.Id).Tax_Classification_Code__c 
                           || engVAT.Effective_Date__c != oldEngVATTreatmentMap.get(engVAT.Id).Effective_Date__c))){
                           engIdSet.add(engVAT.Engagement__c);
                }
            }
        } else if(Trigger.isDelete){
            for(Engagement_VAT_Treatment__c engVAT : oldEngVATTreatmentMap.Values()){
                engIdSet.add(engVAT.Engagement__c);    
            }        
        }
        
        if(engIdSet != null && engIdSet.size() > 0){
            updateTaxClassificationOnContracts(engIdSet);
        }
     }
     
    //Update related contracts with latest VAT Tax Classification Code
    @future
    public static void updateTaxClassificationOnContracts(Set<Id> engagementSet){
        List<Contract__c> contractToUpdateList = new List<Contract__c>();
        Map<Id, Engagement__c> mapOfEngagement = new Map<Id,Engagement__c>();
        
        for(Engagement__c eng : [SELECT Id, Tax_Classification_Code_Eng_VAT_Treatmnt__c, 
                                (SELECT Id, Tax_Classification_Code__c FROM Engagement_VAT_Treatements__r ORDER BY Effective_Date__c DESC, CreatedDate DESC LIMIT 1), 
                                (SELECT Id, ERP_TAX_Classification_Code__c, End_Date__c FROM Contract__r WHERE ERP_Contract_Type__c = 'Engagement') FROM Engagement__c WHERE Id in :engagementSet]){
            if(eng.Contract__r != null && eng.Contract__r.size() > 0){             
                for(Contract__c engContract : eng.Contract__r){
                    if(engContract.End_Date__c == null){
                        Contract__c con = new Contract__c(Id = engContract.Id);
                        if(eng.Engagement_VAT_Treatements__r != null && eng.Engagement_VAT_Treatements__r.size() > 0){
                            con.ERP_TAX_Classification_Code__c = eng.Engagement_VAT_Treatements__r[0].Tax_Classification_Code__c;
                        } else {
                            con.ERP_TAX_Classification_Code__c = '';
                        }
                        contractToUpdateList.add(con);
                    }
                }                   
            }
        }
        
        if(contractToUpdateList != null && contractToUpdateList.size() > 0){
            update contractToUpdateList;
        }
    }
}