force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>This is an HL Contract object. Stores information from Engagement or Opportunity and integrates with Oracle Contract object.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <description>Business Unit in ERP

Maps to /createContract/contractHeader/OrgName/OwningOrgName</description>
    <inlineHelpText>Please select a business unit of this contract</inlineHelpText>
    <label>ERP Business Unit</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ERP_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contract_Type__c</fullName>
    <description>Contract Type for Oracle

Maps to /createContract/contractHeader/ContractTypeName</description>
    <inlineHelpText>Please select Engagement for a customer contract, or ICO for an intercompany ontract</inlineHelpText>
    <label>ERP Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Engagement</fullName>
                <default>true</default>
                <label>Engagement</label>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ERP_Legal_Entity_Lookup__c.field-meta.xml
<CustomField>
    <fullName>ERP_Legal_Entity_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERP Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Contract</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ERP_TAX_Classification_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_TAX_Classification_Code__c</fullName>
    <label>ERP TAX Classification Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Contract</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERP_Invoice_Detail__c/ERP_Invoice_Detail__c.object-meta.xml
<CustomObject>
    <description>This will store the invoice details, sent from the ERP application</description>
    <label>ERP Invoice Detail</label>
    <nameField>
        <displayFormat>ID-{YYYY}{MM}-{0}</displayFormat>
        <label>ERP Invoice Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Invoice Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERP_Invoice_Detail__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>ERP Invoice Details</relationshipLabel>
    <relationshipName>ERP_Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERP_Invoice_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>ERP Invoice Details</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <description>Maintains the legal entities of Houlihan Lokey</description>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Entity__c/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <description>The business unit of the entity in ERP</description>
    <label>ERP Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/fields/ERP_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_Entity_Code__c</fullName>
    <description>The code of the legal entity in ERP</description>
    <label>ERP Entity Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <label>ERP Business Unit</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Legal Entity lookup</description>
    <label>Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(2 AND 3) OR (4 AND 1)</booleanFilter>
        <filterItems>
            <field>Legal_Entity__c.Available_for_Project__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>HL Internal Opportunity</value>
        </filterItems>
        <filterItems>
            <field>Legal_Entity__c.Available_for_Internal_Project__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>HL Internal Opportunity</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_VAT_Treatment__c/Opportunity_VAT_Treatment__c.object-meta.xml
<CustomObject>
    <label>Opportunity VAT Treatment</label>
    <nameField>
        <displayFormat>OVT-{000000}</displayFormat>
        <label>Opportunity VAT Treatment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity VAT Treatments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_VAT_Treatment__c/fields/HL_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>HL_Entity_Code__c</fullName>
    <formula>Opportunity__r.ERP_Entity_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HL Entity Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_VAT_Treatment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity VAT Treatments</relationshipLabel>
    <relationshipName>Opportunity_VAT_Treatments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_VAT_Treatment__c/fields/Treatment__c.field-meta.xml
<CustomField>
    <fullName>Treatment__c</fullName>
    <label>Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Rated</fullName>
            </value>
            <value>
                <fullName>Zero Rated</fullName>
            </value>
            <value>
                <fullName>Exempt with Credit</fullName>
            </value>
            <value>
                <fullName>Exempt without Credit</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
                <isActive>false</isActive>
                <label>Exempt</label>
            </value>
            <value>
                <fullName>Exempt without Credit TCC</fullName>
                <isActive>false</isActive>
                <label>Exempt without Credit TCC</label>
            </value>
            <value>
                <fullName>Exempt without Credit UDFC</fullName>
                <isActive>false</isActive>
                <label>Exempt without Credit UDFC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Billing_Event__c/Revenue_Billing_Event__c.object-meta.xml
<CustomObject>
    <label>Revenue Billing Event</label>
    <nameField>
        <label>Revenue Billing Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Billing Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Billing_Event__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Revenue Billing Events</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/Tax_Classification_Code__mdt.object-meta.xml
<CustomObject>
    <description>Stores the Tax Classification Code assigned to Opportunity VAT Treatments and Engagement VAT Treatments.
Tax Classification Code is determined based on specified Legal Entity &apos;Entity Code&apos; and VAT Treatment.</description>
    <label>Tax Classification Code</label>
    <pluralLabel>Tax Classification Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/ERP_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>ERP_Business_Unit__c</fullName>
    <label>ERP Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/ERP_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_Entity_Code__c</fullName>
    <label>ERP Entity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/Tax_Classification_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Classification_Code__c</fullName>
    <label>Tax Classification Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Classification_Code__mdt/fields/Treatment__c.field-meta.xml
<CustomField>
    <fullName>Treatment__c</fullName>
    <label>Treatment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_OpportunityVATTreatmentHandler.cls
/*
* Name: HL_OpportunityVATTreatmentHandler 
* Created Date: 10/03/2019
* Created By: Publicis Sapient
* Functionality : Handler class to implement logic for Opportunity_VAT_Treatment__c object
*/

public with sharing class HL_OpportunityVATTreatmentHandler {
    private boolean IsExecuting = false;
    private integer BatchSize = 0;
    public static final string CLASS_NAME = 'HL_OpportunityVATTreatmentHandler';
    
    public HL_OpportunityVATTreatmentHandler(boolean executing, integer size){
        IsExecuting = executing;
        BatchSize = size;
    }
    
    //Update VAT Treatment records when the 'Legal Entity' of the parent opportunity changes
    public static void updateTaxClassificationCode(List<Opportunity_VAT_Treatment__c> opportunityVATTreatmentList, List<Opportunity_VAT_Treatment__c> oldOpportunityVATTreatmentList, Boolean listPassedFromParent){
        try{
            List<Tax_Classification_Code__mdt> taxClassificationList = [SELECT MasterLabel,ERP_Business_Unit__c,Legal_Entity_Name__c, ERP_Entity_Code__c, Tax_Classification_Code__c,Treatment__c FROM Tax_Classification_Code__mdt];
            Map<String,Tax_Classification_Code__mdt> taxClassificationMap = new Map<String,Tax_Classification_Code__mdt>();
            for(Tax_Classification_Code__mdt taxClassification :taxClassificationList){
                taxClassificationMap.put(taxClassification.MasterLabel.trim().toLowercase(), taxClassification);
            }        
            Map<Id,Opportunity_VAT_Treatment__c> oldOppVATTreatmentMap;
            if(trigger.isUpdate && listPassedFromParent == false){
                oldOppVATTreatmentMap = new Map<Id,Opportunity_VAT_Treatment__c>(oldOpportunityVATTreatmentList);
            }
            List<Opportunity_VAT_Treatment__c> oppVATTreatmentUpdateList = new List<Opportunity_VAT_Treatment__c>();
            for(Opportunity_VAT_Treatment__c oppVATTreatment : opportunityVATTreatmentList){
                if(listPassedFromParent
                   || Trigger.isInsert
                   || (Trigger.isUpdate 
                       && (oppVATTreatment.Treatment__c !=  oldOppVATTreatmentMap.get(oppVATTreatment.Id).Treatment__c 
                           || oppVATTreatment.Opportunity__c != oldOppVATTreatmentMap.get(oppVATTreatment.Id).Opportunity__c))){         
                               String businessType_Treatment = (oppVATTreatment.Opportunity__r.Legal_Entity__r.ERP_Entity_Code__c +'-'+oppVATTreatment.Treatment__c).trim().toLowercase();
                               Opportunity_VAT_Treatment__c opportunityVATTreatment = new Opportunity_VAT_Treatment__c();
                               if(taxClassificationMap.containsKey(businessType_Treatment)){
                                   opportunityVATTreatment.Tax_Classification_Code__c = taxClassificationMap.get(businessType_Treatment).Tax_Classification_Code__c;
                               }
                               else{
                                   opportunityVATTreatment.Tax_Classification_Code__c = '';
                               }
                               opportunityVATTreatment.Id = oppVATTreatment.Id;
                               oppVATTreatmentUpdateList.add(opportunityVATTreatment);
                           }
            }
            if(oppVATTreatmentUpdateList.size() > 0){
                Database.SaveResult[] saveResultList = Database.update(oppVATTreatmentUpdateList,false);
                ErrorHandlingUtility.handleDatabaseSaveResults(saveResultList, CLASS_NAME);
            }
        }catch(exception ex){
            ErrorHandlingUtility.logException(null, ex);
        }
    }
    
    //Check for duplicate opportunity VAT treatments based on Effective Date
    public static void checkForDuplicateVATTreatments(List<Opportunity_VAT_Treatment__c> opportunityVATTreatmentList){
        Set<Id> oppIds= new Set<Id>();
        Map<String, Opportunity_VAT_Treatment__c> oppVATMap = new Map<String, Opportunity_VAT_Treatment__c>();
        
        for(Opportunity_VAT_Treatment__c oVAT : opportunityVATTreatmentList){
            oppIds.add(oVAT.Opportunity__c);
        }
        
        for(Opportunity_VAT_Treatment__c oVAT : [SELECT Id, Opportunity__c, Effective_Date__c FROM Opportunity_VAT_Treatment__c WHERE Opportunity__c IN :oppIds]){
            oppVATMap.put(oVAT.Opportunity__c + '-' + oVAT.Effective_Date__c.format(), oVAT);
        }
        
        for(Opportunity_VAT_Treatment__c oVAT: opportunityVATTreatmentList){
            Opportunity_VAT_Treatment__c oppVATRecord = oppVATMap.get(oVAT.Opportunity__c + '-' + oVAT.Effective_Date__c.format());
            if(oppVATRecord != null && oVAT.Id != oppVATRecord.Id)
                oVAT.addError('A duplicate VAT Treatment record with Effective Date \'' + oppVATRecord.Effective_Date__c.format() + '\' '  + 'already exist for this opportunity.');
        }
    }
    
    //Assign VAT Treatment Classification Codes
    public static void getVATTaxClassificationCode(List<Opportunity_VAT_Treatment__c > oppVATTreatmentList, Map<Id,Opportunity_VAT_Treatment__c> oldOppVATTreatmentMap){
        List<Tax_Classification_Code__mdt> taxClassificationList = [SELECT MasterLabel,ERP_Business_Unit__c,ERP_Entity_Code__c,Tax_Classification_Code__c,Treatment__c FROM Tax_Classification_Code__mdt];
        Map<String,Tax_Classification_Code__mdt> taxClassificationMap = new Map<String,Tax_Classification_Code__mdt>();
        
        for(Tax_Classification_Code__mdt taxClassification :taxClassificationList){
            taxClassificationMap.put(taxClassification.MasterLabel.trim().toLowercase(), taxClassification);
        }     
        system.debug('Tax_Classification_Code__mdt: ' + taxClassificationMap);
        
        for(Opportunity_VAT_Treatment__c oppVAT : oppVATTreatmentList){
            if(Trigger.isInsert
               || (Trigger.isUpdate 
                   && (oppVAT.Treatment__c != oldOppVATTreatmentMap.get(oppVAT.Id).Treatment__c 
                       || oppVAT.Opportunity__c != oldOppVATTreatmentMap.get(oppVAT.Id).Opportunity__c))){
                           String entityCodeTreatment = (oppVAT.HL_Entity_Code__c + '-' + oppVAT.Treatment__c).trim().toLowercase();
                           system.debug('entityCodeTreatment:  ' + entityCodeTreatment);
                           
                           if(taxClassificationMap.containsKey(entityCodeTreatment)){
                               oppVAT.Tax_Classification_Code__c = taxClassificationMap.get(entityCodeTreatment).Tax_Classification_Code__c;
                           }
                           else{
                               oppVAT.Tax_Classification_Code__c = '';
                           }
                       }
        }
    }
    
    //Check for modified VAT Treatment records
    public static void checkForUpdatedVATTreatments(List<Opportunity_VAT_Treatment__c > oppVATTreatmentList, Map<Id,Opportunity_VAT_Treatment__c> oldOppVATTreatmentMap){
        Set<Id> oppIdSet = new Set<Id>(); 
        if(Trigger.isInsert || Trigger.isUpdate){
            for(Opportunity_VAT_Treatment__c oppVAT : oppVATTreatmentList){
                if(Trigger.isInsert
                   || (Trigger.isUpdate 
                       && (oppVAT.Tax_Classification_Code__c != oldOppVATTreatmentMap.get(oppVAT.Id).Tax_Classification_Code__c 
                           || oppVAT.Effective_Date__c != oldOppVATTreatmentMap.get(oppVAT.Id).Effective_Date__c))){
                           oppIdSet.add(oppVAT.Opportunity__c);
                }
            }
        } else if(Trigger.isDelete){
            for(Opportunity_VAT_Treatment__c oppVAT : oldOppVATTreatmentMap.Values()){
                oppIdSet.add(oppVAT.Opportunity__c);    
            }        
        }
        
        if(oppIdSet != null && oppIdSet.size() > 0){
            updateTaxClassificationOnContracts(oppIdSet);
        }
     }
     
    //Update related contracts with latest VAT Tax Classification Code
    @future
    public static void updateTaxClassificationOnContracts(Set<Id> opportunitySet){
        List<Contract__c> contractToUpdateList = new List<Contract__c>();
        Map<Id, Opportunity__c> opportunityMap = new Map<Id, Opportunity__c>();
        
        for(Opportunity__c opp : [SELECT Id,
                                        (SELECT Id, Tax_Classification_Code__c FROM Opportunity_VAT_Treatments__r ORDER BY Effective_Date__c DESC, CreatedDate DESC LIMIT 1), 
                                        (SELECT Id, ERP_TAX_Classification_Code__c, End_Date__c FROM Contract__r WHERE ERP_Contract_Type__c = 'Engagement') 
                                    FROM Opportunity__C 
                                   WHERE Id in :opportunitySet]){
            if(opp.Contract__r != null && opp.Contract__r.size() > 0){             
                for(Contract__c oppContract : opp.Contract__r){
                    if(oppContract.End_Date__c == null){
                        Contract__c con = new Contract__c(Id = oppContract.Id);
                        if(opp.Opportunity_VAT_Treatments__r != null && opp.Opportunity_VAT_Treatments__r.size() > 0){
                           con.ERP_TAX_Classification_Code__c = opp.Opportunity_VAT_Treatments__r[0].Tax_Classification_Code__c;
                        } else {
                            con.ERP_TAX_Classification_Code__c = '';
                        }
                        contractToUpdateList.add(con);
                    }
                }                   
            }
        }
        
        if(contractToUpdateList != null && contractToUpdateList.size() > 0){
            update contractToUpdateList;
        }
    }
}