force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>This is an HL Contract object. Stores information from Engagement or Opportunity and integrates with Oracle Contract object.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to create a bill to</description>
    <inlineHelpText>Please select a company to send a bill to. For an ICO contract, this is the project owning legal entity.</inlineHelpText>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract (Account)</relationshipLabel>
    <relationshipName>Bill_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Auto_Number_Settings__c/HL_Auto_Number_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the sequence of Client Numbers assigned to Companies.</description>
    <label>HL Auto Number Setting</label>
</CustomObject>

force-app/main/default/objects/HL_Auto_Number_Settings__c/fields/Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Auto_Number__c</fullName>
    <label>Auto Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HL_ContractHandlerTest.cls
@isTest
public class HL_ContractHandlerTest {

    @isTest
    static void updateAccountClientNumberTest(){
        
        HL_Auto_Number_Settings__c autoNumber = new HL_Auto_Number_Settings__c();
        autoNumber.Name = 'Account';
        autoNumber.Auto_Number__c = 100;
        insert autoNumber;
        
        Account account = new Account();
        account.Name = 'Account Test 1';
        insert account;
        
        Contract__c contract = new Contract__c();
        contract.Name = 'Contract Test 1';
        contract.Bill_To__c = account.Id;
        insert contract;
    }
}