force-app/main/default/objects/Account/fields/CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Related Companies</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Operating_Company.recordType-meta.xml
<RecordType>
    <fullName>Operating_Company</fullName>
    <active>true</active>
    <description>Companies that make goods or provide services (ex. Information Technology,  Consumer Products, Healthcare, Law firm, Accounting, etc.)  These are often Portfolio Companies of Private Equity firms or Hedge Funds, prospective, engaged and/or former clients.</description>
    <label>Operating Company</label>
</RecordType>

force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASC - Augmenting Sector Coverage</fullName>
            </value>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>CM - Capital Markets</fullName>
            </value>
            <value>
                <fullName>CORP - Corporate</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>FS - Financial Sponsors</fullName>
            </value>
            <value>
                <fullName>FT - Financial Technology</fullName>
            </value>
            <value>
                <fullName>GEN - General</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IFA - Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>M&amp;A - Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>NRG - Energy</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>PFG - Private Funds Group</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TAG - Tangible Asset Group</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Coverage_Team__c/Coverage_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track officer coverage on accounts.</description>
    <label>Coverage Team</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Coverage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Team__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <formula>TEXT( Officer__r.Industry_Group__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Officer__c.field-meta.xml
<CustomField>
    <fullName>Officer__c</fullName>
    <label>Officer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Industry_Group__c</field>
            <operation>equals</operation>
            <value>FS - Financial Sponsors</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Coverage Team Member</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Standard Coverage Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/recordTypes/FS_Coverage_Team_Member.recordType-meta.xml
<RecordType>
    <fullName>FS_Coverage_Team_Member</fullName>
    <active>true</active>
    <label>FS Coverage Team Member</label>
</RecordType>

force-app/main/default/objects/Coverage_Team__c/recordTypes/Standard_Coverage_Team_Member.recordType-meta.xml
<RecordType>
    <fullName>Standard_Coverage_Team_Member</fullName>
    <active>true</active>
    <label>Standard Coverage Team Member</label>
</RecordType>

force-app/main/default/classes/Test_HL_CoverageTeamController.cls
@isTest
private class Test_HL_CoverageTeamController {
    @testSetup 
    private static void SetupCoverageTeamData(){        
        List<CapIQ_Company__c> capIQCompanyList = (List<CapIQ_Company__c>)HL_TestFactory.CreateSObjectList('CapIQ_Company__c', false, 1);
        insert capIQCompanyList;
        
        RecordType accountOperatingCompanyRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Operating_Company'];
        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, 3);
        accountList[0].Name = 'CapIQ Assigned Standard';
        accountList[0].CapIQ_Company__c = capIQCompanyList[0].Id;
        accountList[0].RecordTypeId = accountOperatingCompanyRecordType.Id;
        accountList[1].Name = 'CapIQ Assigned FS';
        accountList[1].CapIQ_Company__c = capIQCompanyList[0].Id;
        accountList[1].RecordTypeId = accountOperatingCompanyRecordType.Id;
        accountList[2].Name = 'CapIQ Unassigned';
        accountList[2].RecordTypeId = accountOperatingCompanyRecordType.Id;
        insert accountList;
        
        Contact internalContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee, false);
        internalContactRecord.Industry_Group__c = 'FS - Financial Sponsors';
        insert internalContactRecord;        
        
        RecordType coverageTeamStandardRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Coverage_Team__c' AND DeveloperName = 'Standard_Coverage_Team_Member'];
        RecordType coverageTeamFSRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Coverage_Team__c' AND DeveloperName = 'FS_Coverage_Team_Member'];
        List<Coverage_Team__c> coverageTeamList = (List<Coverage_Team__c>)HL_TestFactory.CreateSObjectList('Coverage_Team__c', false, 3);
        coverageTeamList[0].RecordTypeId = coverageTeamStandardRecordType.Id;
        coverageTeamList[0].Company__c = accountList[0].Id;        
        coverageTeamList[0].Officer__c = internalContactRecord.Id;
        coverageTeamList[1].RecordTypeId = coverageTeamFSRecordType.Id;
        coverageTeamList[1].Company__c = accountList[1].Id;
        coverageTeamList[1].Officer__c = internalContactRecord.Id;     
        coverageTeamList[2].RecordTypeId = coverageTeamFSRecordType.Id;
        coverageTeamList[2].Company__c = accountList[2].Id;
        coverageTeamList[2].Officer__c = internalContactRecord.Id;
        insert coverageTeamList;
    }
    
    @isTest
    private static void TestCoverageTeamControllerWithStandardCoverageTeam() {
        Coverage_Team__c coverageTeamRecord = [SELECT Id FROM Coverage_Team__c WHERE Company__r.Name = 'CapIQ Assigned Standard' LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(coverageTeamRecord);        
        ApexPages.currentPage().getParameters().put('Id', coverageTeamRecord.Id);
        HL_CoverageTeamController coverageTeamController = new HL_CoverageTeamController(sc);
        PageReference checkRecordTypeResult = coverageTeamController.CheckRecordType();

        Test.stopTest();
        
        System.assert(checkRecordTypeResult != null);
    }
    
    @isTest
    private static void TestCoverageTeamControllerWithFSCoverageTeam(){
        Coverage_Team__c coverageTeamRecord = [SELECT Id FROM Coverage_Team__c WHERE Company__r.Name = 'CapIQ Assigned FS' LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(coverageTeamRecord);        
        ApexPages.currentPage().getParameters().put('Id', coverageTeamRecord.Id);
        HL_CoverageTeamController coverageTeamController = new HL_CoverageTeamController(sc);
        PageReference checkRecordTypeResult = coverageTeamController.CheckRecordType();

        Test.stopTest(); 
        
        System.assert(checkRecordTypeResult == null);
    }
    
    @isTest
    private static void TestCoverageTeamControllerWithCapIQUnassigned() {
        Coverage_Team__c coverageTeamRecord = [SELECT Id FROM Coverage_Team__c WHERE Company__r.Name = 'CapIQ Unassigned' LIMIT 1];
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(coverageTeamRecord);        
        ApexPages.currentPage().getParameters().put('Id', coverageTeamRecord.Id);
        HL_CoverageTeamController coverageTeamController = new HL_CoverageTeamController(sc);
        PageReference checkRecordTypeResult = coverageTeamController.CheckRecordType();

        Test.stopTest();
        
        System.assert(checkRecordTypeResult == null);
    }
}