force-app/main/default/objects/Account/fields/CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Related Companies</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CapIQ_Company__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CapIQ_Company__c/fields/HL_Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry_Group__c</fullName>
    <label>HL Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food  &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CapIQ_Company__c/fields/HL_Sector__c.field-meta.xml
<CustomField>
    <fullName>HL_Sector__c</fullName>
    <label>HL Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HL_Industry_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Academic Research &amp; IP</fullName>
            </value>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Airlines/Air Cargo</fullName>
            </value>
            <value>
                <fullName>Ambulatory Surgical Centers</fullName>
            </value>
            <value>
                <fullName>Analytics &amp; Big Data</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automotive &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Autonomous Systems</fullName>
            </value>
            <value>
                <fullName>Behavioral &amp; Labs</fullName>
            </value>
            <value>
                <fullName>Broker Dealers</fullName>
            </value>
            <value>
                <fullName>Building Products</fullName>
            </value>
            <value>
                <fullName>Business Management Software</fullName>
            </value>
            <value>
                <fullName>Capital Goods</fullName>
            </value>
            <value>
                <fullName>CBD/Cannabis</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Commercial Financial Co.</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Infrastructure Components</fullName>
            </value>
            <value>
                <fullName>Communications Solutions</fullName>
            </value>
            <value>
                <fullName>Company &amp; Market Intelligence</fullName>
            </value>
            <value>
                <fullName>Consumer/Non-Mortgate Finance Co.</fullName>
            </value>
            <value>
                <fullName>Consumer Products</fullName>
            </value>
            <value>
                <fullName>Customer Information Management</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Data &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>Data Centers</fullName>
            </value>
            <value>
                <fullName>Dealership &amp; Rental Services</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Other Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track portfolio companies related to a fund.</description>
    <label>Investment</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Investment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/HL_Portfolio_Co_HL_Industry__c.field-meta.xml
<CustomField>
    <fullName>HL_Portfolio_Co_HL_Industry__c</fullName>
    <label>Portfolio Co. HL Industry</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Portfolio_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Portfolio Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Sponsor</relationshipLabel>
    <relationshipName>Investment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Sponsor_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Sponsor Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Company</relationshipLabel>
    <relationshipName>Investment_Sponsor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_InvestmentFieldsUpdateBatch.cls
/*
* Name: Test_HL_InvestmentFieldsUpdateBatch 
* Created Date: 2/22/2020
* Description: Test class for HL_InvestmentFieldsUpdateBatch class
*/ 
@isTest
private class Test_HL_InvestmentFieldsUpdateBatch {
    static final string SponsorAccountName = 'Investor';
    static final string PortfolioAccountName = 'Investment';
    static final integer InvestmentSize = 10;
    
    @testSetup
    private static void CreateData(){
        //Create the Base Account with Associate CapIQ Records as our Test Accounts for Investors and Investments
        Account sponsorAccountRecord = (Account)HL_TestFactory.CreateSObject('Account', false);
        sponsorAccountRecord.Name = SponsorAccountName;
        insert sponsorAccountRecord;
        Account portfolioAccountRecord = (Account)HL_TestFactory.CreateSObject('Account', false);
        portfolioAccountRecord.Name = PortfolioAccountName;
        insert portfolioAccountRecord;
        
        CapIQ_Company__c sponsorAccountCapIQRecord = (CapIQ_Company__c)HL_TestFactory.CreateSObject('CapIQ_Company__c', false);
        sponsorAccountCapIQRecord.Company_ID__c = '1';
        sponsorAccountCapIQRecord.HL_Industry_Group__c = 'BUS - Business Services';
        sponsorAccountCapIQRecord.HL_Sector__c = 'Other Services';
        insert sponsorAccountCapIQRecord;

        CapIQ_Company__c portfolioAccountCapIQRecord = (CapIQ_Company__c)HL_TestFactory.CreateSObject('CapIQ_Company__c', false);
        portfolioAccountCapIQRecord.Company_ID__c = '2';
        portfolioAccountCapIQRecord.HL_Industry_Group__c = 'BUS - Business Services';
        portfolioAccountCapIQRecord.HL_Sector__c = 'Other Services';
        insert portfolioAccountCapIQRecord;
        
        sponsorAccountRecord.CapIQ_Company__c = sponsorAccountCapIQRecord.Id;
        portfolioAccountRecord.CapIQ_Company__c = portfolioAccountCapIQRecord.Id;
        
        update sponsorAccountRecord;
        update portfolioAccountRecord;
        
        List<Investment__c> lstInvestment= new List<Investment__c>();
        for(Integer i=0 ;i <200;i++)
        {
            Investment__c investmentRecord = (Investment__c)HL_TestFactory.CreateSObject('Investment__c',false);
            investmentRecord.Portfolio_CapIQ_Company__c = portfolioAccountCapIQRecord.Id;
            investmentRecord.Sponsor_CapIQ_Company__c = sponsorAccountCapIQRecord.Id;
            lstInvestment.add(investmentRecord);
        }
        
        insert lstInvestment;
    }
        
    @isTest
    private static void testRunBatch(){
        
        Test.startTest();

            HL_InvestmentFieldsUpdateBatch batchs=new HL_InvestmentFieldsUpdateBatch();
            database.executeBatch(batchs);
            
        Test.stopTest();
        
        List<Investment__c> inv = [SELECT id, HL_Portfolio_Co_HL_Industry__c FROM investment__c WHERE HL_Portfolio_Co_HL_Industry__c = 'BUS - Business Services'];     
        system.assertNotEquals(inv.size(),0);
    }
}