force-app/main/default/objects/Account/fields/CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Related Companies</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_SLX_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_SLX_ID__c</fullName>
    <externalId>true</externalId>
    <label>Legacy SLX ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CapIQ_Company__c/CapIQ_Company__c.object-meta.xml
<CustomObject>
    <label>CapIQ Company</label>
    <nameField>
        <label>CapIQ Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapIQ Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CapIQ_Company__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CapIQ_Company__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage_Contact__c/Coverage_Contact__c.object-meta.xml
<CustomObject>
    <label>Coverage Contact</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Coverage Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Contact__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Coverage_Contact__r.AccountId</formula>
    <label>Coverage Contact Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage_Contact__c/fields/Coverage_Contact__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coverage Contacts</relationshipLabel>
    <relationshipName>Coverage_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Contact__c/fields/Coverage_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Coverage Team Member</label>
    <referenceTo>Coverage_Team__c</referenceTo>
    <relationshipLabel>Coverage Contacts</relationshipLabel>
    <relationshipName>Coverage_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/Coverage_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track officer coverage on accounts.</description>
    <label>Coverage Team</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Coverage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Team__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Officer__c.field-meta.xml
<CustomField>
    <fullName>Officer__c</fullName>
    <label>Officer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Industry_Group__c</field>
            <operation>equals</operation>
            <value>FS - Financial Sponsors</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Coverage Team Member</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Standard Coverage Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Industry__c/Industry__c.object-meta.xml
<CustomObject>
    <description>Store the Industries</description>
    <label>Industry</label>
    <nameField>
        <label>Industry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>For future enhancements</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Industry__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Industry__c/fields/FSC__c.field-meta.xml
<CustomField>
    <fullName>FSC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FSC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track portfolio companies related to a fund.</description>
    <label>Investment</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Investment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/HL_Industry_LK__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry_LK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>HL&apos;s perspective on the selected Investment&apos;s Industry</inlineHelpText>
    <label>HL Industry LK</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only FSC Industries are allowed.</errorMessage>
        <filterItems>
            <field>Industry__c.FSC__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>Investment</relationshipLabel>
    <relationshipName>Investment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/HL_Industry_Sector__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry_Sector__c</fullName>
    <description>it pulls the industry name because name = sector in this case. the help text is worded that way to minimize confusion - ayu</description>
    <formula>(IF(FIND(&quot; - &quot;, HL_Portfolio_Co_HL_Industry__c) &gt; 0, LEFT(HL_Portfolio_Co_HL_Industry__c, FIND( &quot; - &quot;, HL_Portfolio_Co_HL_Industry__c) - 1), HL_Portfolio_Co_HL_Industry__c)) + &quot; - &quot; + HL_Portfolio_Co_HL_Sector__c</formula>
    <inlineHelpText>Combines Industry reporting group and the selected HL Industry&apos;s sector</inlineHelpText>
    <label>HL Industry Sector</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>Portfolio_CapIQ_Company__r.Industry__c</formula>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Portfolio_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Portfolio Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Sponsor</relationshipLabel>
    <relationshipName>Investment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Sponsor_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Sponsor Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Company</relationshipLabel>
    <relationshipName>Investment_Sponsor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template__c/Offsite_Template__c.object-meta.xml
<CustomObject>
    <label>Offsite Template</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Offsite Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offsite Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template__c/fields/Coverage_Team__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Coverage Team</label>
    <referenceTo>Coverage_Team__c</referenceTo>
    <relationshipLabel>Offsite Templates</relationshipLabel>
    <relationshipName>Offsite_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Offsite Templates</relationshipLabel>
    <relationshipName>Offsite_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Coverage_Contact__c/Offsite_Template_Coverage_Contact__c.object-meta.xml
<CustomObject>
    <description>Offsite Template Coverage Contacts</description>
    <label>Offsite Template Coverage Contact</label>
    <nameField>
        <displayFormat>OTCC-{00000000}</displayFormat>
        <label>Offsite Template Coverage Contact  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offsite Template Coverage Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template_Coverage_Contact__c/fields/Coverage_Contact__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Coverage Contact</description>
    <label>Coverage Contact</label>
    <referenceTo>Coverage_Contact__c</referenceTo>
    <relationshipLabel>Offsite Template Coverage Contacts</relationshipLabel>
    <relationshipName>Offsite_Template_Coverage_Contact_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Coverage_Contact__c/fields/Offsite_Template__c.field-meta.xml
<CustomField>
    <fullName>Offsite_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Offsite Template Record</description>
    <label>Offsite Template</label>
    <referenceTo>Offsite_Template__c</referenceTo>
    <relationshipLabel>Offsite Template Coverage Contacts</relationshipLabel>
    <relationshipName>Offsite_Template_Coverage_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Industry__c/Offsite_Template_Industry__c.object-meta.xml
<CustomObject>
    <label>Offsite Template Industry</label>
    <nameField>
        <displayFormat>OT.Industry-{00000}</displayFormat>
        <label>Offsite Template Industry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offsite Template Industries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template_Industry__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry</label>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>Offsite Template Industries</relationshipLabel>
    <relationshipName>Offsite_Template_Industries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Industry__c/fields/Offsite_Template__c.field-meta.xml
<CustomField>
    <fullName>Offsite_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offsite Template</label>
    <referenceTo>Offsite_Template__c</referenceTo>
    <relationshipLabel>Offsite Template Industries</relationshipLabel>
    <relationshipName>Offsite_Template_Industries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/Offsite_Template_Investment_Company__c.object-meta.xml
<CustomObject>
    <label>Offsite Template Investment Company</label>
    <nameField>
        <displayFormat>OT.Investment-{00000}</displayFormat>
        <label>Offsite Template Investment Company Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offsite Template Investment Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>FROM CAPIQ</description>
    <label>CAPIQ Industry</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Offsite_Template__c.field-meta.xml
<CustomField>
    <fullName>Offsite_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offsite Template</label>
    <referenceTo>Offsite_Template__c</referenceTo>
    <relationshipLabel>Offsite Template Investment Companies</relationshipLabel>
    <relationshipName>Offsite_Template_Investment_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_OffsiteTemplate.cls
@isTest
private class Test_HL_OffsiteTemplate {
    @testSetup
    private static void SetupData(){
        final integer offsiteTemplateRecords = 1;
        final integer relatedRecords = 5;
        List<CapIQ_Company__c> capIQCompanyList = (List<CapIQ_Company__c>)HL_TestFactory.CreateSObjectList('CapIQ_Company__c', false, relatedRecords);
        for(Integer i=0; i<relatedRecords; i++)
            capIQCompanyList[i].Company_ID__c = String.valueOf(i);
        insert capIQCompanyList;
        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, relatedRecords);
        for(Integer i=0; i < relatedRecords; i++)
            accountList[i].CapIQ_Company__c = capIQCompanyList[i].Id;
        insert accountList;
        List<Contact> externalContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, relatedRecords);
        insert externalContactList;
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee, false);
        insert contactRecord;
        List<Industry__c> industryList = (List<Industry__c>)HL_TestFactory.CreateSObjectList('Industry__c', false, relatedRecords);
        for(Integer i =0; i < relatedRecords; i++)
        {
            industryList[i].Active__c = true;
            industryList[i].FSC__c = true;
        }
        insert industryList;
        List<Investment__c> investmentList = (List<Investment__c>)HL_TestFactory.CreateSObjectList('Investment__c', false, relatedRecords);
        for(Integer i = 0; i < relatedRecords; i++){
            investmentList[i].Portfolio_CapIQ_Company__c= capIQCompanyList[1].Id;
            investmentList[i].Sponsor_CapIQ_Company__c = capIQCompanyList[0].Id;
            investmentList[i].HL_Industry_LK__c = industryList[0].Id;
            investmentList[i].HL_Industry_LK__r = industryList[0];
        }
        insert investmentList;
        investmentList = [SELECT HL_Industry_Sector__c FROM Investment__c WHERE Id IN: investmentList];
        Coverage_Team__c coverageTeamRecord = (Coverage_Team__c)HL_TestFactory.CreateSObject('Coverage_Team__c', false);
        coverageTeamRecord.Company__c = accountList[0].Id;
        coverageTeamRecord.Officer__c = contactRecord.Id;
        insert coverageTeamRecord;
        List<Coverage_Contact__c> coverageContactList = (List<Coverage_Contact__c>)HL_TestFactory.CreateSObjectList('Coverage_Contact__c', false, relatedRecords);
        for(Integer i = 0; i < relatedRecords; i++){
            coverageContactList[i].Coverage_Contact__c = externalContactList[i].Id;
            coverageContactList[i].Coverage_Team_Member__c= coverageTeamRecord.Id;
        }
        insert coverageContactList;
        List<Offsite_Template__c> offsiteTemplateList = (List<Offsite_Template__c>)HL_TestFactory.CreateSObjectList('Offsite_Template__c', false, offsiteTemplateRecords);
        for(Integer i = 0; i < offsiteTemplateRecords; i++){
            offsiteTemplateList[i].Coverage_Team__c = coverageTeamRecord.Id;
            offsiteTemplateList[i].Sponsor__c = capIQCompanyList[0].Id;
            offsiteTemplateList[i].Year__c = String.valueOf(Date.Today().year());
        }
        insert offsiteTemplateList;
    }

    @isTest
    private static void TestCreateFunctionality() {
        List<Offsite_Template__c> offsiteTemplateList = [SELECT Coverage_Team__c, Legacy_SLX_ID__c, Coverage_Team__r.Officer__c, Coverage_Team__r.Officer__r.Name,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_From__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_To__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Most_Recent_Fund_Size_MM__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Name,
                                                                Coverage_Team__r.Company__r.BillingCity,
                                                                Coverage_Team__r.Company__r.BillingState,
                                                                Coverage_Team__r.Company__r.BillingCountry,
                                                         		Year__c
                                                         FROM Offsite_Template__c];
       
        Test.startTest();

        HL_OffsiteTemplate.PopulateSnapshotData(offsiteTemplateList);

        Test.stopTest();

        //Verify that the offsite template industry records are equivalent to the FS, Active Industry records
        System.assertEquals([SELECT Id FROM Offsite_Template_Industry__c WHERE Offsite_Template__c =: offsiteTemplateList[0].Id].size(), [SELECT Id FROM Industry__c WHERE FSC__c = true AND Active__c = true].size());
        //Verify that the offsite template investment company records are equivalent to our related records size
        System.assertEquals(5, [SELECT Id FROM Offsite_Template_Investment_Company__c].size());
    }

    @isTest
    private static void TestCreateCloneFunctionality() {
        List<Offsite_Template__c> offsiteTemplateList = [SELECT Coverage_Team__c,
                                                                Coverage_Team__r.Officer__c,
                                                                Coverage_Team__r.Officer__r.Name,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_From__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_To__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Most_Recent_Fund_Size_MM__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Name,
                                                                Coverage_Team__r.Company__r.BillingCity,
                                                                Coverage_Team__r.Company__r.BillingState,
                                                                Coverage_Team__r.Company__r.BillingCountry,
                                                                Legacy_SLX_ID__c,
                                                                Sponsor__c
                                                         FROM Offsite_Template__c];
		Integer month = Date.Today().month();
        Integer year = Date.Today().year() + (month > 3 ? 1 : 0);
        
        for(Offsite_Template__c offsiteTemplateRecord : offsiteTemplateList)
            offsiteTemplateRecord.Year__c = String.valueOf(year - 1);
		update offsiteTemplateList;
        
        Test.startTest();

        Offsite_Template__c offsiteTemplateRecord = offsiteTemplateList[0].clone();
        insert offsiteTemplateRecord;

        Test.stopTest();

        //Verify the Industry Record Count is Equivalent to the Original Offsite Industry Record Count
        System.assertEquals([SELECT Id FROM Offsite_Template_Industry__c WHERE Offsite_Template__c =: offsiteTemplateList[0].Id].size(), [SELECT Id FROM Offsite_Template_Industry__c WHERE Offsite_Template__c !=: offsiteTemplateList[0].Id].size());
    }

    @isTest
    private static void TestInsertedInvestmentRecordsFunctionality() {
        List<Offsite_Template__c> offsiteTemplateList = [SELECT Coverage_Team__c,
                                                                Coverage_Team__r.Officer__c,
                                                                Coverage_Team__r.Officer__r.Name,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_From__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_To__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Most_Recent_Fund_Size_MM__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Name,
                                                                Coverage_Team__r.Company__r.BillingCity,
                                                                Coverage_Team__r.Company__r.BillingState,
                                                                Coverage_Team__r.Company__r.BillingCountry,
                                                                Legacy_SLX_ID__c,
                                                                Sponsor__c
                                                         FROM Offsite_Template__c];
        Map<Id, Investment__c> investmentMap = new Map<Id, Investment__c>();
        Investment__c investmentRecord = (Investment__c)HL_TestFactory.CreateSObject('Investment__c', false);
        investmentRecord.Sponsor_CapIQ_Company__c = offsiteTemplateList[0].Sponsor__c;
        investmentMap.put(investmentRecord.Id, investmentRecord);

        Test.startTest();

        HL_OffsiteTemplate.HandleInsertedInvestmentRecords(investmentMap);

        Test.stopTest();
        //Verify the new investment has been added
        System.assertEquals(5 + 1, [SELECT Id FROM Offsite_Template_Investment_Company__c].size());
    }

    @isTest
    private static void TestInsertedContactRecordsFunctionality() {
        List<Offsite_Template__c> offsiteTemplateList = [SELECT Coverage_Team__c, Legacy_SLX_ID__c, Coverage_Team__r.Officer__c, Coverage_Team__r.Officer__r.Name,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_From__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Equity_Investment_To__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Most_Recent_Fund_Size_MM__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__c,
                                                                Coverage_Team__r.Company__r.CapIQ_Company__r.Name,
                                                                Coverage_Team__r.Company__r.BillingCity,
                                                                Coverage_Team__r.Company__r.BillingState,
                                                                Coverage_Team__r.Company__r.BillingCountry
                                                         FROM Offsite_Template__c];
        Map<Id, Coverage_Contact__c> coverageContactMap = new Map<Id, Coverage_Contact__c>();
        Coverage_Contact__c coverageContactRecord = (Coverage_Contact__c)HL_TestFactory.CreateSObject('Coverage_Contact__c', false);
        coverageContactRecord.Coverage_Team_Member__c = offsiteTemplateList[0].Coverage_Team__c;
        coverageContactMap.put(coverageContactRecord.Id, coverageContactRecord);

        Test.startTest();

        HL_OffsiteTemplate.HandleInsertedContactRecords(coverageContactMap);

        Test.stopTest();

        //Verify the new coverage Contact has been added
        System.assertEquals(5 + 1, [SELECT Id FROM Offsite_Template_Coverage_Contact__c].size());
    }
}