force-app/main/default/objects/Account/fields/CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Related Companies</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Client Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASC - Augmenting Sector Coverage</fullName>
            </value>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>CM - Capital Markets</fullName>
            </value>
            <value>
                <fullName>CORP - Corporate</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>FS - Financial Sponsors</fullName>
            </value>
            <value>
                <fullName>FT - Financial Technology</fullName>
            </value>
            <value>
                <fullName>GEN - General</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IFA - Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>M&amp;A - Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>NRG - Energy</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>PFG - Private Funds Group</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TAG - Tangible Asset Group</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/Coverage_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track officer coverage on accounts.</description>
    <label>Coverage Team</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Coverage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Team__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Coverage_Level__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Level__c</fullName>
    <label>Coverage Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sponsor Officer</fullName>
            </value>
            <value>
                <fullName>Support Sponsor Officer</fullName>
            </value>
            <value>
                <fullName>Calling Officer</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADG</fullName>
            </value>
            <value>
                <fullName>Aerospace Defense and Government</fullName>
            </value>
            <value>
                <fullName>Alternative Investor</fullName>
            </value>
            <value>
                <fullName>Asia Coverage</fullName>
            </value>
            <value>
                <fullName>Building Products</fullName>
            </value>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Business Services - 2015</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>CAPE</fullName>
            </value>
            <value>
                <fullName>Chemical Initiative</fullName>
            </value>
            <value>
                <fullName>Collateralized Loan Obligation</fullName>
            </value>
            <value>
                <fullName>Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Credit Fund</fullName>
            </value>
            <value>
                <fullName>CVAS</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>EU Capital Markets</fullName>
            </value>
            <value>
                <fullName>EU FR</fullName>
            </value>
            <value>
                <fullName>EU IFA</fullName>
            </value>
            <value>
                <fullName>Family Office</fullName>
            </value>
            <value>
                <fullName>FIG</fullName>
            </value>
            <value>
                <fullName>Fintech</fullName>
            </value>
            <value>
                <fullName>Firm-Wide</fullName>
            </value>
            <value>
                <fullName>FVA Coverage</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>HC</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Healthcare - 2015</fullName>
            </value>
            <value>
                <fullName>Hedge Fund</fullName>
            </value>
            <value>
                <fullName>High Yield</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <formula>TEXT( Officer__r.Industry_Group__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Officer__c.field-meta.xml
<CustomField>
    <fullName>Officer__c</fullName>
    <label>Officer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Industry_Group__c</field>
            <operation>equals</operation>
            <value>FS - Financial Sponsors</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Coverage Team Member</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Standard Coverage Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Filed S1 and/or Intending to go Public</fullName>
            </value>
            <value>
                <fullName>Former Client</fullName>
            </value>
            <value>
                <fullName>Client Hold - Out of Tail</fullName>
            </value>
            <value>
                <fullName>Client Hold - Future Opportunity</fullName>
            </value>
            <value>
                <fullName>Not Worth Calling</fullName>
            </value>
            <value>
                <fullName>Keep in Touch</fullName>
            </value>
            <value>
                <fullName>Lead to Qualify</fullName>
            </value>
            <value>
                <fullName>Warm Lead</fullName>
            </value>
            <value>
                <fullName>Qualified Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/recordTypes/FS_Coverage_Team_Member.recordType-meta.xml
<RecordType>
    <fullName>FS_Coverage_Team_Member</fullName>
    <active>true</active>
    <label>FS Coverage Team Member</label>
</RecordType>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Custom object to track portfolio companies related to a fund.</description>
    <label>Investment</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Investment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Portfolio_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Portfolio Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Sponsor</relationshipLabel>
    <relationshipName>Investment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Sponsor_CapIQ_Company__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_CapIQ_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CapIQ Sponsor Company</label>
    <referenceTo>CapIQ_Company__c</referenceTo>
    <relationshipLabel>Investment Company</relationshipLabel>
    <relationshipName>Investment_Sponsor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Prior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_Company.cls
public with sharing class HL_Company {
    public static final string STANDARD_SELECT = 'SELECT Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Client_Number__c, Phone, Industry_Group__c ';

    @AuraEnabled
    public static Account GetById(Id acctId){
        //Modified as part of State/Country Picklist
        List<Account> a = [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, BillingCountryCode, BillingStateCode FROM Account WHERE Id=:acctId];
        return a.size() > 0 ? a[0] : new Account();
    }

    public static List<Coverage_Team__c> GetCoverageTeamAggregate(Id acctId){
        Account a = [SELECT Id, CapIQ_Company__c, Ultimate_Parent__c FROM Account WHERE Id =: acctId];
        Set<Id> sponsorAccts = new Set<Id>();

        if(a.CapIQ_Company__c <> null){
            for(List<Investment__c> iList : [SELECT Sponsor_CapIQ_Company__c FROM Investment__c WHERE Portfolio_CapIQ_Company__c =: a.CapIQ_Company__c AND Status__c = 'Current'])
            {
                for(Investment__c i : iList){
                    if(i.Sponsor_CapIQ_Company__c <> null)
                        sponsorAccts.Add(i.Sponsor_CapIQ_Company__c);
                }
            }
        }

        List<Coverage_Team__c> ct = [SELECT Officer__r.Name, Company__r.Name, RecordType.Name, Coverage_Level__c, Coverage_Type__c, Tier__c, Line_of_Business__c, Product_Specialty__c, Sector__c, Industry_Group__c, Company__r.BillingCity, Company__r.BillingState, Company__r.BillingCountry
                                     FROM Coverage_Team__c
                                     WHERE (Company__c =: a.Id
                                             OR Company__c =: a.Ultimate_Parent__c
                                             OR (Company__r.Ultimate_Parent__c <> null AND (Company__r.Ultimate_Parent__c =: a.Ultimate_Parent__c OR Company__r.Ultimate_Parent__c =: a.Id))
                                             OR Company__r.CapIQ_Company__c IN : sponsorAccts
                                           )
                                     AND RecordType.DeveloperName = 'FS_Coverage_Team_Member'
                                     AND Coverage_Team_Status__c = 'Active'
                                     AND Officer__r.Status__c = 'Active'
                                     ORDER BY Officer__r.Name, Company__r.Name];
        return ct;
    }
}