force-app/main/default/objects/Account/fields/CounterParty__c.field-meta.xml
<CustomField>
    <fullName>CounterParty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies if the account is list as an opportunity counterparty, engagement counterparty or both.</description>
    <inlineHelpText>If checked then this account is listed as a counterparty.</inlineHelpText>
    <label>CounterParty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Counterparty__c/Opportunity_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for prospective engagements.</description>
    <label>Opportunity Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Counterparty__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities Shown</relationshipLabel>
    <relationshipName>Opportunity_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Counterparties</relationshipLabel>
    <relationshipName>Opportunity_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty__c/fields/Opportunity_Counterparty_Comment__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Counterparty_Comment__c</fullName>
    <label>Opportunity Counterparty Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty_Comment__c/Opportunity_Counterparty_Comment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Counterparty Comment</label>
    <nameField>
        <displayFormat>OCC-{0000}</displayFormat>
        <label>Opportunity Counterparty Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Counterparty Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_HL_OpportunityCounterpartyHandler.cls
@isTest
private class Test_HL_OpportunityCounterpartyHandler {
	@isTest
    private static void TestOpportunityCounterpartyComment(){
        Account a = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a;
        Opportunity__c o = (Opportunity__c)HL_TestFactory.CreateSObject('Opportunity__c', false);
        insert o;
        Opportunity_Counterparty__c oc = (Opportunity_Counterparty__c)HL_TestFactory.CreateSObject('Opportunity_Counterparty__c', false);
        oc.Opportunity__c = o.Id;
		oc.Company__c = a.Id;

        Test.startTest();

        insert oc;
        oc.Opportunity_Counterparty_Comment__c = 'Test Comment';
        update oc;

        Test.stopTest();

        //Verify the Comment was Added
        System.assert([SELECT Id FROM Opportunity_Counterparty_Comment__c].size() > 0);

    }
    @isTest
    private static void TestOpportunityCounterpartyAccountIndicatorNew(){
        Account a = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a;
        Opportunity__c o = (Opportunity__c)HL_TestFactory.CreateSObject('Opportunity__c', false);
        insert o;
        Opportunity_Counterparty__c oc = (Opportunity_Counterparty__c)HL_TestFactory.CreateSObject('Opportunity_Counterparty__c', false);
        oc.Opportunity__c = o.Id;
        oc.Company__c = a.Id; 
        
        Test.startTest();

        insert oc;

        Test.stopTest();
        
       Account acct = [SELECT Counterparty__c FROM Account WHERE Id = :a.Id];
       System.assertEquals(true,acct.counterparty__c);
    }
    @isTest
    private static void TestOpportunityCounterpartyAccountIndicatorUpdate(){
        Account a = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a;
        Account a2 = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a2;
        Opportunity__c o = (Opportunity__c)HL_TestFactory.CreateSObject('Opportunity__c', false);
        insert o;
        Opportunity_Counterparty__c oc = (Opportunity_Counterparty__c)HL_TestFactory.CreateSObject('Opportunity_Counterparty__c', false);
        oc.Opportunity__c = o.Id;
        oc.Company__c = a.Id; 
        insert oc;
        
        Test.startTest();

        oc.Company__c = a2.Id;
        update oc;

        Test.stopTest();
        
       Account acct1 = [SELECT Counterparty__c FROM Account WHERE Id = :a.Id];
       Account acct2 = [SELECT Counterparty__c FROM Account WHERE Id = :a2.Id];
       System.assertEquals(false,acct1.Counterparty__c);
       System.assertEquals(true,acct2.Counterparty__c);
    }
    @isTest
    private static void TestOpportunityCounterpartyAccountIndicatorDelete(){
        Account a = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a;
        Opportunity__c o = (Opportunity__c)HL_TestFactory.CreateSObject('Opportunity__c', false);
        insert o;
        Opportunity_Counterparty__c oc = (Opportunity_Counterparty__c)HL_TestFactory.CreateSObject('Opportunity_Counterparty__c', false);
        oc.Opportunity__c = o.Id;
        oc.Company__c = a.Id; 
        insert oc;
        
        Test.startTest();

        delete oc;
        
        Test.stopTest();
        
       Account acct = [SELECT Counterparty__c FROM Account WHERE Id = :a.Id];
       System.assertEquals(false,acct.counterparty__c);
    }
}