force-app/main/default/objects/Account/fields/CounterParty__c.field-meta.xml
<CustomField>
    <fullName>CounterParty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies if the account is list as an opportunity counterparty, engagement counterparty or both.</description>
    <inlineHelpText>If checked then this account is listed as a counterparty.</inlineHelpText>
    <label>CounterParty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/Engagement_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements Shown</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Counterparties</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Engagement_Counterparty_Comment__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Counterparty_Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Comment__c/Engagement_Counterparty_Comment__c.object-meta.xml
<CustomObject>
    <label>Engagement Counterparty Comment</label>
    <nameField>
        <displayFormat>ECC-{0000}</displayFormat>
        <label>Engagement Counterparty Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Counterpart Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_HL_EngagementCounterpartyHandler.cls
@isTest
private class Test_HL_EngagementCounterpartyHandler {
    @isTest
    private static void TestCounterpartyCommentInsertAndUpdate(){
        //Setup Test Data
        Engagement__c e = HL_TestFactory.CreateEngagement(false);
        insert e;
        Engagement_Counterparty__c ec = (Engagement_Counterparty__c)HL_TestFactory.CreateSObject('Engagement_Counterparty__c', false);
        ec.Engagement__c = e.Id;
        
        Test.startTest();
        
        insert ec;
        ec.Engagement_Counterparty_Comment__c = 'Test Comment';
        update ec;
        
        Test.stopTest();
        
        //Verify the Comment was Added
        System.assert([SELECT Id FROM Engagement_Counterparty_Comment__c].size() > 0);
    }
    
    @isTest
    private static void TestCounterpartyAccountIndicatorNew(){
        //Setup Test Data
        Account a = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a;
        Engagement__c e = HL_TestFactory.CreateEngagement(false);
        insert e;
        Engagement_Counterparty__c ec = (Engagement_Counterparty__c)HL_TestFactory.CreateSObject('Engagement_Counterparty__c', false);
        ec.Engagement__c = e.Id;
        ec.Company__c = a.Id;
        
        Test.startTest();
        
        insert ec;
        
        Test.stopTest();
        
        //Verify the Comment was Added
        Account acct = [SELECT Counterparty__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(true,acct.counterparty__c);
    }
    @isTest
    private static void TestEngagementCounterpartyAccountIndicatorUpdate(){
        Account a = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a;
        Account a2 = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a2;
        Engagement__c e = HL_TestFactory.CreateEngagement(false);
        insert e;
        Engagement_Counterparty__c ec = (Engagement_Counterparty__c)HL_TestFactory.CreateSObject('Engagement_Counterparty__c', false);
        ec.Engagement__c = e.Id;
        ec.Company__c = a.Id; 
        insert ec;
        
        Test.startTest();
        
        ec.Company__c = a2.Id;
        update ec;
        
        Test.stopTest();
        
        Account acct1 = [SELECT Counterparty__c FROM Account WHERE Id = :a.Id];
        Account acct2 = [SELECT Counterparty__c FROM Account WHERE Id = :a2.Id];
        System.assertEquals(false,acct1.Counterparty__c);
        System.assertEquals(true,acct2.Counterparty__c);
    }
    @isTest
    private static void TestEngagementCounterpartyAccountIndicatorDelete(){
        Account a = (Account)HL_TestFactory.CreateSObject('Account', false);
        insert a;
        Engagement__c e = HL_TestFactory.CreateEngagement(false);
        insert e;
        Engagement_Counterparty__c ec = (Engagement_Counterparty__c)HL_TestFactory.CreateSObject('Engagement_Counterparty__c', false);
        ec.Engagement__c = e.Id;
        ec.Company__c = a.Id; 
        insert ec;
        
        Test.startTest();
        
        delete ec;
        
        Test.stopTest();
        
        Account acct = [SELECT Counterparty__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(false,acct.counterparty__c);
    }
}