force-app/main/default/objects/Account/fields/CounterParty__c.field-meta.xml
<CustomField>
    <fullName>CounterParty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies if the account is list as an opportunity counterparty, engagement counterparty or both.</description>
    <inlineHelpText>If checked then this account is listed as a counterparty.</inlineHelpText>
    <label>CounterParty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_FS_Coverage_Officer__c.field-meta.xml
<CustomField>
    <fullName>Primary_FS_Coverage_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary FS Coverage Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary FS Coverage Officer)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coverage_Officer__c/Coverage_Officer__c.object-meta.xml
<CustomObject>
    <label>Coverage Officer</label>
    <nameField>
        <displayFormat>CIC-{00000}</displayFormat>
        <label>Coverage Officer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Officer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Officer__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Coverage_Contact__r.AccountId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage Officer Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/Coverage_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track officer coverage on accounts.</description>
    <label>Coverage Team</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Coverage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Team__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT( Officer__r.Line_of_Business__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Officer LOB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/recordTypes/FS_Coverage_Team_Member.recordType-meta.xml
<RecordType>
    <fullName>FS_Coverage_Team_Member</fullName>
    <active>true</active>
    <label>FS Coverage Team Member</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/Engagement_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements Shown</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Coverage_Officer__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage Officer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>HL Employees only.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Counterparties</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Counterparties</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Engagement_Counterparty_Comment__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Counterparty_Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <formula>Engagement__r.PIPELINE_Line_of_Business__c</formula>
    <label>Line Of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Capital Provider</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Comment__c/Engagement_Counterparty_Comment__c.object-meta.xml
<CustomObject>
    <label>Engagement Counterparty Comment</label>
    <nameField>
        <displayFormat>ECC-{0000}</displayFormat>
        <label>Engagement Counterparty Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Counterpart Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty_Comment__c/fields/Comment_Type__c.field-meta.xml
<CustomField>
    <fullName>Comment_Type__c</fullName>
    <inlineHelpText>Administrative - For LOB administrators
Internal - Internal reporting
External - Can be shared with clients on reports</inlineHelpText>
    <label>Comment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
                <default>true</default>
                <label>Internal</label>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Comment__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Comment__c/fields/Related_Engagement_Counterparty__c.field-meta.xml
<CustomField>
    <fullName>Related_Engagement_Counterparty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Engagement Counterparty</label>
    <referenceTo>Engagement_Counterparty__c</referenceTo>
    <relationshipLabel>Engagement Counterparty Comments</relationshipLabel>
    <relationshipName>Engagement_Counterparty_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/Engagement_Counterparty_Contact__c.object-meta.xml
<CustomObject>
    <description>Custom object to track contacts from engagement counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty Contact</label>
    <nameField>
        <displayFormat>ECC-{000000}</displayFormat>
        <label>Counterparty Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Counterparty Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/fields/Counterparty__c.field-meta.xml
<CustomField>
    <fullName>Counterparty__c</fullName>
    <label>Counterparty</label>
    <referenceTo>Engagement_Counterparty__c</referenceTo>
    <relationshipLabel>Engagement Counterparty Contacts</relationshipLabel>
    <relationshipName>Engagement_Counterparty_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <formula>Counterparty__r.Engagement__c</formula>
    <label>Engagement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/Engagement_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that are staffed on an engaged deal/project.</description>
    <label>Engagement Internal Team</label>
    <nameField>
        <displayFormat>EIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty__c/Opportunity_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for prospective engagements.</description>
    <label>Opportunity Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Counterparty__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities Shown</relationshipLabel>
    <relationshipName>Opportunity_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty__c/fields/Coverage_Officer__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage Officer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities as Coverage Officer</relationshipLabel>
    <relationshipName>Opportunity_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Capital Provider</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty_Comment__c/Opportunity_Counterparty_Comment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Counterparty Comment</label>
    <nameField>
        <displayFormat>OCC-{0000}</displayFormat>
        <label>Opportunity Counterparty Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Counterparty Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Counterparty_Comment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Counterparty_Contact__c/Opportunity_Counterparty_Contact__c.object-meta.xml
<CustomObject>
    <description>Custom object to track contacts from opportunity counterparties for a prospective engagement.</description>
    <label>Opportunity Counterparty Contact</label>
    <nameField>
        <displayFormat>OCC-{000000}</displayFormat>
        <label>Counterparty Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Counterparty Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Counterparty_Contact__c/fields/Counterparty__c.field-meta.xml
<CustomField>
    <fullName>Counterparty__c</fullName>
    <label>Counterparty</label>
    <referenceTo>Opportunity_Counterparty__c</referenceTo>
    <relationshipLabel>Opportunity Counterparty Contacts</relationshipLabel>
    <relationshipName>Opportunity_Counterparty_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HL_EngagementCounterpartyHandler.cls
public class HL_EngagementCounterpartyHandler {
    private boolean isExecuting = false;
    private integer batchSize = 0;
    public boolean IsTriggerContext{get{ return isExecuting;}}
    public static Boolean isBeforeInsertFlag = false;
    public static Boolean isBeforeUpdateFlag = false;

    public HL_EngagementCounterpartyHandler(boolean isExecuting, integer size){
        isExecuting = isExecuting;
        batchSize = size;
    }

    public void onAfterInsert(List<Engagement_Counterparty__c> ecList){
        Set<Id> acctSet = new Set<Id>();
        for(Engagement_Counterparty__c ecs : ecList) {
            acctSet.add(ecs.Company__c);
        }
        IndicateCounterparty(acctSet);
    }
    
    public void onAfterUpdate(List<Engagement_Counterparty__c> oldECList, Map<Id,Engagement_Counterparty__c> newECMap){
        Set<Id> acctSet = new Set<Id>();
        for (Engagement_Counterparty__c ecs : oldECList) {
             Engagement_Counterparty__c newECs = newECMAP.get(ecs.id);   
            if(ecs.Company__c <> newECs.Company__c){
                acctSet.add(ecs.Company__c);
                acctSet.add(newECs.Company__c);
            }
        }
        IndicateCounterparty(acctSet);
    }
    
    public void onAfterDelete(List<Engagement_Counterparty__c> ecList){
        Set<Id> acctSet = new Set<Id>();
        for(Engagement_Counterparty__c ecs : ecList) {
            acctSet.add(ecs.Company__c);
        }
        IndicateCounterparty(acctSet);
    }
    
    public void onAfterUndelete(List<Engagement_Counterparty__c> ecList){
        Set<Id> acctSet = new Set<Id>();
        for(Engagement_Counterparty__c ecs : ecList) {
            acctSet.add(ecs.Company__c);
        }
        IndicateCounterparty(acctSet);
    }

    public void InsertCounterpartyComments(List<Engagement_Counterparty__c> ecs){
         List<Engagement_Counterparty_Comment__c> CommentList = new List<Engagement_Counterparty_Comment__c>();
         for(Engagement_Counterparty__c ecp: ecs){
             
            //Check to see if the new comment has a value or not
            if(ecp.Engagement_Counterparty_Comment__c != null && ecp.Engagement_Counterparty_Comment__c != ''){
                //If a value is found, create a new Engagement_Comments Object
                Engagement_Counterparty_Comment__c ecpComment = new Engagement_Counterparty_Comment__c();
                ecpComment.Comment__c = ecp.Engagement_Counterparty_Comment__c;
                ecpComment.Comment_Type__c = 'Internal';
                ecpComment.Line_of_Business__c = 'CF';  //Engagement Counter Party is only CF at this time.
                ecpComment.Related_Engagement_Counterparty__c = ecp.Id;
                ecpComment.CurrencyIsoCode = ecp.CurrencyIsoCode;
                CommentList.add(ecpComment);
                
                //Remove the value for the new comments field so it is never saved to the object and will be blank the next time Pipeline Manager is displayed
                ecp.Engagement_Counterparty_Comment__c = null;
             }      
         }
         insert CommentList;
     }
    
    //Assign the Coverage Officer (if exists), Primary and Secondary Calling Responsibility to Manager/Associate/Analyst
    public void UpdateDefaultFields(List<Engagement_Counterparty__c> ecs){
        Set<Id> accounts = new Set<Id>();
        Set<Id> engagements = new Set<Id>();
        Map<Id, Id> ultimateParentMap = new Map<Id, Id>();
        Map<Id, Id> coverageMap = new Map<Id, Id>();
        Map<Id, Id> managerMap = new Map<Id, Id>();
        Map<Id, Id> associateMap = new Map<Id, Id>();
        for(Engagement_Counterparty__c ec : ecs){
            engagements.add(ec.Engagement__c);
            accounts.add(ec.Company__c);  
        }
        
        //Get the accounts
        for(Account a : [SELECT Primary_FS_Coverage_Officer__c, Ultimate_Parent__c FROM Account WHERE Id IN:accounts]){
            ultimateParentMap.put(a.Id, a.Ultimate_Parent__c);
            if(!String.isBlank(a.Primary_FS_Coverage_Officer__c))
                coverageMap.put(a.Id, a.Primary_FS_Coverage_Officer__c);
        }
        
        //Get the Coverage Officer - this is a standalone query that will grab the FS Officer
        /*for(Coverage_Team__c ct : [SELECT Company__c, Officer__c
                                     FROM Coverage_Team__c 
                                     WHERE (Company__c IN: ultimateParentMap.keySet() OR (Company__r.Ultimate_Parent__c <> null AND (Company__r.Ultimate_Parent__c IN: ultimateParentMap.values() OR Company__r.Ultimate_Parent__c IN: ultimateParentMap.keySet()))) 
                                     AND RecordType.DeveloperName = 'FS_Coverage_Team_Member'
                                     AND Officer__r.Status__c = 'Active'
                                     AND Coverage_level__c = 'Sponsor Officer'
                                     AND Coverage_Team_Status__c = 'Active'
                                     ORDER BY Tier__c ASC]){
                                       coverageMap.put(ct.Company__c, ct.Officer__c);
                                   }
        */
        
        //Get the Manager and Associate
        for(Engagement_Internal_Team__c eit : [SELECT Contact__c, Engagement__c, Role__c FROM Engagement_Internal_Team__c WHERE Engagement__c IN:engagements AND End_Date__c = null AND (Role__c = 'Manager' OR Role__c = 'Associate')]){
            if(eit.Role__c == 'Manager')
                managerMap.put(eit.Engagement__c, eit.Contact__c);
            else 
               associateMap.put(eit.Engagement__c, eit.Contact__c);
        }
        
        for(Engagement_Counterparty__c ec : ecs){
            ec.Coverage_Officer__c = coverageMap.get(ec.Company__c);
            ec.Primary_Calling_Responsibility__c = managerMap.get(ec.Engagement__c);
            if(String.isBlank(ec.Primary_Calling_Responsibility__c))
                ec.Primary_Calling_Responsibility__c = associateMap.get(ec.Engagement__c);
            else{
                ec.Secondary_HL_Contact__c = associateMap.get(ec.Engagement__c);
                if(ec.Primary_Calling_Responsibility__c == ec.Secondary_HL_Contact__c)
                    ec.Secondary_HL_Contact__c = null;
            }
        }
    }

    public List<Engagement_Counterparty__c> InsertConversionRelatedItems(List<Engagement_Counterparty__c> ecList){
        //Check if these are from opportunity conversion
        if(ecList.size() > 0 && !String.isBlank(ecList[0].Opportunity_Counterparty__c)){
            List<Engagement_Counterparty_Contact__c> ecContactsToInsert = new List<Engagement_Counterparty_Contact__c>();
            List<Engagement_Counterparty_Comment__c> ecCommentsToInsert = new List<Engagement_Counterparty_Comment__c>();
            //Create a Map of Opportunity Counterparty Id to Engagement Counterparty
            Map<Id, Engagement_Counterparty__c> ocMap = new Map<Id, Engagement_Counterparty__c>();
            for(Engagement_Counterparty__c ec : ecList){
                if(!String.isBlank(ec.Opportunity_Counterparty__c))
                    ocMap.put(ec.Opportunity_Counterparty__c, ec);
            }

            if(ocMap.size() > 0){
                //Get Opportunity Counterparty Contacts
                for(Opportunity_Counterparty_Contact__c occ : [SELECT Contact__c, Contact_Type__c, Counterparty__c FROM Opportunity_Counterparty_Contact__c WHERE Counterparty__c IN:ocMap.keySet()])
                    ecContactsToInsert.add(new Engagement_Counterparty_Contact__c(Contact__c = occ.Contact__c, Type__c = occ.Contact_Type__c, Counterparty__c = ocMap.get(occ.Counterparty__c).Id));
                for(Opportunity_Counterparty_Comment__c occ : [SELECT Comment__c, Comment_Type__c, Line_of_Business__c, Related_Opportunity_Counterparty__c FROM Opportunity_Counterparty_Comment__c WHERE Related_Opportunity_Counterparty__c IN:ocMap.keySet()])
                    ecCommentsToInsert.add(new Engagement_Counterparty_Comment__c(Comment__c = occ.Comment__c, Comment_Type__c = occ.Comment_Type__c, Line_of_Business__c = occ.Line_of_Business__c, Related_Engagement_Counterparty__c = ocMap.get(occ.Related_Opportunity_Counterparty__c).Id));
            }

            if(ecContactsToInsert.size() > 0)
                insert ecContactsToInsert;     
            if(ecCommentsToInsert.size() > 0)
                insert ecCommentsToInsert;  
        }
        return ecList;
    }

    public void IndicateCounterparty(Set<Id> engagementCounterpartySet){
        List<Account> updateAcctList = new List<Account>();      
        for(Account account : [SELECT Id, (SELECT Id FROM Opportunity_Counterparties__r LIMIT 1), (SELECT Id FROM Engagement_Counterparties__r LIMIT 1) FROM Account WHERE Id IN : engagementCounterpartySet]) {
            account.CounterParty__c = (account.Opportunity_Counterparties__r.size() > 0 || account.Engagement_Counterparties__r.size() > 0) ? true : false;
            updateAcctList.add(account);
        }
        update updateAcctList;
    }
}