force-app/main/default/objects/Account/fields/EBITDA_MM__c.field-meta.xml
<CustomField>
    <fullName>EBITDA_MM__c</fullName>
    <label>EBITDA (MM)</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Debt_MM__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt_MM__c</fullName>
    <label>Total Debt (MM)</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/Affiliation__c.object-meta.xml
<CustomObject>
    <description>Custom object to track a contact to account relationship, where the contact is directly related to the account.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated Contacts</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliated Companies</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Delegate_Public_Group__c/Delegate_Public_Group__c.object-meta.xml
<CustomObject>
    <description>used to store/manage all delegate public groups.</description>
    <label>Delegate Public Group</label>
    <nameField>
        <displayFormat>DPG-{0000}</displayFormat>
        <label>Delegate Public Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegate Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delegate_Public_Group__c/fields/Banker__c.field-meta.xml
<CustomField>
    <fullName>Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delegate_Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/EBITDA_MM__c.field-meta.xml
<CustomField>
    <fullName>EBITDA_MM__c</fullName>
    <label>EBITDA (MM)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c, &quot;Closed&quot;), &quot;Closed&quot;,
IF(ISPICKVAL(Stage__c, &quot;Hold&quot;), &quot;Hold&quot;,
IF(ISPICKVAL(Stage__c, &quot;Dead&quot;), &quot;Dead&quot;,
&quot;Active&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Total_Debt_MM__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt_MM__c</fullName>
    <label>Total Debt (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/Engagement_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( OR( RecordType.Id = &quot;012i0000000tNJN&quot; , RecordType.Id = &quot;012i0000000tKt7&quot; , RecordType.Id = &quot;012i0000001AGQM&quot; ) ,
    Status_Sellside_Joint_Bid_Sellside__c ,
    IF( RecordType.Id = &quot;012i0000000tKt2&quot; ,
        Status_Buyside__c ,
        IF( RecordType.Id = &quot;012i0000000tLTf&quot; ,
            Status_Cap_Markets__c,
            &quot;No Applicable Status&quot;
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/Engagement_Counterparty_Contact__c.object-meta.xml
<CustomObject>
    <description>Custom object to track contacts from engagement counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty Contact</label>
    <nameField>
        <displayFormat>ECC-{000000}</displayFormat>
        <label>Counterparty Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Counterparty Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>External Contacts only.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements Shown</relationshipLabel>
    <relationshipName>Engagement_Counterparty_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/Engagement_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for an engaged deal/project.</description>
    <label>Engagement Contact</label>
    <nameField>
        <displayFormat>EET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_External_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Invalid Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Engagement_Working_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/EBITDA_MM__c.field-meta.xml
<CustomField>
    <fullName>EBITDA_MM__c</fullName>
    <formula>IF(
 RecordType.DeveloperName = &apos;CF&apos; &amp;&amp;   ISPICKVAL(Job_Type__c, &apos;Buyside&apos;),  Subject__r.Recent_EBITDA_MM__c ,
IF(
NOT(ISNULL(Client__r.Recent_EBITDA_MM__c )), Client__r.Recent_EBITDA_MM__c , Subject__r.Recent_EBITDA_MM__c ))</formula>
    <label>EBITDA (MM)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( RecordType.Name = &apos;FR&apos;, 
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
&apos;Active&apos;)))),

IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
&apos;Active&apos;)))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/Opportunity_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for a prospective engagement.</description>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>OET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Contacts</relationshipLabel>
    <relationshipName>Opportunity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Invalid Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Opportunity_Client_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Has_Delegates__c.field-meta.xml
<CustomField>
    <fullName>Has_Delegates__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Has Delegates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SL_Test_RelationshipTearsheet_Report.cls
@isTest
private class SL_Test_RelationshipTearsheet_Report 
{
    @testSetup
    private static void SetupReportData(){
        Integer i = 0;    
        Profile objProfile = [SELECT Name 
                              FROM Profile
                              WHERE Name = 'System Administrator'];
        
        List<User> userList = new List<User>();
        
        for(User userRecord : (List<User>)HL_TestFactory.CreateSObjectList('User', false, 1))
        {
            userRecord.Lastname = 'User';
            userRecord.Email = 'tuser@yahoo.in';
            userRecord.Username = 'test@hl2.com';
            userRecord.ProfileId = objProfile.Id;
            userRecord.Alias = 'tuser';
            userRecord.TimeZoneSidKey = 'GMT';
            userRecord.LocaleSidKey = 'en_US';
            userRecord.EmailEncodingKey = 'ISO-8859-1';
            userRecord.LanguageLocaleKey = 'en_US';
            userRecord.Has_Delegates__c = false;
            userList.add(userRecord);
        }
        insert userList;
        
        List<Delegate_Public_Group__c> delegatePublicGroupList = new List<Delegate_Public_Group__c>();
        for(Delegate_Public_Group__c delegatePublicGroupRecord : (List<Delegate_Public_Group__c>)HL_TestFactory.CreateSObjectList('Delegate_Public_Group__c', false, 1))
        {
            delegatePublicGroupRecord.Banker__c = userList[0].Id;
            delegatePublicGroupList.add(delegatePublicGroupRecord);
        }
        insert delegatePublicGroupList;
        
        List<Account> accountList = new List<Account>();
        for(Account accountRecord : (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, 1))
        {
            accountRecord.Name = 'Abc';
            accountRecord.EBITDA_MM__c = 54545;
            accountRecord.Total_Debt_MM__c = 4500;
            accountRecord.AnnualRevenue = 78754;
            accountList.add(accountRecord);                            
        }
        insert accountList;
        
        List<Contact> AllContacts = new List<Contact>();
        Contact externalContact = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.External_Contact, false);
        //insert externalContact;
        AllContacts.add(externalContact);
        
        List<Contact> hlContactList = new List<Contact>();
        for(Contact contactRecord : HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.Houlihan_Employee, false, 1))
        {
            contactRecord.AccountId = accountList[0].Id;
            contactRecord.Title = 'Title-1';
            contactRecord.Phone = '989898989';
            contactRecord.MobilePhone = '989898989';
            contactRecord.Email = 'abc@silverlinecrm.com';      
            contactRecord.AssistantName = 'TestAsst.-1';
            contactRecord.AssistantPhone = '9875487884';
            contactRecord.User__c = userList[0].Id;
            hlContactList.add(contactRecord);
        }
        AllContacts.addAll(hlContactList);
        //insert hlContactList;
        insert AllContacts;
        
        List<Affiliation__c> affiliationList = new List<Affiliation__c>();
        for(Affiliation__c affiliationRecord : (List<Affiliation__c>)HL_TestFactory.CreateSObjectList('Affiliation__c', false, 7))
        {
            affiliationRecord.Account__c = accountList[0].Id;
            affiliationRecord.Contact__c = hlContactList[0].Id;
            affiliationRecord.End_Date__c = Date.today();
            affiliationRecord.Status__c = 'Former';
            affiliationRecord.End_Date__c = Date.today().addDays(5);
            affiliationRecord.Type__c = 'Outside Board Member';
            affiliationList.add(affiliationRecord);
        }
        
        for(Affiliation__c affiliationRecord : (List<Affiliation__c>)HL_TestFactory.CreateSObjectList('Affiliation__c', false, 7))
        {
            affiliationRecord.Account__c = accountList[0].Id;
            affiliationRecord.Contact__c = hlContactList[0].Id;
            affiliationRecord.End_Date__c = Date.today();
            affiliationRecord.Status__c = 'Current';
            affiliationRecord.End_Date__c = Date.today().addDays(5);
            affiliationRecord.Type__c = 'Parent';
            affiliationList.add(affiliationRecord);
        }
        insert affiliationList;
        
        List<Event> eventList = new List<Event>();
        for(Event eventRecord : (List<Event>)HL_TestFactory.CreateSObjectList('Event', false, 5))
        {
            eventRecord.StartDateTime = datetime.now();
            eventRecord.EndDateTime = datetime.now().addHours(2);
            eventRecord.ActivityDate = date.Today().addDays(-1);
            eventRecord.OwnerId = Userinfo.getUserId();
            eventRecord.WhoId = hlContactList[0].Id;
            eventList.add(eventRecord);
        }
        
        for(Event eventRecord : (List<Event>)HL_TestFactory.CreateSObjectList('Event', false, 5))
        {
            eventRecord.StartDateTime = datetime.now();
            eventRecord.EndDateTime = datetime.now();
            eventRecord.ActivityDate = date.Today().addDays(-1);
            eventRecord.OwnerId = Userinfo.getUserId();
            eventRecord.WhoId = hlContactList[0].Id;
            eventList.add(eventRecord);
        }
        
        for(Event eventRecord : (List<Event>)HL_TestFactory.CreateSObjectList('Event', false, 5))
        {
            eventRecord.StartDateTime = datetime.now();
            eventRecord.EndDateTime = datetime.now();
            eventRecord.ActivityDate = date.Today().addYears(-2);
            eventRecord.OwnerId = Userinfo.getUserId();
            eventRecord.WhoId = hlContactList[0].Id;
            eventList.add(eventRecord);
        }
        insert eventList;
        
        List<Engagement__c> engagementList = new List<Engagement__c>();
        for(Engagement__c engagementRecord : HL_TestFactory.CreateEngagementList(false, 10))
        {
            engagementRecord.Client__c = accountList[0].Id;
            engagementRecord.Subject__c = accountList[0].Id;
            engagementRecord.ProgressMonthly_Fee__c = 1500.0;
            engagementRecord.Close_Date__c = Date.today().addYears(5);
            engagementRecord.Referral_Contact__c = hlContactList[0].Id;
            engagementList.add(engagementRecord);
        }
        insert engagementList;
        
        i = 0;
        /*List<Engagement_External_Team__c> engagementExternalTeamList = new List<Engagement_External_Team__c>();
        for(Engagement_External_Team__c externalTeamRecord : (List<Engagement_External_Team__c>)HL_TestFactory.CreateSObjectList('Engagement_External_Team__c', false, 10))
        {
            externalTeamRecord.Contact__c = externalContact.Id;
            externalTeamRecord.Engagement__c = engagementList[i].Id;
            externalTeamRecord.Type__c ='Referral';
            engagementExternalTeamList.add(externalTeamRecord);
            i++;
        }
        insert engagementExternalTeamList;*/
        
        List<Engagement_Counterparty__c> engagementCounterpartyList = new  List<Engagement_Counterparty__c>();
        for(Engagement_Counterparty__c counterpartyRecord : (List<Engagement_Counterparty__c>)HL_TestFactory.CreateSObjectList('Engagement_Counterparty__c', false, 5))
        {
            counterpartyRecord.Company__c = accountList[0].Id;
            counterpartyRecord.Engagement__c = engagementList[0].Id;
            counterpartyRecord.Coverage_Officer__c = hlContactList[0].Id;
            engagementCounterpartyList.add(counterpartyRecord);
        }
        insert engagementCounterpartyList;
        
        i = 0;
        /*List<Engagement_Counterparty_Contact__c> counterpartyContactList = new List<Engagement_Counterparty_Contact__c>();
        for(Engagement_Counterparty_Contact__c counterpartyContactRecord : (List<Engagement_Counterparty_Contact__c>)HL_TestFactory.CreateSObjectList('Engagement_Counterparty_Contact__c', false, 5))
        {
            counterpartyContactRecord.Contact__c = externalContact.Id;
            counterpartyContactRecord.Counterparty__c = engagementCounterpartyList[i].Id;
            counterpartyContactList.add(counterpartyContactRecord);
            i++;
        }
        insert counterpartyContactList;*/
        
        i = 0;
        Date dtStartDate = Date.today().addDays(5);
        List<Campaign> campaignList = new List<Campaign>();
        for(Campaign campaignRecord : (List<Campaign>)HL_TestFactory.CreateSObjectList('Campaign', false, 5))
        {
            campaignRecord.Name = 'Campaign ' + campaignList.size();
            campaignRecord.Engagement__c = engagementList[i].Id;
            campaignRecord.StartDate = dtStartDate;
            campaignRecord.Type = 'Conference';
            campaignList.add(campaignRecord);
            i++;
            if(i > 2)
                dtStartDate = Date.today().addDays(-5);
        }
        insert campaignList;
        
        i = 0;
        List<CampaignMember> campaignMemberList = new List<CampaignMember>();
        for(CampaignMember campaignMemberRecord : (List<CampaignMember>)HL_TestFactory.CreateSObjectList('CampaignMember', false, 5))
        {
            campaignMemberRecord.CampaignId = campaignList[i].Id;
            campaignMemberRecord.ContactId = hlContactList[0].Id;
            campaignMemberList.add(campaignMemberRecord);
            i++;
        }
        insert campaignMemberList;
        
        List<Opportunity__c> opportunityList = new List<Opportunity__c>();
        for(Opportunity__c opportunityRecord : (List<Opportunity__c>)HL_TestFactory.CreateSObjectList('Opportunity__c', false, 10))
        {
            opportunityRecord.Client__c = accountList[0].Id;
            opportunityRecord.Estimated_Engagement_Date__c = Date.today();
            opportunityList.add(opportunityRecord);
        }
        insert opportunityList;
        
        /*List<Opportunity_External_Team__c> opportunityExternalTeamList = new List<Opportunity_External_Team__c>();
        for(Opportunity_External_Team__c opportunityExternalTeamRecord : (List<Opportunity_External_Team__c>)HL_TestFactory.CreateSObjectList('Opportunity_External_Team__c', false, 1))
        {
            opportunityExternalTeamRecord.Opportunity__c = opportunityList[0].Id;
            opportunityExternalTeamRecord.Contact__c = externalContact.Id;
            opportunityExternalTeamList.add(opportunityExternalTeamRecord);
        }
        insert opportunityExternalTeamList;*/
        
        /*List<Opportunity_Internal_Team__c> opportunityInternalTeamList = new List<Opportunity_Internal_Team__c>();
        for(Opportunity_Internal_Team__c opportunityInternalTeamRecord : (List<Opportunity_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Opportunity_Internal_Team__c', false, 1))
        {
            opportunityInternalTeamRecord.Opportunity__c = opportunityList[0].Id;
            opportunityInternalTeamRecord.Contact__c = hlContactList[0].Id;
            opportunityInternalTeamList.add(opportunityInternalTeamRecord);
        }
        insert opportunityInternalTeamList;*/
        
        i = 0;
        List<Relationship__c> relationshipList = new List<Relationship__c>();
        for(Relationship__c relationshipRecord : (List<Relationship__c>)HL_TestFactory.CreateSObjectList('Relationship__c', false, 1))
        {
            relationshipList.add(new Relationship__c(External_Contact__c = externalContact.Id, 
                                                     HL_Contact__c = hlContactList[0].Id,
                                                     Strength_Rating__c = '2',
                                                     Number_of_Activities_LTM__c = 3, 
                                                     Last_Activity_Date__c = Date.today()));
            i++;                                                    
        }
        insert relationshipList;
        
    }
    
    @isTest
    private static void TestRelationshipTearsheetReport() 
    {       
        List<Contact> hlContactList = [SELECT User__c FROM Contact WHERE RecordType.DeveloperName = 'Houlihan_Employee'];                
        Test.startTest();
        
        System.currentPageReference().getParameters().put('Id','' + hlContactList[0].Id);
        SL_RelationshipTearsheet_Report objRTP = new SL_RelationshipTearsheet_Report();
        objRTP.GetReportData();
        objRTP.GetMostActiveHLRelationship();
        objRTP.GetMostRecentActivities();
        objRTP.GetEngagementHistory();
        objRTP.GetOpenOpportunities();
        objRTP.GetReferralFeesHistory();
        objRTP.GetDealsShown();
        objRTP.GetConferenceAttendance();
        objRTP.GetCareerInformation();
        objRTP.GetBoardInformation();
        
        Test.stopTest();
        
        System.assert(!ApexPages.hasMessages(ApexPages.severity.ERROR));
    }
}