force-app/main/default/objects/Account/fields/Full_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Full_Account_ID__c</fullName>
    <formula>CASESAFEID( Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_Link_URL__c</fullName>
    <description>Link that will execute the report</description>
    <label>Report Link URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HL_CompanyReportLinks.cls
public with sharing class HL_CompanyReportLinks {
    public List<HL_Report_Link__c>	LinkList	{ get;set; }
    public string PageTitle						{ get;set; }
    public string PageStyle						{ get;set; } 
    
    public HL_CompanyReportLinks(Apexpages.StandardController con)
    {
        Account currAccount;
        string CompanyID;
        string ShortCompanyID;
        
        try
        {
            currAccount =  [SELECT Id, Name, Full_Account_ID__c FROM Account WHERE ID =: con.getId()];
            CompanyID = currAccount.Full_Account_ID__c;
			ShortCompanyID = String.valueOf(currAccount.Id).substring(0,15);            
        }
        catch(Exception ex)
        {
            currAccount = null;
            CompanyID = null;
			ShortCompanyID = null;            
        }
        
        if(!String.isBlank(CompanyID))
        {
            LinkList = HL_ReportLink.GetByType('Company Single');
            
            for(HL_Report_Link__c currLink: LinkList){            
                currLink.Report_Link_URL__c = currLink.Report_Link_URL__c.replace('{!Account.Full_Account_ID__c}', CompanyID)
            															 .replace('{!Account.Id}', ShortCompanyID);
            }
            PageTitle = 'Company Reports for ' + currAccount.Name;
            PageStyle = 'display:initial;';             
        }
        else  
        {
       		LinkList = HL_ReportLink.GetByType('Company Group');
            
            PageTitle = 'Company Reports';
            PageStyle = 'display:none;';            
        }        
    }
    
    public HL_CompanyReportLinks(){}
    
    public Pagereference ReturnToParent()
    {
        Pagereference pageref = new Pagereference('/' + ApexPages.currentPage().getParameters().get('id'));
	   	return pageref;
    }    
}