force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Academic Research &amp; IP</fullName>
            </value>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Airlines/Air Cargo</fullName>
            </value>
            <value>
                <fullName>Ambulatory Surgical Centers</fullName>
            </value>
            <value>
                <fullName>Analytics &amp; Big Data</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automotive &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Autonomous Systems</fullName>
            </value>
            <value>
                <fullName>Behavioral &amp; Labs</fullName>
            </value>
            <value>
                <fullName>Broker Dealers</fullName>
            </value>
            <value>
                <fullName>Building Products</fullName>
            </value>
            <value>
                <fullName>Business Management Software</fullName>
            </value>
            <value>
                <fullName>Capital Goods</fullName>
            </value>
            <value>
                <fullName>CBD/Cannabis</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Commercial Financial Co.</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Infrastructure Components</fullName>
            </value>
            <value>
                <fullName>Communications Solutions</fullName>
            </value>
            <value>
                <fullName>Company &amp; Market Intelligence</fullName>
            </value>
            <value>
                <fullName>Consumer/Non-Mortgage Finance Co.</fullName>
            </value>
            <value>
                <fullName>Consumer Products</fullName>
            </value>
            <value>
                <fullName>Customer Information Management</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Data &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>Data Centers</fullName>
            </value>
            <value>
                <fullName>Dealership &amp; Rental Services</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP__c/Eng_VP__c.object-meta.xml
<CustomObject>
    <label>Engagement Valuation Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Valuation Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Valuation Periods</relationshipLabel>
    <relationshipName>Engagement_Portfolio_Valuations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;     Engagement__c ,  Engagement__r.Engagement_Number__c , &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/Eng_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Engagement Valuation Period Positions linked with Engagement and Companies</description>
    <label>Eng Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eng Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP_Position__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Company</description>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Houlihan_Company</value>
        </filterItems>
        <filterItems>
            <field>Account.Id</field>
            <operation>notEqual</operation>
            <value>001i000001T7e9v</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Eng_PV_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;    Engagement_VP__r.Engagement__c    ,   Engagement_VP__r.Engagement__r.Engagement_Number__c  , &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Engagement_VP__c.field-meta.xml
<CustomField>
    <fullName>Engagement_VP__c</fullName>
    <label>Engagement Valuation Period</label>
    <referenceTo>Eng_VP__c</referenceTo>
    <relationshipName>Eng_VP_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Fee_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Fee_Approval_Date__c</fullName>
    <label>Fee Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <formula>TEXT(Company__r.Industry_Group__c)</formula>
    <label>Industry Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed, Generate Accrual</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <inlineHelpText>Case Number</inlineHelpText>
    <label>Engagement Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c, &quot;Closed&quot;), &quot;Closed&quot;,
IF(ISPICKVAL(Stage__c, &quot;Hold&quot;), &quot;Hold&quot;,
IF(ISPICKVAL(Stage__c, &quot;Dead&quot;), &quot;Dead&quot;,
&quot;Active&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_EngVPPositionNewController.cls
public without sharing class HL_EngVPPositionNewController {
    
    Public Eng_VP_Position__c EngVPPositon {get; set;}
    Public Account selectedAcc {get; set;}
    Public List<Engagement__c> EngList {get; set;}
    public Boolean isValidPVUser{get;set;}
    public Boolean IshavingValidRoleForRevAccrual{get;set;}
    public HL_EngVPPositionNewController(ApexPages.StandardController controller) {
        
        EngVPPositon = new Eng_VP_Position__c();
        EngList = new List<Engagement__c>();
        EngVPPositon = (Eng_VP_Position__c) controller.getRecord(); 
        EngVPPositon.Engagement_VP__c = apexpages.currentPage().getParameters().get('VPId');   
        EngVPPositon.Status__c = 'In Progress';
        Engagement__c Eng = new Engagement__c();
        for(Eng_VP__c engVP : [Select Engagement__c From Eng_VP__c Where Id =: EngVPPositon.Engagement_VP__c])
        {
            Eng.id = engVP.Engagement__c;
        }
        if(Eng != null && Eng.id != null ){
            EngList = [Select Id, Client__c,Engagement_Number__c From Engagement__c Where Id =: Eng.id];
            isValidPVUser = HL_EngagementViewController.VerifyUserforVP(Eng, 'PVPositionCreation');  
            IshavingValidRoleForRevAccrual = HL_ConstantsUtil.IshavingValidRoleInInternTeamEng(Eng.id); 
        }
                               
    }
      //To ClearFeeApprovalDate on change of report fee
    public void ClearFeeApprovalDate(){
        EngVPPositon.Fee_Approval_Date__c=null;
        
     }
    //To get IG&S of associated Company
    public void CompanyIGSvalues(){
        if(EngVPPositon.Company__c != null){
            selectedAcc = [SELECT id,Industry_Group__c,Sector__c from Account WHERE id=:EngVPPositon.Company__c];
        }
    }
    
    public PageReference SaveData() {
        
        CompanyIGSvalues();
        try{ 
            if(EngVPPositon.Automation_Tool_Utilized__c == 'No' && (EngVPPositon.Reason__c == '' || EngVPPositon.Reason__c == null)){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Reason: Please select a Reason because Automation Tool Utilized is selected as \'No\''));
                return null;
            }
            
            if(((selectedAcc.Industry_Group__c == null || selectedAcc.Industry_Group__c == '') || (selectedAcc.Sector__c == null || selectedAcc.Sector__c == '')) && 
               ((EngVPPositon.Industry_Group_Picklist__c == null || EngVPPositon.Industry_Group_Picklist__c == '') || (EngVPPositon.Sector__c == null || EngVPPositon.Sector__c == ''))){
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,Label.HL_No_IG_S_on_Position));
                return null;
            }
            
            if(EngVPPositon.Automation_Tool_Utilized__c == 'yes' && (EngVPPositon.Reason__c != '' && EngVPPositon.Reason__c != null)){
                EngVPPositon.Reason__c='';
            }
            
            if((selectedAcc.Industry_Group__c != null && selectedAcc.Industry_Group__c != '') && (selectedAcc.Sector__c != null && selectedAcc.Sector__c != '') &&
                (EngVPPositon.Industry_Group_Picklist__c == null || EngVPPositon.Industry_Group_Picklist__c == '') && (EngVPPositon.Sector__c == null || EngVPPositon.Sector__c == '')){
                
                EngVPPositon.Industry_Group_Picklist__c = selectedAcc.Industry_Group__c;
                EngVPPositon.Sector__c = selectedAcc.Sector__c;
            }
            
            insert EngVPPositon; 
            return new pageReference('/'+ apexpages.currentPage().getParameters().get('VPId'));
        }
        catch(Exception e) {
            Apexpages.addMessages(e);
            //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,e.getmessage()));
            return null;
        }       
        
    }
}