force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Full_Name__c</fullName>
    <formula>IF(!ISBLANK(LastName), TRIM(LastName + &quot;, &quot; + FirstName + &quot; &quot; + MiddleName), &quot;&quot;)</formula>
    <label>Contact Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Hourly Rate</description>
    <label>Hourly Rate</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASC - Augmenting Sector Coverage</fullName>
            </value>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>CM - Capital Markets</fullName>
            </value>
            <value>
                <fullName>CORP - Corporate</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>FS - Financial Sponsors</fullName>
            </value>
            <value>
                <fullName>FT - Financial Technology</fullName>
            </value>
            <value>
                <fullName>GEN - General</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IFA - Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>M&amp;A - Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>NRG - Energy</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>PFG - Private Funds Group</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TAG - Tangible Asset Group</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Foreign_Office__c.field-meta.xml
<CustomField>
    <fullName>Is_Foreign_Office__c</fullName>
    <description>Used to check for a foreign office</description>
    <formula>TEXT(Office__c) == &apos;AM&apos; || TEXT(Office__c) == &apos;BE&apos; || TEXT(Office__c) == &apos;DB&apos;|| TEXT(Office__c) == &apos;FF&apos; || TEXT(Office__c) == &apos;F3&apos; || TEXT(Office__c) == &apos;HK&apos; || TEXT(Office__c) == &apos;LO&apos; || TEXT(Office__c) == &apos;MD&apos; || TEXT(Office__c) == &apos;ML&apos; || TEXT(Office__c) == &apos;MU&apos; || TEXT(Office__c) == &apos;PA&apos; || TEXT(Office__c) == &apos;P2&apos; || TEXT(Office__c) == &apos;RO&apos; || TEXT(Office__c) == &apos;SG&apos; || TEXT(Office__c) == &apos;SY&apos; || TEXT(Office__c) == &apos;TK&apos; || TEXT(Office__c) == &apos;ZG&apos; || TEXT(Office__c) == &apos;BI&apos; || TEXT(Office__c) == &apos;DE&apos; || TEXT(Office__c) == &apos;FK&apos; || TEXT(Office__c) == &apos;HM&apos; || TEXT(Office__c) == &apos;KY&apos; || TEXT(Office__c) == &apos;LS&apos; || TEXT(Office__c) == &apos;LE&apos; || TEXT(Office__c) == &apos;MA&apos; || TEXT(Office__c) == &apos;MC&apos; || TEXT(Office__c) == &apos;NG&apos; || TEXT(Office__c) == &apos;OS&apos; || TEXT(Office__c) == &apos;SH&apos; || TEXT(Office__c) == &apos;ST&apos; || TEXT(Office__c) == &apos;TA&apos;|| TEXT(Office__c) == &apos;ZR&apos;</formula>
    <label>Is Foreign Office</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MU</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered__c.field-meta.xml
<CustomField>
    <fullName>Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Registered HL Employees</description>
    <label>Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Staff_Type__c.field-meta.xml
<CustomField>
    <fullName>Staff_Type__c</fullName>
    <label>Staff Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADMIN</fullName>
            </value>
            <value>
                <fullName>AG-TEMP</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>HL-TEMP</fullName>
            </value>
            <value>
                <fullName>INTERN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MU</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_Contact.cls
public with sharing class HL_Contact {
    public static final string STANDARD_SELECT = 'SELECT Name, Contact_Full_Name__c, User__c, Account.Name, Department, Title, Email, Hourly_Rate__c, Is_Foreign_Office__c, Office__c, Line_Of_Business__c, Industry_Group__C, Phone, MobilePhone, Registered__c, Staff_Type__c, RecordType.DeveloperName ';
    @AuraEnabled
    public static Contact GetById(string Id){
        List<Contact> c = Database.query(STANDARD_SELECT + 'FROM Contact WHERE Id =: Id');
        return c.size() > 0 ? c[0] : null;
    }

    public static List<Contact> GetList(List<Contact> contacts){
        return Database.query(STANDARD_SELECT + 'FROM Contact WHERE Id IN: contacts');
    }

    public static List<Contact> GetListByUsers(List<User> users){
        return Database.query(STANDARD_SELECT + 'FROM Contact WHERE User__c IN: users');
    }

    public static Map<Id, Contact> GetMap(List<Contact> contacts){
        List<Contact> contactList = GetList(contacts);
        return new Map<Id, Contact>(contactList);
    }

    public static Map<Id, Contact> GetMapByUsers(List<User> users){
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
        for(Contact c : GetListByUsers(users))
            contactMap.put(c.User__c, c);
        return contactMap;
    }

    @AuraEnabled
    public static Contact GetByUserId(){
        return GetByUserId(UserInfo.getUserId());
    }
    @AuraEnabled
    public static Contact GetByUserId(id userId){
        List<Contact> c = [SELECT Name, User__c, Account.Name, Department, Title, Email, Hourly_Rate__c, Is_Foreign_Office__c, Office__c, Line_Of_Business__c, Phone, MobilePhone, Registered__c, Staff_Type__c, Industry_Group__c FROM Contact WHERE User__c =: userId];
        return c.size() > 0 ? c[0] : new Contact();
    }
     @AuraEnabled
    public static list<Id> GetByUserIdset(id userId){
    list<Id> conSet = new list<Id>();
        for(contact con : [SELECT Id,Name, User__c, Account.Name, Department, Title, Email, Hourly_Rate__c, Is_Foreign_Office__c, Office__c, Line_Of_Business__c, Phone, MobilePhone, Registered__c, Staff_Type__c, Industry_Group__c FROM Contact WHERE User__c =: userId]){
       conSet.add(con.Id);
        }
        
        return conSet;
    }
    public static List<Contact> GetByCompany(id companyId)
    {
        return [SELECT Name FROM Contact WHERE Account.Id =: companyId];
    }
    
       public static Id GetByContactUserId(id contactId){
        return [SELECT User__c FROM Contact WHERE Id =: contactId limit 1].User__c;
    }
}