force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASC - Augmenting Sector Coverage</fullName>
            </value>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>CM - Capital Markets</fullName>
            </value>
            <value>
                <fullName>CORP - Corporate</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>FS - Financial Sponsors</fullName>
            </value>
            <value>
                <fullName>FT - Financial Technology</fullName>
            </value>
            <value>
                <fullName>GEN - General</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IFA - Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>M&amp;A - Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>NRG - Energy</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>PFG - Private Funds Group</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TAG - Tangible Asset Group</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Legal Entity</description>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_of_Business__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activism Advisory</fullName>
            </value>
            <value>
                <fullName>Board Advisory Services (BAS)</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Buyside &amp; Financing Advisory</fullName>
            </value>
            <value>
                <fullName>Collateral Valuation</fullName>
            </value>
            <value>
                <fullName>Compensation/Formula Analysis</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Corporate Alliances</fullName>
            </value>
            <value>
                <fullName>Creditor Advisors</fullName>
            </value>
            <value>
                <fullName>CVAS - Forensic Services</fullName>
            </value>
            <value>
                <fullName>CVAS - FV Opinion</fullName>
            </value>
            <value>
                <fullName>CVAS - Goodwill or Asset Impairment</fullName>
            </value>
            <value>
                <fullName>CVAS - Pre-Acq Val&apos;n Cons</fullName>
            </value>
            <value>
                <fullName>CVAS - Purchase Price Allocation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 123R/409A Stock, Option Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 133 Derivatives, Liabilities Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Sovereign Advisory</fullName>
            </value>
            <value>
                <fullName>CVAS - Tangible Asset Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Tax Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Transfer Pricing</fullName>
            </value>
            <value>
                <fullName>Debt Advisory</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Advisors</fullName>
            </value>
            <value>
                <fullName>Discretionary Advisory</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Buyside</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Sellside</fullName>
            </value>
            <value>
                <fullName>DRC - Ad Valorem Services</fullName>
            </value>
            <value>
                <fullName>DRC - Appointed Arbitrator/Mediator</fullName>
            </value>
            <value>
                <fullName>DRC - Contract Compliance</fullName>
            </value>
            <value>
                <fullName>DRC - Exp Cons-Arbitrat&apos;n</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Legal Entity</description>
    <label>Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Legal_Entity__c.Available_for_Project__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/Engagement_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Engagement__r.Client__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Counterparties</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <formula>TEXT(Engagement__r.Job_Type__c)</formula>
    <label>Job Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <formula>Engagement__r.PIPELINE_Line_of_Business__c</formula>
    <label>Line Of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <formula>Engagement__r.Subject__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/Engagement_Counterparty_Contact__c.object-meta.xml
<CustomObject>
    <description>Custom object to track contacts from engagement counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty Contact</label>
    <nameField>
        <displayFormat>ECC-{000000}</displayFormat>
        <label>Counterparty Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Counterparty Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty_Contact__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <formula>Counterparty__r.Engagement__c</formula>
    <label>Engagement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CounterPartyEditTest.cls
@IsTest
private class CounterPartyEditTest {
    @IsTest
    static void myUnitTest(){
        Map<String,Engagement_Counterparty_List_View__mdt> metaMap = CounterPartyEdit.getListViewMeta();
        Account client = new Account();
        client.name = 'Client test';
        insert client;
        
        Account subject = new Account();
        subject.name = 'subject test';
        insert subject;
        
        Contact cntct = new contact();
        cntct.Accountid = client.id;
        cntct.lastname = 'TEST';
        cntct.Firstname = 'TEST';
        cntct.Email='testasdf234@xyz.com';
        insert cntct;
        
        Legal_Entity__c lgE = new Legal_Entity__c ();
        lge.name ='test LGE';
        
        insert lgE;
        
        Engagement__c engMent = new Engagement__c ();
        engMent.name = 'Test';
        engMent.Subject__c  = subject.Id;
        engMent.Client__c   = Client.Id;
        engMent.Line_of_Business__c  = 'CF';
        engMent.Job_Type__c ='Activism Advisory';
        engMent.Industry_Group__c  = 'BUS - Business Services';
        engMent.Sector__c  ='Education & Training';
        engMent.Stage__c  = 'Retained';
        engMent.Primary_Office__c  = 'AM';
        engMent.Legal_Entity__c  = lgE.Id;        
        insert engMent;
        
        Engagement_Counterparty__c ec = new Engagement_Counterparty__c(Name='Test',Engagement__c=engment.Id);
        insert ec;
        
        Engagement_Counterparty_Contact__c ecc = new Engagement_Counterparty_Contact__c(Counterparty__c=ec.Id,Contact__c=cntct.Id);
        insert ecc;

        CounterPartyEdit.getEngagement(engMent.Id);

        Engagement_Counterparty_List_View__mdt meta = metaMap.values().get(0);
        CounterPartyEdit.getCounterpartyList(engment.Id, 20, 1, meta.Filter__c);
        
        List<CounterPartyEdit.CounterpartyContactWrapper> eccList = CounterpartyEdit.getCounterpartyContacts(new List<String> {ec.Id});
        
        CounterpartyEdit.deleteCounterparties(new List<Id>{ec.Id});
        
        List<EmailTemplate> etList = CounterpartyEdit.getAvailableTemplates();
        
        try{
        	CounterpartyEdit.getEmailTemplate(null);
        }catch(Exception e){
            
        }
    }
}