force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP__c/Eng_VP__c.object-meta.xml
<CustomObject>
    <label>Engagement Valuation Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Valuation Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Valuation Periods</relationshipLabel>
    <relationshipName>Engagement_Portfolio_Valuations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;     Engagement__c ,  Engagement__r.Engagement_Number__c , &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/Eng_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Engagement Valuation Period Positions linked with Engagement and Companies</description>
    <label>Eng Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eng Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP_Position__c/fields/Asset_Classes__c.field-meta.xml
<CustomField>
    <fullName>Asset_Classes__c</fullName>
    <label>Asset Classes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABL</fullName>
            </value>
            <value>
                <fullName>ABS (Other)</fullName>
            </value>
            <value>
                <fullName>Auction Rate Securities</fullName>
            </value>
            <value>
                <fullName>Auto Loans</fullName>
            </value>
            <value>
                <fullName>Bank Assets (FDIC)</fullName>
            </value>
            <value>
                <fullName>CDO</fullName>
            </value>
            <value>
                <fullName>CLO</fullName>
            </value>
            <value>
                <fullName>CLO – MOA / CMV (Asset Manager)</fullName>
            </value>
            <value>
                <fullName>CMBS</fullName>
            </value>
            <value>
                <fullName>Contingent Value Rights</fullName>
            </value>
            <value>
                <fullName>Debt</fullName>
            </value>
            <value>
                <fullName>Debt &amp; Derivatives</fullName>
            </value>
            <value>
                <fullName>Derivatives</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>Equity, Debt, &amp; Derivatives</fullName>
            </value>
            <value>
                <fullName>Equity &amp; Debt</fullName>
            </value>
            <value>
                <fullName>Equity &amp; Derivatives</fullName>
            </value>
            <value>
                <fullName>Fix and Flip Mortgages</fullName>
            </value>
            <value>
                <fullName>Fund Manager Valuation</fullName>
            </value>
            <value>
                <fullName>Interest Rate Lock Commitments</fullName>
            </value>
            <value>
                <fullName>Litigation Claims</fullName>
            </value>
            <value>
                <fullName>Marketplace Lending</fullName>
            </value>
            <value>
                <fullName>Market Study</fullName>
            </value>
            <value>
                <fullName>Mortgage Servicing Rights</fullName>
            </value>
            <value>
                <fullName>Non-Performing Loans</fullName>
            </value>
            <value>
                <fullName>PIPE Investments</fullName>
            </value>
            <value>
                <fullName>Residential Mortgages</fullName>
            </value>
            <value>
                <fullName>Reverse Mortgages</fullName>
            </value>
            <value>
                <fullName>Risk Retention</fullName>
            </value>
            <value>
                <fullName>RMBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Company</description>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Houlihan_Company</value>
        </filterItems>
        <filterItems>
            <field>Account.Id</field>
            <operation>notEqual</operation>
            <value>001i000001T7e9v</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Eng_PV_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;    Engagement_VP__r.Engagement__c    ,   Engagement_VP__r.Engagement__r.Engagement_Number__c  , &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Engagement_VP__c.field-meta.xml
<CustomField>
    <fullName>Engagement_VP__c</fullName>
    <label>Engagement Valuation Period</label>
    <referenceTo>Eng_VP__c</referenceTo>
    <relationshipName>Eng_VP_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <formula>TEXT(Company__r.Industry_Group__c)</formula>
    <label>Industry Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Industry_Group_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group_Picklist__c</fullName>
    <inlineHelpText>Industry Group of the Position.</inlineHelpText>
    <label>Position Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
            <value>
                <fullName>ADG - Aerospace Defense and Government</fullName>
                <isActive>false</isActive>
                <label>ADG - Aerospace Defense and Government</label>
            </value>
            <value>
                <fullName>DA - Data &amp; Analytics</fullName>
                <isActive>false</isActive>
                <label>DA - Data &amp; Analytics</label>
            </value>
            <value>
                <fullName>OTHER - Other</fullName>
                <isActive>false</isActive>
                <label>OTHER - Other</label>
            </value>
            <value>
                <fullName>TMT - Technology Media &amp; Telecommunications</fullName>
                <isActive>false</isActive>
                <label>TMT - Technology Media &amp; Telecommunications</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Report_Fee__c.field-meta.xml
<CustomField>
    <fullName>Report_Fee__c</fullName>
    <label>Report Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed, Generate Accrual</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/recordTypes/Cancelled.recordType-meta.xml
<RecordType>
    <fullName>Cancelled</fullName>
    <active>true</active>
    <description>Record type for cancelled Positions</description>
    <label>Cancelled</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <inlineHelpText>Case Number</inlineHelpText>
    <label>Engagement Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email__c</fullName>
    <formula>Primary_External_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c, &quot;Closed&quot;), &quot;Closed&quot;,
IF(ISPICKVAL(Stage__c, &quot;Hold&quot;), &quot;Hold&quot;,
IF(ISPICKVAL(Stage__c, &quot;Dead&quot;), &quot;Dead&quot;,
&quot;Active&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Transaction_Description__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Description__c</fullName>
    <inlineHelpText>Please enter a description of the transaction for this deal.</inlineHelpText>
    <label>Engagement Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HL_EngValuationPeriodPositions.cls
public  with sharing class HL_EngValuationPeriodPositions {
    public static List<Eng_VP_Position__c> GetEngVPPosition(Id id){
        // commented Industry_Group_Picklist__c from below
        return [SELECT Engagement_VP__c, Company__r.Name, Report_Fee__c,Asset_Classes__c,Industry_Group__c FROM Eng_VP_Position__c WHERE Engagement_VP__c =: id  AND Status__c != 'Cancelled' AND (Report_Fee__c > 0) ORDER BY Company__r.Name ASC];
    }
    
    public static Eng_VP__c GetById(Id id){
        List<Eng_VP__c> EngVPList = Database.Query(GetFullSelect() + 
                                          ', Engagement__r.Transaction_Description__c, Engagement__r.Engagement_Number__c, Engagement__r.Primary_Contact_Email__c, Engagement__r.Primary_Contact_Title__c, Engagement__r.Primary_External_Contact__r.Name, Engagement__r.Client__r.Name, Engagement__r.Client_Number__c, Engagement__r.Opportunity_Number__c, Engagement__r.Client_Billing_Address__c, Engagement__r.Retainer__c FROM Eng_VP__c ' + 
                                          ' WHERE Id =: Id');
        return EngVPList.size() > 0 ? EngVPList[0] : null;
    }
    
    
    public static string GetFullSelect(){
        Map<String, Schema.SObjectField> fldObjMap = schema.SObjectType.Eng_VP__c.fields.getMap();
        List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
        String q = 'SELECT ';
        // Build dynamic query string
        for(Schema.SObjectField s : fldObjMapValues)
        q += s.getDescribe().getName() + ',';
        // Trim last comma
        q = q.subString(0, q.length() - 1);
        return q + ' ';
    }
}