force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Academic Research &amp; IP</fullName>
            </value>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Airlines/Air Cargo</fullName>
            </value>
            <value>
                <fullName>Ambulatory Surgical Centers</fullName>
            </value>
            <value>
                <fullName>Analytics &amp; Big Data</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automotive &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Autonomous Systems</fullName>
            </value>
            <value>
                <fullName>Behavioral &amp; Labs</fullName>
            </value>
            <value>
                <fullName>Broker Dealers</fullName>
            </value>
            <value>
                <fullName>Building Products</fullName>
            </value>
            <value>
                <fullName>Business Management Software</fullName>
            </value>
            <value>
                <fullName>Capital Goods</fullName>
            </value>
            <value>
                <fullName>CBD/Cannabis</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Commercial Financial Co.</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Infrastructure Components</fullName>
            </value>
            <value>
                <fullName>Communications Solutions</fullName>
            </value>
            <value>
                <fullName>Company &amp; Market Intelligence</fullName>
            </value>
            <value>
                <fullName>Consumer/Non-Mortgage Finance Co.</fullName>
            </value>
            <value>
                <fullName>Consumer Products</fullName>
            </value>
            <value>
                <fullName>Customer Information Management</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Data &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>Data Centers</fullName>
            </value>
            <value>
                <fullName>Dealership &amp; Rental Services</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ERP_Invoice_Detail__c/ERP_Invoice_Detail__c.object-meta.xml
<CustomObject>
    <description>This will store the invoice details, sent from the ERP application</description>
    <label>ERP Invoice Detail</label>
    <nameField>
        <displayFormat>ID-{YYYY}{MM}-{0}</displayFormat>
        <label>ERP Invoice Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Invoice Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERP_Invoice_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>ERP Invoice Details</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/Opp_VP__c.object-meta.xml
<CustomObject>
    <label>Opportunity Valuation Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Valuation Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_VP__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Opportunity record</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity_Portfolio_Valuations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Opportunity__c , Opportunity__r.Opportunity_Number__c , &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_VP_Position__c/Opp_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Opportunity Valuation Period Positions linked with Opportunity and Companies</description>
    <label>Opp Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opp Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_VP_Position__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Company</description>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Houlihan_Company</value>
        </filterItems>
        <filterItems>
            <field>Account.Id</field>
            <operation>notEqual</operation>
            <value>001i000001T7e9v</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opp_PV_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_VP_Position__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;  Opportunity_VP__r.Opportunity__c  ,  Opportunity_VP__r.Opportunity__r.Opportunity_Number__c  , &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_VP_Position__c/fields/Opportunity_VP__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_VP__c</fullName>
    <description>Related Opportunity</description>
    <label>Opportunity Valuation Period</label>
    <referenceTo>Opp_VP__c</referenceTo>
    <relationshipName>Opp_VP_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Opp_VP_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process__c</fullName>
    <label>Approval Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DND</fullName>
            </value>
            <value>
                <fullName>CONVERSION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Converted_to_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Engagement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is checked when an opportunity is converted into an engagement.  Validation rules on the conversion to Engagement should, in addition to their execution logic, check if this box is checked.</description>
    <label>Converted to Engagement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Engagement_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Approval_Status__c</fullName>
    <label>Engagement Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Requesting Engagement Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( RecordType.Name = &apos;FR&apos;, 
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
&apos;Active&apos;)))),

IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
&apos;Active&apos;)))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_OppVPPositionNewController.cls
public without sharing class HL_OppVPPositionNewController {
    
    Public Opp_VP_Position__c OppVPPositon {get; set;}
    Public List<Opportunity__c> OppList {get; set;}
	Public Account selectedAcc {get; set;}
    public Boolean isValidPVUser{get;set;}
    public Boolean IshavingValidRoleForRevAccrual{get;set;}
    //This parameter is determining for Opportunity conversion status or for status of Request  Engagement Number on opportunity
    public Boolean isOpportunityConverted {get;set;}
    public string MessageToShow{get;set;}
    
    public HL_OppVPPositionNewController(ApexPages.StandardController controller) {
        MessageToShow = '';
        OppVPPositon = new Opp_VP_Position__c();
        OppList = new List<Opportunity__c>();
        OppVPPositon = (Opp_VP_Position__c) controller.getRecord(); 
        OppVPPositon.Opportunity_VP__c = apexpages.currentPage().getParameters().get('VPId');   
        OppVPPositon.Status__c = 'In Progress';
        Opportunity__c Opp = new Opportunity__c();
        isOpportunityConverted  = false;
        for(Opp_VP__c opVP : [Select Opportunity__c, Opportunity__r.Converted_to_Engagement__c, Opportunity__r.Approval_Process__c, Opportunity__r.Engagement_Approval_Status__c  From Opp_VP__c Where Id =: OppVPPositon.Opportunity_VP__c])
        {
            Opp.id = opVP.Opportunity__c;
            isOpportunityConverted = opVP.Opportunity__r.Converted_to_Engagement__c;
            MessageToShow = Label.HL_OppPV_Is_Locked_NewPosition;
            if(opVP.Opportunity__r.Approval_Process__c == label.HL_AppProcessForEngNo && opVP.Opportunity__r.Engagement_Approval_Status__c == label.HL_Pending_EngReqNo)
            {
                isOpportunityConverted = true;
                MessageToShow = Label.HL_OppPV_Is_Locked_NewPosition_EngNoReqsted;
            }
        }
        if(Opp != null && Opp.id != null ){
            OppList = [Select Id, Client__c,Opportunity_Number__c From Opportunity__c Where Id =: Opp.id];
            isValidPVUser = HL_OpportunityViewController.VerifyUserforVP(Opp, 'PVPositionCreation');
            IshavingValidRoleForRevAccrual = HL_ConstantsUtil.IshavingValidRoleInInternTeamOpp(Opp.id); 
        }
    }
	
	//To get IG&S of associated Company
    public void CompanyIGSvalues(){
        if(OppVPPositon.Company__c != null){
            selectedAcc = [SELECT id,Industry_Group__c,Sector__c from Account WHERE id=:OppVPPositon.Company__c];
        }
    }
    
    public PageReference SaveData() {
        
		CompanyIGSvalues();
        try{ 
			if(((selectedAcc.Industry_Group__c == null || selectedAcc.Industry_Group__c == '') || (selectedAcc.Sector__c == null || selectedAcc.Sector__c == '')) && 
			   ((OppVPPositon.Industry_Group_Picklist__c == null || OppVPPositon.Industry_Group_Picklist__c == '') || (OppVPPositon.Sector__c == null || OppVPPositon.Sector__c == ''))){
				
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,Label.HL_No_IG_S_on_Position));
				return null;
			}
			
			
			if((selectedAcc.Industry_Group__c != null && selectedAcc.Industry_Group__c != '') && (selectedAcc.Sector__c != null && selectedAcc.Sector__c != '') &&
				(OppVPPositon.Industry_Group_Picklist__c == null || OppVPPositon.Industry_Group_Picklist__c == '') && (OppVPPositon.Sector__c == null || OppVPPositon.Sector__c == '')){
				
				OppVPPositon.Industry_Group_Picklist__c = selectedAcc.Industry_Group__c;
				OppVPPositon.Sector__c = selectedAcc.Sector__c;
			}
			
            insert OppVPPositon; 
            return new pageReference('/'+ apexpages.currentPage().getParameters().get('VPId'));
        }
        catch(Exception e) {
            Apexpages.addMessages(e);
            //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,e.getmessage()));
            return null;
        }       
        
    }
}