force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <inlineHelpText>Case Number</inlineHelpText>
    <label>Engagement Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Exclude_From_Reversal__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Reversal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude From Reversal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Exclusion_Comment__c.field-meta.xml
<CustomField>
    <fullName>Exclusion_Comment__c</fullName>
    <inlineHelpText>Please provide a reason for exclusion from reversal.</inlineHelpText>
    <label>Exclusion Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_of_Business__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activism Advisory</fullName>
            </value>
            <value>
                <fullName>Board Advisory Services (BAS)</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Buyside &amp; Financing Advisory</fullName>
            </value>
            <value>
                <fullName>Collateral Valuation</fullName>
            </value>
            <value>
                <fullName>Compensation/Formula Analysis</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Corporate Alliances</fullName>
            </value>
            <value>
                <fullName>Creditor Advisors</fullName>
            </value>
            <value>
                <fullName>CVAS - Forensic Services</fullName>
            </value>
            <value>
                <fullName>CVAS - FV Opinion</fullName>
            </value>
            <value>
                <fullName>CVAS - Goodwill or Asset Impairment</fullName>
            </value>
            <value>
                <fullName>CVAS - Pre-Acq Val&apos;n Cons</fullName>
            </value>
            <value>
                <fullName>CVAS - Purchase Price Allocation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 123R/409A Stock, Option Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 133 Derivatives, Liabilities Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Sovereign Advisory</fullName>
            </value>
            <value>
                <fullName>CVAS - Tangible Asset Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Tax Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Transfer Pricing</fullName>
            </value>
            <value>
                <fullName>Debt Advisory</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Advisors</fullName>
            </value>
            <value>
                <fullName>Discretionary Advisory</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Buyside</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Sellside</fullName>
            </value>
            <value>
                <fullName>DRC - Ad Valorem Services</fullName>
            </value>
            <value>
                <fullName>DRC - Appointed Arbitrator/Mediator</fullName>
            </value>
            <value>
                <fullName>DRC - Contract Compliance</fullName>
            </value>
            <value>
                <fullName>DRC - Exp Cons-Arbitrat&apos;n</fullName>
            </value>
            <value>
                <fullName>Sellside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Percentage_of_Completion__c.field-meta.xml
<CustomField>
    <fullName>Percentage_of_Completion__c</fullName>
    <label>Percentage of Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Primary_Office__c.field-meta.xml
<CustomField>
    <fullName>Primary_Office__c</fullName>
    <label>Primary Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Settlement or Agreement Reached</fullName>
            </value>
            <value>
                <fullName>Book Prep/Underwriting</fullName>
            </value>
            <value>
                <fullName>In Market</fullName>
            </value>
            <value>
                <fullName>Received Indications of Interest</fullName>
            </value>
            <value>
                <fullName>Pre-LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Rec&apos;d Indications/Submitted Bid</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed Term Sheets</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Pending Regulatory Approval</fullName>
            </value>
            <value>
                <fullName>Verbally Retained</fullName>
            </value>
            <value>
                <fullName>Performing Analysis</fullName>
            </value>
            <value>
                <fullName>Ongoing Analysis</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Testimony</fullName>
            </value>
            <value>
                <fullName>Opinion Report</fullName>
            </value>
            <value>
                <fullName>Opinion Development</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Delivered Report</fullName>
            </value>
            <value>
                <fullName>Bill/File</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Total_Estimated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimated_Fee__c</fullName>
    <label>Total Estimated Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Engagement__c/recordTypes/Sellside.recordType-meta.xml
<RecordType>
    <fullName>Sellside</fullName>
    <active>true</active>
    <label>Sellside</label>
</RecordType>

force-app/main/default/objects/Engagement_Allocation__c/Engagement_Allocation__c.object-meta.xml
<CustomObject>
    <label>Engagement Allocations</label>
    <nameField>
        <label>Engagement Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Allocations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Allocation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Allocations</relationshipLabel>
    <relationshipName>ENGAGEMENT_ALLOCATIONS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_EngagementAllocationHandler.cls
@isTest
private class Test_HL_EngagementAllocationHandler {

    private static Account clientAccount;
    private static Account subjectAccount;
    private static Engagement__c engagementCF;
    private static Engagement_Allocation__c engagementAllocation;

    @testSetup static void loadTestData() {
        // Generate Test Data
        string engagementNameCF = 'Test CF Engagement';
        string engagementNumberCF = '80001';
        string engagementStageCF = 'Signed LOI/Due Diligence';
        string jobTypeCF = 'Sellside';
        string engagementRecordTypeIdCF = '012i0000000tIWwAAM';
        string primaryOfficeCF = 'NY';
        
        string engagementAllocationName = 'Test Engagement Allocation Name';
        string engagementAllocationInustryGrp = 'HC - Healthcare';
        Decimal engagementAllocationInustryGrpFee = 12.22;
        string engagementAllocationProdSpecial = 'TAS- TAX';//'Generalist/REVS';
        Decimal engagementAllocationProdSpecialFee = 200.11;

        
        clientAccount = (Account)HL_TestFactory.CreateSObject('Account', false);
        subjectAccount = (Account)HL_TestFactory.CreateSObject('Account', false);
        engagementCF = New Engagement__c(Name = engagementNameCF
                                        ,Engagement_Number__c = engagementNumberCF
                                        ,Client__c = clientAccount.Id
                                        ,Subject__c = subjectAccount.Id
                                        ,Stage__c = engagementStageCF
                                        ,Line_of_Business__c = 'CF'
                                        ,Job_Type__c = jobTypeCF
                                        ,RecordTypeId = engagementRecordTypeIdCF
                                        ,Primary_Office__c = primaryOfficeCF
                                        ,Total_Estimated_Fee__c = 0
                                        ,Percentage_of_Completion__c = 1
                                        ,Exclude_From_Reversal__c = true
                                        ,Exclusion_Comment__c = 'Excluded for testing');
        
        engagementAllocation = new Engagement_Allocation__c(Name = engagementAllocationName,
                                                            Industry_Group__c = engagementAllocationInustryGrp,
                                                            Industry_Group_Fee__c = engagementAllocationInustryGrpFee,
                                                            Product_Specialty__c = engagementAllocationProdSpecial,
                                                            Product_Specialty_Fee__c = engagementAllocationProdSpecialFee
                                        
                                        );
        
        
        insert clientAccount;
        insert subjectAccount;
        insert engagementCF;
        
        engagementAllocation.Engagement__c = engagementCF.Id;
        
        insert engagementAllocation;
        
        
        
        
    }
    
    @isTest
    private static void TestInsertEngagementAllocationRecord()
    {
        // Confirm that Engagement Allocation record was created successfully
        System.assertEquals([Select Id From Engagement_Allocation__c].Size(), 1);
        
        Engagement_Allocation__c engagementAllocation = [Select Id,Line_of_Business__c From Engagement_Allocation__c];

        System.assertEquals(engagementAllocation.Line_of_Business__c,'CF');
    }        
}