force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Date_Engaged__c.field-meta.xml
<CustomField>
    <fullName>Date_Engaged__c</fullName>
    <description>Changed by AYU 2/28, should be mapped to SLX&apos;s Engagement Letter Received.</description>
    <inlineHelpText>Date on Engagement Letter</inlineHelpText>
    <label>Date Engaged</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <inlineHelpText>Case Number</inlineHelpText>
    <label>Engagement Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_of_Business__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activism Advisory</fullName>
            </value>
            <value>
                <fullName>Board Advisory Services (BAS)</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Buyside &amp; Financing Advisory</fullName>
            </value>
            <value>
                <fullName>Collateral Valuation</fullName>
            </value>
            <value>
                <fullName>Compensation/Formula Analysis</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Corporate Alliances</fullName>
            </value>
            <value>
                <fullName>Creditor Advisors</fullName>
            </value>
            <value>
                <fullName>CVAS - Forensic Services</fullName>
            </value>
            <value>
                <fullName>CVAS - FV Opinion</fullName>
            </value>
            <value>
                <fullName>CVAS - Goodwill or Asset Impairment</fullName>
            </value>
            <value>
                <fullName>CVAS - Pre-Acq Val&apos;n Cons</fullName>
            </value>
            <value>
                <fullName>CVAS - Purchase Price Allocation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 123R/409A Stock, Option Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 133 Derivatives, Liabilities Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Sovereign Advisory</fullName>
            </value>
            <value>
                <fullName>CVAS - Tangible Asset Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Tax Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Transfer Pricing</fullName>
            </value>
            <value>
                <fullName>Debt Advisory</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Advisors</fullName>
            </value>
            <value>
                <fullName>Discretionary Advisory</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Buyside</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Sellside</fullName>
            </value>
            <value>
                <fullName>DRC - Ad Valorem Services</fullName>
            </value>
            <value>
                <fullName>DRC - Appointed Arbitrator/Mediator</fullName>
            </value>
            <value>
                <fullName>DRC - Contract Compliance</fullName>
            </value>
            <value>
                <fullName>DRC - Exp Cons-Arbitrat&apos;n</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Opportunity Number for merge templates - ayu</description>
    <formula>Opportunity__r.Opportunity_Number__c</formula>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Settlement or Agreement Reached</fullName>
            </value>
            <value>
                <fullName>Book Prep/Underwriting</fullName>
            </value>
            <value>
                <fullName>In Market</fullName>
            </value>
            <value>
                <fullName>Received Indications of Interest</fullName>
            </value>
            <value>
                <fullName>Pre-LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Rec&apos;d Indications/Submitted Bid</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed Term Sheets</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Pending Regulatory Approval</fullName>
            </value>
            <value>
                <fullName>Verbally Retained</fullName>
            </value>
            <value>
                <fullName>Performing Analysis</fullName>
            </value>
            <value>
                <fullName>Ongoing Analysis</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Testimony</fullName>
            </value>
            <value>
                <fullName>Opinion Report</fullName>
            </value>
            <value>
                <fullName>Opinion Development</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Delivered Report</fullName>
            </value>
            <value>
                <fullName>Bill/File</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Client_Subject__c/Engagement_Client_Subject__c.object-meta.xml
<CustomObject>
    <description>JUNCTION OBJECT: Custom object to track additional clients and subjects for an engagement.</description>
    <label>Engagement Client/Subject</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Clients/Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Client_Subject__c/fields/Client_Subject__c.field-meta.xml
<CustomField>
    <fullName>Client_Subject__c</fullName>
    <inlineHelpText>Client: parties which signed/acceded to HL&apos;s EL (or are anticipated to do so). 
Subject: underlying company</inlineHelpText>
    <label>Client/Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Clients/Subjects</relationshipLabel>
    <relationshipName>Engagement_Clients_Subjects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_Client_Subject__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Additional Clients/Subjects</relationshipLabel>
    <relationshipName>Engagement_Clients_Subjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Type__c/Job_Type__c.object-meta.xml
<CustomObject>
    <label>Job Type</label>
    <nameField>
        <label>JOB TYPE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HL_CompanyRelatedEngagementsController.cls
public with sharing class HL_CompanyRelatedEngagementsController {
    public Account Account {get; set;}
    public ApexPages.StandardSetController setCon {
		 get{
             if(setCon == null){
                setCon = new ApexPages.StandardSetController([SELECT Name, Client__r.Name, Subject__r.Name, Line_of_Business__c, Job_Type__c, Industry_Group__c, Stage__c, LastModifiedDate, Date_Engaged__c, Close_Date__c, Engagement_Number__c, Opportunity_Number__c FROM Engagement__c WHERE ID IN (SELECT Engagement__c FROM Engagement_Client_Subject__c WHERE Client_Subject__c =: Account.ID)
                                                              ORDER BY Date_Engaged__c DESC]);
                setCon.setPageSize(5);
             }
            
             return setCon;
        }set;         
    }
    
    public List<Engagement__c> GetEngList(){
        return setCon.getRecords();
    }
    public HL_CompanyRelatedEngagementsController(ApexPages.StandardController controller){
        Account = (Account)controller.getRecord();
    }
}