force-app/main/default/objects/Industry__c/Industry__c.object-meta.xml
<CustomObject>
    <description>Store the Industries</description>
    <label>Industry</label>
    <nameField>
        <label>Industry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template__c/Offsite_Template__c.object-meta.xml
<CustomObject>
    <label>Offsite Template</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Offsite Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offsite Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/Offsite_Template_Investment_Company__c.object-meta.xml
<CustomObject>
    <label>Offsite Template Investment Company</label>
    <nameField>
        <displayFormat>OT.Investment-{00000}</displayFormat>
        <label>Offsite Template Investment Company Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offsite Template Investment Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/HL_Industry__c.field-meta.xml
<CustomField>
    <fullName>HL_Industry__c</fullName>
    <description>HL&apos;s industry break down</description>
    <label>HL Industry Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Include__c.field-meta.xml
<CustomField>
    <fullName>Include__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Include</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>FROM CAPIQ</description>
    <label>CAPIQ Industry</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Investment_Company__c.field-meta.xml
<CustomField>
    <fullName>Investment_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Company</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Offsite Template Investment Companies</relationshipLabel>
    <relationshipName>Offsite_Template_Investment_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Investment_Date__c.field-meta.xml
<CustomField>
    <fullName>Investment_Date__c</fullName>
    <label>Investment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/LTM_MM_EBITDA__c.field-meta.xml
<CustomField>
    <fullName>LTM_MM_EBITDA__c</fullName>
    <label>LTM MM EBITDA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/LTM_MM_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LTM_MM_Revenue__c</fullName>
    <label>LTM MM Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Offsite_Template__c.field-meta.xml
<CustomField>
    <fullName>Offsite_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offsite Template</label>
    <referenceTo>Offsite_Template__c</referenceTo>
    <relationshipLabel>Offsite Template Investment Companies</relationshipLabel>
    <relationshipName>Offsite_Template_Investment_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <formula>Investment_Company__r.Portfolio_CapIQ_Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portfolio Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prospect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offsite_Template_Investment_Company__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Potential Opportunity</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M&amp;A</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_HL_OTICListController.cls
@isTest
private class Test_HL_OTICListController {
	@isTest private static void TestBasicFunctionality() {
		 //Setup the Test Data
		 List<Offsite_Template__c> otList = SL_TestSetupUtils.CreateOffsiteTemplateDataWithRelated(1,5);
		 List<Offsite_Template_Investment_Company__c> otiList = [SELECT Industry__c, Description__c, HL_Industry__c, Include__c, Investment_Company__c, Investment_Date__c, LTM_MM_EBITDA__c, LTM_MM_Revenue__c, Offsite_Template__c, Portfolio_Company__c, Prospect__c, Service__c, Status__c FROM Offsite_Template_Investment_Company__c WHERE Offsite_Template__c =: otList[0].Id];		 
		 ApexPages.StandardSetController sc = new ApexPages.StandardSetController(otiList);
		 sc.setSelected(otiList);
         //Test the controller functionality
		 Test.startTest();
		 	HL_OTICListController con = new HL_OTICListController(sc);
        	con.updateInclude();
        	con.updateInvestments();
        	con.cancel();
        	con.getInvestments();
            con.SortField = 'Investment_Company__c';
            con.Filter();
            con.Next();
            con.Previous();
		 Test.stopTest();
         //Validate no page errors
		 System.assert(!ApexPages.hasMessages(ApexPages.Severity.ERROR));
	}
}