force-app/main/default/objects/Time_Record__c/Time_Record__c.object-meta.xml
<CustomObject>
    <description>Used to track time records</description>
    <label>Time Record</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Time Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record__c/fields/Time_Record_Period_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period_Staff_Member__c</fullName>
    <description>Related time record period staff member record</description>
    <label>Time Record Period Staff Member</label>
    <referenceTo>Time_Record_Period_Staff_Member__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/recordTypes/Litigation.recordType-meta.xml
<RecordType>
    <fullName>Litigation</fullName>
    <active>true</active>
    <description>Litigation Time Tracking Record</description>
    <label>Litigation</label>
</RecordType>

force-app/main/default/objects/Time_Record_Period__c/Time_Record_Period__c.object-meta.xml
<CustomObject>
    <description>Time record periods</description>
    <label>Time Record Period</label>
    <nameField>
        <displayFormat>TRP-{00000000}</displayFormat>
        <label>Time Record Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/Time_Record_Period_Staff_Member__c.object-meta.xml
<CustomObject>
    <label>Time Record Period Staff Member</label>
    <nameField>
        <displayFormat>TRPSM-{00000000}</displayFormat>
        <label>Time Record Period Staff Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Period Staff Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Time_Record_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period__c</fullName>
    <description>Related time record period record</description>
    <label>Time Record Period</label>
    <referenceTo>Time_Record_Period__c</referenceTo>
    <relationshipLabel>Time Record Period Staff Members</relationshipLabel>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_HL_TimeRecordPeriodSMController.cls
@isTest
private class Test_HL_TimeRecordPeriodSMController {
    @isTest private static void TestGetCurrentRecord(){
        Time_Record__c tr = SL_TestSetupUtils.CreateTimeRecordsWithRelated(1, 'Litigation')[0];
        
        Test.startTest();
        	Time_Record_Period_Staff_Member__c trpsm = HL_TimeRecordPeriodStaffMemberController.GetCurrentRecord('Litigation');
        Test.stopTest();
        
        //Validate the result
        System.assertEquals(tr.Time_Record_Period_Staff_Member__c, trpsm.Id);
    }
    
    @isTest private static void TestGetByPeriod(){
        Time_Record__c tr = SL_TestSetupUtils.CreateTimeRecordsWithRelated(1, 'Litigation')[0];

        Test.startTest();
        	List<Time_Record_Period_Staff_Member__c> trpsm = HL_TimeRecordPeriodStaffMemberController.GetByPeriod('Litigation', tr.Time_Record_Period_Staff_Member__r.Time_Record_Period__c);
        	List<Time_Record_Period_Staff_Member__c> trpsmNoPeriod = HL_TimeRecordPeriodStaffMemberController.GetByPeriod('Litigation', null);
        Test.stopTest();
        
        //Validate results are returned
        System.assert(trpsm != null);
        System.assert(trpsmNoPeriod != null);
    }

    @isTest private static void TestGetCategory(){
        Test.startTest();
        	String category = HL_TimeRecordPeriodStaffMemberController.GetCategory();
        Test.stopTest();
        
        //Validate a category is returned or blank if user is not assigned
        System.assert(category != null);
    }
}