force-app/main/default/objects/SL_RacetrackReport__c/SL_RacetrackReport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to set the parameter of the Racetrack report!</description>
    <label>SL_RacetrackReport</label>
</CustomObject>

force-app/main/default/objects/SL_RacetrackReport__c/fields/ChildObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ChildObjectAPIName__c</fullName>
    <description>This field is used to store the child object API name</description>
    <inlineHelpText>This field is used to store the child object API name</inlineHelpText>
    <label>ChildObjectAPIName</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/FieldSetAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldSetAPIName__c</fullName>
    <description>This field is used to store the field set name.</description>
    <inlineHelpText>This field is used to store the field set name.</inlineHelpText>
    <label>FieldSetAPIName</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/GroupingObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>GroupingObjectAPIName__c</fullName>
    <description>This field is used to store the grouping object name by which the grouping will done.</description>
    <inlineHelpText>This field is used to store the grouping object name by which the grouping will done.</inlineHelpText>
    <label>GroupingObjectAPIName</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/GroupingObjectRelationshipAPIName__c.field-meta.xml
<CustomField>
    <fullName>GroupingObjectRelationshipAPIName__c</fullName>
    <description>This field is used to store the relationship name of the Grouping Object on child object.</description>
    <inlineHelpText>This field is used to store the relationship name of the Grouping Object on child object.</inlineHelpText>
    <label>GroupingObjectRelationshipAPIName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <description>This will store the URL of the logo document.</description>
    <inlineHelpText>This will store the URL of the logo document.</inlineHelpText>
    <label>Logo URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/ParentObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ParentObjectAPIName__c</fullName>
    <description>This filed is used to store the parent object API name.</description>
    <inlineHelpText>This filed is used to store the parent object API name.</inlineHelpText>
    <label>ParentObjectAPIName</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/ParentObjectRelationshipAPIName__c.field-meta.xml
<CustomField>
    <fullName>ParentObjectRelationshipAPIName__c</fullName>
    <description>This field is used to store the Parent Object Relationship API Name on child object.</description>
    <inlineHelpText>This field is used to store the Parent Object Relationship API Name on child object.</inlineHelpText>
    <label>ParentObjectRelationshipAPIName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/Show_Filter__c.field-meta.xml
<CustomField>
    <fullName>Show_Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Filter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SL_RacetrackReport__c/fields/ShowExtraGroupOption__c.field-meta.xml
<CustomField>
    <fullName>ShowExtraGroupOption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowExtraGroupOption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SL_Test_RacetrackReport.cls
/** 
* \arg ClassName      : SL_Test_RacetrackReport
* \arg JIRATicket     : HL-8,9,10
* \arg CreatedOn      : 13/MAY/2014
* \arg LastModifiedOn : 13/MAY/2014
* \arg CreatededBy    : Lodhi
* \arg ModifiedBy     : -
* \arg Description    : Test class for SL_RacetrackReport.cls
*/

@isTest
private class SL_Test_RacetrackReport 
{
    private static testmethod void  test_RacetrackReport() 
    {

        
        List<Account> lstAccount = new List<Account>();
        
        lstAccount.add(new Account(Name='Acc 1'));
        lstAccount.add(new Account(Name='Acc 2'));
        lstAccount.add(new Account(Name='Acc 3'));

        insert lstAccount; 
        
        
        List<Opportunity> lstEC = new  List<Opportunity>();
        for(Opportunity objEC : SL_Test_RacetrackReport.CreateEC('Opp NN1 ', lstAccount[0].Id, 5))
        {
            objEC.OwnerID = UserInfo.getUserId();
            lstEC.add(objEC);
        }
        
        for(Opportunity objEC : SL_Test_RacetrackReport.CreateEC('Opp NN2 ', lstAccount[0].Id, 5))
        {
            objEC.OwnerID = UserInfo.getUserId();
            lstEC.add(objEC);
        }
        
        for(Opportunity objEC : SL_Test_RacetrackReport.CreateEC('Opp NN3 ', lstAccount[0].Id, 5))
        {
            objEC.OwnerID = UserInfo.getUserId();
            lstEC.add(objEC);
        }
        insert lstEC;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('parentId',String.valueOf(lstAccount[0].Id));
        ApexPages.currentPage().getParameters().put('cs','default');
        
        SL_RacetrackReport objRR = new SL_RacetrackReport();
        objRR.getSearchCompParams();


        SL_RacetrackReport__c objRRCustomSetting = new SL_RacetrackReport__c( Name = 'default', 
                                                                              ChildObjectAPIName__c = 'Opportunity',
                                                                              FieldSetAPIName__c = 'SL_OppRacetrackReport',
                                                                              GroupingObjectAPIName__c = 'Account',
                                                                              GroupingObjectRelationshipAPIName__c ='AccountID',   
                                                                              Logo_URL__c = 'https://google.com',
                                                                              ParentObjectAPIName__c = 'User', 
                                                                              ParentObjectRelationshipAPIName__c = 'OwnerId',
                                                                              ShowExtraGroupOption__c = true,
                                                                              Show_Filter__c = true);
       
        
        insert objRRCustomSetting;
        
        objRR = new SL_RacetrackReport();

        
        String strTmp = '';
        SL_RacetrackReport.RecordWrapper recWr = new SL_RacetrackReport.RecordWrapper('Name',lstAccount[0],'Acc 1');
        Sobject sObj = recWr.sObj;
        strTmp = recWr.strRT;
        strTmp = recWr.companyName;
        
        List<SL_RacetrackReport.RecordWrapper> lstRw = new List<SL_RacetrackReport.RecordWrapper>();
        lstRw.add(recWr);
        SL_RacetrackReport.GroupWrapper grWr = new SL_RacetrackReport.GroupWrapper('Name', lstRw, new Map<String, Integer>{'Name'=>10});

        strTmp = grWr.strRT;
        grWr.lstRecordWrapper = lstRw;
        grWr.mapSubTotal = new Map<String, Integer>{'Name'=>5};
        strTmp = objRR.getCurrentDateTime();
         strTmp = objRR.formatDate('2011/10/10');
        
        
        //objRR.engagementCounterparty.OwnerID = UserInfo.getUserId();
        objRR.getGroupByOptions();
        objRR.getCurrentDateTime();
        objRR.getSortingOption();
        objRR.getStageOptions();
        objRR.generateReport();
        
        //objRR.strChildObject = 'Opportunity';
        objRR.inRecordFiltersCols = '';
        objRR.inRecordFiltersAdv = '';
        objRR.generateReport();
        
        
        
        //objRR.isFilter = true;
        objRR.generateReport();
        //objRR.lstPicklistWrapperL[0].selectedValues = new List<String>();
        /*
        objRR.lstSelectedStage = new List<String>{'Book_Returned__c', 'Closing_Round_Bid_Date__c', 'Confidentiality_Agreement__c', 
                                                  'Final_Round_Bid_Date__c','Deal_Ranking__c', 'Declined_Passed__c'};
        */
        objRR.strGroupBy = 'Account:Name';
        objRR.strSortBy = 'Name';
        objRR.generateReport();
        objRR.strGroupBy = 'Account:REFERENCE';
        objRR.generateReport();
        objRR.strGroupBy = 'Account.OwnerId:REFERENCE';
        objRR.generateReport();
        //objRR.lstPicklistWrapperL[0].selectedValues = new List<String>{'A', 'B', 'C'};
        //objRR.generateReport();
        Test.stopTest();
    }
    
    public static List<Opportunity> CreateEC(String basename, ID inAccID, Integer inCount)
	{
		List<Opportunity> results = new List<Opportunity>();
		
		for(Integer x = 0; x< inCount; x++)
		{
			Opportunity objEC = new Opportunity(Name=basename+' '+x, AccountId=inAccID, CloseDate=Date.today(),StageName='Qualification');
			results.add(objEC);
		}
		return results;
	}
    
}