force-app/main/default/objects/Job_Type__c/Job_Type__c.object-meta.xml
<CustomObject>
    <label>Job Type</label>
    <nameField>
        <label>JOB TYPE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Type__c/fields/Has_Multiple_Deliverables__c.field-meta.xml
<CustomField>
    <fullName>Has_Multiple_Deliverables__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the deal has multiple deliverables, by default. If this is true, the accrual can be made according to the stage.</description>
    <inlineHelpText>Indicates if the deal has multiple deliverables, by default. If this is true, the accrual can be made according to the stage.</inlineHelpText>
    <label>Has Multiple Deliverables</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Type__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <externalId>true</externalId>
    <label>Job Code</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Type__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Capital Markets</fullName>
            </value>
            <value>
                <fullName>Consulting / InSource</fullName>
            </value>
            <value>
                <fullName>CVAS - Consulting / InSource</fullName>
            </value>
            <value>
                <fullName>CVAS - Corporate Valuation Advisory Services</fullName>
            </value>
            <value>
                <fullName>CVAS - Other</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>ESOP</fullName>
            </value>
            <value>
                <fullName>Estate &amp; Gift Tax</fullName>
            </value>
            <value>
                <fullName>Fairness, Negotiated Fairness, Solvency</fullName>
            </value>
            <value>
                <fullName>Fairness, Transaction Opinions</fullName>
            </value>
            <value>
                <fullName>Financial Restructuring - Creditor / Debtor</fullName>
            </value>
            <value>
                <fullName>Financial Restructuring - Other</fullName>
            </value>
            <value>
                <fullName>Fund Opinions</fullName>
            </value>
            <value>
                <fullName>Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Portfolio Valuation &amp; Advisory</fullName>
            </value>
            <value>
                <fullName>Private Funds Advisory</fullName>
            </value>
            <value>
                <fullName>Sellside</fullName>
            </value>
            <value>
                <fullName>Strategic Consulting</fullName>
            </value>
            <value>
                <fullName>TAS - Due Diligence Services</fullName>
            </value>
            <value>
                <fullName>Tech+IP Advisory</fullName>
            </value>
            <value>
                <fullName>Transaction Opinions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Type__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Capital Markets</fullName>
            </value>
            <value>
                <fullName>Consulting / InSource</fullName>
            </value>
            <value>
                <fullName>CVAS - Consulting / InSource</fullName>
            </value>
            <value>
                <fullName>CVAS - Corporate Valuation Advisory Services</fullName>
            </value>
            <value>
                <fullName>CVAS - Other</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Equity Capital Markets</fullName>
            </value>
            <value>
                <fullName>ESOP</fullName>
            </value>
            <value>
                <fullName>Estate &amp; Gift Tax</fullName>
            </value>
            <value>
                <fullName>FA - Fund Opinions-Fairness</fullName>
            </value>
            <value>
                <fullName>FA - Fund Opinions-Non-Fairness</fullName>
            </value>
            <value>
                <fullName>FA - Fund Opinions-Valuation</fullName>
            </value>
            <value>
                <fullName>Fairness, Negotiated Fairness, Solvency</fullName>
            </value>
            <value>
                <fullName>Fairness, Transaction Opinions</fullName>
            </value>
            <value>
                <fullName>Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>Liability Management</fullName>
            </value>
            <value>
                <fullName>Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Portfolio Valuation &amp; Advisory</fullName>
            </value>
            <value>
                <fullName>Private Funds Advisory</fullName>
            </value>
            <value>
                <fullName>Sellside</fullName>
            </value>
            <value>
                <fullName>Syndicated Finance</fullName>
            </value>
            <value>
                <fullName>TAS - Due Diligence Services</fullName>
            </value>
            <value>
                <fullName>Tech+IP Advisory</fullName>
            </value>
            <value>
                <fullName>Transaction Opinions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Type__c/fields/Product_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Type_Code__c</fullName>
    <label>Product Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00000</fullName>
            </value>
            <value>
                <fullName>ADV</fullName>
            </value>
            <value>
                <fullName>CVAS</fullName>
            </value>
            <value>
                <fullName>DR</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>FO</fullName>
            </value>
            <value>
                <fullName>FRCD</fullName>
            </value>
            <value>
                <fullName>FRO</fullName>
            </value>
            <value>
                <fullName>GEH</fullName>
            </value>
            <value>
                <fullName>GER</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>GNL</fullName>
            </value>
            <value>
                <fullName>M_A</fullName>
            </value>
            <value>
                <fullName>NFO</fullName>
            </value>
            <value>
                <fullName>OTH</fullName>
            </value>
            <value>
                <fullName>PFA</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>TIA</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_JobType.cls
/*
* Name: HL_JobType
* Created Date: 4/17/2015
* Description: Apex handler for Job_Type__c object
* Modified Date: 11/04/2019
* Description: Modified GetJobTypeMap() to retreive the following fields:
*              Product_Line__c, Product_Type__c, Product_Type_Code__c
*/

public class HL_JobType {
    private static Map<String, Job_Type__c> mapJobType;
    private static Map<String, Id> mapJobCode;

    static {
        mapJobType = new Map<String, Job_Type__c>();
        mapJobCode = new Map<String, Id>();

        for (Job_Type__c jobType : [
            SELECT Id, Name, Job_Code__c, Product_Line__c, Has_Multiple_Deliverables__c, 
            Is_Active__c, Product_Type__c, Product_Type_Code__c 
            FROM Job_Type__c]) {

            mapJobType.put(jobType.Name, jobType);
            mapJobCode.put(jobType.Name, jobType.Id);
        }
    }

    public static String GetJobCode(String jobType) {
        Job_Type__c jt = mapJobType.get(jobType);

        return (jt != null) ? jt.Job_Code__c : '';

        //List<Job_Type__c> jt = [SELECT Job_Code__c FROM Job_Type__c WHERE Name=:jobType LIMIT 1];
        //return jt.size() > 0 ? jt[0].Job_Code__c : '';
    }
    
    public static List<Job_Type__c> GetAll() {
        return mapJobType.values();

        //return [SELECT Name, Job_Code__c FROM Job_Type__c];
    }

    public static Map<String, Id> GetJobCodeMap() {
        return mapJobCode;
    }

    public static Map<String, Job_Type__c> GetJobTypeMap() {
        return mapJobType;
    }

    // GM Jan 6, 2022 - this implementation causes too many SOQL queries, moved to static initialization at top of class
/*    
    //This Map returns the Job Type Name with the Job Code
    public static Map<String, Id> GetJobCodeMap(){
         List<Job_Type__c> jobTypes = GetAll();
         Map<String, Id> mapJobCode = new Map<String, Id>();
         for(Job_Type__c jt : jobTypes)
                mapJobCode.put(jt.Name, jt.Id);
        return mapJobCode;
    }
*/    

    // GM Jan 6, 2022 - this implementation causes too many SOQL queries, moved to static initialization at top of class
/*
    //This Map returns the job type name and the Job Type sObject
    public static Map<String, Job_Type__c> GetJobTypeMap(){
         Map<String, Job_Type__c> mapJobType = new Map<String, Job_Type__c>();
         for (Job_Type__c jobType : [SELECT Id, Name, Job_Code__c,Product_Line__c, Has_Multiple_Deliverables__c, Is_Active__c, Product_Type__c, Product_Type_Code__c FROM Job_Type__c])
             mapJobType.put(jobType.Name, jobType);
        return mapJobType;
    }
*/    
}