force-app/main/default/objects/Approval_Object__c/Approval_Object__c.object-meta.xml
<CustomObject>
    <label>Approval Object</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Approval Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Object__c/fields/Base_Object__c.field-meta.xml
<CustomField>
    <fullName>Base_Object__c</fullName>
    <externalId>true</externalId>
    <label>Base Object</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Approval_Object__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Object__c/fields/Master_Detail_Field__c.field-meta.xml
<CustomField>
    <fullName>Master_Detail_Field__c</fullName>
    <label>Master-Detail Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Page__c/Approval_Page__c.object-meta.xml
<CustomObject>
    <label>Approval Page</label>
    <nameField>
        <label>Approval Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Page__c/fields/Approval_Object__c.field-meta.xml
<CustomField>
    <fullName>Approval_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Object</label>
    <referenceTo>Approval_Object__c</referenceTo>
    <relationshipLabel>Approval Pages</relationshipLabel>
    <relationshipName>Approval_Pages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Page__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Approval_Properties__c/Approval_Properties__c.object-meta.xml
<CustomObject>
    <label>Approval Properties</label>
    <nameField>
        <label>Approval Properties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Properties__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Properties__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>FRG</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Properties__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Approval_Properties__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <referenceTo>Approval_Section__c</referenceTo>
    <relationshipLabel>Approval Properties</relationshipLabel>
    <relationshipName>Approval_Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval_Section__c/Approval_Section__c.object-meta.xml
<CustomObject>
    <label>Approval Section</label>
    <nameField>
        <label>Approval Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Section__c/fields/Approval_Page__c.field-meta.xml
<CustomField>
    <fullName>Approval_Page__c</fullName>
    <label>Approval Page</label>
    <referenceTo>Approval_Page__c</referenceTo>
    <relationshipLabel>Approval Sections</relationshipLabel>
    <relationshipName>Approval_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval_Section__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <inlineHelpText>API name of the object being modified in this section. ex. &apos;Opportunity_Approval__c&apos; for normal sections and &apos;Financials__c&apos; for related list sections.</inlineHelpText>
    <label>Object API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Section__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Controls the order sections show up in within a page.</inlineHelpText>
    <label>Order</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Approval_Section__c/fields/Parent_Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Field__c</fullName>
    <label>Parent Relationship Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Section__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <inlineHelpText>master-detail or lookup field on the object for this section that should be pre-filled and not visible to the user.</inlineHelpText>
    <label>Relationship Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Section__c/recordTypes/Related_List.recordType-meta.xml
<RecordType>
    <fullName>Related_List</fullName>
    <active>true</active>
    <label>Related List</label>
</RecordType>

force-app/main/default/objects/Approval_Section__c/recordTypes/Standard_Fields.recordType-meta.xml
<RecordType>
    <fullName>Standard_Fields</fullName>
    <active>true</active>
    <label>Standard Fields</label>
</RecordType>

force-app/main/default/objects/Financials__c/Financials__c.object-meta.xml
<CustomObject>
    <label>Financials</label>
    <nameField>
        <displayFormat>FIN-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financials__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Company</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Related_Account__c</field>
            <operation>equals</operation>
            <valueField>Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Related_Account__c</field>
            <operation>equals</operation>
            <valueField>Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/Opportunity_Approval__c.object-meta.xml
<CustomObject>
    <description>These records are related to Opportunities and are required for submission before attaining committee approval and engagement.</description>
    <label>Opportunity Review</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Opportunity Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <formula>Related_Opportunity__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Form</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Is_Majority_Sale__c.field-meta.xml
<CustomField>
    <fullName>Is_Majority_Sale__c</fullName>
    <label>Is Majority Sale?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <inlineHelpText>Please indicate the related Opportunity record.</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Reviews</relationshipLabel>
    <relationshipName>Opportunity_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SL_test_ApprovalValidation.cls
/**
 * \author Vladimir Dobrelya
 * \date Jan 20, 2015
 * \brief The test class for SL_handler_ApprovalSection and SL_handler_ApprovalProperty trigger handlers
 */
@isTest
public class SL_test_ApprovalValidation {
	
	static String incorrectName = '!##$#(&(YAS';
	static Boolean hasError = false;

	@isTest static void test_validate_Standard() {
		pStandardSection.Object_API_Name__c = incorrectName; // incorrect object name
		system.assertEquals( false, upsertObject( pStandardSection ) );

		pStandardSection.Object_API_Name__c = 'Opportunity_Approval__c'; // correct object name
		system.assertEquals( true, upsertObject( pStandardSection ) );

		pStandardProperty.Field_API_Name__c = incorrectName; // incorrect field name
		system.assertEquals( false, upsertObject( pStandardProperty ) );

		pStandardProperty.Field_API_Name__c = 'Is_Majority_Sale__c'; // correct field name
		system.assertEquals( true, upsertObject( pStandardProperty ) );

		pStandardSection.Object_API_Name__c = 'Financials__c'; // correct object name, but incorrect for pStandardProperty.Field_API_Name__c
		system.assertEquals( false, upsertObject( pStandardSection ) );
	}
	
	@isTest static void test_validate_RelatedList() {
		pRelatedListSection.Object_API_Name__c = incorrectName; // incorrect object name
		pRelatedListSection.Relationship_Field__c = incorrectName;
		system.assertEquals( false, upsertObject( pRelatedListSection ) );

		pRelatedListSection.Relationship_Field__c = null; // https://silverline.jira.com/browse/HL-61
		pRelatedListSection.Object_API_Name__c = 'Financials__c';
		system.assertEquals( false, upsertObject( pRelatedListSection ) );

		pRelatedListSection.Relationship_Field__c = 'Related_Account__c'; // correct object name
		pRelatedListSection.Object_API_Name__c = 'Financials__c';
		system.assertEquals( true, upsertObject( pRelatedListSection ) );

		pRelatedListProperty.Field_API_Name__c = incorrectName; // incorrect field name
		system.assertEquals( false, upsertObject( pRelatedListProperty ) );

		pRelatedListProperty.Field_API_Name__c = 'Name'; // correct field name
		system.assertEquals( true, upsertObject( pRelatedListProperty ) );

		pRelatedListProperty.Field_API_Name__c = incorrectName; // incorrect field name, just for update coverage
		system.assertEquals( false, upsertObject( pRelatedListProperty ) );

		// https://silverline.jira.com/browse/HL-61
		pRelatedListSection.Relationship_Field__c = 'Related_Account__c'; // correct field name
		pRelatedListSection.Parent_Relationship_Field__c = incorrectName; // incorrect field name
		system.assertEquals( false, upsertObject( pRelatedListSection ) );

		pRelatedListSection.Relationship_Field__c = 'Related_Account__c'; // correct field name
		pRelatedListSection.Parent_Relationship_Field__c = 'Related_Opportunity__r.Client_c'; // incorrect field name
		system.assertEquals( false, upsertObject( pRelatedListSection ) );

		pRelatedListSection.Parent_Relationship_Field__c = 'Related_Opportunity__r.Client__c'; // correct field name
		system.assertEquals( true, upsertObject( pRelatedListSection ) );
	}

	@isTest static void test_validate_ApprovalObject() {
		Approval_Object__c approvalObject = new Approval_Object__c(
			Form__c = 'FVA'
		);

		approvalObject.Base_Object__c = incorrectName; // incorrect Base_Object__c
		system.assertEquals( false, upsertObject( approvalObject ) );

		approvalObject.Base_Object__c = 'Opportunity_Approval__c'; // correct Base_Object__c
		system.assertEquals( true, upsertObject( approvalObject ) );
		
		approvalObject.Master_Detail_Field__c = incorrectName; // incorrect Master_Detail_Field__c
		system.assertEquals( false, upsertObject( approvalObject ) ); 

		approvalObject.Master_Detail_Field__c = 'Related_Opportunity__c'; // correct Master_Detail_Field__c
		system.assertEquals( true, upsertObject( approvalObject ) );
	}

	static Boolean upsertObject( SObject obj ) {
		try {
			upsert obj;
		} catch ( Exception e ) {
			return false;
		}
		return true;
	}

	public static Approval_Object__c pApprovalObject {
		get {
			if ( pApprovalObject == null ) {
				pApprovalObject = new Approval_Object__c(
					Base_Object__c = 'Opportunity_Approval__c',
					Master_Detail_Field__c = 'Related_Opportunity__c',
					Form__c = 'FVA'
				);
				insert pApprovalObject;
			}
			return pApprovalObject;
		} set;
	}

	public static Approval_Page__c pApprovalPage {
		get {
			if ( pApprovalPage == null ) {
				pApprovalPage = new Approval_Page__c(
					Name = 'TestOAPage',
					Order__c = 1,
					Approval_Object__c = pApprovalObject.Id
				);
				insert pApprovalPage;
			}
			return pApprovalPage;
		} set;
	}

	// STANDARD 
	public static Approval_Section__c pStandardSection {
		get {
			if ( pStandardSection == null ) {
				pStandardSection = new Approval_Section__c(
					Name = 'TestApprovalSection',
					Approval_Page__c = pApprovalPage.Id,
					Order__c = 1,
					RecordTypeId = idStandardSectionRT
				);
			}
			return pStandardSection;
		} set;
	}

	public static Approval_Properties__c pStandardProperty {
		get {
			if ( pStandardProperty == null ) {
				pStandardProperty = new Approval_Properties__c(
					Name = 'TestApprovalSection',
					Order__c = 1,
					Section__c = pStandardSection.Id
				);
			}
			return pStandardProperty;
		} set;
	}

	public static ID idStandardSectionRT {
		get {
			if ( idStandardSectionRT == null ) {
				for ( RecordType record : [ SELECT Id FROM RecordType WHERE SObjectType = 'Approval_Section__c' AND DeveloperName = 'Standard_Fields' limit 1 ] ) {
					idStandardSectionRT = record.Id;
				}
				system.assertNotEquals( null, idStandardSectionRT, 'Could not find "Standard_Fields" RecordType for the Approval Section object.' );
			}
			return idStandardSectionRT;
		}
	}


	// RELATED LIST
	public static Approval_Section__c pRelatedListSection {
		get {
			if ( pRelatedListSection == null ) {
				pRelatedListSection = new Approval_Section__c(
					Name = 'TestApprovalSection',
					Approval_Page__c = pApprovalPage.Id,
					Order__c = 2,
					RecordTypeId = idRelatedListSectionRT
				);
			}
			return pRelatedListSection;
		} set;
	}

	public static Approval_Properties__c pRelatedListProperty {
		get {
			if ( pRelatedListProperty == null ) {
				pRelatedListProperty = new Approval_Properties__c(
					Name = 'TestApprovalSection',
					Order__c = 2,
					Section__c = pRelatedListSection.Id
				);
			}
			return pRelatedListProperty;
		} set;
	}

	public static ID idRelatedListSectionRT {
		get {
			if ( idRelatedListSectionRT == null ) {
				for ( RecordType record : [ SELECT Id FROM RecordType WHERE SObjectType = 'Approval_Section__c' AND DeveloperName = 'Related_List' limit 1 ] ) {
					idRelatedListSectionRT = record.Id;
				}
				system.assertNotEquals( null, idStandardSectionRT, 'Could not find "Related_List" RecordType for the Opportunity Approval Section object.' );
			}
			return idRelatedListSectionRT;
		}
	}
}