force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <description>RIVA Custom Object</description>
    <label>Activity (R)</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities (R)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Supplement__c/Activity_Supplement__c.object-meta.xml
<CustomObject>
    <description>Stores related activity fields that cannot be added to the restrictive activity custom fields
- Long Text Area (Over 255 characters)
- Possible Rich Text as a later enhancement</description>
    <label>Activity Supplement</label>
    <nameField>
        <displayFormat>ASN-{00000000}</displayFormat>
        <label>Activity Supplement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Supplements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Supplement__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <description>Activity Record Id</description>
    <externalId>true</externalId>
    <label>Activity</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Activity_Supplement__c/fields/Sync_Description__c.field-meta.xml
<CustomField>
    <fullName>Sync_Description__c</fullName>
    <description>Holds the synch description to be sent to outlook</description>
    <label>Sync Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/InternalNotesEmailHandler.cls
global class InternalNotesEmailHandler implements Messaging.InboundEmailHandler{
	global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {        
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        String body=email.plainTextBody;
        String refId,note;
        System.debug('received:'+body);
        
        if(body.containsIgnoreCase('<refid>')){
          refId=body.substring((body.indexOfIgnoreCase('<refid>')+7),body.indexOfIgnoreCase('</refId>'));
    	    note=body.substring((body.indexOfIgnoreCase('<note>')+6),body.indexOfIgnoreCase('</note>'));
          System.debug('refId:'+refId);
          upsert new Activity_Supplement__c(Activity__c = refId,Sync_Description__c = note) Activity__c;
        }
        result.success=true;
		    return result;
    }
}