force-app/main/default/objects/Coverage_Team__c/Coverage_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track officer coverage on accounts.</description>
    <label>Coverage Team</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Coverage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Team__c/fields/CoverageTypeLookup__c.field-meta.xml
<CustomField>
    <fullName>CoverageTypeLookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Coverage Type (Lookup)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SectorValue__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>SectorValue__c.DependencyValue__c</field>
            <operation>equals</operation>
            <value>Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SectorValue__c</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Coverage_Team1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CoverageSector__c/CoverageSector__c.object-meta.xml
<CustomObject>
    <description>Ability to Tag Multiple Sectors for the Standard Coverage Records.</description>
    <label>Coverage Sector</label>
    <nameField>
        <displayFormat>Company - {000}</displayFormat>
        <label>Company Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoverageSector__c/fields/CoverageTeam__c.field-meta.xml
<CustomField>
    <fullName>CoverageTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Coverage Team</label>
    <referenceTo>Coverage_Team__c</referenceTo>
    <relationshipLabel>Coverage Sectors</relationshipLabel>
    <relationshipName>CoverageSectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CoverageSector__c/fields/IsMain__c.field-meta.xml
<CustomField>
    <fullName>IsMain__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Main</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HL_CoverageSectorWrapper.cls
public inherited sharing class HL_CoverageSectorWrapper {
    public String newCoverageTeamId {get;set;}
    public String coverageTeamType {get;set;}
    public boolean isMain {get;set;}
    public HL_CoverageSectorWrapper(ApexPages.StandardController con){
        CoverageSector__c sector = (CoverageSector__c)con.getRecord();
        System.debug('isMain:'+sector.IsMain__c);
        isMain=sector.IsMain__c;
        if(sector.Id==null && sector.CoverageTeam__c!=null){
            Coverage_Team__c ct = [SELECT Id,CoverageTypeLookup__c,(SELECT Id FROM CoverageSectors__r) FROM Coverage_Team__c WHERE Id=:sector.CoverageTeam__c];
            System.debug('ct:'+ct.CoverageSectors__r.isEmpty());
            isMain = ct.CoverageSectors__r.isEmpty();
            coverageTeamType = ct.CoverageTypeLookup__c;
        }
    }
    public PageReference handleRedirect(){
        PageReference pr = new PageReference('/'+newCoverageTeamId);
        return pr;
    }
}