force-app/main/default/objects/HL_General__c/HL_General__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store General Values that would otherwise be hard-coded
Would eventually like to move the default/profile ids in here too</description>
    <label>HL General</label>
</CustomObject>

force-app/main/default/objects/HL_General__c/fields/Offsite_Archive_Date__c.field-meta.xml
<CustomField>
    <fullName>Offsite_Archive_Date__c</fullName>
    <description>Date used to archive (lock) offsite template records</description>
    <label>Offsite Archive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Offsite_Template__c/Offsite_Template__c.object-meta.xml
<CustomObject>
    <label>Offsite Template</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Offsite Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offsite Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offsite_Template__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <description>Indicates that the record is archived or ready to be archived</description>
    <formula>$Setup.HL_General__c.Offsite_Archive_Date__c &gt; FYE_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offsite_Template__c/fields/FYE_Date__c.field-meta.xml
<CustomField>
    <fullName>FYE_Date__c</fullName>
    <label>FYE Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_HL_Batch_OffsiteTemplateArchive.cls
@isTest
private class Test_HL_Batch_OffsiteTemplateArchive {
    @isTest private static void TestArchiveRecords(){
        //Setup Test Data
        HL_General__c hl = new HL_General__c();
        hl.Offsite_Archive_Date__c = Date.today();
        insert hl;
        List<Offsite_Template__c> otList = SL_TestSetupUtils.CreateOffsiteTemplateDataWithRelated(1,5);
        Id recordTypeId = otList[0].RecordTypeId;
        otList[0].FYE_Date__c = Date.today().addYears(-2);
        update otList;
        System.Debug(otList[0].Archive__c);
        Test.startTest();
        	HL_Batch_OffsiteTemplateArchive batch = new HL_Batch_OffsiteTemplateArchive();
        	Database.executeBatch(batch, 200); 
        Test.stopTest();
        System.assertNotEquals([SELECT RecordTypeId FROM Offsite_Template__c WHERE Id =: otList[0].Id].RecordTypeId, recordTypeId);
    }
}