force-app/main/default/objects/Eng_VP__c/Eng_VP__c.object-meta.xml
<CustomObject>
    <label>Engagement Valuation Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Valuation Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Valuation Periods</relationshipLabel>
    <relationshipName>Engagement_Portfolio_Valuations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP__c/fields/Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Valuation_Date__c</fullName>
    <label>Valuation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/Eng_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Engagement Valuation Period Positions linked with Engagement and Companies</description>
    <label>Eng Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eng Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP_Position__c/fields/Asset_Classes__c.field-meta.xml
<CustomField>
    <fullName>Asset_Classes__c</fullName>
    <label>Asset Classes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABL</fullName>
            </value>
            <value>
                <fullName>ABS (Other)</fullName>
            </value>
            <value>
                <fullName>Auction Rate Securities</fullName>
            </value>
            <value>
                <fullName>Auto Loans</fullName>
            </value>
            <value>
                <fullName>Bank Assets (FDIC)</fullName>
            </value>
            <value>
                <fullName>CDO</fullName>
            </value>
            <value>
                <fullName>CLO</fullName>
            </value>
            <value>
                <fullName>CLO – MOA / CMV (Asset Manager)</fullName>
            </value>
            <value>
                <fullName>CMBS</fullName>
            </value>
            <value>
                <fullName>Contingent Value Rights</fullName>
            </value>
            <value>
                <fullName>Debt</fullName>
            </value>
            <value>
                <fullName>Debt &amp; Derivatives</fullName>
            </value>
            <value>
                <fullName>Derivatives</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>Equity, Debt, &amp; Derivatives</fullName>
            </value>
            <value>
                <fullName>Equity &amp; Debt</fullName>
            </value>
            <value>
                <fullName>Equity &amp; Derivatives</fullName>
            </value>
            <value>
                <fullName>Fix and Flip Mortgages</fullName>
            </value>
            <value>
                <fullName>Fund Manager Valuation</fullName>
            </value>
            <value>
                <fullName>Interest Rate Lock Commitments</fullName>
            </value>
            <value>
                <fullName>Litigation Claims</fullName>
            </value>
            <value>
                <fullName>Marketplace Lending</fullName>
            </value>
            <value>
                <fullName>Market Study</fullName>
            </value>
            <value>
                <fullName>Mortgage Servicing Rights</fullName>
            </value>
            <value>
                <fullName>Non-Performing Loans</fullName>
            </value>
            <value>
                <fullName>PIPE Investments</fullName>
            </value>
            <value>
                <fullName>Residential Mortgages</fullName>
            </value>
            <value>
                <fullName>Reverse Mortgages</fullName>
            </value>
            <value>
                <fullName>Risk Retention</fullName>
            </value>
            <value>
                <fullName>RMBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Automation_Tool_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Automation_Tool_Utilized__c</fullName>
    <label>Automation Tool Utilized</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Company</description>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Houlihan_Company</value>
        </filterItems>
        <filterItems>
            <field>Account.Id</field>
            <operation>notEqual</operation>
            <value>001i000001T7e9v</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Eng_PV_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Engagement_VP__c.field-meta.xml
<CustomField>
    <fullName>Engagement_VP__c</fullName>
    <label>Engagement Valuation Period</label>
    <referenceTo>Eng_VP__c</referenceTo>
    <relationshipName>Eng_VP_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Report_Fee__c.field-meta.xml
<CustomField>
    <fullName>Report_Fee__c</fullName>
    <label>Report Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed, Generate Accrual</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Valuation_Date__c</fullName>
    <formula>Engagement_VP__r.Valuation_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c, &quot;Closed&quot;), &quot;Closed&quot;,
IF(ISPICKVAL(Stage__c, &quot;Hold&quot;), &quot;Hold&quot;,
IF(ISPICKVAL(Stage__c, &quot;Dead&quot;), &quot;Dead&quot;,
&quot;Active&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Valuation_Date__c</fullName>
    <label>Valuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_HL_AutomationToolMassUpdate_Class.cls
/*
test class for HL_AutomationToolMassUpdate_Class 
Author : Himanshu Sharma
*/
@istest

private class Test_HL_AutomationToolMassUpdate_Class{
    
    @testSetup static void setup() {        
        Account client = SL_TestSetupUtils.CreateAccount('', 1)[0];
        client.Name = 'TestClient'; 
        insert client;
        Account subject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        insert subject;
        
        Engagement__c e = SL_TestSetupUtils.CreateEngagement('',1)[0];
        e.Client__c = client.Id;
        e.Subject__c = subject.Id;
        insert e;
        
        Eng_VP__c testEngVP = new Eng_VP__c(); 
        testEngVP .Valuation_Date__c = system.today(); 
        testEngVP.Engagement__c = e.id; 
        insert testEngVP; 
        
    }
    
    @isTest static void myUnitTest1() {
        
        Eng_VP__c  testEngVP = [Select id from Eng_VP__c Limit 1 ]; 
        Account testClient = [Select id from Account where Name = 'TestClient' ];
        List<Eng_VP_Position__c> vppList = new List<Eng_VP_Position__c>();
        
        Test.StartTest();
            Eng_VP_Position__c testPosition = new Eng_VP_Position__c();        
            testPosition.Engagement_VP__c = testEngVP.id;
            testPosition.Company__c = testClient .id; 
            testPosition.Report_Fee__c = 100.0;
            testPosition.Asset_Classes__c = 'Equity';
            testPosition.Status__c = 'In Progress';
            testPosition.Automation_Tool_Utilized__c = 'No';
            insert testPosition;
            vppList.add(testPosition);
            
            HL_AutomationToolMassUpdate_Class objHLAutomationToolMassUpdate = new HL_AutomationToolMassUpdate_Class();
            objHLAutomationToolMassUpdate.VPPostionList = vppList;
            objHLAutomationToolMassUpdate.SavePosition();
            objHLAutomationToolMassUpdate.CancelPosition();
        Test.StopTest();  
        
        System.assertNotEquals(testPosition.id, null );
        System.assert(objHLAutomationToolMassUpdate.VPPostionList.size()>0);
    }
    
    @isTest static void myUnitTest2() {
        
        Eng_VP__c  testEngVP = [Select id from Eng_VP__c Limit 1 ]; 
        Account testClient = [Select id from Account where Name = 'TestClient' ];
        List<Eng_VP_Position__c> vppList = new List<Eng_VP_Position__c>();
        
        Test.StartTest();
            Eng_VP_Position__c testPosition = new Eng_VP_Position__c();        
            testPosition.Engagement_VP__c = testEngVP.id;
            testPosition.Company__c = testClient .id; 
            testPosition.Report_Fee__c = 100.0;
            testPosition.Asset_Classes__c = 'Equity';
            testPosition.Status__c = 'In Progress';
            testPosition.Automation_Tool_Utilized__c = 'Yes';
            insert testPosition;
            vppList.add(testPosition);
            
            HL_AutomationToolMassUpdate_Class objHLAutomationToolMassUpdate = new HL_AutomationToolMassUpdate_Class();
            objHLAutomationToolMassUpdate.VPPostionList = vppList;
            objHLAutomationToolMassUpdate.SavePosition();
            objHLAutomationToolMassUpdate.CancelPosition();
        Test.StopTest();  
        
        System.assertNotEquals(testPosition.id, null );
        System.assert(objHLAutomationToolMassUpdate.VPPostionList.size()>0);
    }
    
}