force-app/main/default/objects/Monthly_Revenue_Process_Control__c/Monthly_Revenue_Process_Control__c.object-meta.xml
<CustomObject>
    <description>Kick off and track each step of the Monthly Revenue Process in JDE</description>
    <label>Monthly Revenue Process Control</label>
    <nameField>
        <label>Monthly Revenue Process Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Revenue Process Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Current_Month__c</fullName>
    <description>Select the Current Month for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Month for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Current Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Current_Month_and_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Month_and_Year__c</fullName>
    <description>This field is set by workflow and determines unique records</description>
    <label>Current Month and Year</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Year__c</fullName>
    <description>Select the Current Year for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Year for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Current Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1999</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/IsCurrent__c.field-meta.xml
<CustomField>
    <fullName>IsCurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this is the current Monthly Revenue Process Control record (only one record can be active at a time)</description>
    <inlineHelpText>Indicates that this is the current Monthly Revenue Process Control record (only one record can be active at a time)</inlineHelpText>
    <label>Is Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Staff_Summary_Report_Sent__c.field-meta.xml
<CustomField>
    <fullName>Staff_Summary_Report_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the final report request has been distributed</description>
    <inlineHelpText>Flag to indicate if the final report request has been distributed</inlineHelpText>
    <label>Staff Summary Report Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SL_MonthlyRevenueProcessControllerExt.cls
public class SL_MonthlyRevenueProcessControllerExt {

    private final ApexPages.StandardController controller;
    
    public SL_MonthlyRevenueProcessControllerExt(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    public PageReference createRecord() {
        Boolean createNewRecord;
        Integer newMonthInt, newYearInt;
        String currMonth, currYear, newMonth, newYear, externalId, strURL, retURL;
        PageReference p;
        Monthly_Revenue_Process_Control__c newMrpc = new Monthly_Revenue_Process_Control__c();
        Monthly_Revenue_Process_Control__c currMrpc;
        
        // Set Database SavePoint
        Savepoint sp = Database.setSavepoint();
        
        // Obtain current month and year from Monthly_Revenue_Process_Control__c record
        Monthly_Revenue_Process_Control__c[] currMrpcs = [SELECT Id, IsCurrent__c, Current_Month__c, Current_Year__c, Current_Month_and_Year__c, Staff_Summary_Report_Sent__c FROM Monthly_Revenue_Process_Control__c WHERE IsCurrent__c = true LIMIT 1];
        if (currMrpcs.size() > 0) {
            currMrpc = currMrpcs[0];
            // Validate that current Mrpc record is ready to be closed
            if (currMrpc.Staff_Summary_Report_Sent__c != true) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'The current Monthly Revenue Process Control record is not ready to be closed.<br/><br/>You must progress through all steps until the Staff Summary Report has been sent.'));                
                // Set flag
                createNewRecord = false;
            } else {
                // Set isCurrent flag on existing record
                currMrpc.IsCurrent__c = false;
                try {
                    update currMrpc;
                    // Set Default Values for New Process Control Record
                    // Default Month and Year
                    currMonth = currMrpc.Current_Month__c;
                    currYear = currMrpc.Current_Year__c;
                    if (currMonth == '01') {
                        newMonth = '02';
                        newYear = currYear;
                    } else if  (currMonth == '02') {
                        newMonth = '03';
                        newYear = currYear;
                    } else if (currMonth == '03') {
                        newMonth = '04';
                        newYear = currYear;
                    } else if (currMonth == '04') {
                        newMonth = '05';
                        newYear = currYear;
                    } else if (currMonth == '05') {
                        newMonth = '06';
                        newYear = currYear;
                    } else if (currMonth == '06') {
                        newMonth = '07';
                        newYear = currYear;
                    } else if (currMonth == '07') {
                        newMonth = '08';
                        newYear = currYear;
                    } else if (currMonth == '08') {
                        newMonth = '09';
                        newYear = currYear;
                    } else if (currMonth == '09') {
                        newMonth = '10';
                        newYear = currYear;
                    } else if (currMonth == '10') {
                        newMonth = '11';
                        newYear = currYear;
                    } else if (currMonth == '11') {
                        newMonth = '12';
                        newYear = currYear;
                    } else if (currMonth == '12') {
                        newMonth = '01';
                        newYearInt = Integer.valueOf(currYear)+1;
                        newYear = newYearInt.format();
                        newYear = newYear.replace(',','');
                    }
                    newMrpc.Current_Month__c = newMonth;
                    newMrpc.Current_Year__c = newYear;
                    // Default External Id
                    externalId = newMonth+'|'+newYear;
                    newMrpc.Current_Month_and_Year__c = externalId;
                    // Set IsCurrent flag
                    newMrpc.IsCurrent__c = true;
                    // Set flag
                    createNewRecord = true;
                } catch (DmlException e) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'An error occurred while updating the current Process Control record:<br/><br/>'+e.getMessage()));
                    createNewRecord = false;
                }
            }
        } else {
            // Default Month and Year
            Date today = Date.today();
            newMonthInt = today.month();
            if (newMonthInt < 10) {
                newMonth = '0'+newMonthInt.format();
            } else {
                newMonth = newMonthInt.format();
            }
            newYearInt = today.year();
            newYear = newYearInt.format();
            newMrpc.Current_Month__c = newMonth;
            newMrpc.Current_Year__c = newYear;
            // Default External Id
            externalId = newMonth+'|'+newYear;
            newMrpc.Current_Month_and_Year__c = externalId;
            // Set isCurrent flag
            newMrpc.IsCurrent__c = true;
            // Set flag
            createNewRecord = true;
        }
        if (createNewRecord) {
            // Save Monthly Revenue Process Control record
            try {
                insert newMrpc;
                // Set return URL
                retURL ='%2F'+newMrpc.Id;
                strURL = '/'+newMrpc.id+'/e?retURL='+retURL;
                system.debug('>>>>> strURL = ' + strURL);
                // Set page reference and return
                p = new PageReference(strURL);
                return p.setRedirect(true);
            } catch(DmlException e) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'An error occurred while saving the new Monthly Revenue Process Control record:<br/><br/>' + e.getMessage()));
                // Roll back to SavePoint
                Database.rollback(sp);
            }
        }
        return null;
    }
}