force-app/main/default/objects/Monthly_Revenue_Process_Control__c/Monthly_Revenue_Process_Control__c.object-meta.xml
<CustomObject>
    <description>Kick off and track each step of the Monthly Revenue Process in JDE</description>
    <label>Monthly Revenue Process Control</label>
    <nameField>
        <label>Monthly Revenue Process Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Revenue Process Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Current_Month__c</fullName>
    <description>Select the Current Month for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Month for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Current Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Year__c</fullName>
    <description>Select the Current Year for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Year for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Current Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1999</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/IsCurrent__c.field-meta.xml
<CustomField>
    <fullName>IsCurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this is the current Monthly Revenue Process Control record (only one record can be active at a time)</description>
    <inlineHelpText>Indicates that this is the current Monthly Revenue Process Control record (only one record can be active at a time)</inlineHelpText>
    <label>Is Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SL_Test_MonthlyRevenueProcessController.cls
@isTest
private class SL_Test_MonthlyRevenueProcessController 
{
    @isTest static void test_MonthlyRevenueProcessController() 
    {
        Monthly_Revenue_Process_Control__c mrpcNew = new Monthly_Revenue_Process_Control__c(IsCurrent__c = TRUE, 
                                                              Current_Month__c = '02', Current_Year__c = '2015'
                                                              );
        insert mrpcNew;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(mrpcNew);
        SL_MonthlyRevenueProcessController controller = new SL_MonthlyRevenueProcessController(sc);
        controller.initialReversal();
        //controller.unlockAll();
        //controller.lockAll();
        controller.finalReversal();
        controller.exportRevenue();
        controller.earlyLook();
        controller.currencyConversion();
        controller.finalReport();
        controller.staffSummary();
       controller.generateRevenue();
    }
}