force-app/main/default/objects/Contact/fields/Full_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Full_Contact_ID__c</fullName>
    <formula>CASESAFEID( Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Contact ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_Link_URL__c</fullName>
    <description>Link that will execute the report</description>
    <label>Report Link URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HL_ContactReportLinks.cls
public with sharing class HL_ContactReportLinks {
    public List<HL_Report_Link__c>	LinkList	{ get;set; }
    public string PageTitle						{ get;set; }
    public string PageStyle						{ get;set; }
    
    public HL_ContactReportLinks(Apexpages.StandardController con)
    {
        Contact currContact;
        string ContactID; 
        
        try
        {
            currContact = [SELECT Name, Full_Contact_ID__c FROM Contact WHERE ID =: con.getId()]; 
            ContactID = currContact.Full_Contact_ID__c;             
        }
       	catch(Exception ex) 
        {
            currContact = null;
            ContactID = null;             
        }
       
        
        if(!String.isBlank(ContactID))
        {
            LinkList = HL_ReportLink.GetByType('Contact Single');
            
			for(HL_Report_Link__c currLink: LinkList)            
                currLink.Report_Link_URL__c = currLink.Report_Link_URL__c.replace('{!Contact.Full_Contact_ID__c}', ContactID);
            
            PageTitle = 'Contact Reports for ' + currContact.Name;
            PageStyle = 'display:initial;';              
        }
        else   
        {	
            LinkList = HL_ReportLink.GetByType('Contact Group');
            
            PageTitle = 'Contact Reports';
            PageStyle = 'display:none;';            
        }        
    }
    
    public HL_ContactReportLinks(){}
    
    public Pagereference ReturnToParent()
    {
        Pagereference pageref = new Pagereference('/' + ApexPages.currentPage().getParameters().get('id'));
	   	return pageref;
    }    
    
}