force-app/main/default/objects/Contact/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASC - Augmenting Sector Coverage</fullName>
            </value>
            <value>
                <fullName>BUS - Business Services</fullName>
            </value>
            <value>
                <fullName>CFR - Consumer Food &amp; Retail</fullName>
            </value>
            <value>
                <fullName>CM - Capital Markets</fullName>
            </value>
            <value>
                <fullName>CORP - Corporate</fullName>
            </value>
            <value>
                <fullName>FIG - Financial Institutions</fullName>
            </value>
            <value>
                <fullName>FS - Financial Sponsors</fullName>
            </value>
            <value>
                <fullName>FT - Financial Technology</fullName>
            </value>
            <value>
                <fullName>GEN - General</fullName>
            </value>
            <value>
                <fullName>HC - Healthcare</fullName>
            </value>
            <value>
                <fullName>IFA - Illiquid Financial Assets</fullName>
            </value>
            <value>
                <fullName>IG - Industrials</fullName>
            </value>
            <value>
                <fullName>M&amp;A - Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>NRG - Energy</fullName>
            </value>
            <value>
                <fullName>O&amp;G - Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>PFG - Private Funds Group</fullName>
            </value>
            <value>
                <fullName>POW - Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>RE - Real Estate Lodging and Leisure</fullName>
            </value>
            <value>
                <fullName>SOV - Sovereigns</fullName>
            </value>
            <value>
                <fullName>TAG - Tangible Asset Group</fullName>
            </value>
            <value>
                <fullName>TECH - Technology</fullName>
            </value>
            <value>
                <fullName>TRANS - Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered__c.field-meta.xml
<CustomField>
    <fullName>Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Registered HL Employees</description>
    <label>Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Staff_Type__c.field-meta.xml
<CustomField>
    <fullName>Staff_Type__c</fullName>
    <label>Staff Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADMIN</fullName>
            </value>
            <value>
                <fullName>AG-TEMP</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>HL-TEMP</fullName>
            </value>
            <value>
                <fullName>INTERN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Job_Type__c/Job_Type__c.object-meta.xml
<CustomObject>
    <label>Job Type</label>
    <nameField>
        <label>JOB TYPE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Type__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <externalId>true</externalId>
    <label>Job Code</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_of_Business__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activism Advisory</fullName>
            </value>
            <value>
                <fullName>Board Advisory Services (BAS)</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Buyside &amp; Financing Advisory</fullName>
            </value>
            <value>
                <fullName>Collateral Valuation</fullName>
            </value>
            <value>
                <fullName>Compensation/Formula Analysis</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Corporate Alliances</fullName>
            </value>
            <value>
                <fullName>Creditor Advisors</fullName>
            </value>
            <value>
                <fullName>CVAS - Forensic Services</fullName>
            </value>
            <value>
                <fullName>CVAS - FV Opinion</fullName>
            </value>
            <value>
                <fullName>CVAS - Goodwill or Asset Impairment</fullName>
            </value>
            <value>
                <fullName>CVAS - Pre-Acq Val&apos;n Cons</fullName>
            </value>
            <value>
                <fullName>CVAS - Purchase Price Allocation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 123R/409A Stock, Option Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 133 Derivatives, Liabilities Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Sovereign Advisory</fullName>
            </value>
            <value>
                <fullName>CVAS - Tangible Asset Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Tax Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Transfer Pricing</fullName>
            </value>
            <value>
                <fullName>Debt Advisory</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Advisors</fullName>
            </value>
            <value>
                <fullName>Discretionary Advisory</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Buyside</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Sellside</fullName>
            </value>
            <value>
                <fullName>DRC - Ad Valorem Services</fullName>
            </value>
            <value>
                <fullName>DRC - Appointed Arbitrator/Mediator</fullName>
            </value>
            <value>
                <fullName>DRC - Contract Compliance</fullName>
            </value>
            <value>
                <fullName>DRC - Exp Cons-Arbitrat&apos;n</fullName>
            </value>
            <value>
                <fullName>Fairness</fullName>
            </value>
            <value>
                <fullName>Private Funds: Primary Advisory</fullName>
            </value>
            <value>
                <fullName>Tech+IP - Patent Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/CF.recordType-meta.xml
<RecordType>
    <fullName>CF</fullName>
    <active>true</active>
    <description>Corporate Finance</description>
    <label>CF</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/recordTypes/FR.recordType-meta.xml
<RecordType>
    <fullName>FR</fullName>
    <active>true</active>
    <description>Financial Restructuring</description>
    <label>FR</label>
</RecordType>

force-app/main/default/objects/Staff_Role__c/Staff_Role__c.object-meta.xml
<CustomObject>
    <description>Used internally to control staff role display and order.</description>
    <label>Staff Role</label>
    <nameField>
        <label>Staff Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Role__c/fields/CF__c.field-meta.xml
<CustomField>
    <fullName>CF__c</fullName>
    <defaultValue>true</defaultValue>
    <label>CF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Fin_Only__c.field-meta.xml
<CustomField>
    <fullName>Fin_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Available to Financial (FIN) Staff Only</description>
    <label>Fin Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/FS__c.field-meta.xml
<CustomField>
    <fullName>FS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Non_Fin_Only__c.field-meta.xml
<CustomField>
    <fullName>Non_Fin_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Available Only to Non-Financial Staff</description>
    <label>Non Fin Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Non_Registered_Only__c.field-meta.xml
<CustomField>
    <fullName>Non_Registered_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Staff Role is Available to Only Non Registered Staff</description>
    <label>Non Registered Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Registered_Excluded_Job_Codes__c.field-meta.xml
<CustomField>
    <fullName>Registered_Excluded_Job_Codes__c</fullName>
    <description>Define the Job Codes that Bypass the Registered Only Ruleset</description>
    <label>Registered Excluded Job Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5000</fullName>
            </value>
            <value>
                <fullName>5101</fullName>
            </value>
            <value>
                <fullName>5111</fullName>
            </value>
            <value>
                <fullName>5121</fullName>
            </value>
            <value>
                <fullName>5131</fullName>
            </value>
            <value>
                <fullName>5141</fullName>
            </value>
            <value>
                <fullName>5161</fullName>
            </value>
            <value>
                <fullName>5171</fullName>
            </value>
            <value>
                <fullName>5181</fullName>
            </value>
            <value>
                <fullName>5501</fullName>
            </value>
            <value>
                <fullName>5511</fullName>
            </value>
            <value>
                <fullName>5521</fullName>
            </value>
            <value>
                <fullName>5531</fullName>
            </value>
            <value>
                <fullName>5541</fullName>
            </value>
            <value>
                <fullName>5555</fullName>
            </value>
            <value>
                <fullName>5561</fullName>
            </value>
            <value>
                <fullName>5571</fullName>
            </value>
            <value>
                <fullName>5581</fullName>
            </value>
            <value>
                <fullName>5601</fullName>
            </value>
            <value>
                <fullName>5611</fullName>
            </value>
            <value>
                <fullName>5631</fullName>
            </value>
            <value>
                <fullName>5641</fullName>
            </value>
            <value>
                <fullName>5651</fullName>
            </value>
            <value>
                <fullName>5661</fullName>
            </value>
            <value>
                <fullName>5671</fullName>
            </value>
            <value>
                <fullName>5681</fullName>
            </value>
            <value>
                <fullName>5701</fullName>
            </value>
            <value>
                <fullName>5721</fullName>
            </value>
            <value>
                <fullName>5731</fullName>
            </value>
            <value>
                <fullName>5741</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Registered_Only__c.field-meta.xml
<CustomField>
    <fullName>Registered_Only__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the Role is Available for Only Registered Staff</description>
    <label>Registered Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_HL_Staff_Role.cls
@IsTest
private class Test_HL_Staff_Role {
    
    @testSetup static void InsertRoles() {
        List<Staff_Role__c> roles = new List<Staff_Role__c>();
        roles.add(new Staff_Role__c(Name = 'Analyst', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
    roles.add(new Staff_Role__c(Name = 'Associate', Opportunity__c = True, CF__c = False, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Fairness', Opportunity__c = True, CF__c = False, FS__c = False, Registered_Only__c = False, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Final Reviewer', Opportunity__c = True, CF__c = True, FS__c = True, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Ind/Prod/Geog Person', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Initiator', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Intern', Opportunity__c = True, CF__c = True, FS__c = True, Registered_Only__c = False, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = True));
        roles.add(new Staff_Role__c(Name = 'Manager', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Analyst', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Marketing Team', Opportunity__c = True, CF__c = True, FS__c = True, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Non-Registered', Opportunity__c = True, CF__c = True, FS__c = True, Registered_Only__c = False, Non_Registered_Only__c = True, Fin_Only__c = True, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'PE/Hedge Fund', Opportunity__c = True, CF__c = True, FS__c = True, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
    roles.add(new Staff_Role__c(Name = 'Prelim Reviewer', Opportunity__c = True, CF__c = False, FS__c = True, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Pricing Committee Approver', Opportunity__c = False, CF__c = True, FS__c = True, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Principal', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Public Person', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Reviewer', Opportunity__c = True, CF__c = False, FS__c = True, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));
        roles.add(new Staff_Role__c(Name = 'Seller', Opportunity__c = True, CF__c = True, FS__c = False, Registered_Only__c = True, Non_Registered_Only__c = False, Fin_Only__c = False, Non_Fin_Only__c = False));

        insert roles;
        
        Job_Type__c job1 = new Job_Type__c(Name = 'Tech+IP - Patent Sales', Job_Code__c = '6000');
        Job_Type__c job2 = new Job_Type__c(Name = 'Private Funds: Primary Advisory', Job_Code__c = '6001');
        
        insert job1;
        insert job2;
  }
    
    @isTest private static void TestGetByName(){
        Test.startTest();

        //Result Found
        List<Staff_Role__c> resultList = HL_Staff_Role.GetByName('Associate');

        //No Result Found
        List<Staff_Role__c> noResultList = HL_Staff_Role.GetByName('NoRole');

        Test.stopTest();

        System.assert(resultList.size() == 1);
        System.assert(noResultList.size() == 0);
    }

     @isTest private static void TestRoleSort(){
       Test.startTest();

       List<Staff_Role__c> cfOppRoleList = HL_Staff_Role.GetRoles(HL_Staff_Role.RoleType.Opportunity, HL_Staff_Role.RoleLOB.CF);
       Set<String> rolesToSortSet = new Set<String>();
       for(Staff_Role__c sr : cfOppRoleList)
            rolesToSortSet.Add(sr.Name);
       List<String> sortedRoleList = HL_Staff_Role.GetSortedRoles(rolesToSortSet);

       Test.stopTest();

       //Verify the sorted roles list still contains roles
      System.assert(sortedRoleList.size() > 0);
    }
    
    @isTest private static void TestFilterSelectableRolesFS(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'CM - Capital Markets';
        c.Department = 'FS';
        c.Registered__c = true;
        insert c;
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c 
                                     FROM Staff_Role__c WHERE Name = 'Associate'];

        Test.startTest();

        List<Staff_Role__c> roleResultList = HL_Staff_Role.FilterSelectableRoles(c, 'CF', 'jobCode', false, false, roles);

        Test.stopTest();

        System.assert(roleResultList.size() == 0);
    }
    
    @isTest private static void TestFilterSelectableRolesAdmin(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'CM - Capital Markets';
        c.Department = 'FS';
        c.Registered__c = true;
        c.Staff_type__c = 'Admin';
        insert c;
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c 
                                     FROM Staff_Role__c WHERE Name = 'Associate'];

        Test.startTest();

        List<Staff_Role__c> roleResultList = HL_Staff_Role.FilterSelectableRoles(c, 'CF', 'jobCode', false, false, roles);

        Test.stopTest();

        System.assert(roleResultList.size() == 0);
    }
    
    
     @isTest private static void TestFilterSelectableRolesRegisteredStaffNonRegisteredOnlyRole(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
         c.Registered__c = true;
         c.Industry_Group__c = 'CM - Capital Markets';
        insert c;
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c 
                                     FROM Staff_Role__c WHERE Name = 'Associate'];

        Test.startTest();

        List<Staff_Role__c> roleResultList = HL_Staff_Role.FilterSelectableRoles(c, 'CF', 'jobCode', false, false, roles);

        Test.stopTest();

        System.assertEquals(roleResultList.size(), 1);
    }
    
    @isTest private static void TestFilterSelectableRolesFinStaffNonFinOnlyRole(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'CM - Capital Markets';
        c.Registered__c = true;
        c.Staff_Type__c = 'FIN';
        insert c;
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c 
                                     FROM Staff_Role__c WHERE Name = 'Associate'];

        Test.startTest();

        List<Staff_Role__c> roleResultList = HL_Staff_Role.FilterSelectableRoles(c, 'CF', 'jobCode', false, false, roles);

        Test.stopTest();

        System.assertEquals(roleResultList.size(), 1);
    }
    
    @isTest private static void TestFilterSelectableRolesNonFinStaffFinOnlyRole(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'CM - Capital Markets';
        c.Registered__c = true;
        c.Staff_Type__c = '';
        insert c;
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c 
                                     FROM Staff_Role__c WHERE Name = 'Associate'];

        Test.startTest();

        List<Staff_Role__c> roleResultList = HL_Staff_Role.FilterSelectableRoles(c, 'CF', 'jobCode', false, false, roles);

        Test.stopTest();

        System.assert(roleResultList.size() == 1);
    }

    @isTest private static void TestFilterSelectableRolesNonRegistered(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'CM - Capital Markets';
        c.Office__c = 'LA';
        c.Registered__c = false;
        
        insert c;
        c = [SELECT Department, Is_Foreign_Office__c, Registered__c, Industry_Group__c, Staff_Type__c FROM Contact WHERE Id =: c.Id];
        
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c,  Registered_Excluded_Job_Codes__c
                                     FROM Staff_Role__c WHERE Name = 'Associate'];

        Test.startTest();

        List<Staff_Role__c> roleResultList = HL_Staff_Role.FilterSelectableRoles(c, 'CF', '', false, false, roles);

        Test.stopTest();

        System.assert(roleResultList.size() == 0);
    }
    
    @isTest private static void TestFilterSelectableRolesNonRegisteredForeign(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'CM - Capital Markets';
        c.Office__c = 'HK';
        c.Staff_Type__c = '';
        c.Registered__c = false;
        
        insert c;
        c = [SELECT Department, Is_Foreign_Office__c, Registered__c, Industry_Group__c, Staff_Type__c FROM Contact WHERE Id =: c.Id];
        
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c 
                                     FROM Staff_Role__c WHERE Name = 'Associate'];
        
        Test.startTest();

        List<Staff_Role__c> roleResultList = HL_Staff_Role.FilterSelectableRoles(c, 'CF', 'jobCode', false, false, roles);

        Test.stopTest();

        System.assert(roleResultList.size() == 0);
    }
    
    //Test that the new Bear Tooth Rules work
    //A contact in Private Funds Group Industry can be staffed on any role on an Engagement/Opp that is of job type Private Funds: Primary Advisory
    //A contact that is non-registered can still be staffed as non-registered
    @isTest private static void TestFilterSelectableRolesPrivateFundsAdvisory(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'PFG - Private Funds Group';
        c.Office__c = 'HK';
        c.Staff_Type__c = 'FIN';
        c.Registered__c = true;
        
        
        insert c;
        c = [SELECT Department, Is_Foreign_Office__c, Registered__c, Industry_Group__c, Staff_Type__c FROM Contact WHERE Id =: c.Id];
        
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c
                                     FROM Staff_Role__c];

        Test.startTest();  
        String pfaJobCode = HL_JobType.GetJobCode('Private Funds: Primary Advisory');
        List<Staff_Role__c> roleResultCFListPFA = HL_Staff_Role.FilterSelectableRoles(c, 'CF', pfaJobCode, false, false, roles);
        c.Registered__c = false;
        List<Staff_Role__c> roleResultNonRegisteredCFListPFA = HL_Staff_Role.FilterSelectableRoles(c, 'CF', pfaJobCode, false, false, roles);      
        Test.stopTest();
        
        System.assertEquals(roleResultCFListPFA.size(), 17, 'All roles except Non-Registered');
        System.assertEquals(roleResultNonRegisteredCFListPFA.size(), 18, 'All roles and Non-Registered for foreign HK PFG');
    }
    
    //Test that the new Bear Tooth Rules work
    //A contact in Private Funds Group Industry can be staffed on Initiator and Seller for CF/FR Engagement/Opp that is NOT of job type Private Funds: Primary Advisory
    //A contact that is non-registered can still be staffed as non-registered
    @isTest private static void TestFilterSelectableRolesNonPrivateFundsAdvisory(){
        //Setup Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        c.Industry_Group__c = 'PFG - Private Funds Group';
        c.Office__c = 'HK';
        c.Staff_Type__c = 'FIN';
        c.Registered__c = true;
        
        insert c;
        c = [SELECT Department, Is_Foreign_Office__c, Registered__c, Industry_Group__c, Staff_Type__c FROM Contact WHERE Id =: c.Id];
        
        List<Staff_Role__c> roles = [SELECT Name, Opportunity__c, CF__c, FS__c, Registered_Only__c, Non_Registered_Only__c, Fin_Only__c, Non_Fin_Only__c, Registered_Excluded_Job_Codes__c
                                     FROM Staff_Role__c];

        
        Test.startTest();  

        String ifaJobCode = HL_JobType.GetJobCode('Tech+IP - Patent Sales');
        List<Staff_Role__c> roleResultCFListIFA = HL_Staff_Role.FilterSelectableRoles(c, 'CF', ifaJobCode, false, false, roles);
        List<Staff_Role__c> roleResultFRListIFA = HL_Staff_Role.FilterSelectableRoles(c, 'FR', ifaJobCode, false, false, roles);
        c.Registered__c = false;
        List<Staff_Role__c> roleResultNonRegisteredCFListIFA = HL_Staff_Role.FilterSelectableRoles(c, 'CF', ifaJobCode, false, false, roles);
        List<Staff_Role__c> roleResultNonRegisteredFRListIFA = HL_Staff_Role.FilterSelectableRoles(c, 'FR', ifaJobCode, false, false, roles);      
        Test.stopTest();
        
        System.assertEquals(4, roleResultCFListIFA.size(), 'Seller, Marketing, Specialty, and Initiator Only');
        System.assertEquals(4, roleResultFRListIFA.size(), 'Seller, Marketing, Specialty, and Initiator Only');    
        System.assertEquals(1, roleResultNonRegisteredCFListIFA.size(), 'Only Non-Registered');
        System.assertEquals(1, roleResultNonRegisteredFRListIFA.size(), 'Only Non-Registered');
    }
}