force-app/main/default/objects/Contact/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Legal Entity</description>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>This is an HL Contract object. Stores information from Engagement or Opportunity and integrates with Oracle Contract object.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract (Client)</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Contract</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/ERP_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_Entity_Code__c</fullName>
    <description>ERP Entity Code - Code from Legal Entity lookup value and populating value through Process builder</description>
    <label>ERP Entity Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Legal Entity</description>
    <label>Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Legal_Entity__c.Available_for_Project__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/Engagement_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for an engaged deal/project.</description>
    <label>Engagement Contact</label>
    <nameField>
        <displayFormat>EET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_External_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Invalid Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Engagement_Working_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HL_Auto_Number_Settings__c/HL_Auto_Number_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the sequence of Client Numbers assigned to Companies.</description>
    <label>HL Auto Number Setting</label>
</CustomObject>

force-app/main/default/objects/HL_Auto_Number_Settings__c/fields/Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Auto_Number__c</fullName>
    <label>Auto Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <description>Maintains the legal entities of Houlihan Lokey</description>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Entity__c/fields/Available_for_Project__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this legal entity is available in Opportunity or Engagement</description>
    <inlineHelpText>Indicates if this legal entity is available in Opportunity or Engagement</inlineHelpText>
    <label>Available for Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/fields/ERP_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ERP_Entity_Code__c</fullName>
    <description>The code of the legal entity in ERP</description>
    <label>ERP Entity Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/fields/ERP_VAT_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>ERP_VAT_Legal_Entity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field value  set to True and used for VAT Treatment on Opportunity and Engagement.</description>
    <inlineHelpText>ERP VAT Treatment Legal Entity</inlineHelpText>
    <label>ERP VAT Treatment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Legal Entity lookup</description>
    <label>Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(2 AND 3) OR (4 AND 1)</booleanFilter>
        <filterItems>
            <field>Legal_Entity__c.Available_for_Project__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>HL Internal Opportunity</value>
        </filterItems>
        <filterItems>
            <field>Legal_Entity__c.Available_for_Internal_Project__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>HL Internal Opportunity</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_C1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/Opportunity_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for a prospective engagement.</description>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>OET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_VAT_Treatment__c/Opportunity_VAT_Treatment__c.object-meta.xml
<CustomObject>
    <label>Opportunity VAT Treatment</label>
    <nameField>
        <displayFormat>OVT-{000000}</displayFormat>
        <label>Opportunity VAT Treatment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity VAT Treatments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_VAT_Treatment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity VAT Treatments</relationshipLabel>
    <relationshipName>Opportunity_VAT_Treatments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_ContractHandler.cls
@isTest
public class Test_HL_ContractHandler {
    
    @isTest
    static void updateContractTest(){
        
        HL_Auto_Number_Settings__c autoNumber= new HL_Auto_Number_Settings__c();
        autoNumber.Name = 'Account';
        autoNumber.Auto_Number__c = 100;
        insert autoNumber;
        
        Legal_Entity__c legalEntity = new Legal_Entity__c();
        legalEntity.name = 'HL Inc.';
        legalEntity.Available_for_Project__c = true;
        legalEntity.ERP_VAT_Legal_Entity__c = true;
        legalEntity.ERP_Entity_Code__c = '030';
        insert legalEntity;
        
        Account account = new Account();
        account.Name = 'Account Test 1';
        account.BillingCountry = 'United States';
        insert account;
        
        Contact contact = new Contact();
        contact.FirstName = 'Contact';
        contact.LastName = 'Test145';
        contact.Email = 'contacttest145@test145.com';
        contact.Phone = '9999999999';
        contact.AccountId = account.Id;
        contact.Title = 'CFO';
        insert contact;
        
        Opportunity__c opportunity = new Opportunity__c();
        opportunity.Name = 'Engagement 125';
        opportunity.Client__c = account.Id;
        opportunity.Subject__c = account.Id;
        opportunity.Legal_Entity__c = legalEntity.Id;
        opportunity.Beneficial_Owner_Control_Person_form__c = 'No';
        insert opportunity;
        
        
        Opportunity_External_Team__c oppExternal = new Opportunity_External_Team__c();
        oppExternal.Contact__c = contact.id;
        oppExternal.Opportunity__c = opportunity.id;
        oppExternal.Billing_Contact__c = True;
        oppExternal.Acknowledge_Billing_Contact__c = True;
        insert oppExternal;
        
        Engagement__c engagement = new Engagement__c();
        engagement.Name = 'Engagement 125';
        engagement.Client__c = account.Id;
        engagement.Subject__c = account.Id;
        engagement.Legal_Entity__c = legalEntity.Id;
        insert engagement;
        
        Engagement_External_Team__c engExternal = new Engagement_External_Team__c();
        engExternal.Contact__c = contact.id;
        engExternal.Engagement__c = engagement.id;
        engExternal.Billing_Contact__c = True;
        engExternal.Acknowledge_Billing_Contact__c = True;
        insert engExternal;
        
        Engagement_VAT_Treatment__c engVATTreatment = new Engagement_VAT_Treatment__c();
        engVATTreatment.Engagement__c = engagement.Id;
        engVATTreatment.Effective_Date__c = system.today();
        engVATTreatment.Treatment__c = 'Standard Rated';
        insert engVATTreatment;
        
       /* Opportunity_VAT_Treatment__c oppVATTreatment = new Opportunity_VAT_Treatment__c();
        oppVATTreatment.Opportunity__c = opportunity.Id;
        oppVATTreatment.Effective_Date__c = system.today();
        oppVATTreatment.Treatment__c = 'Standard Rated';
        insert oppVATTreatment; */
        
        test.startTest();
        List<Contract__c> contractList = new List<Contract__c>();
        Contract__c contract = new Contract__c();
        contract.Name = 'Contract Test 1';
        contract.Bill_To__c = account.Id;
        contract.Client__c = account.Id;
        contract.Ship_To__c = account.Id;
        contract.Billing_Contact__c = contact.Id;
        contract.Engagement__c = engagement.Id;
        contract.ERP_Contract_Type__c = 'Engagement';
        contract.HL_Entity__c = '030';
        contractList.add(contract);
        
        Contract__c icoContract = new Contract__c();
        icoContract.Name = 'Contract Test 1';
        icoContract.Bill_To__c = account.Id;
        icoContract.Client__c = account.Id;
        icoContract.Ship_To__c = account.Id;
        icoContract.Billing_Contact__c = contact.Id;
        icoContract.Engagement__c = engagement.Id;
        icoContract.ERP_Contract_Type__c = 'ICO';
        icoContract.HL_Entity__c = '030';
        contractList.add(icoContract);
        
        Contract__c oppContract = new Contract__c();
        oppContract.Name = 'Contract Test 1';
        oppContract.Bill_To__c = account.Id;
        oppContract.Client__c = account.Id;
        oppContract.Ship_To__c = account.Id;
        oppContract.Billing_Contact__c = contact.Id;
        oppContract.Opportunity__c = opportunity.Id;
        oppContract.ERP_Contract_Type__c = 'Engagement';
        oppContract.HL_Entity__c = '030';
        contractList.add(oppContract);
        
        Contract__c oppIPOContract = new Contract__c();
        oppIPOContract.Name = 'Contract Test 1';
        oppIPOContract.Bill_To__c = account.Id;
        oppIPOContract.Client__c = account.Id;
        oppIPOContract.Ship_To__c = account.Id;
        oppIPOContract.Billing_Contact__c = contact.Id;
        oppIPOContract.Opportunity__c = opportunity.Id;
        oppIPOContract.ERP_Contract_Type__c = 'ICO';
        oppIPOContract.HL_Entity__c = '030';
        contractList.add(oppIPOContract);
        
        insert contractList;
        test.stopTest();
    }
}