force-app/main/default/objects/Contact/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mentor)</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERP_Invoice_Detail__c/ERP_Invoice_Detail__c.object-meta.xml
<CustomObject>
    <description>This will store the invoice details, sent from the ERP application</description>
    <label>ERP Invoice Detail</label>
    <nameField>
        <displayFormat>ID-{YYYY}{MM}-{0}</displayFormat>
        <label>ERP Invoice Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Invoice Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERP_Invoice_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>ERP Invoice Details</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Staff Role</label>
    <referenceTo>Staff_Role__c</referenceTo>
    <relationshipLabel>Opportunity Internal Teams</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/Staff_Role__c.object-meta.xml
<CustomObject>
    <description>Used internally to control staff role display and order.</description>
    <label>Staff Role</label>
    <nameField>
        <label>Staff Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HL_dupOppInternalCheckSchCls.cls
global class HL_dupOppInternalCheckSchCls implements Schedulable{
    global void execute(SchedulableContext ctx){        
List<DuplicateOppInternalWrapper> lstDuplicateOppInternal = new List<DuplicateOppInternalWrapper>();
Set<String> setOppIds = new Set<String>();

        String htmlBody = '<html><head><style>table {font-family: arial, sans-serif; border-collapse: collapse; width: 100%;}td, th { border: 1px solid #dddddd;  text-align: left;  padding: 8px;}tr:nth-child(even) {  background-color: #dddddd;}</style></head><body> <P> This automated message is to inform you of the following duplicate records on Opportunity Internal Team </p> <br/><table><tr><th>Opportunity Number</th><th>Opportunity</th><th>Line Of Business</th><th>Contact</th><th>Duplicate Staff Role Name</th></tr>';
        List<AggregateResult> grpInternalTeamRecords = [Select Opportunity__r.Name OppName,Opportunity__c oppId, Staff_Role__r.Name SName, Contact__r.Name conName, Contact__c ConId, count(Name) dupCount from opportunity_Internal_Team__c where End_Date__c = null AND CreatedDate = LAST_N_DAYS:365 group by Opportunity__r.Name,Opportunity__c, Staff_Role__r.Name, Contact__r.Name, Contact__c having count(Name) > 1 limit 200];
        if(grpInternalTeamRecords != null && grpInternalTeamRecords.size() > 0){
            for(AggregateResult ar : grpInternalTeamRecords){
                Integer recCount = Integer.valueOf(ar.get('dupCount'));
                if(recCount > 1){
DuplicateOppInternalWrapper objDuplicateOppInternal = new DuplicateOppInternalWrapper();
objDuplicateOppInternal.OppName = String.valueOf(ar.get('OppName'));
objDuplicateOppInternal.OppId = String.valueOf(ar.get('oppId'));
objDuplicateOppInternal.ContactName = String.valueOf(ar.get('conName'));
objDuplicateOppInternal.ContactId = String.valueOf(ar.get('ConId'));
objDuplicateOppInternal.StaffRole = String.valueOf(ar.get('SName'));
lstDuplicateOppInternal.add(objDuplicateOppInternal);
setOppIds.add(objDuplicateOppInternal.OppId);
                }
            }
if(setOppIds.size() > 0){
Map<String,Opportunity__c> mapOpp = new Map<String,Opportunity__c>([SELECT Id, Opportunity_Number__c, Line_Of_Business__c FROM Opportunity__c WHERE Id in :setOppIds]);
for(DuplicateOppInternalWrapper objDuplicateOppInternal : lstDuplicateOppInternal){
htmlBody = htmlBody + '<tr><td>'+ mapOpp.get(objDuplicateOppInternal.OppId).Opportunity_Number__c+'</td><td><a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/' + objDuplicateOppInternal.OppId + '">' + objDuplicateOppInternal.OppName + '</a></td><td>' + mapOpp.get(objDuplicateOppInternal.OppId).Line_Of_Business__c + '</td><td><a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/' + objDuplicateOppInternal.ContactId + '">' + objDuplicateOppInternal.ContactName + '</a></td><td>'+objDuplicateOppInternal.StaffRole+'</td></tr>';
}
htmlBody = htmlBody + '</table> <br/> <p> Thanks and Regards, <br/> Salesforce Administrator. </p> </body></html>';
List<String> userIdsToSendEmail = new List<String>();
Map<String,User> mapGrpUsers = new Map<String,User>([Select Email from User where Id in (SELECT UserOrGroupId FROM GroupMember where Group.Name = 'InternalTeamDuplicateNotification')]);
if(mapGrpUsers != null && mapGrpUsers.size() > 0){
userIdsToSendEmail.addAll(mapGrpUsers.keySet());        
Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
mail.setToAddresses(userIdsToSendEmail);
mail.setSubject('Duplicate Opportunity Internal Team Role ');
mail.setHTMLBody(htmlBody);
    try{
Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });   
    }
    catch(Exception ex){
        System.debug(ex);
    }
}
}
           
        }
    }
public class DuplicateOppInternalWrapper{
public string OppName {get;set;}
public string OppId {get;set;}
public string ContactName {get;set;}
public string ContactId {get;set;}
public string StaffRole {get;set;}
}
     
   }