force-app/main/default/objects/Contact/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>FVA</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eng_VP__c/Eng_VP__c.object-meta.xml
<CustomObject>
    <label>Engagement Valuation Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Valuation Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Valuation Periods</relationshipLabel>
    <relationshipName>Engagement_Portfolio_Valuations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eng_VP__c/fields/Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Valuation_Date__c</fullName>
    <label>Valuation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/Eng_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Engagement Valuation Period Positions linked with Engagement and Companies</description>
    <label>Eng Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eng Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eng_VP_Position__c/fields/Report_Fee__c.field-meta.xml
<CustomField>
    <fullName>Report_Fee__c</fullName>
    <label>Report Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eng_VP_Position__c/fields/Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Valuation_Date__c</fullName>
    <formula>Engagement_VP__r.Valuation_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_of_Business__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activism Advisory</fullName>
            </value>
            <value>
                <fullName>Board Advisory Services (BAS)</fullName>
            </value>
            <value>
                <fullName>Buyside</fullName>
            </value>
            <value>
                <fullName>Buyside &amp; Financing Advisory</fullName>
            </value>
            <value>
                <fullName>Collateral Valuation</fullName>
            </value>
            <value>
                <fullName>Compensation/Formula Analysis</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Corporate Alliances</fullName>
            </value>
            <value>
                <fullName>Creditor Advisors</fullName>
            </value>
            <value>
                <fullName>CVAS - Forensic Services</fullName>
            </value>
            <value>
                <fullName>CVAS - FV Opinion</fullName>
            </value>
            <value>
                <fullName>CVAS - Goodwill or Asset Impairment</fullName>
            </value>
            <value>
                <fullName>CVAS - Pre-Acq Val&apos;n Cons</fullName>
            </value>
            <value>
                <fullName>CVAS - Purchase Price Allocation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 123R/409A Stock, Option Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - SFAS 133 Derivatives, Liabilities Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Sovereign Advisory</fullName>
            </value>
            <value>
                <fullName>CVAS - Tangible Asset Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Tax Valuation</fullName>
            </value>
            <value>
                <fullName>CVAS - Transfer Pricing</fullName>
            </value>
            <value>
                <fullName>Debt Advisory</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Advisors</fullName>
            </value>
            <value>
                <fullName>Discretionary Advisory</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Buyside</fullName>
            </value>
            <value>
                <fullName>DM&amp;A Sellside</fullName>
            </value>
            <value>
                <fullName>DRC - Ad Valorem Services</fullName>
            </value>
            <value>
                <fullName>DRC - Appointed Arbitrator/Mediator</fullName>
            </value>
            <value>
                <fullName>DRC - Contract Compliance</fullName>
            </value>
            <value>
                <fullName>DRC - Exp Cons-Arbitrat&apos;n</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Primary_Office__c.field-meta.xml
<CustomField>
    <fullName>Primary_Office__c</fullName>
    <label>Primary Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Settlement or Agreement Reached</fullName>
            </value>
            <value>
                <fullName>Book Prep/Underwriting</fullName>
            </value>
            <value>
                <fullName>In Market</fullName>
            </value>
            <value>
                <fullName>Received Indications of Interest</fullName>
            </value>
            <value>
                <fullName>Pre-LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Rec&apos;d Indications/Submitted Bid</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed Term Sheets</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Pending Regulatory Approval</fullName>
            </value>
            <value>
                <fullName>Verbally Retained</fullName>
            </value>
            <value>
                <fullName>Performing Analysis</fullName>
            </value>
            <value>
                <fullName>Ongoing Analysis</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Testimony</fullName>
            </value>
            <value>
                <fullName>Opinion Report</fullName>
            </value>
            <value>
                <fullName>Opinion Development</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Delivered Report</fullName>
            </value>
            <value>
                <fullName>Bill/File</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Valuation_Date__c</fullName>
    <label>Valuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_HL_ValuationPeriodPositionDelete.cls
@isTest
Private class Test_HL_ValuationPeriodPositionDelete {
    
    @testSetup 
    static void setup() {
        
        
        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, 2);        
        for(integer i = 0; i < accountList.size(); i++){
            accountList[i].Name = 'Test_Account' +i;        
            accountList[i].BillingCountry = 'United States';
            accountList[i].BillingState = 'California';
            accountList[i].ShippingCountry = accountList[i].BillingCountry;
            accountList[i].ShippingState = accountList[i].BillingState;
        }
        
        insert accountList;
        
        List<Contact> CList = (List<Contact>)HL_TestFactory.CreateSObjectList('Contact', false, 2);        
        for(integer i = 0; i < CList.size(); i++){
            CList[i].FirstName = 'TestFirst' +i;
            CList[i].LastName = 'TestLast' +i;
            CList[i].AccountId = accountList[0].id;
        }
        Insert CList; 
        
        Engagement__c Engagement =(Engagement__c)HL_TestFactory.CreateSObject('Engagement__c',false);        
        Engagement.Name='Test_Engagement';
        Engagement.Client__c = accountList[0].Id;
        Engagement.Subject__c = accountList[0].Id;
        Engagement.Stage__c = 'Pitched';
        Engagement.Line_of_Business__c = 'CF';
        Engagement.Job_Type__c = 'Financing';
        Engagement.Primary_Office__c = 'AT';
        insert Engagement;
        
        List<Eng_VP__c> EngVPList = (List<Eng_VP__c>)HL_TestFactory.CreateSObjectList('Eng_VP__c',false,2);
        for(integer i = 0; i < EngVPList.size(); i++){
            EngVPList[i].Name='Test_Engagement_VP'+i;        
            EngVPList[i].Engagement__c=Engagement.id;
            EngVPList[i].Valuation_Date__c=System.Today();
            EngVPList[i].CurrencyIsoCode='USD';    
        }
        Insert EngVPList; 
        
        
        List<Eng_VP_Position__c> EngVPPosList = (List<Eng_VP_Position__c>)HL_TestFactory.CreateSObjectList('Eng_VP_Position__c',false,2);
        for(integer i = 0; i < EngVPPosList.size(); i++){
            EngVPPosList[i].Report_Fee__c=100;
            EngVPPosList[i].Asset_Classes__c='Debt';
            EngVPPosList[i].CurrencyIsoCode='USD';
            EngVPPosList[i].Engagement_VP__c=EngVPList[i].Id;
            EngVPPosList[i].Company__c=accountList[i].Id;
        }
        insert EngVPPosList; 
    }
    
    @isTest
    static void testBackAndDelete() {
        
        List<Eng_VP_Position__c> EngVPPosList = [select id, Name from Eng_VP_Position__c];
        List<Eng_VP__c> EngVPList = [select id, Name from Eng_VP__c];
        System.currentPageReference().getParameters().put('id',EngVPPosList[0].id) ;
        System.currentPageReference().getParameters().put('sObjectName', 'Eng_VP_Position__c');
        System.currentPageReference().getParameters().put('ReturnID', EngVPList[0].id);
        
        HL_ValuationPeriodPositionDeleteClass  clsObj = new HL_ValuationPeriodPositionDeleteClass();
        clsObj.Back();
        clsObj.onDelete();
    }
}