force-app/main/default/objects/Contact/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mentor)</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delegate_Public_Group__c/Delegate_Public_Group__c.object-meta.xml
<CustomObject>
    <description>used to store/manage all delegate public groups.</description>
    <label>Delegate Public Group</label>
    <nameField>
        <displayFormat>DPG-{0000}</displayFormat>
        <label>Delegate Public Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegate Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delegate_Public_Group__c/fields/Banker__c.field-meta.xml
<CustomField>
    <fullName>Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delegate_Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delegate_Public_Group__c/fields/Public_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_ID__c</fullName>
    <externalId>true</externalId>
    <label>Public Group ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Delegate_Public_Group_Member__c/Delegate_Public_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Delegate Public Group Member</label>
    <nameField>
        <displayFormat>DPGM-{0000}</displayFormat>
        <label>Delegate Public Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegate Public Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delegate_Public_Group_Member__c/fields/Delegate__c.field-meta.xml
<CustomField>
    <fullName>Delegate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delegate_Public_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delegate_Public_Group_Member__c/fields/Delegate_Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Delegate_Public_Group__c</fullName>
    <label>Delegate Public Group</label>
    <referenceTo>Delegate_Public_Group__c</referenceTo>
    <relationshipLabel>Delegate Public Group Members</relationshipLabel>
    <relationshipName>Delegate_Public_Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ERP_Invoice_Detail__c/ERP_Invoice_Detail__c.object-meta.xml
<CustomObject>
    <description>This will store the invoice details, sent from the ERP application</description>
    <label>ERP Invoice Detail</label>
    <nameField>
        <displayFormat>ID-{YYYY}{MM}-{0}</displayFormat>
        <label>ERP Invoice Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Invoice Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERP_Invoice_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>ERP Invoice Details</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/Opp_VP__c.object-meta.xml
<CustomObject>
    <label>Opportunity Valuation Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Valuation Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_VP__c/fields/Fee_Total__c.field-meta.xml
<CustomField>
    <fullName>Fee_Total__c</fullName>
    <description>sum of all related VP&apos;s Report Fee field</description>
    <label>Fee Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Opportunity record</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity_Portfolio_Valuations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/fields/Overall_VP_Status__c.field-meta.xml
<CustomField>
    <fullName>Overall_VP_Status__c</fullName>
    <description>Valuation Period Status</description>
    <label>Overall Valuation Period Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_VP__c/fields/Parent_Currency_Formula__c.field-meta.xml
<CustomField>
    <fullName>Parent_Currency_Formula__c</fullName>
    <formula>TEXT(Opportunity__r.CurrencyIsoCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Currency Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_VP__c/fields/ResultingEngagemnetRTonVP__c.field-meta.xml
<CustomField>
    <fullName>ResultingEngagemnetRTonVP__c</fullName>
    <description>Resulting Engagement Record Type On VP</description>
    <formula>Opportunity__r.Resulting_Egmt_Record_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ResultingEngagemnetRTonVP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_VP_Position__c/Opp_VP_Position__c.object-meta.xml
<CustomObject>
    <description>Opportunity Valuation Period Positions linked with Opportunity and Companies</description>
    <label>Opp Valuation Period Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opp Valuation Period Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_VP_Position__c/fields/Opportunity_VP__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_VP__c</fullName>
    <description>Related Opportunity</description>
    <label>Opportunity Valuation Period</label>
    <referenceTo>Opp_VP__c</referenceTo>
    <relationshipName>Opp_VP_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Opp_VP_Position__c/fields/Parent_Currency_Formula__c.field-meta.xml
<CustomField>
    <fullName>Parent_Currency_Formula__c</fullName>
    <formula>TEXT(Opportunity_VP__r.CurrencyIsoCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Currency Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_VP_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process__c</fullName>
    <label>Approval Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DND</fullName>
            </value>
            <value>
                <fullName>CONVERSION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Converted_to_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Engagement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is checked when an opportunity is converted into an engagement.  Validation rules on the conversion to Engagement should, in addition to their execution logic, check if this box is checked.</description>
    <label>Converted to Engagement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Engagement_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Approval_Status__c</fullName>
    <label>Engagement Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Requesting Engagement Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( RecordType.Name = &apos;FR&apos;, 
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
&apos;Active&apos;)))),

IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
&apos;Active&apos;)))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_Opp_VP_TriggerHelper.cls
public class HL_Opp_VP_TriggerHelper {
    
    public static void beforeInsert(List<Opp_VP__c> newOoppVPList, Map<Id, Opp_VP__c> newOoppVPMap, List<Opp_VP__c> oldOoppVPList , Map<Id, Opp_VP__c> oldOoppVPMap) {
        changeOwnershipToSystemAdmin(newOoppVPList);
        avoidChangesOnRollupFieldsOnVP('BeforeInsert', newOoppVPList, null, null, null);  
    }
    
    public static void afterInsert(List<Opp_VP__c> newOoppVPList, Map<Id, Opp_VP__c> newOoppVPMap, List<Opp_VP__c> oldOoppVPList , Map<Id, Opp_VP__c> oldOoppVPMap) { 
        SetupSharingforOppVp(newOoppVPList);
        
    }
    
    public static void beforeUpdate(List<Opp_VP__c> newOoppVPList, Map<Id, Opp_VP__c> newOoppVPMap, List<Opp_VP__c> oldOoppVPList , Map<Id, Opp_VP__c> oldOoppVPMap) {
        avoidChangesOnRollupFieldsOnVP('BeforeUpdate', newOoppVPList, newOoppVPMap, oldOoppVPList , oldOoppVPMap);     
    }
    /*
    public static void afterUpdate(List<Opp_VP__c> newOoppVPList, Map<Id, Opp_VP__c> newOoppVPMap, List<Opp_VP__c> oldOoppVPList , Map<Id, Opp_VP__c> oldOoppVPMap) {
    }*/
    
    public static void beforeDelete(List<Opp_VP__c> newOoppVPList, Map<Id, Opp_VP__c> newOoppVPMap, List<Opp_VP__c> oldOoppVPList , Map<Id, Opp_VP__c> oldOoppVPMap) {
        avoidChangesOnRollupFieldsOnVP('BeforeDelete',null,null,oldOoppVPList,null);  
        if(oldOoppVPMap != null)
            stopDeletion(oldOoppVPMap);
    //    if(newOoppVPList != null)   

    }
    /*
    public static void afterDelete(List<Opp_VP__c> newOoppVPList, Map<Id, Opp_VP__c> newOoppVPMap, List<Opp_VP__c> oldOoppVPList , Map<Id, Opp_VP__c> oldOoppVPMap) {

    }*/
    private static void stopDeletion(map<id, Opp_VP__c> oldOoppVPMap) {
        
        for(Opp_VP__c opVp : [Select id, Opportunity__r.Converted_to_Engagement__c, Opportunity__r.Approval_Process__c, Opportunity__r.Engagement_Approval_Status__c From Opp_Vp__c Where (Opportunity__r.Converted_to_Engagement__c = true OR (Opportunity__r.Approval_Process__c =: label.HL_AppProcessForEngNo AND Opportunity__r.Engagement_Approval_Status__c=: label.HL_Pending_EngReqNo)) AND Id IN : oldOoppVPMap.KeySet()]) {
            if(opVP.Opportunity__r.Converted_to_Engagement__c == true)
                oldOoppVPMap.get(opVp.Id).AddError(Label.HL_Val_Pos_Deleted_On_ConvtedOpp);
            if(opVp.Opportunity__r.Approval_Process__c == label.HL_AppProcessForEngNo && opVp.Opportunity__r.Engagement_Approval_Status__c == label.HL_Pending_EngReqNo)
                 oldOoppVPMap.get(opVp.Id).addError(Label.HL_Val_Pos_Deleted_ReqstedEngNo);
            
        }
        if(!HL_ConstantsUtil.IsSupervisorOrAdmin() && oldOoppVPMap != null && oldOoppVPMap.values() != null&& oldOoppVPMap.values().size() > 0 ) {
            oldOoppVPMap.values()[0].addError(Label.HL_No_Delete_Privilige_VP_Position);
        }
    }
    
    
    // To change owner of Opp VP records to System Administrator 
    private static void changeOwnershipToSystemAdmin(list<Opp_VP__c> newOoppVPList) {
        for(Opp_VP__c oppVP : newOoppVPList)
        {
                oppVP.ownerId = Label.Salesforce_Administrator_ID;
                oppVP.CurrencyIsoCode = OppVP.Parent_Currency_Formula__c;
        }
    }
    
    private static void SetupSharingforOppVp(list<Opp_VP__c> newOoppVPList) {       
        
        map<String, list<Id>> OpportunityWithRelatedTMDelegatedUserMap = new map<String, list<Id>>(); 
        Set<Id> RelatedOpportunityIdSet = new Set<Id>();
        for(Opp_VP__c opVp : newOoppVPList) 
        {
            RelatedOpportunityIdSet.add(opVp.Opportunity__c);
        }
        OpportunityWithRelatedTMDelegatedUserMap = fetchUserGroupToBeShared(RelatedOpportunityIdSet);
        SetupSharingCoreLogicForOppVP(newOoppVPList, OpportunityWithRelatedTMDelegatedUserMap);
        
    }       
    
    public static map<String, list<Id>> fetchUserGroupToBeShared(Set<Id> RelatedOpportunityIdSet) {        
        
        map<String, list<Id>> OpportunityWithRelatedTMDelegatedUserMap = new map<String, list<Id>>();
        list<Opportunity_Internal_Team__c> OppInternalTeamMemberList = new list<Opportunity_Internal_Team__c>();
        OppInternalTeamMemberList = [SELECT contact__r.user__c, Opportunity__c 
                                     FROM Opportunity_Internal_Team__c 
                                     WHERE End_Date__c = NULL AND contact__r.user__r.IsActive = True AND Opportunity__c IN : RelatedOpportunityIdSet];
                                                
        if(OppInternalTeamMemberList.size() > 0)
            OpportunityWithRelatedTMDelegatedUserMap = fetchUserGroupOnlyRelatedToOIT(OppInternalTeamMemberList);        
           
     
        Id PVSupervisorGrpId ;            
        for(Group grp:  [SELECT Id, Name     FROM Group WHERE Name =: system.Label.HL_PV_Portfolio_Valuation_Supervisors])
        {          
            if(grp.Name == system.Label.HL_PV_Portfolio_Valuation_Supervisors)
            {
                PVSupervisorGrpId = grp.Id;
            }
        }
        
        for(Id optyId : RelatedOpportunityIdSet)
        {            
            OpportunityWithRelatedTMDelegatedUserMap.put(optyId+'_PVSupervsr',new List<Id>{PVSupervisorGrpId});
        }       
        return OpportunityWithRelatedTMDelegatedUserMap;
    }    
    
    public static void SetupSharingCoreLogicForOppVP(list<Opp_VP__c> newOoppVPList , map<String, list<Id>> OpportunityWithRelatedTMDelegatedUserMap)
    {
        list<Opp_VP__share> SharingOppVPList = new list<Opp_VP__Share>();
        if(newOoppVPList != null )
        for(Opp_VP__c opVp : newOoppVPList) 
        {
            if(OpportunityWithRelatedTMDelegatedUserMap.containsKey(opVp.Opportunity__c+'_TM'))            
                for(Id UserGroupId : OpportunityWithRelatedTMDelegatedUserMap.get(opVp.Opportunity__c+'_TM'))
                {
                     if(UserGroupId != null && UserGroupId != opVp.ownerId)
                        SharingOppVPList.add(new Opp_VP__share(ParentId = opVp.id, UserOrGroupId = UserGroupId, Accesslevel = 'Edit'));
                }
            if(OpportunityWithRelatedTMDelegatedUserMap.containsKey(opVp.Opportunity__c+'_DU'))             
                for(Id UserGroupId : OpportunityWithRelatedTMDelegatedUserMap.get(opVp.Opportunity__c+'_DU'))
                {
                    if(UserGroupId != null && UserGroupId != opVp.ownerId)
                        SharingOppVPList.add(new Opp_VP__share(ParentId = opVp.id, UserOrGroupId = UserGroupId, Accesslevel = 'Edit'));
                }
            if(OpportunityWithRelatedTMDelegatedUserMap.containsKey(opVp.Opportunity__c+'_PVSupervsr'))
                for(Id UserGroupId : OpportunityWithRelatedTMDelegatedUserMap.get(opVp.Opportunity__c+'_PVSupervsr'))
                {
                    if(UserGroupId != null && UserGroupId != opVp.ownerId)
                        SharingOppVPList.add(new Opp_VP__share(ParentId = opVp.id, UserOrGroupId = UserGroupId, Accesslevel = 'Edit'));
                } 
            // Commented Code by Sandeep SF-820
            /*if(OpportunityWithRelatedTMDelegatedUserMap.containsKey(opVp.Opportunity__c+'_PVStafng'))
                for(Id UserGroupId : OpportunityWithRelatedTMDelegatedUserMap.get(opVp.Opportunity__c+'_PVStafng'))
                {
                    if(UserGroupId != null && UserGroupId != opVp.ownerId)
                        SharingOppVPList.add(new Opp_VP__share(ParentId = opVp.id, UserOrGroupId = UserGroupId, Accesslevel = 'Read'));
                }*/            
        }    
        
        if(SharingOppVPList.size() > 0 )
        {
            insert SharingOppVPList;
        }           
    }     
    
    public static map<String, list<Id>> fetchUserGroupOnlyRelatedToOIT(list<Opportunity_Internal_Team__c> OppInternalTeamMemberList) { 
        
        map<String, list<Id>> OpportunityWithRelatedTMDelegatedUserMap = new map<String, list<Id>>();
        map<Id, Set<Id>> userOpportunityMap = new map<Id, Set<Id>>();
        Set<id> matchingSet = new Set<id>();
        for(Opportunity_Internal_Team__c oit : OppInternalTeamMemberList)
        {
             if(!matchingSet.contains(oit.contact__r.user__c)){
                if(!OpportunityWithRelatedTMDelegatedUserMap.containskey(oit.Opportunity__c+'_TM'))
                    OpportunityWithRelatedTMDelegatedUserMap.put(oit.Opportunity__c+'_TM', new list<id>{oit.contact__r.user__c});
                else
                    OpportunityWithRelatedTMDelegatedUserMap.get(oit.Opportunity__c+'_TM').add(oit.contact__r.user__c);
                matchingSet.add(oit.contact__r.user__c);
            }
            if(!userOpportunityMap.containskey(oit.contact__r.user__c))
                userOpportunityMap.put(oit.contact__r.user__c, new set<id>{oit.Opportunity__c});
            else
                userOpportunityMap.get(oit.contact__r.user__c).add(oit.Opportunity__c);
            
        }
        
        map<Id, Set<Id>> UserWithDelegatedGroupIdMap = new map<Id, Set<Id>>();
            
        
        Set<id> relatedpublicGroupIdSet = new Set<Id>();
        if(userOpportunityMap.KeySet().size() > 0 )
        for(Delegate_Public_Group__c dpg : [SELECT Banker__c , Public_Group_ID__c, (select Delegate__c, Delegate_Public_Group__r.Banker__c  from Delegate_Public_Group_Members__r )
                                            FROM Delegate_Public_Group__c
                                            WHERE Banker__c IN : userOpportunityMap.KeySet()])
        {
            if(userOpportunityMap.containsKey(dpg.Banker__c))
                for(Id opportunityId : userOpportunityMap.get(dpg.Banker__c))
                {
                    if(!OpportunityWithRelatedTMDelegatedUserMap.containskey(opportunityId+'_DU'))
                        OpportunityWithRelatedTMDelegatedUserMap.put(opportunityId+'_DU',new list<id>{dpg.Public_Group_ID__c});             
                    else                    
                        OpportunityWithRelatedTMDelegatedUserMap.get(opportunityId+'_DU').add(dpg.Public_Group_ID__c);      
                }               
        }
        return OpportunityWithRelatedTMDelegatedUserMap;
    }
 
    public static void avoidChangesOnRollupFieldsOnVP(String eventType, List<Opp_VP__c> newOppVPList, Map<Id, Opp_VP__c> newOppVPMap, List<Opp_VP__c> oldOppVPList , Map<Id, Opp_VP__c> oldOppVPMap){        
        if(eventType == 'BeforeInsert'){
            for(Opp_VP__c newOppVPObj : newOppVPList) {  
               if(newOppVPObj.ResultingEngagemnetRTonVP__c != 'Portfolio_Valuation' )  
               {
                   newOppVPObj.addError(System.Label.HL_VP_Stop_Create_Edit_Delete);
               }        
               newOppVPObj.Fee_Total__c  = 0.0;                  
               newOppVPObj.Overall_VP_Status__c = 'New';       
            }
        }
        else if (eventType == 'BeforeUpdate'){
            List<Id> oppVPToProcess = new List <Id>();
            for(Opp_VP__c newOppVPObj : newOppVPList) {  
                if(newOppVPObj.ResultingEngagemnetRTonVP__c != 'Portfolio_Valuation' ){                
                     newOppVPObj.addError(System.Label.HL_VP_Stop_Create_Edit_Delete);
                }
                if(newOppVPObj.Name == '' || newOppVPObj.Name == null) {
                   newOppVPObj.addError(label.HL_Name_Required);                                      
                }     
                if((newOppVPObj.Fee_Total__c != oldOppVPMap.get(newOppVPObj.id).Fee_Total__c)||(newOppVPObj.Overall_VP_Status__c != oldOppVPMap.get(newOppVPObj.id).Overall_VP_Status__c )){
                    OppVPToProcess.add(newOppVPObj.Id);   
                }  
            }
            Map<String, String>strMap = new Map<String, String>();        
            for(Opp_VP__c  oppObj : [SELECT id, Fee_Total__c, Overall_VP_Status__c, (select id, Report_Fee__c, Status__c from Opp_VP_Positions__r) 
                             FROM Opp_VP__c 
                             WHERE ID IN : oppVPToProcess]){
                if(oppObj.Opp_VP_Positions__r.size() == 0) {
                    newOppVPMap.get(oppObj.id).Fee_Total__c = 0.0;  
                    newOppVPMap.get(oppObj.id).Overall_VP_Status__c = 'New';             
                }
                else {
                    decimal tempTotal = 0.0;
                    String tempStatus = 'Completed';
                    for(Opp_VP_Position__c oppVpPos : oppObj.Opp_VP_Positions__r) {  
                        if(oppVpPos!= null){
                            tempTotal += (oppVpPos.Report_Fee__c != null ?oppVpPos.Report_Fee__c : 0);  
                        }  
                        if (oppVpPos!= null && (oppVpPos.Status__c != 'Completed'))
                        {
                            tempStatus = 'In Progress';
                        }
                    }    
                    newOppVPMap.get(oppObj.id).Fee_Total__c = tempTotal;  
                    newOppVPMap.get(oppObj.id).Overall_VP_Status__c = tempStatus ;                                   
                }  
            } 
        }         
        if(eventType == 'BeforeDelete'){ 
            for(Opp_VP__c newOppVPObj : oldOppVPList) {  
               if(newOppVPObj.ResultingEngagemnetRTonVP__c != null && newOppVPObj.ResultingEngagemnetRTonVP__c != 'Portfolio_Valuation')  
               {
                   newOppVPObj.addError(System.Label.HL_VP_Stop_Create_Edit_Delete);
               } 
            }
       }          
    }
}