force-app/main/default/objects/Contact/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mentor)</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/Engagement_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for an engaged deal/project.</description>
    <label>Engagement Contact</label>
    <nameField>
        <displayFormat>EET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_External_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Invalid Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Engagement_Working_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Engagement_Working_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Key_External_Contact__c.field-meta.xml
<CustomField>
    <fullName>Key_External_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for FR Engagement Summary for FR LOB Post-Transaction  Tab</description>
    <inlineHelpText>This box should be checked if the contact should be contacted about post-transaction HL opportunities</inlineHelpText>
    <label>Key External Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement_External_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Accountant to Official Creditors Committee</fullName>
            </value>
            <value>
                <fullName>Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Adverse Party</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Attorney (Acquirer)</fullName>
            </value>
            <value>
                <fullName>Attorney (Target)</fullName>
            </value>
            <value>
                <fullName>Attorney Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Houlihan Lokey</fullName>
            </value>
            <value>
                <fullName>Audit Partner</fullName>
            </value>
            <value>
                <fullName>Balloting/Solicitation Agent</fullName>
            </value>
            <value>
                <fullName>Banker Advising Acquirer</fullName>
            </value>
            <value>
                <fullName>Banker Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Banker Advising Target</fullName>
            </value>
            <value>
                <fullName>Bank Group</fullName>
            </value>
            <value>
                <fullName>Bank Group - First Lien</fullName>
            </value>
            <value>
                <fullName>Bank Group - Second Lien</fullName>
            </value>
            <value>
                <fullName>Bank Lender</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Clerk</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Bank Group</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Board of Directors</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to DIP Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_EET.cls
public with sharing class HL_EET {
    public static List<Engagement_External_Team__c> GetByRole(id engagementId, string role){
        return [SELECT Contact__c, Contact__r.Name, Contact__r.Account.Name, Primary__c FROM Engagement_External_Team__c WHERE Engagement__c =: engagementId AND Role__c =: role ORDER BY Contact__r.Name];
    }
    
    public static List<Engagement_External_Team__c> GetByRecordTypeId(id engagementId, id recordTypeId){
        return [SELECT Contact__r.Name, Role__c FROM Engagement_External_Team__c WHERE Engagement__c =: engagementId AND RecordTypeId =: recordTypeId ORDER BY Contact__r.Name];
    }
    
    public static List<Engagement_External_Team__c> GetByRecordTypeIdFRExt(id engagementId, id recordTypeId){
        return [SELECT Contact__r.Name, Role__c FROM Engagement_External_Team__c WHERE Engagement__c =: engagementId AND RecordTypeId =: recordTypeId AND Key_External_Contact__c = TRUE ORDER BY Contact__r.Name];
    }
    
}