force-app/main/default/objects/Contact/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mentor)</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Primary_External_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_External_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary External Contact (updated via trigger)</description>
    <label>Primary External Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary External Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/Opportunity_External_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track client and external contacts for a prospective engagement.</description>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>OET-{000000}</displayFormat>
        <label>External Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Bill_To_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Billing_Country__c</fullName>
    <formula>Contact__r.Account.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Billing Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Bill_To_Company__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Company__c</fullName>
    <formula>Contact__r.Account.Name</formula>
    <label>Bill To Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Invalid Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Opportunity_Client_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/OET_UNIQUE__c.field-meta.xml
<CustomField>
    <fullName>OET_UNIQUE__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>OET UNIQUE</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>FVA TO, FMV, Fairness, Solvency and BAS  roles: 
-Adverse Party 
-Attorney 
-Banker 
-BoD 
-CEO 
-CFO 
-Company Mgmt 
-Fin Advisor 
-Independent Director 
-Majority Owner 
-Mgmt Contact
-Independent Director</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Accountant to Official Creditors Committee</fullName>
            </value>
            <value>
                <fullName>Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Adverse Party</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Attorney (Acquirer)</fullName>
            </value>
            <value>
                <fullName>Attorney (Target)</fullName>
            </value>
            <value>
                <fullName>Attorney Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Adverse Party Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Board/Special Committee</fullName>
            </value>
            <value>
                <fullName>Attorney to Company</fullName>
            </value>
            <value>
                <fullName>Attorney to Houlihan Lokey</fullName>
            </value>
            <value>
                <fullName>Audit Partner</fullName>
            </value>
            <value>
                <fullName>Balloting/Solicitation Agent</fullName>
            </value>
            <value>
                <fullName>Banker Advising Acquirer</fullName>
            </value>
            <value>
                <fullName>Banker Advising other Transaction Party</fullName>
            </value>
            <value>
                <fullName>Banker Advising Target</fullName>
            </value>
            <value>
                <fullName>Bank Group</fullName>
            </value>
            <value>
                <fullName>Bank Group - First Lien</fullName>
            </value>
            <value>
                <fullName>Bank Group - Second Lien</fullName>
            </value>
            <value>
                <fullName>Bank Lender</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Clerk</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Ad Hoc Noteholders Committee</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Bank Group</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Board of Directors</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to Company/Debtor</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Counsel to DIP Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_External_Team__c/fields/Sort_Role_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Role_Order__c</fullName>
    <defaultValue>&apos;00000&apos;</defaultValue>
    <description>Determines the role sort order for the Working Group List
Note: This must be text to allow grouping/sorting easily - numeric fields cannot be grouped in SF</description>
    <label>Sort Role Order</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_OpportunityExternalTeamHandler.cls
/*
* Name: HL_OpportunityExternalTeamHandler
* Created Date: 4/6/2015
* Description: Handler class for OpportunityExternalTeam records
* Modified Date: 12/10/2019
* Description:  Added the following methods for ERP Integration. The new methods are invoked from OnBeforeInsert and OnBeforeUpdate methods.
*   a) checkForBillToBillingCountry()
*/

public class HL_OpportunityExternalTeamHandler {
    private List<Opportunity_External_Team__c> OpportunityExternalTeam {get; set;}

    public HL_OpportunityExternalTeamHandler(List<Opportunity_External_Team__c> opportunityExternalTeam){
        this.OpportunityExternalTeam = opportunityExternalTeam;
    }

    //Populate The OET_UNIQUE__c Field
    public List<Opportunity_External_Team__c> UpdateOETUnique(){
        for(Opportunity_External_Team__c oet : OpportunityExternalTeam)
                oet.OET_UNIQUE__c = oet.Opportunity__c + '|' + oet.Contact__c;

        return OpportunityExternalTeam;
    }
    
    //Updates the Primary Opportunity Contact Lookup field on the Opportunities
    //Also updates the Primary Checkbox on other OIT fields to make sure only one is marked as primary per Opportunity
    public List<Opportunity_External_Team__c> UpdatePrimaryOpportunityContact(){
        Map<Id,Id> oppsToPrimaryOIT = new Map<Id,Id>(); //Map of Opportunities to Primary
        List<Opportunity__c> oppsToUpdate = new List<Opportunity__c>();
        List<Opportunity_External_Team__c> oetsToUpdate = new List<Opportunity_External_Team__c>();
        Set<Id> oets = new Set<Id>();
        Id primaryContact;
        for(Opportunity_External_Team__c oet: OpportunityExternalTeam){
            if(oet.Primary__c){
                oets.add(oet.Id);
                oppsToPrimaryOIT.put(oet.Opportunity__c, oet.Contact__c);
            }
        }
        //Update the Primary External Contact Lookup Field on the Opportunity
        if(oppsToPrimaryOIT.size() > 0){
            for(Opportunity__c o : [SELECT Primary_External_Contact__c FROM Opportunity__c WHERE Id IN:oppsToPrimaryOIT.keySet()]){
                primaryContact = oppsToPrimaryOIT.get(o.Id);
                if(o.Primary_External_Contact__c <> primaryContact){
                    o.Primary_External_Contact__c = primaryContact;
                    oppsToUpdate.add(o);
                }
            }
        }
        //Update the Opportunities that might have Changed
        if(oppsToUpdate.size() > 0){
            update oppsToUpdate;
            for(Opportunity_External_Team__c oet : [SELECT Primary__c FROM Opportunity_External_Team__c WHERE Id NOT IN:oets AND Opportunity__c IN:oppsToPrimaryOIT.keySet() AND Primary__c = true]){
                oet.Primary__c = false;
                oetsToUpdate.add(oet);
            }
            if(oetsToUpdate.size() > 0)
                update oetsToUpdate;
        }

        return OpportunityExternalTeam;
    }
    
    //Handle the Before Delete to Remove the Primary Reference if the Contact is Deleted
    public List<Opportunity_External_Team__c> RemovePrimaryOET(){
        Set<Id> oppIds = new Set<Id>(); //Store the Opportunities to Update
        List<Opportunity__c> oppsToUpdate = new List<Opportunity__c>();
        for(Opportunity_External_Team__c oet: OpportunityExternalTeam){
            if(oet.Primary__c)
                oppIds.add(oet.Opportunity__c);
        }
        for(Opportunity__c o : [SELECT Primary_External_Contact__c FROM Opportunity__c WHERE Id IN:oppIds]){
            o.Primary_External_Contact__c = null;
            oppsToUpdate.add(o);
        }
        if(oppsToUpdate.size() > 0)
            update oppsToUpdate; 

        return OpportunityExternalTeam;
    }
    
    public List<Opportunity_External_Team__c> UpdateSortFields(){
        Set<Id> oppIds = new Set<Id>();
        Set<String> roles = new Set<String>();
        Set<Id> contacts = new Set<Id>();
        Id oppId, acctId;
        String companySort, role, roleSort;
        
        for(Opportunity_External_Team__c oet : OpportunityExternalTeam){
            oppIds.add(oet.Opportunity__c);
            roles.add(oet.Role__c);
            contacts.add(oet.Contact__c);
        }
        
        //Get a contact map for the account Ids
        Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT AccountId FROM Contact WHERE Id IN:contacts]);
        
        for(AggregateResult ar : [SELECT Opportunity__c, Role__c, Contact__r.AccountId accountId, MAX(Sort_Role_Order__c) sortRole, MAX(Sort_Company_Order__c) sortCompany FROM Opportunity_External_Team__c WHERE Opportunity__c IN: oppIds AND Role__c IN: roles GROUP BY Opportunity__c, Role__c, Contact__r.AccountId]){
            oppId = (Id)ar.get('Opportunity__c');
            acctId = (Id)ar.get('accountId');
            role = (String)ar.get('Role__c');
            roleSort = (String)ar.get('sortRole');
            companySort = (String)ar.get('sortCompany');
            for(Opportunity_External_Team__c oet : OpportunityExternalTeam){
                if(oet.Opportunity__c == oppId && oet.Role__c == role){
                    oet.Sort_Role_Order__c = roleSort;
                    if(contactMap.get(oet.Contact__c).AccountId == acctId)
                        oet.Sort_Company_Order__c = companySort;
                }
            }
        }
        
        return OpportunityExternalTeam;
    }
    
    //Check if Bill To Company has a 'Billing Country'
    public List<Opportunity_External_Team__c> checkForBillToBillingCountry(){
        Set<Id> oppExtContactIds = new Set<Id>();
        Map<Id, Opportunity_External_Team__c> opptyExtTeamMap = new Map<Id, Opportunity_External_Team__c>();
        
        for(Opportunity_External_Team__c oet : OpportunityExternalTeam){
            system.debug('*** oet: ' + oet);
            if(oet.Billing_Contact__c == true 
               && (oet.Bill_To_Billing_Country__c == null || oet.Bill_To_Billing_Country__c == '')){
                   String errorMsg = 'Bill To company \'' +  oet.Bill_To_Company__c + '\' should have a Billing Country.';
                   oet.addError(errorMsg);
            }
        }       
        return OpportunityExternalTeam;
    }
}