force-app/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MU</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>/**stages to EXCLUDE**/
NOT(
  OR(
  ISPICKVAL(Stage__c, &apos;Dead&apos;),
  ISPICKVAL(Stage__c, &apos;Closed&apos;),
  ISPICKVAL(Stage__c, &apos;On Hold&apos;)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Determines whether an engagement is active for the purposes of pipeline manager, tearsheets and relationship aggregation calculations.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/recordTypes/Litigation.recordType-meta.xml
<RecordType>
    <fullName>Litigation</fullName>
    <active>true</active>
    <label>Litigation</label>
</RecordType>

force-app/main/default/objects/Engagement_Title_Rate_Sheet__c/Engagement_Title_Rate_Sheet__c.object-meta.xml
<CustomObject>
    <description>Engagement Title Rate Sheets: Junction Object between Engagements and Title Rate Sheets.  Used by the FAS Litigation (Dispute Resolution Consulting) Group</description>
    <label>Engagement Title Rate Sheet</label>
    <nameField>
        <label>Engagement Title Rate Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Title Rate Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Title_Rate_Sheet__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date for the Rate Sheet</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement_Title_Rate_Sheet__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <description>Related Engagement Record</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Title Rate Sheets</relationshipLabel>
    <relationshipName>Engagement_Title_Rate_Sheets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_Title_Rate_Sheet__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Rate Sheet Start Date</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement_Title_Rate_Sheet__c/fields/Title_Rate_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Title_Rate_Sheet__c</fullName>
    <description>Related Title Rate Sheet Record</description>
    <label>Title Rate Sheet</label>
    <referenceTo>Title_Rate_Sheet__c</referenceTo>
    <relationshipLabel>Engagement Title Rate Sheets</relationshipLabel>
    <relationshipName>Engagement_Title_Rate_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/Time_Record__c.object-meta.xml
<CustomObject>
    <description>Used to track time records</description>
    <label>Time Record</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Time Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/fields/Time_Record_Period_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period_Staff_Member__c</fullName>
    <description>Related time record period staff member record</description>
    <label>Time Record Period Staff Member</label>
    <referenceTo>Time_Record_Period_Staff_Member__c</referenceTo>
    <relationshipLabel>Time Records</relationshipLabel>
    <relationshipName>Time_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record__c/recordTypes/Litigation.recordType-meta.xml
<RecordType>
    <fullName>Litigation</fullName>
    <active>true</active>
    <description>Litigation Time Tracking Record</description>
    <label>Litigation</label>
</RecordType>

force-app/main/default/objects/Time_Record_Period__c/Time_Record_Period__c.object-meta.xml
<CustomObject>
    <description>Time record periods</description>
    <label>Time Record Period</label>
    <nameField>
        <displayFormat>TRP-{00000000}</displayFormat>
        <label>Time Record Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date for the Period</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period__c/fields/Period_Category__c.field-meta.xml
<CustomField>
    <fullName>Period_Category__c</fullName>
    <description>Used to categorize the period to allow for multiple functionalities</description>
    <label>Period Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beta</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Litigation</fullName>
                <default>true</default>
                <label>Litigation</label>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>TFR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Record_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Period Start date</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/Time_Record_Period_Staff_Member__c.object-meta.xml
<CustomObject>
    <label>Time Record Period Staff Member</label>
    <nameField>
        <displayFormat>TRPSM-{00000000}</displayFormat>
        <label>Time Record Period Staff Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Period Staff Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Staff member&apos;s office at time of creation</description>
    <label>Office</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Time_Record_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Record_Period__c</fullName>
    <description>Related time record period record</description>
    <label>Time Record Period</label>
    <referenceTo>Time_Record_Period__c</referenceTo>
    <relationshipLabel>Time Record Period Staff Members</relationshipLabel>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Staff Member&apos;s Title at time of Creation</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period_Staff_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related user record</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_Record_Period_Staff_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/Title_Rate_Sheet__c.object-meta.xml
<CustomObject>
    <description>Used by FVA Litigation Time Tracking (Dispute Resolution Consulting)</description>
    <label>Title Rate Sheet</label>
    <nameField>
        <label>Title Rate Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Title Rate Sheets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates the Rate Sheet is Active (Selectable)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Associate_Rate__c.field-meta.xml
<CustomField>
    <fullName>Associate_Rate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Associate Rate</description>
    <label>Associate Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Director_Rate__c.field-meta.xml
<CustomField>
    <fullName>Director_Rate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Director Rate</description>
    <label>Director Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Financial_Analyst_Rate__c.field-meta.xml
<CustomField>
    <fullName>Financial_Analyst_Rate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Financial Analyst Rate</description>
    <label>Financial Analyst Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Managing_Director_Rate__c.field-meta.xml
<CustomField>
    <fullName>Managing_Director_Rate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>MD Rate</description>
    <label>Managing Director Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Senior_Managing_Director_Rate__c.field-meta.xml
<CustomField>
    <fullName>Senior_Managing_Director_Rate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Senior MD Rate</description>
    <label>Senior Managing Director Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Senior_Vice_President_Rate__c.field-meta.xml
<CustomField>
    <fullName>Senior_Vice_President_Rate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>SVP Rate</description>
    <label>Senior Vice President Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Title_Rate_Sheet__c/fields/Vice_President_Rate__c.field-meta.xml
<CustomField>
    <fullName>Vice_President_Rate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>VP Rate</description>
    <label>Vice President Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_HL_EngagementTitleRateSheetHandler.cls
@isTest
private class Test_HL_EngagementTitleRateSheetHandler {
    @testSetup
    private static void SetupRateSheetData(){
        Time_Record_Period__c periodRecord = (Time_Record_Period__c)HL_TestFactory.CreateSObject('Time_Record_Period__c',false);
        Time_Record_Period_Staff_Member__c periodStaffMemberRecord = (Time_Record_Period_Staff_Member__c)HL_TestFactory.CreateSObject('Time_Record_Period_Staff_Member__c',false);
        List<Time_Record__c> timeRecordList = (List<Time_Record__c>)HL_TestFactory.CreateSObjectList('Time_Record__c',false, 10);
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        Engagement__c engagementRecord = HL_TestFactory.CreateEngagement(false);
        List<Title_Rate_Sheet__c> titleRateSheetList = (List<Title_Rate_Sheet__c>)HL_TestFactory.CreateSObjectList('Title_Rate_Sheet__c',false, 2);
        for(Title_Rate_Sheet__c rateSheetRecord : titleRateSheetList){
            rateSheetRecord.Active__c = true;
            rateSheetRecord.Financial_Analyst_Rate__c = 100.00;
            rateSheetRecord.Associate_Rate__c = 200.00;
            rateSheetRecord.Vice_President_Rate__c = 300.00;
            rateSheetRecord.Senior_Vice_President_Rate__c = 400.00;
            rateSheetRecord.Director_Rate__c = 500.00;
            rateSheetRecord.Managing_Director_Rate__c = 600.00;
            rateSheetRecord.Senior_Managing_Director_Rate__c = 700.00;
        }
        
        //Set Rates to Double on the Second Title Rate Sheet
        titleRateSheetList[1].Financial_Analyst_Rate__c = titleRateSheetList[1].Financial_Analyst_Rate__c * 2.0;
        titleRateSheetList[1].Associate_Rate__c = titleRateSheetList[1].Associate_Rate__c * 2.0;
        titleRateSheetList[1].Vice_President_Rate__c = titleRateSheetList[1].Vice_President_Rate__c * 2.0;
        titleRateSheetList[1].Senior_Vice_President_Rate__c = titleRateSheetList[1].Senior_Vice_President_Rate__c * 2.0;
        titleRateSheetList[1].Director_Rate__c = titleRateSheetList[1].Director_Rate__c * 2.0;
        titleRateSheetList[1].Managing_Director_Rate__c = titleRateSheetList[1].Managing_Director_Rate__c * 2.0;
        titleRateSheetList[1].Senior_Managing_Director_Rate__c = titleRateSheetList[1].Senior_Managing_Director_Rate__c * 2.0;
        
        //Set the Names to be sure order is Maintained
        titleRateSheetList[0].Name = 'Rate Sheet 01';
        titleRateSheetList[1].Name = 'Rate Sheet 02';
        
        insert titleRateSheetList;
        insert engagementRecord;
        
        periodRecord.Start_Date__c = Date.today();
        periodRecord.End_Date__c = Date.today().addDays(7);
        periodRecord.Period_Category__c = 'Litigation';
        periodStaffMemberRecord.Title__c = 'Financial Analyst';
        periodStaffMemberRecord.Office__c = 'LA';
        contactRecord.Office__c = 'LA';
        contactRecord.Title = 'Financial Analyst';
        contactRecord.User__c = UserInfo.getUserId();
        insert periodRecord;
        insert contactRecord;
        
        periodStaffMemberRecord.Contact__c = contactRecord.Id;
        periodStaffMemberRecord.Contact__r = contactRecord;
        periodStaffMemberRecord.Time_Record_Period__c = periodRecord.Id;
        periodStaffMemberRecord.Time_Record_Period__r = periodRecord;
        periodStaffMemberRecord.User__c = UserInfo.getuserId();
        
        insert periodStaffMemberRecord;
        for(Time_Record__c timeRecord : timeRecordList){
            timeRecord.Activity_Type__c = 'Consult';
            timeRecord.Time_Record_Period_Staff_Member__c = periodStaffMemberRecord.Id;
            timeRecord.Time_Record_Period_Staff_Member__r = periodStaffMemberRecord;
            timeRecord.Hourly_Rate__c = 0;
            timeRecord.Hours_Worked__c = 0.0;
            timeRecord.Seconds_Worked_Actual__c = 0;
            timeRecord.Engagement__c = engagementRecord.Id;
        }
        insert timeRecordList;
    }
    
    @isTest
    private static void TestRecordInsert(){
        Engagement__c engagementRecord = [SELECT Id FROM Engagement__c LIMIT 1];
        List<Title_Rate_Sheet__c> titleRateSheetList = HL_TitleRateSheet.GetActive();
        Engagement_Title_Rate_Sheet__c titleRateSheet = (Engagement_Title_Rate_Sheet__c)HL_TestFactory.CreateSObject('Engagement_Title_Rate_Sheet__c',false);
        
        Test.startTest();
        
        titleRateSheet.Engagement__c = engagementRecord.Id;
        titleRateSheet.Title_Rate_Sheet__c = titleRateSheetList[0].Id;
        titleRateSheet.Start_Date__c = Date.today();
        
        insert titleRateSheet;
        
        Test.stopTest();
        
        //Validate the Insert was Successful
        System.assert(!String.isBlank(titleRateSheet.Id));
        
        //Validate the Rate was Assigned
        for(Time_Record__c timeRecord : [SELECT Hourly_Rate__c FROM Time_Record__c WHERE Recording_Status__c = 'Complete'])
            System.assert(timeRecord.Hourly_Rate__c != 0.0);
    }
    
    @isTest
    private static void TestInsertOverlapFailure_SameStartDate(){
        Engagement__c engagementRecord = [SELECT Id FROM Engagement__c LIMIT 1];
        List<Title_Rate_Sheet__c> titleRateSheetList = HL_TitleRateSheet.GetActive();
        List<Engagement_Title_Rate_Sheet__c> engagementTitleRateSheetList = (List<Engagement_Title_Rate_Sheet__c>)HL_TestFactory.CreateSObjectList('Engagement_Title_Rate_Sheet__c', false,2);
        
        engagementTitleRateSheetList[0].Engagement__c = engagementRecord.Id;
        engagementTitleRateSheetList[1].Engagement__c = engagementRecord.Id;
        engagementTitleRateSheetList[0].Title_Rate_Sheet__c = titleRateSheetList[0].Id;
        engagementTitleRateSheetList[1].Title_Rate_Sheet__c = titleRateSheetList[0].Id;
        //Setting both with the same Start Date to verify failure
        engagementTitleRateSheetList[0].Start_Date__c = Date.today();
        engagementTitleRateSheetList[1].Start_Date__c = Date.today();
        
        insert engagementTitleRateSheetList[0];
        
        Test.startTest();
        
        Database.SaveResult result = Database.insert(engagementTitleRateSheetList[1], false);
        
        Test.stopTest();
        
        //Validate the Insert was Unsuccessful
        System.assertEquals(false, result.isSuccess());
    }
    
    @isTest
    private static void TestInsertOverlapFailure_DateOverlaps(){
        Engagement__c engagementRecord = [SELECT Id FROM Engagement__c LIMIT 1];
        List<Title_Rate_Sheet__c> titleRateSheetList = HL_TitleRateSheet.GetActive();
        List<Engagement_Title_Rate_Sheet__c> engagementTitleRateSheetList = (List<Engagement_Title_Rate_Sheet__c>)HL_TestFactory.CreateSObjectList('Engagement_Title_Rate_Sheet__c', false,2);
        
        engagementTitleRateSheetList[0].Engagement__c = engagementRecord.Id;
        engagementTitleRateSheetList[1].Engagement__c = engagementRecord.Id;
        engagementTitleRateSheetList[0].Title_Rate_Sheet__c = titleRateSheetList[0].Id;
        engagementTitleRateSheetList[1].Title_Rate_Sheet__c = titleRateSheetList[0].Id;
        //Setting date range overlap
        engagementTitleRateSheetList[0].Start_Date__c = Date.today();
        engagementTitleRateSheetList[0].End_Date__c = Date.today().addDays(100);
        engagementTitleRateSheetList[1].Start_Date__c = Date.today().addDays(75);
        
        insert engagementTitleRateSheetList[0];
        
        Test.startTest();
        
        Database.SaveResult result = Database.insert(engagementTitleRateSheetList[1], false);
        
        Test.stopTest();
        
        //Validate the Insert was Unsuccessful
        System.assertEquals(false, result.isSuccess());
    }
    
    @isTest
    private static void TestUpdate(){
        Engagement__c engagementRecord = [SELECT Id FROM Engagement__c LIMIT 1];
        List<Title_Rate_Sheet__c> titleRateSheetList = HL_TitleRateSheet.GetActive();
        List<Engagement_Title_Rate_Sheet__c> engagementTitleRateSheetList = (List<Engagement_Title_Rate_Sheet__c>)HL_TestFactory.CreateSObjectList('Engagement_Title_Rate_Sheet__c', false,2);
        Date today = Date.today();
        Date tomorrow = Date.today().addDays(1);
        Date yesterday = Date.today().addDays(-1);
        
        engagementTitleRateSheetList[0].Engagement__c = engagementRecord.Id;
        engagementTitleRateSheetList[1].Engagement__c = engagementRecord.Id;
        engagementTitleRateSheetList[0].Title_Rate_Sheet__c = titleRateSheetList[0].Id;
        engagementTitleRateSheetList[1].Title_Rate_Sheet__c = titleRateSheetList[1].Id;
        engagementTitleRateSheetList[0].Start_Date__c = today;
        engagementTitleRateSheetList[0].End_Date__c = today;
        engagementTitleRateSheetList[1].Start_Date__c = tomorrow;
        
        
        insert engagementTitleRateSheetList;
        
        //Store off the Time Records to Validate Later
        Map<Id, Time_Record__c> originalTimeRecordMap = new Map<Id, Time_Record__c>([SELECT Hourly_Rate__c FROM Time_Record__c]);
        
        //Update the Initial Rate Sheet
        Engagement_Title_Rate_Sheet__c engagementTitleRateSheetUpdateList = [SELECT Start_Date__c, End_Date__c, Engagement__c FROM Engagement_Title_Rate_Sheet__c WHERE Start_Date__c =: today LIMIT 1];
        engagementTitleRateSheetUpdateList.Start_Date__c = yesterday;
        engagementTitleRateSheetUpdateList.End_Date__c = yesterday;
        update engagementTitleRateSheetUpdateList;
        
        Engagement_Title_Rate_Sheet__c engagementTitleRateSheetNewUpdate = [SELECT Start_Date__c, End_Date__c, Engagement__c FROM Engagement_Title_Rate_Sheet__c WHERE Start_Date__c =: tomorrow LIMIT 1];
        engagementTitleRateSheetNewUpdate.Start_Date__c = today;
        
        Test.startTest();
        
        update engagementTitleRateSheetNewUpdate;
        
        Test.stopTest();
        
        //Validate the New Rate was Assigned - Should be Double the Original based on our Setup Data
        for(Time_Record__c timeRecord : [SELECT Hourly_Rate__c FROM Time_Record__c]){
            Decimal originalRate = originalTimeRecordMap.get(timeRecord.Id).Hourly_Rate__c;
            System.assertEquals(originalRate * 2.0, timeRecord.Hourly_Rate__c);
        }
    }
    
}