force-app/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MU</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <description>SEC Tracking of gifts to external Contacts</description>
    <label>Gift Request</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Approve_Date__c.field-meta.xml
<CustomField>
    <fullName>Approve_Date__c</fullName>
    <description>Date gift was approved/denied</description>
    <inlineHelpText>Date gift was approved/denied</inlineHelpText>
    <label>Approve Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Desired_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date the gift will be purchased by.</description>
    <inlineHelpText>Date the gift will be purchased by.</inlineHelpText>
    <label>Desired Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Value__c</fullName>
    <description>The gift&apos;s market value in the specified currency excluding the cost of tax, shipping, and engraving.</description>
    <inlineHelpText>The gift&apos;s market value in the specified currency excluding the cost of tax, shipping, and engraving.</inlineHelpText>
    <label>Gift Value</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Recipient_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Company_Name__c</fullName>
    <description>Recipient Company (Account) Name</description>
    <formula>Recipient__r.Account.Name</formula>
    <label>Recipient Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Submitted By Lookup to Contact</description>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Gift_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Submitted_For__c.field-meta.xml
<CustomField>
    <fullName>Submitted_For__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>HL Staff member giving gift</description>
    <inlineHelpText>HL Staff member giving gift</inlineHelpText>
    <label>Submitted For</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be submitted for a Houlihan Employee.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <infoMessage>Shows only Houlihan Employees.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Submitted_For</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SL_Gift.cls
public with sharing class SL_Gift implements Comparable {
    public Gift__c Gift {get; set;}
    public Boolean Selected {get; set;}
    public Decimal GiftYTD {get; set;}
    public Decimal GiftPrevYTD {get; set;}
    public SL_GiftRecipient Recipient {get; set;}        
    public static String SortField = 'GiftName';
    public static String SortDirection = 'ASC';    
    public SL_Gift(Gift__c gift, Decimal YTD, Decimal PrevYTD, SL_GiftRecipient recipient) {
            this.Gift = gift;
            this.Recipient = recipient;                                     
            Selected = false;
            GiftYTD = YTD;
            GiftPrevYTD = PrevYTD;
    }        
    public Decimal GetGiftValue(){        
        return GiftYTD-GiftPrevYTD;
    }
    public Boolean GetGiftValueOver(){        
        return recipient.IsValuePassedOver(getGiftValue());
    }
    public Boolean GetTotalOver(){
        return recipient.IsTotalOver(getGiftValue());
    }
     
    public Integer CompareTo(Object compareTo) {
        HL_GiftUtil.SortDirection = SortDirection;
        SL_Gift compareToObj = (SL_Gift)compareTo;        
        if(SortField == 'GiftName'){
            return HL_GiftUtil.CompareStringValues(Gift.Name, compareToObj.Gift.Name);
        }else if(SortField == 'Recipient'){
            return HL_GiftUtil.CompareStringValues(Recipient.recipient.Name, compareToObj.Recipient.recipient.Name);
        }else if(SortField == 'RecipientCompany'){
            return HL_GiftUtil.CompareStringValues(Gift.Recipient_Company_Name__c, compareToObj.Gift.Recipient_Company_Name__c);
        }else if(sortField == 'Office'){
            return HL_GiftUtil.CompareStringValues(Gift.Submitted_By__r.Office__c, compareToObj.Gift.Submitted_By__r.Office__c);
        }else if(SortField == 'SubmittedFor'){            
            return HL_GiftUtil.CompareStringValues(Gift.Submitted_For__r.Name, compareToObj.Gift.Submitted_For__r.Name);            
        }else if(SortField == 'SubmittedBy'){            
           return  HL_GiftUtil.CompareStringValues(Gift.Submitted_By__r.Name, compareToObj.Gift.Submitted_By__r.Name);
        }else if(sortField == 'DesiredDate'){
           return  HL_GiftUtil.CompareDateValues(Gift.Desired_Date__c, compareToObj.Gift.Desired_Date__c);
        }else if(SortField == 'ApprovalDate'){
           return  HL_GiftUtil.CompareDateTimeValues(Gift.Approve_Date__c, compareToObj.Gift.Approve_Date__c);
        }else if(SortField == 'CreatedDate'){
           return  HL_GiftUtil.CompareDateTimeValues(Gift.CreatedDate, compareToObj.Gift.CreatedDate);
        }else if(SortField == 'PrevYTD'){
           return  HL_GiftUtil.CompareCurrencyValues(GiftPrevYTD, compareToObj.GiftPrevYTD);
        }else if(SortField == 'GiftYTD'){
           return  HL_GiftUtil.CompareCurrencyValues(GiftYTD, compareToObj.GiftYTD);
        }else if(SortField == 'GiftValue'){
           return  HL_GiftUtil.CompareCurrencyValues(Gift.Gift_Value__c, compareToObj.Gift.Gift_Value__c);
        }   
        return null;
    }    
}