force-app/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MU</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/Engagement_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that are staffed on an engaged deal/project.</description>
    <label>Engagement Internal Team</label>
    <nameField>
        <displayFormat>EIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select HL employee</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Staff Role</label>
    <referenceTo>Staff_Role__c</referenceTo>
    <relationshipLabel>Engagement Internal Teams</relationshipLabel>
    <relationshipName>Engagement_Internal_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/Opportunity_Approval__c.object-meta.xml
<CustomObject>
    <description>These records are related to Opportunities and are required for submission before attaining committee approval and engagement.</description>
    <label>Opportunity Review</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Opportunity Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <inlineHelpText>Please indicate the related Opportunity record.</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Reviews</relationshipLabel>
    <relationshipName>Opportunity_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Houlihan Employee&apos;s office when added to Internal Team</description>
    <label>Office</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Staff Role</label>
    <referenceTo>Staff_Role__c</referenceTo>
    <relationshipLabel>Opportunity Internal Teams</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/Staff_Role__c.object-meta.xml
<CustomObject>
    <description>Used internally to control staff role display and order.</description>
    <label>Staff Role</label>
    <nameField>
        <label>Staff Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Role__c/fields/CF__c.field-meta.xml
<CustomField>
    <fullName>CF__c</fullName>
    <defaultValue>true</defaultValue>
    <label>CF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Engagement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_HL_InternalTeamController.cls
@isTest
private class Test_HL_InternalTeamController {
    
    Static List<Contact> cList ;
    Static List<Staff_Role__c> roleList;
    Static List<Engagement__c> engagementList;
    Static List<Opportunity_Internal_Team__c> oitList;
    Static List<Engagement_Internal_Team__c> eitList;
    Static Opportunity__c opp;
    
    
    static void PreparecommonData()
    {  
        cList = SL_TestSetupUtils.CreateContact('', 2, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE);
        for (Integer index = 0; index < cList.size(); index++)
            cList[index].User__c = UserInfo.getUserId();
        insert cList;
        
        roleList = new List<Staff_Role__c> {
                                             new Staff_Role__c(Name = 'Initiator', Display_Order__c = 1, Opportunity__c = True, CF__c = True), 
                                             new Staff_Role__c(Name = 'Analyst', Display_Order__c = 2, Opportunity__c = True, CF__c = True), 
                                             new Staff_Role__c(Name = 'Associate', Display_Order__c = 3, Opportunity__c = True, CF__c = True)
                };
        insert roleList;
    }
    static void createOppData(){ 
        PreparecommonData();
        opp = SL_TestSetupUtils.CreateOpp('', 1)[0];
        opp.Beneficial_Owner_Control_Person_form__c = 'No';
        insert opp;
        
        Opportunity_Approval__c oa = SL_TestSetupUtils.CreateOA('', 1)[0];
        oa.Related_Opportunity__c = opp.id;
        insert oa;  
        
        oitList = new List<Opportunity_Internal_Team__c> {
                new Opportunity_Internal_Team__c(Opportunity__c = opp.Id, Contact__c = cList[0].Id, Start_Date__c = Date.today(), Staff_Role__c = roleList[0].Id, Office__c = 'LA'),
                new Opportunity_Internal_Team__c(Opportunity__c = opp.Id, Contact__c = cList[1].Id, Start_Date__c = Date.today(), Staff_Role__c = roleList[0].Id, Office__c = 'CH')
                };
        insert oitList;
    }
    
    static void createEnggData(){ 
        PreparecommonData();
        engagementList = SL_TestSetupUtils.CreateEngagement('', 2);
        insert engagementList;
      
        eitList = new List<Engagement_Internal_Team__c> {
                new Engagement_Internal_Team__c(Engagement__c = engagementList[1].Id, Contact__c = cList[1].Id, Start_Date__c = Date.today(), Staff_Role__c = roleList[0].Id),
                new Engagement_Internal_Team__c(Engagement__c = engagementList[0].Id, Contact__c = cList[1].Id, Start_Date__c = Date.today(), Staff_Role__c = roleList[1].Id)
                };
        insert eitList;
    }
    
    @isTest 
    private static void TestBasicFunctionality1() {
        createOppData();
        Test.startTest();
            ApexPages.currentPage().getParameters().put('Id', opp.Id);
            HL_InternalTeamController itc = new HL_InternalTeamController();       
            List<HL_InternalTeamRecord> team = itc.TeamRecords;
            String customFilter = itc.CustomFilter;
            itc.BackToEntity();
            itc.EditClicked();
            itc.RefreshNewStaffRoles();
            Boolean ShowReturn = itc.ShowReturn;
            itc.SelectedStaffId = cList[0].id;
            itc.StaffMemberToAdd.RoleAssignments[0].Assigned = True;
            itc.SaveTeamEdits();   
        Test.stopTest();        
        System.assertEquals(itc.TeamRecords.size(), 2);        
    }
    
    @isTest 
    private static void TestBasicFunctionality2() {
        createEnggData();        
        Test.startTest();       
            ApexPages.currentPage().getParameters().put('Id', engagementList[0].Id);
            HL_InternalTeamController engITC = new HL_InternalTeamController();
            List<HL_InternalTeamRecord> engTeam = engITC.TeamRecords;
            engITC.BackToEntity();
            engITC.EditClicked();
            engITC.SelectedStaffId = cList[1].id;
            engITC.StaffMemberToAdd.RoleAssignments[0].Assigned = True;
            engITC.SaveTeamEdits();
            Contact cr = engITC.TeamRecords[0].ContactRecord;
            engITC.TeamRecords[0].RoleAssignments[0].Assigned = False;
            engITC.SaveTeamEdits();   
        Test.stopTest(); 
        System.assertEquals(engITC.TeamRecords.size(), 1);  
    }
 }