force-app/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MU</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Record_Period__c/Time_Record_Period__c.object-meta.xml
<CustomObject>
    <description>Time record periods</description>
    <label>Time Record Period</label>
    <nameField>
        <displayFormat>TRP-{00000000}</displayFormat>
        <label>Time Record Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Record Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Record_Period__c/fields/Period_Category__c.field-meta.xml
<CustomField>
    <fullName>Period_Category__c</fullName>
    <description>Used to categorize the period to allow for multiple functionalities</description>
    <label>Period Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beta</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Litigation</fullName>
                <default>true</default>
                <label>Litigation</label>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>TFR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
            <value>
                <fullName>FK</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HM</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LE</fullName>
            </value>
            <value>
                <fullName>LO</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MU</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_Group.cls
public class HL_Group {
    private String GroupName {get; set;}
    public HL_Group(String groupName){
        this.GroupName = groupName;
    }

    //Gets the contact records for the users within the group
    public List<Contact> GetContacts(){
        List<Contact> contactRecords = new List<Contact>();
        
        for(Contact c : [SELECT Name, Email, Office__c, Title, User__c FROM Contact WHERE User__c IN: HL_Group.GetGroupMembers(GroupName)])
                contactRecords.add(c);

        return contactRecords;
    }

    public static Group CreateGroup(String groupName,Boolean includeBosses){
        Group newGroup = new Group(Name = groupName, Type = 'Regular', DoesIncludeBosses = includeBosses);
        insert newGroup;
        return newGroup;
    }
    
    public static void AddGroupMembers(Id groupId, Set<Id> userIds){
        List<GroupMember> newMembers = new List<GroupMember>();
        
        for(Id userId : userIds){
            newMembers.add(new GroupMember(GroupId = groupId,UserOrGroupId = userId));
        }
        
        if(newMembers.size() > 0)
            insert newMembers;
    }
    
    public static Group DeleteGroup(Id groupId){
        Group deleteGroup = [SELECT Id FROM Group WHERE Id=:groupId];
        delete deleteGroup;
        return deleteGroup;
    }

    public static Boolean IsInGroup(String groupName){
        return IsInGroup(UserInfo.getUserId(), groupName);
    }
    public static Boolean IsInGroup(Id userOrGroupId, String groupName){
        List<GroupMember> gms = [SELECT Id FROM GroupMember WHERE UserOrGroupId =: userOrGroupId AND Group.DeveloperName =: groupName];
        return gms.size() > 0;
    }
    
    public static List<GroupMember> GetGroups(Id userId){
        List<GroupMember> gmList = [SELECT Group.DeveloperName FROM GroupMember WHERE UserOrGroupId =: userId];
        return gmList;
    }
    
    @AuraEnabled
    public static List<User> GetTimeTrackingGroupMembers(){
        return GetGroupMembers('Time_Tracking_' + GetTimeTrackingGroup());
    }

    @AuraEnabled
    public static List<User> GetGroupMembers(string groupName){
        Set<Id> userIds = new Set<Id>();
        
        for(GroupMember gm : [SELECT userOrGroupId FROM GroupMember WHERE Group.DeveloperName =: groupName])
            userIds.add(gm.UserOrGroupId);
        
        return [SELECT Name, Title, Phone, Email FROM User WHERE Id IN:userIds ORDER BY Name];
    }

    public static String GetTimeTrackingGroup(){
        List<String> categories = HL_Utility.GetPicklistValues('Time_Record_Period__c', 'Period_Category__c');
        List<GroupMember> groupList = GetGroups(UserInfo.getUserId());
        string category = '';
        
        //All Time Tracking Groups Should/Must Start with: Time_Tracking_
        for(string c : categories){
            for(GroupMember gm : groupList){
                if('Time_Tracking_' + c == gm.Group.DeveloperName || 'Time_Tracking_' + c + '_Supervisor' == gm.Group.DeveloperName){
                    category = c;
                    break;
                }
            }
        }

        return category;
    }
}