force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c, &quot;Closed&quot;), &quot;Closed&quot;,
IF(ISPICKVAL(Stage__c, &quot;Hold&quot;), &quot;Hold&quot;,
IF(ISPICKVAL(Stage__c, &quot;Dead&quot;), &quot;Dead&quot;,
&quot;Active&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Expense__c/Event_Expense__c.object-meta.xml
<CustomObject>
    <label>HL_Expense Request</label>
    <nameField>
        <displayFormat>EE{00000000}</displayFormat>
        <label>Expense Preapproval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HL_Expense Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Expense__c/fields/Is_Clone__c.field-meta.xml
<CustomField>
    <fullName>Is_Clone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Clone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Expense__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Requestor can only be HL internal employee</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL_Expense Requests (Requesting Officer)</relationshipLabel>
    <relationshipName>Event_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>More Information Requested</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>RFC#2547 - created new field as part of CF Expense Request functionality.</description>
    <inlineHelpText>Enter the city where the event will be held</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( RecordType.Name = &apos;FR&apos;, 
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
&apos;Active&apos;)))),

IF(ISPICKVAL(Stage__c, &apos;Hold&apos;),&apos;Hold&apos;,
IF(ISPICKVAL(Stage__c, &apos;Lost&apos;),&apos;Lost&apos;,
IF(ISPICKVAL(Stage__c, &apos;Dead&apos;),&apos;Dead&apos;,
IF(ISPICKVAL(Stage__c, &apos;Engaged&apos;),&apos;Engaged&apos;,
&apos;Active&apos;)))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities_C1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_ConstantsUtil.cls
@isTest
private class Test_HL_ConstantsUtil {
    @isTest
     public static void testUtilClassMethod() { 
         Boolean StopValidation = HL_ConstantsUtil.StopValidation; 
         Boolean AllowExecutionForManualInsertEngCounterparty = HL_ConstantsUtil.AllowExecutionForManualInsertEngCounterparty;
         Boolean stopCopyingNameFromCompToPosition = HL_ConstantsUtil.stopCopyingNameFromCompToPosition;
         Boolean engagementValue = HL_ConstantsUtil.engagementValue;
         Boolean stopExecuteEstFeeUpdateTrigger = HL_ConstantsUtil.stopExecuteEstFeeUpdateTrigger;
         Boolean stopExecutionForPVConversion = HL_ConstantsUtil.stopExecutionForPVConversion;
         HL_ConstantsUtil.IsSupervisorOrAdmin();
     } 
    Static testMethod void testUtilClassMethod1(){
        Profile profile1 = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User user1 = new User(
            Alias = 'standt01',
            Email='standarduser01@testorg.com', 
            EmailEncodingKey='UTF-8',
            LastName='Testing01',
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            ProfileId = profile1.Id, 
            TimeZoneSidKey='America/Los_Angeles',
            UserName='standarduser01@testorg1234.com');
        Insert user1;
        
        System.runAs(user1){
        System.assertEquals(true, HL_ConstantsUtil.IsHavingPVPermissionSetOrIsSysAdmin());     
        }
        
        Profile profile2 = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User user2 = new User(
            Alias = 'standt02',
            Email='standarduser02@testorg.com', 
            EmailEncodingKey='UTF-8',
            LastName='Testing02',
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            ProfileId = profile2.Id, 
            TimeZoneSidKey='America/Los_Angeles',
            UserName='standarduser02@testorg12345.com');
        Insert user2;
        
        System.runAs(user2){
        HL_ConstantsUtil.IsHavingPVPermissionSetOrIsSysAdmin();     
        }
            
    }
    @isTest
    public Static void testConstantsUtil(){
        Account account = new Account();
        account.Name = 'Account Test 1';
        account.BillingCountry = 'United States';
        insert account;
        
        Contact contact = new Contact();
        contact.FirstName = 'Contact';
        contact.LastName = 'Test145';
        contact.Email = 'contacttest145@test145.com';
        contact.Phone = '9999999999';
        contact.AccountId = account.Id;
        contact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Houlihan Employee').getRecordTypeId();
        insert contact;
        
        Opportunity__c opportunity = new Opportunity__c();
        opportunity.Name = 'Engagement 125';
        opportunity.Client__c = account.Id;
        opportunity.Subject__c = account.Id;
        opportunity.Beneficial_Owner_Control_Person_form__c = 'No';
        insert opportunity;
        
        Engagement__c engagement = new Engagement__c();
        engagement.Name = 'Engagement 125';
        engagement.Client__c = account.Id;
        engagement.Subject__c = account.Id;
        insert engagement;
         
        Profile profile1 = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User user1 = new User(
            Alias = 'standt',
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8',
            FirstName = 'Test',
            LastName='User',
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            ProfileId = profile1.Id, 
            TimeZoneSidKey='America/Los_Angeles',
            UserName='standarduser@testorg1234.com');
        Insert user1;
  
        System.runAs(user1){
        Event_Expense__c eveExp = new Event_Expense__c();
        eveExp.City__c = 'New York';
        eveExp.Start_Date__c = Date.newInstance(2019, 01, 26);
        eveExp.End_Date__c = Date.newInstance(2019, 06, 26);
        eveExp.Requestor_Name__c = contact.id ;
        eveExp.Is_Clone__c = true;
        eveExp.Status__c = 'Approved';
        insert eveExp;
        
        HL_ConstantsUtil.IshavingValidRoleInInternTeamEng(engagement.id);
        HL_ConstantsUtil.IshavingValidRoleInInternTeamOpp(opportunity.id);
        HL_ConstantsUtil.EventExpenseNonCAOPrivilegedUsers();
        HL_ConstantsUtil.getSingleQuotesStr('test');
        HL_ConstantsUtil.buildEventExpenseWhereClause(eveExp,'mon','fri','test','cl');
        }
    }
}