force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Report_Link__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Name of report that the end user will see</description>
    <label>Display Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/IsTableau__c.field-meta.xml
<CustomField>
    <fullName>IsTableau__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is being used in a workflow, that if the Report URL is a Tableau URL, then this field is checked TRUE.  The field is also used at the subscriber level in a formula, for reporting and list view criteria.</description>
    <label>Is Tableau</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_Link_URL__c</fullName>
    <description>Link that will execute the report</description>
    <label>Report Link URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Dashboards</fullName>
            </value>
            <value>
                <fullName>Accounting Group</fullName>
            </value>
            <value>
                <fullName>Company Group</fullName>
            </value>
            <value>
                <fullName>Company Single</fullName>
            </value>
            <value>
                <fullName>Contact Group</fullName>
            </value>
            <value>
                <fullName>Contact Single</fullName>
            </value>
            <value>
                <fullName>Engagement Group</fullName>
            </value>
            <value>
                <fullName>Engagement Single</fullName>
            </value>
            <value>
                <fullName>FSC Group</fullName>
            </value>
            <value>
                <fullName>Opportunity Group</fullName>
                <default>true</default>
                <label>Opportunity Group</label>
            </value>
            <value>
                <fullName>Opportunity Single</fullName>
            </value>
            <value>
                <fullName>My Dashboards</fullName>
            </value>
            <value>
                <fullName>Line of Business Dashboards</fullName>
            </value>
            <value>
                <fullName>Industry Group/Product Line Dashboards</fullName>
            </value>
            <value>
                <fullName>Revenue Group</fullName>
            </value>
            <value>
                <fullName>Sector Coverage Dashboards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates the order the links should be presented on the page</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/HL_Subscription__c.object-meta.xml
<CustomObject>
    <label>HL Subscription</label>
    <nameField>
        <displayFormat>SUB{00000}</displayFormat>
        <label>HL Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HL Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Subscription__c/fields/HL_Report_Link__c.field-meta.xml
<CustomField>
    <fullName>HL_Report_Link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Report to Link this Record To for Security Assignments</description>
    <inlineHelpText>Report to Link this Record To for Security Assignments</inlineHelpText>
    <label>HL Report Link</label>
    <referenceTo>HL_Report_Link__c</referenceTo>
    <relationshipLabel>HL Subscriptions</relationshipLabel>
    <relationshipName>HL_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Is_Tableau__c.field-meta.xml
<CustomField>
    <fullName>Is_Tableau__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to allow the related report to appear or not appear in the VF Web Tab for Tableau.  If true and the Report Link record has a Tableau URL, then the Display Name of the Report will appear in the drop down. to be selected and loaded.</description>
    <label>Is Tableau</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>This field is used to relist the value in the drop down within the VF web tab by priority over alphabetically.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the email recipient or the user that the security is applied to.</description>
    <inlineHelpText>This is the email recipient or the user that the security is applied to.</inlineHelpText>
    <label>Subscriber</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only HL Employees and Disribution Lists can be added to Subscriptions.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distribution_Lists</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Subscriptions (Subscriber)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>true</active>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/TableauDashboardController.cls
/*
2020-04-22 - Publicis Sapient - Created Class - Controller Class for TableauDashboardPage 
2020-07-23 - Publicis Sapient - Added logic to display My Dashboards picklist values in the dropdown
*/
public class TableauDashboardController {
    public List<SelectOption> dashboardOptions{get;set;}
    public String landingUrl{get;set;} 
    
    public TableauDashboardController() {
        // read the url parameter 'displayName' passed from the home page components and query for the dashboard to be displayed
        String displayName = Apexpages.currentPage().getParameters().get('displayName');
        List<HL_Report_Link__c> reportLinkList = [SELECT Id, Report_Link_URL__c, Report_Type__c 
                                                  FROM HL_Report_Link__c
                                                  WHERE Display_Name__c =: displayName
                                                  LIMIT 1];
        if(reportLinkList.size() > 0){
            landingUrl =  reportLinkList[0].Report_Link_URL__c;
            getDashboards();
        }
    }
    
    public List<SelectOption> getDashboards(){   
        /* update the  'Dashboard' picklist values that is accessible to the current logged in user 
           and filter the 'Dashboard' picklist based on the Report Type selected */
        String currentLoggedInUser = UserInfo.getUserId();
        List<String> reportLinkUrlSet = new List<String>();
        String selectClause = 'SELECT Id, HL_Report_Link__c, HL_Report_Link__r.Report_Link_URL__c, HL_Report_Link__r.Display_Name__c,'+
            +'Subscriber__c, Subscriber__r.Name, Subscriber__r.User__c'+ 
            + ' FROM HL_Subscription__c';
        String basicWhereClauseCondition = ' WHERE Subscriber__r.User__c = :currentLoggedInUser AND Active__c = TRUE AND Is_Tableau__c = TRUE  AND HL_Report_Link__r.Report_Type__c != \'My Dashboards\'';
        String orderByClause = ' ORDER BY Sort_Order__c';
        String query = selectClause + basicWhereClauseCondition + orderByClause;
        List<HL_Subscription__c> subscriptionList = Database.query(query);
        dashboardOptions = new List<SelectOption>();
        dashboardOptions.add(new SelectOption( '', '--None--'));
        for(HL_Subscription__c  subscription : subscriptionList)
        {
            if(subscription.HL_Report_Link__r.Report_Link_URL__c != null){
                reportLinkUrlSet.add(subscription.HL_Report_Link__r.Report_Link_URL__c);
                dashboardOptions.add(new SelectOption( subscription.HL_Report_Link__r.Report_Link_URL__c, subscription.HL_Report_Link__r.Display_Name__c));
            }
        }
        List<HL_Report_Link__c> reportLinkList = [SELECT Id, Name, Display_Name__c, Report_Link_URL__c
                                                  FROM HL_Report_Link__c
                                                  WHERE Report_Type__c = 'My Dashboards'
                                                  AND IsTableau__c = TRUE
                                                  ORDER BY Display_Name__c];
        for(HL_Report_Link__c reportLink : reportLinkList)
        {
            if(reportLink.Report_Link_URL__c != null){
                reportLinkUrlSet.add(reportLink.Report_Link_URL__c);
                dashboardOptions.add(new SelectOption(reportLink.Report_Link_URL__c, reportLink.Display_Name__c));
            }
        }
        dashboardOptions.sort();
        String displayName = Apexpages.currentPage().getParameters().get('displayName');
        if(displayName == null && reportLinkUrlSet.size() == 1){
            landingUrl = reportLinkUrlSet[0];
        }
        return dashboardOptions;
    }
}