force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Report_Link__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Name of report that the end user will see</description>
    <label>Display Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Home_Page_Access__c.field-meta.xml
<CustomField>
    <fullName>Home_Page_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Home Page Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/IsTableau__c.field-meta.xml
<CustomField>
    <fullName>IsTableau__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is being used in a workflow, that if the Report URL is a Tableau URL, then this field is checked TRUE.  The field is also used at the subscriber level in a formula, for reporting and list view criteria.</description>
    <label>Is Tableau</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_Link_URL__c</fullName>
    <description>Link that will execute the report</description>
    <label>Report Link URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Dashboards</fullName>
            </value>
            <value>
                <fullName>Accounting Group</fullName>
            </value>
            <value>
                <fullName>Company Group</fullName>
            </value>
            <value>
                <fullName>Company Single</fullName>
            </value>
            <value>
                <fullName>Contact Group</fullName>
            </value>
            <value>
                <fullName>Contact Single</fullName>
            </value>
            <value>
                <fullName>Engagement Group</fullName>
            </value>
            <value>
                <fullName>Engagement Single</fullName>
            </value>
            <value>
                <fullName>FSC Group</fullName>
            </value>
            <value>
                <fullName>Opportunity Group</fullName>
                <default>true</default>
                <label>Opportunity Group</label>
            </value>
            <value>
                <fullName>Opportunity Single</fullName>
            </value>
            <value>
                <fullName>My Dashboards</fullName>
            </value>
            <value>
                <fullName>Line of Business Dashboards</fullName>
            </value>
            <value>
                <fullName>Industry Group/Product Line Dashboards</fullName>
            </value>
            <value>
                <fullName>Revenue Group</fullName>
            </value>
            <value>
                <fullName>Sector Coverage Dashboards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates the order the links should be presented on the page</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Thumbnail_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_Image_Url__c</fullName>
    <description>This field is used to house the URL to the dashboard image that will then, be used in the SFDC Home Page Component of the subscriber with Home Page Access = TRUE.</description>
    <label>Thumbnail Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/HL_Subscription__c.object-meta.xml
<CustomObject>
    <label>HL Subscription</label>
    <nameField>
        <displayFormat>SUB{00000}</displayFormat>
        <label>HL Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HL Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Subscription__c/fields/HL_Report_Link__c.field-meta.xml
<CustomField>
    <fullName>HL_Report_Link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Report to Link this Record To for Security Assignments</description>
    <inlineHelpText>Report to Link this Record To for Security Assignments</inlineHelpText>
    <label>HL Report Link</label>
    <referenceTo>HL_Report_Link__c</referenceTo>
    <relationshipLabel>HL Subscriptions</relationshipLabel>
    <relationshipName>HL_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Home_Page_Access__c.field-meta.xml
<CustomField>
    <fullName>Home_Page_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to add/remove images within the home page component.  If true and the related report link has a thumbnail URL, then this report will appear in the component.</description>
    <label>Home Page Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Is_Tableau__c.field-meta.xml
<CustomField>
    <fullName>Is_Tableau__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to allow the related report to appear or not appear in the VF Web Tab for Tableau.  If true and the Report Link record has a Tableau URL, then the Display Name of the Report will appear in the drop down. to be selected and loaded.</description>
    <label>Is Tableau</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>This field is used to relist the value in the drop down within the VF web tab by priority over alphabetically.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the email recipient or the user that the security is applied to.</description>
    <inlineHelpText>This is the email recipient or the user that the security is applied to.</inlineHelpText>
    <label>Subscriber</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only HL Employees and Disribution Lists can be added to Subscriptions.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distribution_Lists</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Subscriptions (Subscriber)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>true</active>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/TableauHomePageDashboardController.cls
/*
2020-04-22 - Publicis Sapient - Created Class - Controller Class for hlHomePageDashboard lightning web component 
2020-07-23 - Publicis Sapient - Added getMyDashboardList method to display 'My Dashboards' on home page - controller class for hlHomePageMyDashboards lwc
*/
public class TableauHomePageDashboardController {
    @AuraEnabled(cacheable=true)
    public static List<DashboardWrapper> getDashboardList() {
        //get the current logged in user and query the thumbnail images to be displayed on the home page
        List<DashboardWrapper> dashboardWrapperList = new List<DashboardWrapper>();
        String currentLoggedInUser = UserInfo.getUserId();
        List<HL_Subscription__c> subscriptionList = [SELECT Id, HL_Report_Link__c, HL_Report_Link__r.Report_Link_URL__c, HL_Report_Link__r.Display_Name__c,
                                                     HL_Report_Link__r.Thumbnail_Image_Url__c, Subscriber__c, Subscriber__r.Name, Subscriber__r.User__c
                                                     FROM HL_Subscription__c
                                                     WHERE Subscriber__r.User__c = :currentLoggedInUser 
                                                     AND Active__c = TRUE
                                                     AND Is_Tableau__c = TRUE
                                                     AND Home_Page_Access__c = TRUE
                                                     AND HL_Report_Link__r.Report_Type__c != 'My Dashboards'
                                                     ORDER BY Sort_Order__c NULLS LAST];
        String tabId = getTabId();
        for(HL_Subscription__c subscription : subscriptionList){
            if(subscription.HL_Report_Link__r.Report_Link_URL__c != null){
                DashboardWrapper dashWrapper = new DashboardWrapper();
                dashWrapper.name = subscription.HL_Report_Link__r.Display_Name__c;
                dashWrapper.imageUrl = subscription.HL_Report_Link__r.Thumbnail_Image_Url__c;
                dashWrapper.url = subscription.HL_Report_Link__r.Report_Link_URL__c;
                dashboardWrapperList.add(dashWrapper);
            }
        }
        return dashboardWrapperList;
    }
    
    @auraEnabled(cacheable=true)
    public static List<DashboardWrapper> getMyDashboardList() {
        List<DashboardWrapper> dashboardWrapperList = new List<DashboardWrapper>();
        List<HL_Report_Link__c> hlReportLinkList = [SELECT Id, Report_Link_URL__c, Display_Name__c, Thumbnail_Image_Url__c, Report_Type__c
                                                    FROM HL_Report_Link__c
                                                    WHERE Report_Type__c = 'My Dashboards'
                                                    AND Home_Page_Access__c  = TRUE
                                                    AND IsTableau__c = TRUE];
        String tabId = getTabId();
        for(HL_Report_Link__c reportLink : hlReportLinkList){
            if(reportLink.Report_Link_URL__c != null){
                DashboardWrapper dashWrapper = new DashboardWrapper();
                dashWrapper.name = reportLink.Display_Name__c;
                dashWrapper.imageUrl = reportLink.Thumbnail_Image_Url__c;
                dashWrapper.url = reportLink.Report_Link_URL__c;
                dashWrapper.tabId = tabId;
                dashboardWrapperList.add(dashWrapper);
            }
        }
        return dashboardWrapperList;
    }
    
    public static String getTabId(){
        String tabId = '';
        List<TabDefinition> tabDefinitionList = [SELECT Id, Name, MobileUrl FROM TabDefinition WHERE Name = 'Tableau_Reports' LIMIT 1];
        system.debug('tabDefinitionList>>>'+tabDefinitionList);
        if(!tabDefinitionList.isEmpty()){
            tabId = tabDefinitionList[0].MobileUrl.substringAfter('sfdc.tabName=').left(15);
            system.debug('tabId>>>'+tabId);
        }
        return tabId;
    }
    
    public class DashboardWrapper{
        @auraEnabled
        public String name {get;set;}
        @auraEnabled
        public String imageUrl {get;set;}
        @auraEnabled 
        public String url {get;set;}
        @auraEnabled 
        public String tabId {get;set;}
    }
}