force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <description>SEC Tracking of gifts to external Contacts</description>
    <label>Gift Request</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <description>Whether the gift is approved</description>
    <inlineHelpText>Whether the gift is approved</inlineHelpText>
    <label>Approved</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency that the gift will be purchased in.</description>
    <inlineHelpText>Currency that the gift will be purchased in.</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Dollar</fullName>
                <default>true</default>
                <label>U.S. Dollar</label>
            </value>
            <value>
                <fullName>Euro (not in France)</fullName>
            </value>
            <value>
                <fullName>Euro (in France)</fullName>
            </value>
            <value>
                <fullName>British Pound</fullName>
            </value>
            <value>
                <fullName>Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>Australian Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Type__c.field-meta.xml
<CustomField>
    <fullName>Gift_Type__c</fullName>
    <description>Type of gift</description>
    <inlineHelpText>Type of gift</inlineHelpText>
    <label>Gift Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Charitable Contribution</fullName>
            </value>
            <value>
                <fullName>Closing Party Client Gifts</fullName>
            </value>
            <value>
                <fullName>Gifts: Customers</fullName>
            </value>
            <value>
                <fullName>Gifts: Customers Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Value__c</fullName>
    <description>The gift&apos;s market value in the specified currency excluding the cost of tax, shipping, and engraving.</description>
    <inlineHelpText>The gift&apos;s market value in the specified currency excluding the cost of tax, shipping, and engraving.</inlineHelpText>
    <label>Gift Value</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/HL_Relationship__c.field-meta.xml
<CustomField>
    <fullName>HL_Relationship__c</fullName>
    <label>HL Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Reason_For_Gift__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Gift__c</fullName>
    <description>Reason for the gift</description>
    <inlineHelpText>Reason for the gift</inlineHelpText>
    <label>Reason For Gift</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <description>External Contact to receive gift</description>
    <inlineHelpText>External Contact to receive gift</inlineHelpText>
    <label>Recipient For Gift</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Gift Requests (Recipient For Gift)</relationshipLabel>
    <relationshipName>Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Submitted By Lookup to Contact</description>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Gift_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Submitted_For__c.field-meta.xml
<CustomField>
    <fullName>Submitted_For__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>HL Staff member giving gift</description>
    <inlineHelpText>HL Staff member giving gift</inlineHelpText>
    <label>Submitted For</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be submitted for a Houlihan Employee.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <infoMessage>Shows only Houlihan Employees.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Submitted_For</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <description>Vendor to be used for gift.</description>
    <inlineHelpText>Vendor to be used for gift.</inlineHelpText>
    <label>Vendor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_HL_GiftSubmitterController.cls
@isTest
private class Test_HL_GiftSubmitterController {
    @testSetup
    private static void SetupSubmitterData(){
        List<Account> acctForContactList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, 2);
        List<Contact> internContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.Houlihan_Employee, false, 1);
        List<Contact> externContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, 1);
        List<Gift__c> giftList = (List<Gift__c>)HL_TestFactory.CreateSObjectList('Gift__c', false, 1);

        insert acctForContactList[0];

        internContactList[0].FirstName = 'TestInternFirstContact';
        internContactList[0].LastName = 'TestInternLastContact';
        internContactList[0].Account = AcctForContactList[0];
        internContactList[0].User__c = UserInfo.getUserId();
        insert internContactList[0];

        externContactList[0].FirstName = 'TestExterFirstContact';
        externContactList[0].LastName = 'TestExterLastContact';
        insert externContactList[0];

        giftList[0].Name = 'TestGift';
        giftList[0].Recipient__c = externContactList[0].Id;
        giftList[0].Submitted_For__c = internContactList[0].Id;
        giftList[0].Submitted_By__c = internContactList[0].Id;
        giftList[0].Gift_Type__c = 'Gift: Customers';
        giftList[0].Vendor__c = 'TestVendor';
        giftList[0].Currency__c = 'U.S. Dollar';
        giftList[0].HL_Relationship__c = 'Client';
        giftList[0].Gift_Value__c = 50.00;
        giftList[0].Reason_For_Gift__c = 'Test Reason';
        giftList[0].Approved__c = 'Pending';
        insert giftList[0];
    }

    @isTest
    private static void TestApprovedGifts() {
        Gift__c giftRecord =  [SELECT Name, Approved__c, Submitted_For__r.MailingCountry, CurrencyIsoCode
                               FROM Gift__c
                               LIMIT 1];

        Test.startTest();

        HL_GiftSubmitterController gsc = new HL_GiftSubmitterController();
        gsc.getYearFilterOptions();
        List<SelectOption> opts =  gsc.getApprovalOptions();
        System.assertEquals(3, opts.size());
        List<SL_Gift> savedGiftList = gsc.giftList;
        giftRecord.Approved__c='Approved';
        update giftRecord;
        gsc.viewType = 'Approved';
        gsc.yearFilter = Date.Today().Year();
        gsc.searchGifts();
        savedGiftList = gsc.giftList;

        Test.stopTest();

        System.assertEquals(1, savedGiftList.size());
    }

    @isTest
    private static void TestDeniedGifts() {
        Gift__c giftRecord =  [SELECT Name, Approved__c, Submitted_For__r.MailingCountry, CurrencyIsoCode
                               FROM Gift__c
                               LIMIT 1];

        Test.startTest();

        HL_GiftSubmitterController gsc = new HL_GiftSubmitterController();
        gsc.getYearFilterOptions();
        List<SelectOption> optionList =  gsc.getApprovalOptions();
        List<SL_Gift> savedGiftList = gsc.giftList;
        giftRecord.Approved__c='Denied';
        giftRecord.CurrencyIsoCode='';
        update giftRecord;
        gsc.viewType = 'Denied';
        gsc.searchGifts();
        savedGiftList = gsc.giftList;

        Test.stopTest();

        System.assertEquals(3, optionList.size());
        System.assertEquals(1, savedGiftList.size());
    }

    @isTest
    private static void TestPendingGifts(){
        Gift__c giftRecord =  [SELECT Name, Approved__c, Submitted_For__r.MailingCountry, CurrencyIsoCode
                               FROM Gift__c
                               LIMIT 1];

        Test.startTest();

        HL_GiftSubmitterController gsc = new HL_GiftSubmitterController();
        gsc.getYearFilterOptions();
        List<SelectOption> optionList =  gsc.getApprovalOptions();
        List<SL_Gift> savedGiftList = gsc.giftList;
        giftRecord.Approved__c='Pending';
        update giftRecord;
        gsc.viewType = 'Pending';
        gsc.yearFilter = Date.Today().Year();
        gsc.nameFilter = '';
        gsc.searchGifts();
        savedGiftList = gsc.giftList;
        PageReference pageRef = gsc.AddGift();
        gsc.ApplySort();
        gsc.ToggleDirection('GiftName');

        Test.stopTest();

        System.assertEquals(3, optionList.size());
        System.assertEquals(pageRef.getUrl(), '/apex/SL_GiftPreApproval');
        System.assertEquals(gsc.SortDirection, 'DESC');

    }
}