force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/Engagement_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that are staffed on an engaged deal/project.</description>
    <label>Engagement Internal Team</label>
    <nameField>
        <displayFormat>EIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select HL employee</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_General__c/HL_General__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store General Values that would otherwise be hard-coded
Would eventually like to move the default/profile ids in here too</description>
    <label>HL General</label>
</CustomObject>

force-app/main/default/objects/HL_General__c/fields/Mobile_Search_Result_Default__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Search_Result_Default__c</fullName>
    <defaultValue>200</defaultValue>
    <label>Mobile Search Result Default</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HL_General__c/fields/Mobile_Search_Result_Limit__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Search_Result_Limit__c</fullName>
    <defaultValue>800</defaultValue>
    <description>Store the Default Mobile Search Results Limit</description>
    <label>Mobile Search Result Limit</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <description>Custom object to track a contact-to-contact relationships.</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/External_Contact__c.field-meta.xml
<CustomField>
    <fullName>External_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>External Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No external contacts met the criteria for your search.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Relationships</relationshipLabel>
    <relationshipName>Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/HL_Contact__c.field-meta.xml
<CustomField>
    <fullName>HL_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>HL Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No Houlihan employees met the criteria for your search.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_MyObjectComponentController.cls
@isTest
private class Test_HL_MyObjectComponentController{
    private static final integer MobileSearchResultDefault =10;
    private static final integer MobileSearchResultLimit =20;
  @isTest
    private static void TestRetrievalOfCustomLimitSettings(){
        HL_General__c customSettings = new HL_General__c(Mobile_Search_Result_Default__c = MobileSearchResultDefault,
                                                    Mobile_Search_Result_Limit__c = MobileSearchResultLimit);
        insert customSettings;

        Test.startTest();

        integer mobileSearchResultsDefault = HL_MyObjectComponentController.GetMobileSearchResultDefault();
        integer mobileSearchResultsLimit = HL_MyObjectComponentController.GetMobileSearchResultLimit();

        Test.stopTest();

        System.assertEquals(customSettings.Mobile_Search_Result_Default__c, mobileSearchResultsDefault);
        System.assertEquals(customSettings.Mobile_Search_Result_Limit__c, mobileSearchResultsLimit);
    }

    @isTest
    private static void TestFindContactByName(){
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.External_Contact,false);
        insert contactRecord;

        Test.startTest();

        Test.setFixedSearchResults(new List<Id>{contactRecord.Id});

        List<Contact> contactResultsList = HL_MyObjectComponentController.FindByName('Contact', 'Test', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, contactResultsList.size());
    }

    @isTest
    private static void TestFindContactByNameNoResults(){
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.External_Contact,false);
        insert contactRecord;

        Test.startTest();

        List<Contact> contactResultsList = HL_MyObjectComponentController.FindByName('Contact', 'ZZ', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(0, contactResultsList.size());
    }

    @isTest
    private static void TestFindContactByNameUsingMultipleNameParts(){
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.External_Contact,false);
        contactRecord.FirstName = 'Jack';
        contactRecord.LastName = 'Banker';
        insert contactRecord;

        Test.startTest();

        Test.setFixedSearchResults(new List<Id>{contactRecord.Id});

        List<Contact> contactResultsList = HL_MyObjectComponentController.FindByName('Contact', 'Jack Banker', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, contactResultsList.size());
    }

    @isTest
    private static void TestFindMyContactByName(){
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        Contact externalContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.External_Contact,false);
        insert externalContactRecord;
        Relationship__c relationshipRecord = (Relationship__c)HL_TestFactory.CreateSObject('Relationship__c',false);
        relationshipRecord.External_Contact__c = externalContactRecord.Id;
        relationshipRecord.HL_Contact__c = houlihanContactRecord.Id;
        insert relationshipRecord;

        Test.startTest();

        List<Contact> contactResultsList = HL_MyObjectComponentController.FindByName('Contact', 'Test', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, contactResultsList.size());
    }

    @isTest
    private static void TestFindMyContactsDefaultResults(){
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Contact> externalContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, MobileSearchResultLimit);
        insert externalContactList;
        List<Relationship__c> relationshipList = (List<Relationship__c>)HL_TestFactory.CreateSObjectList('Relationship__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            relationshipList[index].External_Contact__c = externalContactList[index].Id;
            relationshipList[index].HL_Contact__c = houlihanContactRecord.Id;
        }
        insert relationshipList;

        Test.startTest();

        List<Contact> contactResultList = HL_MyObjectComponentController.FindByName('Contact', 'Test', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, contactResultList.size());
    }

    @isTest
    private static void TestFindMyContactsShowMoreResults(){
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Contact> externalContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, MobileSearchResultLimit);
        insert externalContactList;
        List<Relationship__c> relationshipList = (List<Relationship__c>)HL_TestFactory.CreateSObjectList('Relationship__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            relationshipList[index].External_Contact__c = externalContactList[index].Id;
            relationshipList[index].HL_Contact__c = houlihanContactRecord.Id;
        }
        insert relationshipList;

        Test.startTest();
    
        List<Contact> contactResultList = HL_MyObjectComponentController.FindByName('Contact', 'Test', true, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, contactResultList.size());
    }

    @isTest
    private static void TestFindContactsDefaultResults(){
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Contact> externalContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, MobileSearchResultLimit);
        insert externalContactList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Contact>([SELECT Id FROM Contact]).keySet()));
        List<Contact> contactResultList = HL_MyObjectComponentController.FindByName('Contact', 'Test', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, contactResultList.size());
    }

    @isTest
    private static void TestFindContactsShowMoreResults(){
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Contact> externalContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, MobileSearchResultLimit);
        insert externalContactList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Contact>([SELECT Id FROM Contact]).keySet()));
        List<Contact> contactResultList = HL_MyObjectComponentController.FindByName('Contact', 'Test', false, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, contactResultList.size());
    }

    @isTest
    private static void TestFindAccountByName(){
        Account accountRecord = (Account)HL_TestFactory.CreateSObject('Account', false);
        accountRecord.Name = 'Test Account';
        insert accountRecord;

        Test.startTest();

        Test.setFixedSearchResults(new List<Id>{accountRecord.Id});

        List<Account> accountResultsList = HL_MyObjectComponentController.FindByName('Company', 'Te', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, accountResultsList.size());
    }

    @isTest
    private static void TestFindMyAccountByName(){
        Account accountRecord = (Account)HL_TestFactory.CreateSObject('Account', false);
        accountRecord.Name = 'Test Account';
        insert accountRecord;
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        Contact externalContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.External_Contact,false);
        externalContactRecord.AccountId = accountRecord.Id;
        insert externalContactRecord;
        Relationship__c relationshipRecord = (Relationship__c)HL_TestFactory.CreateSObject('Relationship__c',false);
        relationshipRecord.External_Contact__c = externalContactRecord.Id;
        relationshipRecord.HL_Contact__c = houlihanContactRecord.Id;
        insert relationshipRecord;

        Test.startTest();

        List<Account> accountResultsList = HL_MyObjectComponentController.FindByName('Company', 'Test', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, accountResultsList.size());
    }

    @isTest
    private static void TestFindMyAccountsDefaultResults(){
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            accountList[index].Name = 'Test '+ String.valueOf(index);
        insert accountList;
        List<Contact> externalContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            externalContactList[index].AccountId = accountList[index].Id;
        }
        insert externalContactList;
        List<Relationship__c> relationshipList = (List<Relationship__c>)HL_TestFactory.CreateSObjectList('Relationship__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            relationshipList[index].External_Contact__c = externalContactList[index].Id;
            relationshipList[index].HL_Contact__c = houlihanContactRecord.Id;
        }
        insert relationshipList;

        Test.startTest();

        List<Account> accountResultList = HL_MyObjectComponentController.FindByName('Company', 'Test', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, accountResultList.size());
    }

    @isTest
    private static void TestFindMyAccountsShowMoreResults(){
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            accountList[index].Name = 'Test '+ String.valueOf(index);
        insert accountList;
        List<Contact> externalContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            externalContactList[index].AccountId = accountList[index].Id;
        }
        insert externalContactList;
        List<Relationship__c> relationshipList = (List<Relationship__c>)HL_TestFactory.CreateSObjectList('Relationship__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            relationshipList[index].External_Contact__c = externalContactList[index].Id;
            relationshipList[index].HL_Contact__c = houlihanContactRecord.Id;
        }
        insert relationshipList;

        Test.startTest();

        List<Account> accountResultList = HL_MyObjectComponentController.FindByName('Company', 'Test', true, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, accountResultList.size());
    }

    @isTest
    private static void TestFindAccountsDefaultResults(){
        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            accountList[index].Name = 'Test '+ String.valueOf(index);
        insert accountList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Account>([SELECT Id FROM Account]).keySet()));
        List<Account> accountResultList = HL_MyObjectComponentController.FindByName('Company', 'Test', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, accountResultList.size());
    }

    @isTest
    private static void TestFindAccountsShowMoreResults(){
        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            accountList[index].Name = 'Test '+ String.valueOf(index);
        insert accountList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Account>([SELECT Id FROM Account]).keySet()));
        List<Account> accountResultList = HL_MyObjectComponentController.FindByName('Company', 'Test', false, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, accountResultList.size());
    }

    @isTest
    private static void TestFindOpportunityByName(){
        Opportunity__c opportunityRecord = (Opportunity__c)HL_TestFactory.CreateSObject('Opportunity__c', false);
        opportunityRecord.Name = 'Test Opportunity';
        insert opportunityRecord;

        Test.startTest();

        Test.setFixedSearchResults(new List<Id>{opportunityRecord.Id});

        List<Opportunity__c> opportunityResultsList = HL_MyObjectComponentController.FindByName('Opportunity', 'Te', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, opportunityResultsList.size());
    }

    @isTest
    private static void TestFindMyOpportunityByName(){
        Opportunity__c opportunityRecord = (Opportunity__c)HL_TestFactory.CreateSObject('Opportunity__c', false);
        opportunityRecord.Name = 'Test Opportunity';
        insert opportunityRecord;
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        Opportunity_Internal_Team__c teamRecord = (Opportunity_Internal_Team__c)HL_TestFactory.CreateSObject('Opportunity_Internal_Team__c', false);
        teamRecord.Opportunity__c = opportunityRecord.Id;
        teamRecord.Contact__c = houlihanContactRecord.Id;
        insert teamRecord;

        Test.startTest();

        Test.setFixedSearchResults(new List<Id>{opportunityRecord.Id});

        List<Opportunity__c> opportunityResultsList = HL_MyObjectComponentController.FindByName('Opportunity', 'Te', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, opportunityResultsList.size());
    }

    @isTest
    private static void TestFindMyOpportunitiesDefaultResults(){
        List<Opportunity__c> opportunityRecordList = (List<Opportunity__c>)HL_TestFactory.CreateSObjectList('Opportunity__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            opportunityRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert opportunityRecordList;
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Opportunity_Internal_Team__c> teamRecordList = (List<Opportunity_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Opportunity_Internal_Team__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            teamRecordList[index].Opportunity__c = opportunityRecordList[index].Id;
            teamRecordList[index].Contact__c = houlihanContactRecord.Id;
        }
        insert teamRecordList;

        Test.startTest();

        List<Opportunity__c> opportunityResultList = HL_MyObjectComponentController.FindByName('Opportunity', 'Test', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, opportunityResultList.size());
    }

    @isTest
    private static void TestFindMyOpportunitiesShowMoreResults(){
        List<Opportunity__c> opportunityRecordList = (List<Opportunity__c>)HL_TestFactory.CreateSObjectList('Opportunity__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            opportunityRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert opportunityRecordList;
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Opportunity_Internal_Team__c> teamRecordList = (List<Opportunity_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Opportunity_Internal_Team__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            teamRecordList[index].Opportunity__c = opportunityRecordList[index].Id;
            teamRecordList[index].Contact__c = houlihanContactRecord.Id;
        }
        insert teamRecordList;

        Test.startTest();

        List<Opportunity__c> opportunityResultList = HL_MyObjectComponentController.FindByName('Opportunity', 'Test', true, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, opportunityResultList.size());
    }

    @isTest
    private static void TestFindOpportunitiesDefaultResults(){
        List<Opportunity__c> opportunityRecordList = (List<Opportunity__c>)HL_TestFactory.CreateSObjectList('Opportunity__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            opportunityRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert opportunityRecordList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Opportunity__c>([SELECT Id FROM Opportunity__c]).keySet()));
        List<Opportunity__c> opportunityResultList = HL_MyObjectComponentController.FindByName('Opportunity', 'Test', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, opportunityResultList.size());
    }

    @isTest
    private static void TestFindOpportunitiesShowMoreResults(){
        List<Opportunity__c> opportunityRecordList = (List<Opportunity__c>)HL_TestFactory.CreateSObjectList('Opportunity__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            opportunityRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert opportunityRecordList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Opportunity__c>([SELECT Id FROM Opportunity__c]).keySet()));
        List<Opportunity__c> opportunityResultList = HL_MyObjectComponentController.FindByName('Opportunity', 'Test', false, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, opportunityResultList.size());
    }

    @isTest
    private static void TestFindEngagementByName(){
        Engagement__c engagementRecord = (Engagement__c)HL_TestFactory.CreateSObject('Engagement__c', false);
        engagementRecord.Name = 'Test Engagement';
        insert engagementRecord;

        Test.startTest();

        Test.setFixedSearchResults(new List<Id>{engagementRecord.Id});
        List<Engagement__c> engagementResultsList = HL_MyObjectComponentController.FindByName('Engagement', 'Te', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, engagementResultsList.size());
    }

    @isTest
    private static void TestFindMyEngagementByName(){
        Engagement__c engagementRecord = (Engagement__c)HL_TestFactory.CreateSObject('Engagement__c', false);
        engagementRecord.Name = 'Test Engagement';
        insert engagementRecord;
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        Engagement_Internal_Team__c teamRecord = (Engagement_Internal_Team__c)HL_TestFactory.CreateSObject('Engagement_Internal_Team__c', false);
        teamRecord.Engagement__c = engagementRecord.Id;
        teamRecord.Contact__c = houlihanContactRecord.Id;
        insert teamRecord;

        Test.startTest();

        Test.setFixedSearchResults(new List<Id>{engagementRecord.Id});
        List<Engagement__c> engagementResultsList = HL_MyObjectComponentController.FindByName('Engagement', 'Te', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(1, engagementResultsList.size());
    }

    @isTest
    private static void TestFindMyEngagementsDefaultResults(){
        List<Engagement__c> engagementRecordList = (List<Engagement__c>)HL_TestFactory.CreateSObjectList('Engagement__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            engagementRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert engagementRecordList;
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Engagement_Internal_Team__c> teamRecordList = (List<Engagement_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Engagement_Internal_Team__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            teamRecordList[index].Engagement__c = engagementRecordList[index].Id;
            teamRecordList[index].Contact__c = houlihanContactRecord.Id;
        }
        insert teamRecordList;

        Test.startTest();

        List<Engagement__c> engagementResultList = HL_MyObjectComponentController.FindByName('Engagement', 'Test', true, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, engagementResultList.size());
    }

    @isTest
    private static void TestFindMyEngagementsShowMoreResults(){
        List<Engagement__c> engagementRecordList = (List<Engagement__c>)HL_TestFactory.CreateSObjectList('Engagement__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            engagementRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert engagementRecordList;
        Contact houlihanContactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        houlihanContactRecord.User__c = UserInfo.getUserId();
        insert houlihanContactRecord;
        List<Engagement_Internal_Team__c> teamRecordList = (List<Engagement_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Engagement_Internal_Team__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++){
            teamRecordList[index].Engagement__c = engagementRecordList[index].Id;
            teamRecordList[index].Contact__c = houlihanContactRecord.Id;
        }
        insert teamRecordList;

        Test.startTest();

        List<Engagement__c> engagementResultList = HL_MyObjectComponentController.FindByName('Engagement', 'Test', true, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, engagementResultList.size());
    }

    @isTest
    private static void TestFindEngagementsDefaultResults(){
        List<Engagement__c> engagementRecordList = (List<Engagement__c>)HL_TestFactory.CreateSObjectList('Engagement__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            engagementRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert engagementRecordList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Engagement__c>([SELECT Id FROM Engagement__c]).keySet()));
        List<Engagement__c> engagementResultList = HL_MyObjectComponentController.FindByName('Engagement', 'Test', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assertEquals(MobileSearchResultDefault, engagementResultList.size());
    }

    @isTest
    private static void TestFindEngagementsShowMoreResults(){
        List<Engagement__c> engagementRecordList = (List<Engagement__c>)HL_TestFactory.CreateSObjectList('Engagement__c', false, MobileSearchResultLimit);
        for(integer index = 0; index < MobileSearchResultLimit; index++)
            engagementRecordList[index].Name = 'Test ' + String.valueOf(index);
        insert engagementRecordList;

        Test.startTest();
    
        Test.setFixedSearchResults(new List<Id>(new Map<Id, Engagement__c>([SELECT Id FROM Engagement__c]).keySet()));
        List<Engagement__c> engagementResultList = HL_MyObjectComponentController.FindByName('Engagement', 'Test', false, MobileSearchResultLimit);

        Test.stopTest();

        System.assertEquals(MobileSearchResultLimit, engagementResultList.size());
    }

    @isTest
    private static void TestFindWithInvalidObjectType(){
        Test.startTest();

        List<sObject> resultsList = HL_MyObjectComponentController.FindByName('Account', 'Te', false, MobileSearchResultDefault);

        Test.stopTest();

        System.assert(resultsList.size() == 0);
    }
}