force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Delegate_Public_Group__c/Delegate_Public_Group__c.object-meta.xml
<CustomObject>
    <description>used to store/manage all delegate public groups.</description>
    <label>Delegate Public Group</label>
    <nameField>
        <displayFormat>DPG-{0000}</displayFormat>
        <label>Delegate Public Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegate Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delegate_Public_Group__c/fields/Banker__c.field-meta.xml
<CustomField>
    <fullName>Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delegate_Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Client</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements as Subject</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/Engagement_Counterparty__c.object-meta.xml
<CustomObject>
    <description>Custom object to track firms listed as counterparties for engaged deals/projects.</description>
    <label>Engagement Counterparty</label>
    <nameField>
        <label>Counterparty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Counterparties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Engagement__r.Client__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements Shown</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Counterparties</relationshipLabel>
    <relationshipName>Engagement_Counterparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Counterparty__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <formula>Engagement__r.Subject__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/Engagement_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that are staffed on an engaged deal/project.</description>
    <label>Engagement Internal Team</label>
    <nameField>
        <displayFormat>EIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select HL employee</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/Monthly_Revenue_Process_Control__c.object-meta.xml
<CustomObject>
    <description>Kick off and track each step of the Monthly Revenue Process in JDE</description>
    <label>Monthly Revenue Process Control</label>
    <nameField>
        <label>Monthly Revenue Process Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Revenue Process Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Current_Month__c</fullName>
    <description>Select the Current Month for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Month for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Current Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Year__c</fullName>
    <description>Select the Current Year for this Monthly Revenue Process Control record</description>
    <inlineHelpText>Select the Current Year for this Monthly Revenue Process Control record</inlineHelpText>
    <label>Current Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1999</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Revenue_Process_Control__c/fields/IsCurrent__c.field-meta.xml
<CustomField>
    <fullName>IsCurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this is the current Monthly Revenue Process Control record (only one record can be active at a time)</description>
    <inlineHelpText>Indicates that this is the current Monthly Revenue Process Control record (only one record can be active at a time)</inlineHelpText>
    <label>Is Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Accrual__c/Revenue_Accrual__c.object-meta.xml
<CustomObject>
    <label>Revenue Accrual</label>
    <nameField>
        <displayFormat>REV-{000000}</displayFormat>
        <label>Revenue Accrual #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Accruals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Accrual__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Revenue Accruals</relationshipLabel>
    <relationshipName>Revenue_Accruals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Accrual__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Accrual__c/fields/Monthly_Revenue_Process_Control__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Revenue_Process_Control__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Monthly Revenue Process Control Record</description>
    <label>Monthly Revenue Process Control</label>
    <referenceTo>Monthly_Revenue_Process_Control__c</referenceTo>
    <relationshipLabel>Revenue Accruals</relationshipLabel>
    <relationshipName>Revenue_Accruals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Has_Delegates__c.field-meta.xml
<CustomField>
    <fullName>Has_Delegates__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Has Delegates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_HL_RemoveInactiveUsersFromEngShare.cls
@isTest(SeeAllData=False)
private class Test_HL_RemoveInactiveUsersFromEngShare {
    @testSetup
    private static void CreateData()
    {
        List<User> userList;
        List<Engagement__c> engagementList;
        List<Engagement_Internal_Team__c> eitList;
        List<Delegate_Public_Group__c> dpgList;
        Monthly_Revenue_Process_Control__c mrpcNew = new Monthly_Revenue_Process_Control__c(IsCurrent__c = TRUE,Current_Month__c = '02', Current_Year__c = '2015');
        insert mrpcNew;
        Profile objProfile = [SELECT Name
                              FROM Profile
                              WHERE Name = 'Solution Manager'];

        integer i = 0;
        integer j = 0;
        userList = new List<User>();
        for(User userRecord : (List<User>)HL_TestFactory.CreateSObjectList('User', false, 3))
        {
            userRecord.Lastname = 'User';
            userRecord.Email = 'tuser@yahoo.in';
            userRecord.Username =  i+'test543552542@hl2.com';
            userRecord.ProfileId = objProfile.Id;
            userRecord.Alias = 'tuser';
            userRecord.TimeZoneSidKey = 'GMT';
            userRecord.LocaleSidKey = 'en_US';
            userRecord.EmailEncodingKey = 'ISO-8859-1';
            userRecord.LanguageLocaleKey = 'en_US';
            userRecord.Has_Delegates__c = false;
            userRecord.IsActive = true;
            userList.add(userRecord);
            i++;
        }
        insert userList;

        List<Account> accountList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, 1);
        insert accountList;

        i = 0;
        List<Contact> hlContactList = new List<Contact>();
        for(Contact contactRecord : HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.Houlihan_Employee, false, 3))
        {
            contactRecord.AccountId = accountList[0].Id;
            contactRecord.User__c = userList[i].Id;
            hlContactList.add(contactRecord);
            i++;
        }
        insert hlContactList;

        dpgList = new List<Delegate_Public_Group__c>();
        for(Delegate_Public_Group__c dpgRecord : (List<Delegate_Public_Group__c>)HL_TestFactory.CreateSObjectList('Delegate_Public_Group__c', false, 1))
        {
            dpgRecord.Banker__c = userList[0].Id;
            dpgList.add(dpgRecord);
        }
        insert dpgList;

        engagementList = new List<Engagement__c>();
        for(Engagement__c engagementRecord : HL_TestFactory.CreateEngagementList(false, 2))
        {
            engagementRecord.Client__c = accountList[0].Id;
            engagementRecord.Subject__c = accountList[0].Id;
            engagementList.add(engagementRecord);
        }
        insert engagementList;

        i = 0;
        List<Engagement_Counterparty__c> engagementCounterpartyList = new  List<Engagement_Counterparty__c>();
        for(Engagement_Counterparty__c engagementCounterpartyRecord : (List<Engagement_Counterparty__c>)HL_TestFactory.CreateSObjectList('Engagement_Counterparty__c', false, 4))
        {
            if(i>1)
                j = 1;
            engagementCounterpartyRecord.Company__c = accountList[0].Id;
            engagementCounterpartyRecord.Engagement__c = engagementList[j].Id;
            engagementCounterpartyList.add(engagementCounterpartyRecord);
            i++;
        }
        insert engagementCounterpartyList;

        List<Revenue_Accrual__c> revenueAccrualList = new List<Revenue_Accrual__c>{new Revenue_Accrual__c(Engagement__c = engagementList[0].Id, Month__c = 'Jan', Year__c = '2014'),
                                                                                   new Revenue_Accrual__c(Engagement__c = engagementList[1].Id, Month__c = 'Feb', Year__c = '2015')};
        insert revenueAccrualList;

        i = 0; j = 0;
        eitList = new List<Engagement_Internal_Team__c>();
        for(Engagement_Internal_Team__c eitRecord : (List<Engagement_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Engagement_Internal_Team__c', false, 6))
        {
            if(i > 2)
            {
                i = 0;
                j = 1;
            }
            eitRecord.Contact__c = hlContactList[i].Id;
            eitRecord.Engagement__c = engagementList[j].Id;
            eitRecord.End_Date__c = Date.today();
            eitRecord.Start_Date__c = Date.today();
            eitList.add(eitRecord);
            i++;
        }
        insert eitList;
    }

    @isTest
    private static void TestRemoveInactiveUsersFromEngShare()
    {
        List<User> userList = [SELECT IsActive FROM User];

        userList[0].IsActive = false;

        Test.startTest();

        update userList[0];
        SL_Batch_RemoveInactiveUsersFromEngShare objBatchRIU = new SL_Batch_RemoveInactiveUsersFromEngShare();
        Database.executeBatch(objBatchRIU, 50);

        Test.stopTest();

      //  System.assertEquals([SELECT Id FROM Engagement__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 6); 
    }

    @isTest
    private static void TestUpdateEndDateCase()
    {
        List<Engagement_Internal_Team__c> eitList = [SELECT End_Date__c FROM Engagement_Internal_Team__c];

        Test.startTest();

        eitList[0].End_Date__c = Date.today().addDays(-2);
        update eitList[0];

        Test.stopTest();

        System.assertEquals([SELECT Id FROM Engagement__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 5);
        System.assertEquals([SELECT Id FROM Engagement_Counterparty__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 10);
        System.assertEquals([SELECT Id FROM Revenue_Accrual__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 5);
    }

    @isTest
    private static void TestOnChangeParentName()
    {
        List<Engagement__c> engagementList = [SELECT Name FROM Engagement__c];

        Test.startTest();

        engagementList[1].Name = 'DNDTestEngagement';
        update engagementList[1];

        Test.stopTest();

        System.assertEquals([SELECT Id FROM Engagement__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 6);
        System.assertEquals([SELECT Id FROM Engagement_Counterparty__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 12);
        System.assertEquals([SELECT Id FROM Revenue_Accrual__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 6);
    }

    @isTest
    private static void TestDNDCase()
    {
        delete [SELECT Id FROM Engagement__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'];

        Test.startTest();

        SL_Batch_RemoveInactiveUsersFromEngShare objBatchRIU = new SL_Batch_RemoveInactiveUsersFromEngShare();
        Database.executeBatch(objBatchRIU, 50);

        Test.stopTest();

        System.assertEquals([SELECT Id FROM Engagement__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 6);
        System.assertEquals([SELECT Id FROM Engagement_Counterparty__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 12);
        System.assertEquals([SELECT Id FROM Revenue_Accrual__Share WHERE RowCause='Manual' AND AccessLevel ='Edit'].size(), 6);
    }
}