force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Date_Engaged__c.field-meta.xml
<CustomField>
    <fullName>Date_Engaged__c</fullName>
    <inlineHelpText>Date on Engagement Letter</inlineHelpText>
    <label>Date Engaged</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage/Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Relationship Building</fullName>
            </value>
            <value>
                <fullName>Evaluating Opportunity</fullName>
            </value>
            <value>
                <fullName>Pre-Marketing</fullName>
            </value>
            <value>
                <fullName>Pitch Scheduled</fullName>
            </value>
            <value>
                <fullName>Pitched</fullName>
            </value>
            <value>
                <fullName>Retainer Outstanding</fullName>
            </value>
            <value>
                <fullName>Active Discussion</fullName>
            </value>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Opportunity Identified</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Verbally Engaged</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Staff Role</label>
    <referenceTo>Staff_Role__c</referenceTo>
    <relationshipLabel>Opportunity Internal Teams</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/Staff_Role__c.object-meta.xml
<CustomObject>
    <description>Used internally to control staff role display and order.</description>
    <label>Staff Role</label>
    <nameField>
        <label>Staff Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Role__c/fields/CF__c.field-meta.xml
<CustomField>
    <fullName>CF__c</fullName>
    <defaultValue>true</defaultValue>
    <label>CF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/FAS__c.field-meta.xml
<CustomField>
    <fullName>FAS__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Do not change Field Name, only Label at this time.  Changing Field Name may break integrations.</description>
    <label>FVA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_HL_Opportunity.cls
@isTest
private class Test_HL_Opportunity {
    @testSetup
    static void SetupOpportunityData(){
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        contactRecord.User__c = UserInfo.getUserId();      
        insert contactRecord;
        
        Opportunity__c opportunityRecord = (Opportunity__c)HL_TestFactory.CreateSObject('Opportunity__c', false);
        opportunityRecord.Stage__c = 'Engaged';
        opportunityRecord.Date_Engaged__c = Date.today().AddMonths(-1);
        List<String> teamRoleList = new List<String> {'Principal','Seller','Manager','Associate','Initiator'};
        List<Opportunity_Internal_Team__c> opportunityTeamList = (List<Opportunity_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Opportunity_Internal_Team__c', false, teamRoleList.size());
        List<Staff_Role__c> staffRoleList = new List<Staff_Role__c>();
        insert opportunityRecord;
  
        for(Integer i = 0; i<teamRoleList.size(); i++)
            staffRoleList.add(new Staff_Role__c(Name=teamRoleList[i], Display_Name__c = teamRoleList[i], CF__c = true, FAS__c = true));
        
        insert staffRoleList;
        for(Integer i = 0; i<teamRoleList.size(); i++)
        {
            opportunityTeamList[i].Opportunity__c = opportunityRecord.Id;
            opportunityTeamList[i].Staff_Role__c = staffRoleList[i].Id;
            opportunityTeamList[i].Contact__c = contactRecord.Id;
        }

        insert opportunityTeamList;
    }

    @isTest 
    private static void TestGetByUser(){
        Test.startTest();
        
        List<Opportunity__c> oppByUserList = HL_Opportunity.GetByUser(UserInfo.getUserId(), new Set<String>{'Active','Engaged', 'Hold'});
        List<Opportunity__c> oppByUserWithDateList = HL_Opportunity.GetByUser(UserInfo.getUserId(), new Set<String>{'Engaged'}, Date.today().addMonths(-2));
        //Confirm no results if there is no data
        List<Opportunity__c> oppByUserWithDateNoResultList = HL_Opportunity.GetByUser(UserInfo.getUserId(), new Set<String>{'Active','Engaged', 'Hold'}, Date.today());
        //Test with Null User
        List<Opportunity__c> oppByUserNullUserList = HL_Opportunity.GetByUser(null, new Set<String>{'Active','Engaged', 'Hold'});
        List<Opportunity__c> oppByUserWithDateNullUserList = HL_Opportunity.GetByUser(null, new Set<String>{'Engaged'}, Date.today().addMonths(-2));
        
        Test.stopTest();
        
        System.assert(oppByUserList.size() > 0);
        System.assert(oppByUserWithDateList.size() > 0);
        System.assert(oppByUserWithDateNoResultList.size() == 0);
        System.assert(oppByUserNullUserList.size() > 0);
        System.assert(oppByUserWithDateNullUserList.size() > 0);
    }
    
    @isTest 
    private static void TestGetOpportunityMapByContacts(){
        List<Contact> contactList = [SELECT Id FROM Contact];
        
        Test.startTest();
        
        Map<Id, Set<Id>> opportunityMap = HL_Opportunity.GetOpportunityMapByContacts(new Set<Id> {contactList[0].Id}, new Set<String>{'Active','Engaged', 'Hold'});
        
        Test.stopTest();
        
        System.assert(opportunityMap.size() > 0);
    }
}