force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Custom object to track engaged deals/projects.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Number__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Number__c</fullName>
    <inlineHelpText>Case Number</inlineHelpText>
    <label>Engagement Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Settlement or Agreement Reached</fullName>
            </value>
            <value>
                <fullName>Book Prep/Underwriting</fullName>
            </value>
            <value>
                <fullName>In Market</fullName>
            </value>
            <value>
                <fullName>Received Indications of Interest</fullName>
            </value>
            <value>
                <fullName>Pre-LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Rec&apos;d Indications/Submitted Bid</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed LOI/Due Diligence</fullName>
            </value>
            <value>
                <fullName>Signed Term Sheets</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Pending Regulatory Approval</fullName>
            </value>
            <value>
                <fullName>Verbally Retained</fullName>
            </value>
            <value>
                <fullName>Performing Analysis</fullName>
            </value>
            <value>
                <fullName>Ongoing Analysis</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Testimony</fullName>
            </value>
            <value>
                <fullName>Opinion Report</fullName>
            </value>
            <value>
                <fullName>Opinion Development</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Delivered Report</fullName>
            </value>
            <value>
                <fullName>Bill/File</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/Engagement_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that are staffed on an engaged deal/project.</description>
    <label>Engagement Internal Team</label>
    <nameField>
        <displayFormat>EIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select HL employee</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Engagement_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Staff Role</label>
    <referenceTo>Staff_Role__c</referenceTo>
    <relationshipLabel>Engagement Internal Teams</relationshipLabel>
    <relationshipName>Engagement_Internal_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/Staff_Role__c.object-meta.xml
<CustomObject>
    <description>Used internally to control staff role display and order.</description>
    <label>Staff Role</label>
    <nameField>
        <label>Staff Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Role__c/fields/CF__c.field-meta.xml
<CustomField>
    <fullName>CF__c</fullName>
    <defaultValue>true</defaultValue>
    <label>CF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Engagement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/fields/FAS__c.field-meta.xml
<CustomField>
    <fullName>FAS__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Do not change Field Name, only Label at this time.  Changing Field Name may break integrations.</description>
    <label>FVA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_HL_Engagement.cls
@isTest
private class Test_HL_Engagement {
    @testSetup
    static void SetupEngagementData(){
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.Houlihan_Employee,false);
        contactRecord.User__c = UserInfo.getUserId();      
        insert contactRecord;
        
        Engagement__c engagementRecord = HL_TestFactory.CreateEngagement(false);
        engagementRecord.Stage__c = 'Closed';
        engagementRecord.Close_Date__c = Date.today().AddMonths(-1);
        List<String> teamRoleList = new List<String> {'Principal','Seller','Manager','Associate','Initiator'};
        List<Engagement_Internal_Team__c> engagementTeamList = (List<Engagement_Internal_Team__c>)HL_TestFactory.CreateSObjectList('Engagement_Internal_Team__c', false, teamRoleList.size());
        List<Staff_Role__c> staffRoleList = new List<Staff_Role__c>();
        insert engagementRecord;
  
        for(Integer i = 0; i<teamRoleList.size(); i++)
            staffRoleList.add(new Staff_Role__c(Name=teamRoleList[i], Display_Name__c = teamRoleList[i], CF__c = true, FAS__c = true));
        
        insert staffRoleList;
        for(Integer i = 0; i<teamRoleList.size(); i++)
        {
            engagementTeamList[i].Engagement__c = engagementRecord.Id;
            engagementTeamList[i].Staff_Role__c = staffRoleList[i].Id;
            engagementTeamList[i].Contact__c = contactRecord.Id;
            engagementTeamList[i].Start_Date__c = Date.today().AddMonths(-2);
        }

        insert engagementTeamList;
    }
    
    @isTest 
    private static void TestGetByUser(){
        Test.startTest();
        
        List<Engagement__c> engByUserList = HL_Engagement.GetByUser(UserInfo.getUserId(), new Set<String>{'Active','Closed', 'Hold'});
        List<Engagement__c> engByUserWithDateList = HL_Engagement.GetByUser(UserInfo.getUserId(), new Set<String>{'Closed'}, Date.today().addMonths(-2));
        List<Engagement__c> engByUserPointInTimeList = HL_Engagement.GetByUserAtPointInTime(UserInfo.getUserId(), Date.today().addMonths(-2), Date.today(), Date.today().addMonths(-2));
        //Confirm no results if there is no data
        List<Engagement__c> engByUserWithDateNoResultList = HL_Engagement.GetByUser(UserInfo.getUserId(), new Set<String>{'Active','Closed', 'Hold'}, Date.today());
        //Test with Null User
        List<Engagement__c> engByUserNullUserList = HL_Engagement.GetByUser(null, new Set<String>{'Active','Closed', 'Hold'});
        List<Engagement__c> engByUserWithDateNullUserList = HL_Engagement.GetByUser(null, new Set<String>{'Closed'}, Date.today().addMonths(-2));
        List<Engagement__c> engByUserPointInTimeNullUserList = HL_Engagement.GetByUserAtPointInTime(null, Date.today().addMonths(-2), Date.today(), Date.today().addMonths(-2));
        
        Test.stopTest();
        
        System.assert(engByUserList.size() > 0);
        System.assert(engByUserWithDateList.size() > 0);
        System.assert(engByUserPointInTimeList.size() > 0);
        System.assert(engByUserWithDateNoResultList.size() == 0);
        System.assert(engByUserNullUserList.size() > 0);
        System.assert(engByUserWithDateNullUserList.size() > 0);
        System.assert(engByUserPointInTimeNullUserList.size() > 0);
    }
    
    @isTest 
    private static void TestGetEngagementMapByContacts(){
        List<Contact> contactList = [SELECT Id FROM Contact];
        
        Test.startTest();
        
        Map<Id, Set<Id>> engagementMap = HL_Engagement.GetEngagementMapByContacts(new Set<Id> {contactList[0].Id}, new Set<String>{'Active','Closed', 'Hold'});
        
        Test.stopTest();
        
        System.assert(engagementMap.size() > 0);
    }

    @isTest 
    private static void TestMailMerge(){
        Engagement__c engagementRecord = (Engagement__c)HL_TestFactory.CreateSObject('Engagement__c', false);
        engagementRecord.Name = 'Test Engagement';
        engagementRecord.Engagement_Number__c = '123456';
        insert engagementRecord;
        
        Test.startTest();
        
        Engagement__c eMailMerge = HL_Engagement.GetMailMerge(engagementRecord.Id);
        
        Test.stopTest();
        
        System.assertEquals(eMailMerge.Id, engagementRecord.Id);
    }
}