force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Report_Link__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Name of report that the end user will see</description>
    <label>Display Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Home_Page_Access__c.field-meta.xml
<CustomField>
    <fullName>Home_Page_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Home Page Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/IsTableau__c.field-meta.xml
<CustomField>
    <fullName>IsTableau__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is being used in a workflow, that if the Report URL is a Tableau URL, then this field is checked TRUE.  The field is also used at the subscriber level in a formula, for reporting and list view criteria.</description>
    <label>Is Tableau</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_Link_URL__c</fullName>
    <description>Link that will execute the report</description>
    <label>Report Link URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Dashboards</fullName>
            </value>
            <value>
                <fullName>Accounting Group</fullName>
            </value>
            <value>
                <fullName>Company Group</fullName>
            </value>
            <value>
                <fullName>Company Single</fullName>
            </value>
            <value>
                <fullName>Contact Group</fullName>
            </value>
            <value>
                <fullName>Contact Single</fullName>
            </value>
            <value>
                <fullName>Engagement Group</fullName>
            </value>
            <value>
                <fullName>Engagement Single</fullName>
            </value>
            <value>
                <fullName>FSC Group</fullName>
            </value>
            <value>
                <fullName>Opportunity Group</fullName>
                <default>true</default>
                <label>Opportunity Group</label>
            </value>
            <value>
                <fullName>Opportunity Single</fullName>
            </value>
            <value>
                <fullName>My Dashboards</fullName>
            </value>
            <value>
                <fullName>Line of Business Dashboards</fullName>
            </value>
            <value>
                <fullName>Industry Group/Product Line Dashboards</fullName>
            </value>
            <value>
                <fullName>Revenue Group</fullName>
            </value>
            <value>
                <fullName>Sector Coverage Dashboards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates the order the links should be presented on the page</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HL_Report_Link__c/fields/Thumbnail_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_Image_Url__c</fullName>
    <description>This field is used to house the URL to the dashboard image that will then, be used in the SFDC Home Page Component of the subscriber with Home Page Access = TRUE.</description>
    <label>Thumbnail Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/HL_Subscription__c.object-meta.xml
<CustomObject>
    <label>HL Subscription</label>
    <nameField>
        <displayFormat>SUB{00000}</displayFormat>
        <label>HL Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HL Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Subscription__c/fields/HL_Report_Link__c.field-meta.xml
<CustomField>
    <fullName>HL_Report_Link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Report to Link this Record To for Security Assignments</description>
    <inlineHelpText>Report to Link this Record To for Security Assignments</inlineHelpText>
    <label>HL Report Link</label>
    <referenceTo>HL_Report_Link__c</referenceTo>
    <relationshipLabel>HL Subscriptions</relationshipLabel>
    <relationshipName>HL_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Home_Page_Access__c.field-meta.xml
<CustomField>
    <fullName>Home_Page_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to add/remove images within the home page component.  If true and the related report link has a thumbnail URL, then this report will appear in the component.</description>
    <label>Home Page Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Is_Tableau__c.field-meta.xml
<CustomField>
    <fullName>Is_Tableau__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to allow the related report to appear or not appear in the VF Web Tab for Tableau.  If true and the Report Link record has a Tableau URL, then the Display Name of the Report will appear in the drop down. to be selected and loaded.</description>
    <label>Is Tableau</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>This field is used to relist the value in the drop down within the VF web tab by priority over alphabetically.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the email recipient or the user that the security is applied to.</description>
    <inlineHelpText>This is the email recipient or the user that the security is applied to.</inlineHelpText>
    <label>Subscriber</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only HL Employees and Disribution Lists can be added to Subscriptions.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distribution_Lists</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Subscriptions (Subscriber)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <description>HL Subscription is used for the email notifications/security or the report access in CRM.</description>
    <inlineHelpText>HL Subscription is used for the email notifications/security or the report access in CRM.</inlineHelpText>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual Subscriber</fullName>
            </value>
            <value>
                <fullName>Outlook Distribution Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>true</active>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/TableauDashboardControllerTest.cls
@isTest
public class TableauDashboardControllerTest {
    
    @isTest
    static void testTableauDashboardController(){
        Id hlAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Houlihan Company').getRecordTypeId();
        Id hlContactTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Houlihan Employee').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'HL';
        acc.RecordTypeId = hlAccountRecordTypeId;
        insert acc;
        
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName='ContactHL';
        contact.AccountId = acc.Id;
        contact.User__c = userInfo.getUserId();
        contact.recordTypeId = hlContactTypeId;
        insert contact;
        
        List<HL_Report_Link__c> reportLinkList = new List<HL_Report_Link__c>();
        HL_Report_Link__c hlReportLink = new HL_Report_Link__c();
        hlReportLink.Name = 'TableauDashboardView';
        hlReportLink.Display_Name__c = 'TableauDashboardView';
        hlReportLink.Report_Link_URL__c = 'https://tableau.hl.com/t/DEV/views/Dev-FVAStaffingAllocationReport/Dashboard1';
        hlReportLink.Thumbnail_Image_Url__c ='https://tableau.hl.com/vizportal/api/rest/v1/views/2496/thumbnail';
        hlReportLink.Sort_Order__c = 1;
        reportLinkList.add(hlReportLink);
        
        HL_Report_Link__c hlReportLink1 = new HL_Report_Link__c();
        hlReportLink1.Name = 'TableauMyDashboardView';
        hlReportLink1.Display_Name__c = 'TableauMyDashboardView';
        hlReportLink1.Report_Link_URL__c = 'https://tableau.hl.com/t/DEV/views/Dev-FVAStaffingAllocationReport/Dashboard1';
        hlReportLink1.Thumbnail_Image_Url__c ='https://tableau.hl.com/vizportal/api/rest/v1/views/2496/thumbnail';
        hlReportLink1.Sort_Order__c = 1;
        hlReportLink1.Home_Page_Access__c =true;
        hlReportLink1.Report_Type__c = 'My Dashboards';
        hlReportLink1.IsTableau__c =true;
        reportLinkList.add(hlReportLink1);
        
        insert reportLinkList;
        
        HL_Subscription__c subscription = new HL_Subscription__c();
        subscription.Active__c = true;
        subscription.Subscription_Type__c = 'Individual Subscriber';
        subscription.Home_Page_Access__c = true;
        subscription.Subscriber__c = contact.Id;
        subscription.HL_Report_Link__c = hlReportLink.Id;
        subscription.Is_Tableau__c = true;
        insert subscription;
        
        List<HL_Subscription__c> sub = [SELECT Id, Subscriber__c, Subscriber__r.User__c FROM HL_Subscription__c];
        Test.startTest();
        PageReference pageRef = Page.TableauDashboardPage; // Add your VF page Name here
        pageRef.getParameters().put('displayName', 'TableauDashboardView');
        Test.setCurrentPage(pageRef);
        TableauDashboardController controller = new TableauDashboardController();
        controller.getDashboards();
        TableauHomePageDashboardController.getDashboardList();
        TableauHomePageDashboardController.getMyDashboardList();
        Test.stopTest();
    }
}