force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Subscription__c/HL_Subscription__c.object-meta.xml
<CustomObject>
    <label>HL Subscription</label>
    <nameField>
        <displayFormat>SUB{00000}</displayFormat>
        <label>HL Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HL Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Subscription__c/fields/HL_Report_Link__c.field-meta.xml
<CustomField>
    <fullName>HL_Report_Link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Report to Link this Record To for Security Assignments</description>
    <inlineHelpText>Report to Link this Record To for Security Assignments</inlineHelpText>
    <label>HL Report Link</label>
    <referenceTo>HL_Report_Link__c</referenceTo>
    <relationshipLabel>HL Subscriptions</relationshipLabel>
    <relationshipName>HL_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the email recipient or the user that the security is applied to.</description>
    <inlineHelpText>This is the email recipient or the user that the security is applied to.</inlineHelpText>
    <label>Subscriber</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only HL Employees and Disribution Lists can be added to Subscriptions.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distribution_Lists</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Subscriptions (Subscriber)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL_Subscription__c/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>true</active>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/Test_HL_SubscriptionHandler.cls
@isTest
private class Test_HL_SubscriptionHandler { 
    @testSetup
    static void setupSubscriptionData(){
        //Create Test Data
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        c.User__c = UserInfo.getUserId();      
        insert c;
        HL_Report_Link__c reportLink = SL_TestSetupUtils.CreateHLReportLink('', 1)[0];
        insert reportLink;
    }
    
     @isTest private static void TestInsert(){
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        HL_Report_Link__c reportLink = [SELECT Id FROM HL_Report_Link__c LIMIT 1];
        HL_Subscription__c subscription = new HL_Subscription__c(Active__c = true, Subscriber__c = c.Id, HL_Report_Link__c = reportLink.Id);
        Test.startTest();
        	insert subscription;
        Test.stopTest();
        
        //Verify the Sharing Record was Created
        System.assert([SELECT Id FROM HL_Report_Link__Share WHERE RowCause =: Schema.HL_Report_Link__Share.RowCause.Subscription__c].size() > 0);
    }
    
     @isTest private static void TestUpdateStandard(){
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        HL_Report_Link__c reportLink = [SELECT Id FROM HL_Report_Link__c LIMIT 1];
        HL_Subscription__c subscription = new HL_Subscription__c(Active__c = true, Subscriber__c = c.Id, HL_Report_Link__c = reportLink.Id);
        insert subscription;
        HL_Subscription__c subscriptionToUpdate = [SELECT Active__c, Subscriber__c, HL_Report_Link__c FROM HL_Subscription__c];
        
        Test.startTest();
        	 update subscriptionToUpdate;
        Test.stopTest();
        
        //Verify the Sharing Record was Created
        System.assert([SELECT Id FROM HL_Report_Link__Share WHERE RowCause =: Schema.HL_Report_Link__Share.RowCause.Subscription__c].size() > 0);
    }
    
    @isTest private static void TestUpdateToInactive(){
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        HL_Report_Link__c reportLink = [SELECT Id FROM HL_Report_Link__c LIMIT 1];
        HL_Subscription__c subscription = new HL_Subscription__c(Active__c = true, Subscriber__c = c.Id, HL_Report_Link__c = reportLink.Id);
        insert subscription;
        HL_Subscription__c subscriptionToUpdate = [SELECT Active__c, Subscriber__c, HL_Report_Link__c FROM HL_Subscription__c];
        subscriptionToUpdate.Active__c = false;
        
         Test.startTest();
        	 update subscriptionToUpdate;
        Test.stopTest();
        
        //Verify the Sharing Record was Created
        System.assert([SELECT Id FROM HL_Report_Link__Share WHERE RowCause =: Schema.HL_Report_Link__Share.RowCause.Subscription__c].size() == 0);
    }
    
    @isTest private static void TestDelete(){
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        HL_Report_Link__c reportLink = [SELECT Id FROM HL_Report_Link__c LIMIT 1];
        HL_Subscription__c subscription = new HL_Subscription__c(Active__c = true, Subscriber__c = c.Id, HL_Report_Link__c = reportLink.Id);
        insert subscription;
        HL_Subscription__c subscriptionToDelete = [SELECT Active__c, Subscriber__c, HL_Report_Link__c FROM HL_Subscription__c];
        Test.startTest();
        	 delete subscriptionToDelete;
        Test.stopTest();
        
        //Verify the Sharing Record was Removed
        System.assert([SELECT Id FROM HL_Report_Link__Share WHERE RowCause =: Schema.HL_Report_Link__Share.RowCause.Subscription__c].size() == 0);
    }
    
}