force-app/main/default/objects/LOOKUP__c/LOOKUP__c.object-meta.xml
<CustomObject>
    <description>Stores lookup/picklist values for various objects.
This will have the ability to sort using a sort order for special lists if need be.</description>
    <label>Lookup</label>
    <nameField>
        <label>LOOKUP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LOOKUP__c/fields/Lookup_Group__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Group__c</fullName>
    <label>Lookup Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOOKUP__c/fields/Short_Text__c.field-meta.xml
<CustomField>
    <fullName>Short_Text__c</fullName>
    <label>Short Text</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOOKUP__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>Sort order for the lookup</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOOKUP__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Full Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_Lookup.cls
global with sharing class HL_Lookup {
    public HL_Lookup(HL_CompanyHomeController controller){}
    @RemoteAction
    public static List<Lookup__c> GetByGroup(String groupName){
        return [SELECT Text__c, Lookup_Group__c, Short_Text__c FROM Lookup__c WHERE Lookup_Group__c =: groupName ORDER BY Sort_Order__c];
    }
    
    @RemoteAction
    global static List<Lookup__c> LookupCountry(String country){
        country = '%' + country + '%';
        return [SELECT Text__c FROM Lookup__c WHERE Lookup_Group__c =: 'Country' AND Text__c LIKE : country ORDER BY Text__c];
    }
}