force-app/main/default/objects/Financials__c/Financials__c.object-meta.xml
<CustomObject>
    <label>Financials</label>
    <nameField>
        <displayFormat>FIN-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financials__c/fields/Related_Approval__c.field-meta.xml
<CustomField>
    <fullName>Related_Approval__c</fullName>
    <label>Related Approval</label>
    <referenceTo>Opportunity_Approval__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
            </value>
            <value>
                <fullName>Projected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_FinancialsTriggerHandler.cls
public class HL_FinancialsTriggerHandler 
{
    public void FinancialValidationsbeforeinsetandupdate(list<Financials__c> fin)
    {
        set<id> oppreviewids= new set<id>();
        map<id, Financials__c> mapfid = new map<id, Financials__c>();
        map<id, Financials__c> mapfinancerecords= new map<id, Financials__c>();
        
        for(Financials__c f: fin)
        {
            oppreviewids.add(f.Related_Approval__c ); 
            mapfid.put(f.id,f);
        }
        
        if(oppreviewids.size()>0)
        {
            list<Financials__c> financerecords=[select Related_Approval__c, Type__c, Year__c , id from Financials__c where Related_Approval__c in :oppreviewids];
            if(financerecords.size()>0)
            {
                for(Financials__c f: financerecords)
                {
					//if(!mapfid.containsKey(f.id))                    
                	mapfinancerecords.put(f.id, f);                    
                }
            }
            system.debug('mapfinancerecords.size()='+ mapfinancerecords.size());
        }
        
        if(mapfinancerecords.size()>0)
        {
            for(Financials__c f: fin)
            {
                for(Financials__c ff: mapfinancerecords.values())
                {                                        
                    if(ff.Related_Approval__c==f.Related_Approval__c && f.id!=ff.Id)
                    {
                        if(f.Year__c==ff.Year__c && f.Type__c==ff.Type__c)
                        {                                                                    
                            Trigger.new[0].addError('A record already exist with same Year and Type'); 
                        }
                    }                    
                }
            }
        }
    }
}