force-app/main/default/objects/Financials__c/Financials__c.object-meta.xml
<CustomObject>
    <label>Financials</label>
    <nameField>
        <displayFormat>FIN-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financials__c/fields/Assets_Under_Management__c.field-meta.xml
<CustomField>
    <fullName>Assets_Under_Management__c</fullName>
    <label>Assets Under Management (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Book_Value_MM__c.field-meta.xml
<CustomField>
    <fullName>Book_Value_MM__c</fullName>
    <label>Book Value (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/EBIT_MM__c.field-meta.xml
<CustomField>
    <fullName>EBIT_MM__c</fullName>
    <label>EBIT (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/EBITDA__c.field-meta.xml
<CustomField>
    <fullName>EBITDA__c</fullName>
    <label>EBITDA (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Face_Value_MM__c.field-meta.xml
<CustomField>
    <fullName>Face_Value_MM__c</fullName>
    <label>Face Value (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Interest_and_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>Interest_and_Fee_Income__c</fullName>
    <label>Interest and Fee Income (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Net_Asset_Value_MM__c.field-meta.xml
<CustomField>
    <fullName>Net_Asset_Value_MM__c</fullName>
    <label>Net Asset Value (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Number_of_Companies__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Companies__c</fullName>
    <label>Number of Companies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Number_of_Interests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Interests__c</fullName>
    <label>Number of Interests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Number_of_Loans__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Loans__c</fullName>
    <label>Number of Loans</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Number_of_Policies__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Policies__c</fullName>
    <label>Number of Policies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Pre_Tax_Income__c.field-meta.xml
<CustomField>
    <fullName>Pre_Tax_Income__c</fullName>
    <label>Pre-Tax Income (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Company</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Related_Account__c</field>
            <operation>equals</operation>
            <valueField>Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Related_Account__c</field>
            <operation>equals</operation>
            <valueField>Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Related_Approval__c.field-meta.xml
<CustomField>
    <fullName>Related_Approval__c</fullName>
    <label>Related Approval</label>
    <referenceTo>Opportunity_Approval__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Revenue_MM__c.field-meta.xml
<CustomField>
    <fullName>Revenue_MM__c</fullName>
    <label>Revenue (MM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
            </value>
            <value>
                <fullName>Projected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_FinancialController.cls
public class HL_FinancialController {
	public Id RecordId {get; set;}
    public Id ApprovalId {get; set;}
    public Id SubjectId {get; set;}
    public string CurrencyISO {get; set;}
    public Financials__c Financial {get{
        if(financial == null){
            if(RecordId <> null)
                financial = [SELECT Related_Approval__c, Related_Account__c, Assets_Under_Management__c, Book_Value_MM__c, EBIT_MM__c,  EBITDA__c, Face_Value_MM__c, Interest_and_Fee_Income__c, Net_Asset_Value_MM__c, Number_of_Companies__c, Number_of_Loans__c, Number_of_Interests__c, Number_of_Policies__c, Pre_Tax_Income__c,  Revenue_MM__c, Type__c, Year__c, CurrencyIsoCode FROM Financials__c WHERE Id =: recordId LIMIT 1];
            else
                financial = new Financials__c(Related_Approval__c = ApprovalId, Related_Account__c = SubjectId, CurrencyIsoCode = CurrencyISO);
        }
        return financial;
    } set;}
    public HL_FinancialController(){
        RecordId = HL_PageUtility.GetParameter('id');
        ApprovalId = HL_PageUtility.GetParameter('oa');
        SubjectId = HL_PageUtility.GetParameter('subject');
        CurrencyISO = HL_PageUtility.GetParameter('currencyISO');
    }
    public void Save(){
        try{        
            upsert Financial;
            RecordId = Financial.Id;
            HL_PageUtility.ShowConfirm('Record Saved');
        }
        catch(DmlException ex){
            ApexPages.addMessages(ex);
        }
    }
}