force-app/main/default/objects/Financials__c/Financials__c.object-meta.xml
<CustomObject>
    <label>Financials</label>
    <nameField>
        <displayFormat>FIN-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financials__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Company</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Related_Account__c</field>
            <operation>equals</operation>
            <valueField>Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Related_Account__c</field>
            <operation>equals</operation>
            <valueField>Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Related_Approval__c.field-meta.xml
<CustomField>
    <fullName>Related_Approval__c</fullName>
    <label>Related Approval</label>
    <referenceTo>Opportunity_Approval__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
            </value>
            <value>
                <fullName>Projected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Beneficial_Owner_Control_Person_form__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner_Control_Person_form__c</fullName>
    <description>Compliance has requested that the FinCEN mandated information identifying Beneficial Owner(s) and Control Person(s) form to be submitted when the Opportunity is converting to an Engagement.</description>
    <inlineHelpText>Engagements done through &apos;Cap, Inc.&apos; as the HL Entity, and the HL Client&apos;s ownership is not excluded from the CDD requirements (please see the Beneficial Owner &amp; Control Person form on the intranet), REQUIRE the completion of a form.</inlineHelpText>
    <label>Beneficial Owner &amp; Control Person form?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M&amp;A</fullName>
            </value>
            <value>
                <fullName>Capital Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/SC.recordType-meta.xml
<RecordType>
    <fullName>SC</fullName>
    <active>true</active>
    <description>Strategic Consulting</description>
    <label>SC</label>
</RecordType>

force-app/main/default/objects/Opportunity_Approval__c/Opportunity_Approval__c.object-meta.xml
<CustomObject>
    <description>These records are related to Opportunities and are required for submission before attaining committee approval and engagement.</description>
    <label>Opportunity Review</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Opportunity Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Approval__c/fields/EU_Override__c.field-meta.xml
<CustomField>
    <fullName>EU_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EU Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <description>Used for approval processes and to identify records between FEIS and NBC</description>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FEIS</fullName>
            </value>
            <value>
                <fullName>NBC</fullName>
            </value>
            <value>
                <fullName>CNBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Is_Client_EU__c.field-meta.xml
<CustomField>
    <fullName>Is_Client_EU__c</fullName>
    <formula>IF(Related_Opportunity__r.Client__r.Is_Client_EU_CF__c ||  EU_Override__c, &quot;TRUE&quot;, &quot;FALSE&quot;)</formula>
    <label>Is Client EU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Is_Majority_Sale__c.field-meta.xml
<CustomField>
    <fullName>Is_Majority_Sale__c</fullName>
    <label>Is Majority Sale?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Approval__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <inlineHelpText>Please indicate the related Opportunity record.</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Reviews</relationshipLabel>
    <relationshipName>Opportunity_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/Opportunity_Client_Subject__c.object-meta.xml
<CustomObject>
    <description>Custom object to track additional clients and subjects for an opportunity.</description>
    <label>Opportunity Client/Subject</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Clients/Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Client_Subject__c.field-meta.xml
<CustomField>
    <fullName>Client_Subject__c</fullName>
    <inlineHelpText>Client: parties which signed/acceded to HL&apos;s EL (or are anticipated to do so). 
Subject: underlying company</inlineHelpText>
    <label>Client/Subject</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Additional Clients/Subjects</relationshipLabel>
    <relationshipName>Opportunity_Clients_Subjects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The primary client or subject defined on the opportunity level.</inlineHelpText>
    <label>Primary?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Key Creditor: (i) creditor-side HL client, (ii) AHG member, (iii) other creditor with meaningful negotiation with the debtor, or (iv) lender holding &gt;10% of total debt or &gt;$50m</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Key Creditor</fullName>
            </value>
            <value>
                <fullName>PE Firm</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Client_Subject__c/recordTypes/Subject.recordType-meta.xml
<RecordType>
    <fullName>Subject</fullName>
    <active>true</active>
    <description>Type = &quot;Subject&quot;</description>
    <label>Subject</label>
</RecordType>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>HL Team</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Staff Role</label>
    <referenceTo>Staff_Role__c</referenceTo>
    <relationshipLabel>Opportunity Internal Teams</relationshipLabel>
    <relationshipName>Opportunity_Internal_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Role__c/Staff_Role__c.object-meta.xml
<CustomObject>
    <description>Used internally to control staff role display and order.</description>
    <label>Staff Role</label>
    <nameField>
        <label>Staff Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_HL_NBCController.cls
@isTest
private class Test_HL_NBCController
{
    @isTest
    private static void TestBasicFunctionality()
    {
        //Setup Test Data
        Account a = SL_TestSetupUtils.CreateAccount('', 1)[0];
        Insert a;
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('', 1)[0];
        o.Beneficial_Owner_Control_Person_form__c = 'No';
        Insert o;
        Opportunity_Approval__c oa = SL_TestSetupUtils.CreateOA('', 1)[0];
        oa.Related_Opportunity__c = o.Id;
        Insert oa;
        Test.startTest();
        PageReference pageRef = Page.HL_CNBC;
        Test.setCurrentPage(pageRef);
        //Setup Standard Controller
        ApexPages.StandardController sc = new  ApexPages.StandardController(oa);
        //Test Controller Properties/Methods
        HL_NBCController con = new  HL_NBCController(sc);
        List<Financials__c> financials = con.Financials;
        Financials__c financial = con.NewFinancials;
        con.NewFinancials.Related_Account__c = a.Id;
        con.RefreshFinancials();
        con.SaveAndReturn();
        con.SaveNewFinancial();
        con.SaveRecord();
        Test.stopTest();
        //Confirm there are no errors
        //System.assert(!ApexPages.hasMessages(ApexPages.severity.ERROR));
    }
    @isTest
    private static void Test2()
    {
        //Setup Test Data
        //Insert Additional Clients/Subjects
        Account newClient = SL_TestSetupUtils.CreateAccount('', 1)[0];
        Insert newClient;
        Account newSubject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        Insert newSubject;
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('', 1)[0];
        o.Beneficial_Owner_Control_Person_form__c = 'No';
        Insert o;
        
        contact objcon = new  contact();
        objcon.FirstName = 'Test';
        objcon.LastName = 'Contact';
        objcon.AccountId = newClient.Id;
        Insert objcon;
        
        List<Staff_Role__c> staffRoleList = new List<Staff_Role__c>();
        Staff_Role__c staffRole = new Staff_Role__c();
        staffRole.Name = 'Principal';
        staffRoleList.add(staffRole);
        Staff_Role__c staffRole1 = new Staff_Role__c();
        staffRole.Name = 'Manager';
        staffRoleList.add(staffRole1);
        Staff_Role__c staffRole2 = new Staff_Role__c();
        staffRole.Name = 'Initiator';
        staffRoleList.add(staffRole2);
        insert staffRoleList;
        //System.debug('Staffrole' +staffRoleList[0].Id +staffRoleList[1].Id +staffRoleList[2].Id );
        
        List<Opportunity_Internal_Team__c> oppIntList = new List<Opportunity_Internal_Team__c>();
        Opportunity_Internal_Team__c oppIntTeam = new Opportunity_Internal_Team__c();
        oppIntTeam.Contact__c = objcon.Id;
        oppIntTeam.Opportunity__c = o.Id;
        oppIntTeam.Staff_Role__c = staffRoleList[0].Id;
        oppIntList.add(oppIntTeam);
        
        Opportunity_Internal_Team__c oppIntTeam1 = new Opportunity_Internal_Team__c();
        oppIntTeam1.Contact__c = objcon.Id;
        oppIntTeam1.Opportunity__c = o.Id;
        oppIntTeam1.Staff_Role__c = staffRoleList[1].Id;
        oppIntList.add(oppIntTeam1);
        
        Opportunity_Internal_Team__c oppIntTeam2 = new Opportunity_Internal_Team__c();
        oppIntTeam2.Contact__c = objcon.Id;
        oppIntTeam2.Opportunity__c = o.Id;
        oppIntTeam2.Staff_Role__c = staffRoleList[2].Id;
        oppIntList.add(oppIntTeam2);
        
        insert oppIntList;
        
        Opportunity_Approval__c oa = SL_TestSetupUtils.CreateOA('', 1)[0];
        oa.Related_Opportunity__c = o.Id;
        oa.Form_Type__c = 'NBC';
        oa.Is_Majority_Sale__c = 'Yes';
        oa.EU_Override__c = true;
        Insert oa;
        System.debug(oa.Is_Client_EU__c);
        Financials__c pFinancials = new  Financials__c(Related_Account__c = newClient.Id, Related_Approval__c = oa.Id);
        Insert pFinancials;
        System.debug(oa.Form_Type__C);
        Opportunity_Client_Subject__c addSubject = new  Opportunity_Client_Subject__c(Opportunity__c = o.Id, Primary__c = false, Client_Subject__c = newSubject.Id, Type__c = 'Subject');
        Insert addSubject;
        System.debug(oa.Form_Type__C);
        Test.startTest();
        PageReference pageRef = Page.HL_CNBC;
        Test.setCurrentPage(pageRef);
        //Setup Standard Controller
        ApexPages.StandardController sc = new  ApexPages.StandardController(oa);
        //Test Controller Properties/Methods
        HL_NBCController con = new  HL_NBCController(sc);
        con.SubmitForReview();
        con.SaveRecord();
        System.debug(oa.Form_Type__C);
        con.SaveAndReturn();
        System.debug(oa.Form_Type__C);
        con.DelId = pFinancials.Id;
        Boolean OnOIT = con.OnOIT;
        PageReference objPf = con.TriggerValidation();
        con.DelId = pFinancials.Id;
        con.SubmitToAdmin();
        con.DeleteFinancial();
        con.EUOverride();
        con.IsMajoritySaleValid();
        //con.ValidateNBCForm(oa);
        //con.ValidateCNBCForm();
        /*contact objcon = new  contact();
        objcon.FirstName = 'Test1';
        objcon.LastName = 'Test2';
        Insert objcon;
        contact objcon2 = new  contact();
        objcon2.FirstName = 'Test3';
        objcon2.LastName = 'Test4';
        Insert objcon2;
        list<Contact> lstcon = new  list<Contact>();
        lstcon.add(objcon);
        lstcon.add(objcon2); */
        //con.GetMajoritySaleContactNames(lstcon);
        con.CancelSubmission();
        Test.stopTest();
        //Confirm there are no errors
        //System.assert(!ApexPages.hasMessages(ApexPages.severity.ERROR));
    }
    @isTest
    private static void Test3()
    {
        //Setup Test Data
        //Insert Additional Clients/Subjects
        Account newClient = SL_TestSetupUtils.CreateAccount('', 1)[0];
        Insert newClient;
        Account newSubject = SL_TestSetupUtils.CreateAccount('', 1)[0];
        Insert newSubject;
        Opportunity__c o = SL_TestSetupUtils.CreateOpp('', 1)[0];
        o.Beneficial_Owner_Control_Person_form__c = 'No';
        Insert o;
        Opportunity_Approval__c oa = SL_TestSetupUtils.CreateOA('', 1)[0];
        oa.Related_Opportunity__c = o.Id;
        oa.Form_Type__c = 'NBC';
        Insert oa;
        System.debug(oa.Form_Type__C);
        Financials__c pFinancials = new  Financials__c(Related_Account__c = newClient.Id, Related_Approval__c = oa.Id);
        Insert pFinancials;
        System.debug(oa.Form_Type__C);
        Opportunity_Client_Subject__c addSubject = new  Opportunity_Client_Subject__c(Opportunity__c = o.Id, Primary__c = false, Client_Subject__c = newSubject.Id, Type__c = 'Subject');
        Insert addSubject;
        System.debug(oa.Form_Type__C);
        PageReference pageRef = Page.HL_NBC;
        Test.setCurrentPage(pageRef);
        //Setup Standard Controller
        ApexPages.StandardController sc = new  ApexPages.StandardController(oa);
        //Test Controller Properties/Methods
        HL_NBCController con = new  HL_NBCController(sc);
        con.onchangeFlagSet();
        System.debug(oa.Form_Type__C);
        con.SubmitForReview();
        
    }
}