force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <description>SEC Tracking of gifts to external Contacts</description>
    <label>Gift Request</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <description>Whether the gift is approved</description>
    <inlineHelpText>Whether the gift is approved</inlineHelpText>
    <label>Approved</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency that the gift will be purchased in.</description>
    <inlineHelpText>Currency that the gift will be purchased in.</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Dollar</fullName>
                <default>true</default>
                <label>U.S. Dollar</label>
            </value>
            <value>
                <fullName>Euro (not in France)</fullName>
            </value>
            <value>
                <fullName>Euro (in France)</fullName>
            </value>
            <value>
                <fullName>British Pound</fullName>
            </value>
            <value>
                <fullName>Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>Australian Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Desired_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date the gift will be purchased by.</description>
    <inlineHelpText>Date the gift will be purchased by.</inlineHelpText>
    <label>Desired Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Type__c.field-meta.xml
<CustomField>
    <fullName>Gift_Type__c</fullName>
    <description>Type of gift</description>
    <inlineHelpText>Type of gift</inlineHelpText>
    <label>Gift Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Charitable Contribution</fullName>
            </value>
            <value>
                <fullName>Closing Party Client Gifts</fullName>
            </value>
            <value>
                <fullName>Gifts: Customers</fullName>
            </value>
            <value>
                <fullName>Gifts: Customers Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Value__c</fullName>
    <description>The gift&apos;s market value in the specified currency excluding the cost of tax, shipping, and engraving.</description>
    <inlineHelpText>The gift&apos;s market value in the specified currency excluding the cost of tax, shipping, and engraving.</inlineHelpText>
    <label>Gift Value</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/HL_Relationship__c.field-meta.xml
<CustomField>
    <fullName>HL_Relationship__c</fullName>
    <label>HL Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Reason_For_Gift__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Gift__c</fullName>
    <description>Reason for the gift</description>
    <inlineHelpText>Reason for the gift</inlineHelpText>
    <label>Reason For Gift</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <description>External Contact to receive gift</description>
    <inlineHelpText>External Contact to receive gift</inlineHelpText>
    <label>Recipient For Gift</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Gift Requests (Recipient For Gift)</relationshipLabel>
    <relationshipName>Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Submitted By Lookup to Contact</description>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Gift_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Submitted_For__c.field-meta.xml
<CustomField>
    <fullName>Submitted_For__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>HL Staff member giving gift</description>
    <inlineHelpText>HL Staff member giving gift</inlineHelpText>
    <label>Submitted For</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be submitted for a Houlihan Employee.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <infoMessage>Shows only Houlihan Employees.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Submitted_For</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <description>Vendor to be used for gift.</description>
    <inlineHelpText>Vendor to be used for gift.</inlineHelpText>
    <label>Vendor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_HL_GiftEditControllerExt.cls
@isTest
private class Test_HL_GiftEditControllerExt {
    @testSetup
    private static void SetupGiftEditData(){
        List<Account> acctForContactList = (List<Account>)HL_TestFactory.CreateSObjectList('Account', false, 2);
        List<Contact> internContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.Houlihan_Employee, false, 1);
        List<Contact> externContactList = HL_TestFactory.CreateContactList(HL_TestFactory.ContactRecordType.External_Contact, false, 1);
        List<Gift__c> giftList = (List<Gift__c>)HL_TestFactory.CreateSObjectList('Gift__c', false, 2);

        insert acctForContactList[0];

        internContactList[0].FirstName = 'TestInternFirstContact';
        internContactList[0].LastName = 'TestInternLastContact';
        internContactList[0].Account = AcctForContactList[0];
        insert internContactList[0];

        externContactList[0].FirstName = 'TestExterFirstContact';
        externContactList[0].LastName = 'TestExterLastContact';
        insert externContactList[0];

        giftList[0].Name='TestGift';
        giftList[0].Recipient__c=ExternContactList[0].Id;
        giftList[0].Submitted_For__c=InternContactList[0].Id;
        giftList[0].Submitted_By__c=InternContactList[0].Id;
        giftList[0].Gift_Type__c='Gift: Customers';
        giftList[0].Vendor__c='TestVendor';
        giftList[0].Currency__c='U.S. Dollar';
        giftList[0].HL_Relationship__c='Client';
        giftList[0].Gift_Value__c=101.00;
        giftList[0].Reason_For_Gift__c='Test Reason';
        giftList[0].Approved__c='Approved';
        giftList[0].Desired_Date__c = Date.today();
        giftList[0].CurrencyIsoCode = 'USD';
        giftList[1].Name='TestGift';
        giftList[1].Recipient__c=ExternContactList[0].Id;
        giftList[1].Submitted_For__c=InternContactList[0].Id;
        giftList[1].Submitted_By__c=InternContactList[0].Id;
        giftList[1].Gift_Type__c='Gift: Customers';
        giftList[1].Vendor__c='TestVendor';
        giftList[1].Currency__c='Euro (in France)';
        giftList[1].HL_Relationship__c='Client';
        giftList[1].Gift_Value__c=0.00;
        giftList[1].Reason_For_Gift__c='Test Reason';
        giftList[1].Approved__c='Approved';
        giftList[1].Desired_Date__c = Date.today();
        giftList[1].CurrencyIsoCode = 'EUR';
        insert giftList;
    }

    @isTest
    private static void TestGiftEditSave() {
        List<Gift__c> giftList = [SELECT Name, CurrencyIsoCode, Currency__c, Recipient__c, Desired_Date__c, Gift_Value__c FROM Gift__c WHERE CurrencyIsoCode = 'USD'];
        ApexPages.StandardController sc = new ApexPages.StandardController(giftList[0]);
        ApexPages.currentPage().getParameters().put('Id', giftList[0].Id);

        Test.startTest();

        HL_GiftEditControllerExt controllerExt = new HL_GiftEditControllerExt(sc);
        controllerExt.save();

        Test.stopTest();

        List<Gift__c> giftResultList = [SELECT Name, Recipient__r.LastName, Recipient__c
                                        FROM Gift__c
                                        WHERE Name = 'TestGift' LIMIT 1];

        System.assertEquals('TestExterLastContact', giftResultList[0].Recipient__r.LastName);
    }

    @isTest
    private static void TestAddGift(){
        List<Gift__c> giftList = [SELECT Name FROM Gift__c WHERE CurrencyIsoCode = 'USD'];
        ApexPages.StandardController sc = new ApexPages.StandardController(giftList[0]);
        ApexPages.currentPage().getParameters().put('Id', giftList[0].Id);

        Test.startTest();

        HL_GiftEditControllerExt controllerExt = new HL_GiftEditControllerExt(sc);
        String AddPageUrl = controllerExt.AddGift().getUrl();

        Test.stopTest();

        System.assertEquals('/apex/SL_GiftPreApproval', AddPageUrl);
    }

    @isTest
    private static void TestGiftMaxValue(){
        List<Gift__c> giftList = [SELECT Name FROM Gift__c WHERE CurrencyIsoCode = 'USD'];
        Gift__c[] gifts = [SELECT Name, Recipient__r.LastName, Recipient__c, CurrencyIsoCode,Currency__c, Gift_Value__c, Desired_Date__c
                           FROM Gift__c
                           WHERE Name = 'TestGift' LIMIT 1];

        Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(gifts[0]);
        ApexPages.currentPage().getParameters().put('Id', giftList[0].Id);
        HL_GiftEditControllerExt controllerExt = new HL_GiftEditControllerExt(sc);
        GiftList[0].Gift_Value__c = 101.00;
        update GiftList[0];
        ApexPages.currentPage().getParameters().put('Id', giftList[0].Id);
        controllerExt.save();

        Test.stopTest();

        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            if(msg.getSeverity() == ApexPages.Severity.WARNING){
                System.assertEquals(ApexPages.Severity.WARNING, msg.getSeverity());
            }else if(msg.getSeverity() == ApexPages.Severity.CONFIRM){
                System.assertEquals(ApexPages.Severity.CONFIRM, msg.getSeverity());
            }
        }
    }

    @isTest
    private static void TestGiftMinValue(){
        List<Gift__c> giftList = [SELECT Name FROM Gift__c];
        Gift__c[] gifts = [SELECT Name, Recipient__r.LastName, Recipient__c, CurrencyIsoCode, Currency__c, Gift_Value__c, Desired_Date__c
                           FROM Gift__c
                           WHERE Name = 'TestGift' LIMIT 2];
        ApexPages.StandardController sc = new ApexPages.StandardController(gifts[1]);
        ApexPages.currentPage().getParameters().put('Id', giftList[1].Id);
        HL_GiftEditControllerExt controllerExt = new HL_GiftEditControllerExt(sc);
        GiftList[1].Gift_Value__c = 0.00;
        GiftList[1].Desired_Date__c=system.today().addDays(-2);
        update GiftList[1];
        ApexPages.currentPage().getParameters().put('Id', giftList[1].Id);

        Test.startTest();

        controllerExt.save();

        Test.stopTest();

        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
    }

    @isTest
    private static void TestCancel(){
        List<Gift__c> giftList = [SELECT Name FROM Gift__c WHERE CurrencyIsoCode = 'USD'];
        ApexPages.StandardController sc = new ApexPages.StandardController(giftList[0]);
        ApexPages.currentPage().getParameters().put('Id', giftList[0].Id);

        Test.startTest();

        HL_GiftEditControllerExt controllerExt = new HL_GiftEditControllerExt(sc);
        controllerExt.ReturnURL='/apex/SL_GiftPreApproval';
        PageReference pageRef = controllerExt.Cancel();

        Test.stopTest();

        System.assertEquals(new PageReference('/apex/SL_GiftPreApproval').getUrl(), pageRef.getUrl());
    }
}