force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Coverage_Contact__c/Coverage_Contact__c.object-meta.xml
<CustomObject>
    <label>Coverage Contact</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Coverage Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Contact__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Coverage_Contact__r.AccountId</formula>
    <label>Coverage Contact Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage_Contact__c/fields/Coverage_Contact__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coverage Contacts</relationshipLabel>
    <relationshipName>Coverage_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Contact__c/fields/Coverage_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Coverage Team Member</label>
    <referenceTo>Coverage_Team__c</referenceTo>
    <relationshipLabel>Coverage Contacts</relationshipLabel>
    <relationshipName>Coverage_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/Coverage_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track officer coverage on accounts.</description>
    <label>Coverage Team</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Coverage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Team__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coverage_Team__c/fields/Officer__c.field-meta.xml
<CustomField>
    <fullName>Officer__c</fullName>
    <label>Officer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Houlihan_Employee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Industry_Group__c</field>
            <operation>equals</operation>
            <value>FS - Financial Sponsors</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Coverage Team Member</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Standard Coverage Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coverage Team</relationshipLabel>
    <relationshipName>Accounts_Coverage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_HL_CoverageContactHandler.cls
@IsTest
private class Test_HL_CoverageContactHandler {
    @isTest private static void TestNewCoverageTeamRecordWithNewData(){
        //Setup our test data
        Account a = SL_TestSetupUtils.CreateAccount('',1)[0];
        insert a;
        Contact extContact = SL_TestSetupUtils.CreateContact('',1,SL_TestSetupUtils.ContactType.External_Contact)[0];
        extContact.AccountId = a.Id;
        insert extContact;
        Contact officerContact = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.Houlihan_Employee)[0];
        insert officerContact;
        
        Test.startTest();
        Coverage_Team__c ct = new Coverage_Team__c(Officer__c = officerContact.Id, Company__c = a.Id);
        insert ct;
        Coverage_Contact__c cc = new Coverage_Contact__c(Coverage_Contact__c = extContact.Id, Coverage_Team_Member__c = ct.Id);
  
        insert cc;
        update cc;
        delete cc;
   		Test.stopTest();
    }
}