force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <description>Custom object to track a contact-to-contact relationships.</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/External_Contact__c.field-meta.xml
<CustomField>
    <fullName>External_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>External Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No external contacts met the criteria for your search.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Relationships</relationshipLabel>
    <relationshipName>Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/HL_Contact__c.field-meta.xml
<CustomField>
    <fullName>HL_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>HL Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No Houlihan employees met the criteria for your search.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SL_Test_ContactClone.cls
/**
* \arg ClassName      : SL_ContactClone
* \arg JIRATicket     : HL-22
* \arg CreatedOn      : 15/JULY/2014
* \arg LastModifiedOn : 15/JULY/2014
* \arg CreatededBy    : Lodhi
* \arg ModifiedBy     : -
* \arg Description    : Test class for SL_ContactClone.
*/
@isTest()
public with sharing class SL_Test_ContactClone 
{
	@isTest()
	static void test_ContactClone()
    {
    	List<Contact> lstContactHL = SL_TestSetupUtils.CreateContact('Contact', 5, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE);
    	insert lstContactHL;
    	
    	List<Contact> lstContactEX = SL_TestSetupUtils.CreateContact('Contact', 5, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT);
        insert lstContactEX;
    	
    	List<Relationship__c> lstRelationship = SL_TestSetupUtils.CreateRelationship('Relationship__c', 5);
        for(integer i=0; i<5; i++)
        {
            lstRelationship[i].External_Contact__c = lstContactEX[i].Id;
            lstRelationship[i].HL_Contact__c = lstContactHL[i].Id;
        }

        insert lstRelationship;
        System.assertEquals(lstRelationship.size(), 5);
        
    	ApexPages.StandardController sc = new ApexPages.standardController(lstContactHL[0]);
    	SL_ContactClone objContactClone = new SL_ContactClone(sc); 
    	objContactClone.cloneContact();
    	
    	List<Contact> lstContact = [SELECT Id FROM Contact];
    	System.assertEquals(lstContact.size(), 11);
    }
}