force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <description>Custom object to track a contact-to-contact relationships.</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/External_Contact__c.field-meta.xml
<CustomField>
    <fullName>External_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>External Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No external contacts met the criteria for your search.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>External Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Relationships</relationshipLabel>
    <relationshipName>Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/HL_Contact__c.field-meta.xml
<CustomField>
    <fullName>HL_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>HL Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No Houlihan employees met the criteria for your search.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Houlihan Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_HL_RelationshipHandler.cls
@isTest
private class Test_HL_RelationshipHandler {
    @isTest private static void TestBasicFunctionality(){
         //Setup Test Data
        Contact con = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.EXTERNAL_CONTACT)[0];
        insert con;
        Contact c = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert c;
        Contact c2 = SL_TestSetupUtils.CreateContact('', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert c2;
        List<Relationship__c> rList = SL_TestSetupUtils.CreateRelationship('',2);
        for(Relationship__c r : rList){
            r.External_Contact__c = con.Id;
        }
        rList[0].HL_Contact__c = c.id;
        rList[1].HL_Contact__c = c2.id;
        insert rList;          
       
        delete rList;
       
    }
}