force-app/main/default/objects/Contact/recordTypes/Houlihan_Employee.recordType-meta.xml
<RecordType>
    <fullName>Houlihan_Employee</fullName>
    <active>true</active>
    <description>Use for current employees of Houlihan Lokey.</description>
    <label>Houlihan Employee</label>
</RecordType>

force-app/main/default/objects/Contact_Comment__c/Contact_Comment__c.object-meta.xml
<CustomObject>
    <label>HL Contact Comment</label>
    <nameField>
        <displayFormat>CCOM-{0000}</displayFormat>
        <label>Comment Label</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Comment__c/fields/Comment_Type__c.field-meta.xml
<CustomField>
    <fullName>Comment_Type__c</fullName>
    <label>Comment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compliance</fullName>
                <default>true</default>
                <label>Compliance</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Comment__c/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HL Contact Comments</relationshipLabel>
    <relationshipName>Contact_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delegate_Public_Group__c/Delegate_Public_Group__c.object-meta.xml
<CustomObject>
    <description>used to store/manage all delegate public groups.</description>
    <label>Delegate Public Group</label>
    <nameField>
        <displayFormat>DPG-{0000}</displayFormat>
        <label>Delegate Public Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegate Public Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delegate_Public_Group__c/fields/Banker__c.field-meta.xml
<CustomField>
    <fullName>Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delegate_Public_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delegate_Public_Group_Member__c/Delegate_Public_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Delegate Public Group Member</label>
    <nameField>
        <displayFormat>DPGM-{0000}</displayFormat>
        <label>Delegate Public Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegate Public Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delegate_Public_Group_Member__c/fields/Delegate__c.field-meta.xml
<CustomField>
    <fullName>Delegate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delegate_Public_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delegate_Public_Group_Member__c/fields/Delegate_Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Delegate_Public_Group__c</fullName>
    <label>Delegate Public Group</label>
    <referenceTo>Delegate_Public_Group__c</referenceTo>
    <relationshipLabel>Delegate Public Group Members</relationshipLabel>
    <relationshipName>Delegate_Public_Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_HL_ContactCommentHandler.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_HL_ContactCommentHandler {
    
   
   private static User createTestUser(Id profID, String fName, String lName)
   {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
       
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                                lastName = lName,
                                email = uniqueName + '@test' + orgId + '.org',
                                Username = uniqueName + '@test' + orgId + '.org',
                                EmailEncodingKey = 'ISO-8859-1',
                                Alias = uniqueName.substring(18, 23),
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US',
                                ProfileId = profId
                             );
        return tuser;
    }
    
    @isTest
    static void testInsertCase1() {
        Contact testContactRecord = SL_TestSetupUtils.CreateContact('Contact', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert testContactRecord ;
        Contact_Comment__c testcc1 = new Contact_Comment__c(Related_Contact__c = testContactRecord.Id, Comment_Type__c = 'Compliance',Comment__c = 'Test');
        insert testcc1;
    }
    
    @isTest
    static void testInsertCase2() {
        
        List<User> lstofUsers = new list<User>();       
        Profile pf1 = [SELECT Id FROM Profile WHERE Name = 'Compliance User'];
        User user1 = createTestUser(pf1.Id, 'Test FirstName1', 'Test LastName');        
        lstofUsers.add(user1);
        
        Profile pf2 = [SELECT Id FROM Profile WHERE Name = 'Standard User Template'];
        User delegateUser = createTestUser(pf2.Id, 'Test FirstName2', 'Test LastName');        
        lstofUsers.add(delegateUser);
        insert lstofUsers;
        Delegate_Public_Group_Member__c DGM = new Delegate_Public_Group_Member__c();
        for(Delegate_Public_Group__c DPG : [Select id From Delegate_Public_Group__c Where Banker__c =: user1.id])
        {
            DGM.Delegate_Public_Group__c = DPG.Id;
            DGM.Delegate__C = delegateUser.Id;
            insert DGM;
        }
        
        System.runAs(delegateUser) {
            try{
                Contact testContactRecord = SL_TestSetupUtils.CreateContact('Contact', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
                insert testContactRecord ;        
                Contact_Comment__c testcc2 = new Contact_Comment__c(Related_Contact__c = testContactRecord.Id, Comment_Type__c = 'Compliance',Comment__c = 'Test');    
                insert testcc2;                
            }catch(Exception e){
                system.assertNotEquals(e.getmessage(),null);
            }
        }       
        
    }
    
    @isTest
    static void testInsertCase3() {
        Contact testContactRecord = SL_TestSetupUtils.CreateContact('Contact', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert testContactRecord ;
               
        Profile pf2 = [SELECT Id FROM Profile WHERE Name = 'Standard User Template'];
        User normalUser = createTestUser(pf2.Id, 'Test FirstName2', 'Test LastName');    
        insert normalUser ;
        
        System.runAs(normalUser ) {
            try{                     
                Contact_Comment__c testcc2 = new Contact_Comment__c(Related_Contact__c = testContactRecord.Id, Comment_Type__c = 'Compliance',Comment__c = 'Test');    
                insert testcc2;                
            }catch(Exception e){
                system.assertNotEquals(e.getmessage(),null);
            }
        }  
    }
    
    @isTest
    static void testInsertCase4() {
        
        List<User> lstofUsers = new list<User>();       
        Profile pf1 = [SELECT Id FROM Profile WHERE Name = 'Compliance User'];
        User user1 = createTestUser(pf1.Id, 'Test FirstName1', 'Test LastName');        
        lstofUsers.add(user1);
        
        Profile pf2 = [SELECT Id FROM Profile WHERE Name = 'Standard User Template'];
        User delegateUser = createTestUser(pf2.Id, 'Test FirstName2', 'Test LastName');        
        lstofUsers.add(delegateUser);
        insert lstofUsers;
        Delegate_Public_Group_Member__c DGM = new Delegate_Public_Group_Member__c();
        for(Delegate_Public_Group__c DPG : [Select id From Delegate_Public_Group__c Where Banker__c =: user1.id])
        {
            DGM.Delegate_Public_Group__c = DPG.Id;
            DGM.Delegate__C = delegateUser.Id;
            insert DGM;
        }
        Contact testContactRecord = SL_TestSetupUtils.CreateContact('Contact', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert testContactRecord ;        
        Contact_Comment__c testcc2 = new Contact_Comment__c(Related_Contact__c = testContactRecord.Id, Comment_Type__c = 'Compliance',Comment__c = 'Test');    
        testcc2.ownerId = delegateUser.id;
        insert testcc2;   
           
        
    }
    
    @isTest
    static void testUpdateCase() {
        Contact testContactRecord = SL_TestSetupUtils.CreateContact('Contact', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert testContactRecord ;
        Contact_Comment__c testcc = new Contact_Comment__c(Related_Contact__c = testContactRecord.Id, Comment_Type__c = 'Compliance',Comment__c = 'Test');
        insert testcc;
                
        List<User> lstofUsers = new list<User>();       
        Profile pf1 = [SELECT Id FROM Profile WHERE Name = 'Compliance User'];
        User user1 = createTestUser(pf1.Id, 'Test FirstName1', 'Test LastName');        
        lstofUsers.add(user1);
        
        Profile pf2 = [SELECT Id FROM Profile WHERE Name = 'Accounting User'];
        User delegateUser = createTestUser(pf2.Id, 'Test FirstName2', 'Test LastName');        
        lstofUsers.add(delegateUser);
        insert lstofUsers;
        Delegate_Public_Group_Member__c DGM = new Delegate_Public_Group_Member__c();
        for(Delegate_Public_Group__c DPG : [Select id From Delegate_Public_Group__c Where Banker__c =: user1.id])
        {
            DGM.Delegate_Public_Group__c = DPG.Id;
            DGM.Delegate__C = delegateUser.Id;
            insert DGM;
        }
        try{
        testcc.comment__c = 'test3';      
        update testcc;
        }catch(Exception e)
        {
            system.assertNotEquals(e.getmessage(),null);
        }
    }
    
    @isTest
    static void testDeleteCase1() {
        Contact testContactRecord = SL_TestSetupUtils.CreateContact('Contact', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert testContactRecord ;
        Contact_Comment__c testcc = new Contact_Comment__c(Related_Contact__c = testContactRecord.Id, Comment_Type__c = 'Compliance',Comment__c = 'Test');
        insert testcc;                
        delete testcc;
        boolean isRecordExist = false;
        for(Contact_Comment__c c : [Select id From Contact_Comment__c where id =: testcc.id])
            isRecordExist = true;
        system.assertEquals(false,isRecordExist);        
    }
    
    @isTest
    static void testDeleteCase2() {
        Contact testContactRecord = SL_TestSetupUtils.CreateContact('Contact', 1, SL_TestSetupUtils.ContactType.HOULIHAN_EMPLOYEE)[0];
        insert testContactRecord ;
        Contact_Comment__c testcc = new Contact_Comment__c(Related_Contact__c = testContactRecord.Id, Comment_Type__c = 'Compliance',Comment__c = 'Test');
        insert testcc;        
       
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'Compliance User'];
        User user1 = createTestUser(pf.Id, 'Test FirstName', 'Test LastName');        
        insert user1;
        
        System.runAs(user1) {
            try{
                delete testcc;
            }catch(Exception e){
                system.assertNotEquals(e.getmessage(),null);
            }
        } 
    }
}