force-app/main/default/objects/Postal_Code__c/Postal_Code__c.object-meta.xml
<CustomObject>
    <label>Postal Code</label>
    <nameField>
        <label>ZIP CODE LOOK UP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code__c/fields/CITY__c.field-meta.xml
<CustomField>
    <fullName>CITY__c</fullName>
    <label>CITY</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Postal_Code__c/fields/COUNTY__c.field-meta.xml
<CustomField>
    <fullName>COUNTY__c</fullName>
    <label>COUNTY</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Postal_Code__c/fields/STATE__c.field-meta.xml
<CustomField>
    <fullName>STATE__c</fullName>
    <label>STATE</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Postal_Code__c/fields/ZIPCODE__c.field-meta.xml
<CustomField>
    <fullName>ZIPCODE__c</fullName>
    <label>ZIPCODE</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_PostalCode.cls
global with sharing class HL_PostalCode {
    public HL_PostalCode(ApexPages.StandardController controller) {} // empty constructor
    public HL_PostalCode(HL_LookupAccountController controller){}
    @RemoteAction
    global static List<Postal_Code__c> GetByPostalCode(String postalCode){
        if(!String.isBlank(postalCode) && postalCode.length() > 5){
            postalCode = postalCode.substring(0,5);
        }
        return [SELECT CITY__c, COUNTY__c, STATE__c FROM Postal_Code__c WHERE ZIPCODE__c =: postalCode];
    }
}