force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Report_Link__c/fields/Report_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_Link_URL__c</fullName>
    <description>Link that will execute the report</description>
    <label>Report Link URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom object to track potential engagements.</description>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Full_Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Full_Opportunity_ID__c</fullName>
    <formula>CASESAFEID( Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Opportunity ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HL_OpportunityReportLinks.cls
public with sharing class HL_OpportunityReportLinks {
    public List<HL_Report_Link__c>	LinkList	{ get;set; }
    public string PageTitle						{ get;set; }
    public string PageStyle						{ get;set; }
    
    public HL_OpportunityReportLinks(Apexpages.StandardController con)
    {        
        Opportunity__c currOpportunity;
        string OpportunityID; 
      
        try
        {
        	currOpportunity = [SELECT Name, Full_Opportunity_ID__c FROM Opportunity__c WHERE ID =: con.getId()];
            OpportunityID = currOpportunity.Full_Opportunity_ID__c; 
        }
        catch(Exception ex)
        {
            currOpportunity = null;
            OpportunityID = null;
        }       
        
        if(!String.isBlank(OpportunityID))
        {
            LinkList = HL_ReportLink.GetByType(OpportunityID, 'Opportunity Single');
            
			for(HL_Report_Link__c currLink: LinkList)            
                currLink.Report_Link_URL__c = currLink.Report_Link_URL__c.replace('{!Opportunity__c.Full_Opportunity_ID__c}', OpportunityID);
            
            PageTitle = 'Opportunity Reports for ' + currOpportunity.Name;   
            PageStyle = 'display:initial;';            
        }
        else     
        {
        	LinkList = HL_ReportLink.GetByType('Opportunity Group');
            
            PageTitle = 'Opportunity Reports';
            PageStyle = 'display:none;';
        }    
    }
    
    public HL_OpportunityReportLinks(){}
    
    public Pagereference ReturnToParent()
    {
        Pagereference pageref = new Pagereference('/' + ApexPages.currentPage().getParameters().get('id'));
	   	return pageref;
    }
}