force-app/main/default/objects/HL_Report_Link__c/HL_Report_Link__c.object-meta.xml
<CustomObject>
    <label>HL Report Link</label>
    <nameField>
        <label>HL Report Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HL Report Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HL_Report_Link__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Name of report that the end user will see</description>
    <label>Display Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_HL_ReportLink.cls
@isTest
private class Test_HL_ReportLink {
    @isTest private static void TestBasicFunctionality(){
        //Create Test Data of Engagement Single Link Records
        List<HL_Report_Link__c> lnksCreated = SL_TestSetupUtils.CreateHLReportLink(null,5);
        for(integer i=0;i<lnksCreated.size(); i++)
            lnksCreated[i].Display_Name__c += '_' + i; 
        insert lnksCreated;     
        Test.startTest();
        	List<HL_Report_Link__c> lnkResults = HL_ReportLink.GetByType('Engagement Single');
        Test.stopTest();      
        System.assertEquals(lnkResults.size(), lnksCreated.size()); 
    }
    
    @isTest private static void TestAsStandardUser(){
        //Create Test Data of Engagement Single Link Records
        User u = SL_TestSetupUtils.CreateTestUser('Standard User');
        List<HL_Report_Link__c> lnksCreated = SL_TestSetupUtils.CreateHLReportLink(null,5);
        for(integer i=0;i<lnksCreated.size(); i++)
            lnksCreated[i].Display_Name__c += '_' + i; 
        insert lnksCreated;
        insert u;
        System.runAs(u){
            Test.startTest();
                List<HL_Report_Link__c> lnkResults = HL_ReportLink.GetByType('Engagement Single');
            Test.stopTest();
            
            System.assertEquals(0, lnkResults.size()); 
        }
    }
}