force-app/main/default/objects/Engagement_Internal_Team__c/Engagement_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that are staffed on an engaged deal/project.</description>
    <label>Engagement Internal Team</label>
    <nameField>
        <displayFormat>EIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Internal_Team__c/fields/Invalid_Office_LOB__c.field-meta.xml
<CustomField>
    <fullName>Invalid_Office_LOB__c</fullName>
    <formula>IF( 
AND(	
OR(TEXT(Contact__r.Line_of_Business__c) != LOB__c, 
TEXT( Contact__r.Office__c ) != Office__c 
), 
AND(Start_Date__c &lt;= TODAY(), End_Date__c &gt; TODAY()), 
AND(NOT(TEXT(Engagement__r.Stage__c)=&apos;Dead&apos;), NOT(TEXT(Engagement__r.Stage__c)=&apos;Closed&apos;)) 
) 

, 
&apos;true&apos; 
, 
&apos;false&apos; 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invalid Office/LOB?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Internal_Team__c/Opportunity_Internal_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object to track Houlihan Lokey employees that participate as team members for a prospective engagement.</description>
    <label>Opportunity Internal Team</label>
    <nameField>
        <displayFormat>OIT-{000000}</displayFormat>
        <label>Internal Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Internal Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Internal_Team__c/fields/Invalid_Office_LOB__c.field-meta.xml
<CustomField>
    <fullName>Invalid_Office_LOB__c</fullName>
    <formula>IF( 
AND(	
OR(TEXT(Contact__r.Line_of_Business__c) != LOB__c, 
TEXT( Contact__r.Office__c ) != Office__c 
), 
AND(Start_Date__c &lt;= TODAY(), End_Date__c &gt; TODAY()), 
AND(NOT(TEXT(Opportunity__r.Stage__c)=&apos;Dead&apos;), NOT(TEXT(Opportunity__r.Stage__c)=&apos;Lost&apos;), NOT(TEXT(Opportunity__r.Stage__c)=&apos;Engaged&apos;)) 
) 

, 
&apos;true&apos; 
, 
&apos;false&apos; 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invalid Office/LOB?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SL_Scheduler_Stamp_InternalTeam.cls
/**  
* \arg ClassName      : SL_Scheduler_Stamp_InternalTeam
* \arg JIRATicket     : HL-91
* \arg CreatedOn      : 20/JAN/2015
* \arg LastModifiedOn : 20/JAN/2015
* \arg CreatededBy    : GM
* \arg ModifiedBy     : -
* \arg Description    : Scheduler class to schedule the Batch Stamp Internal Teams
*/
global with sharing class SL_Scheduler_Stamp_InternalTeam implements Schedulable
{
    /* Start - Variables */
    /* End - Variables */
    
    /* Start - Constructor */
    global SL_Scheduler_Stamp_InternalTeam()
    {
        //do nothing.
    }
    /* End - Constructor */
    /*
        @MethodName : execute.
        @param      : SchedulableContext
        @Description: This Class calls Batch class
    */
    global void execute(SchedulableContext sc)
    {
        //Initiate 2 instances of batch job, 1 for Opportunity Internal Team and other for 
        System.debug('\n\nIn Schedule: ');
        try
        {            
            //Engagement Internal Team.            
            
            String oitQuery = HL_PercentageSplitHandler.GetCreatableFieldsSOQL('Opportunity_Internal_Team__c');
            oitQuery = oitQuery + ' WHERE Invalid_Office_LOB__c=\'true\'';
            SL_Batch_StampInternalTeam batch = new SL_Batch_StampInternalTeam(oitQuery);
            Database.executeBatch(batch, 200);                        
        }
        catch(Exception e)
        {
            //Show exception in debug logs if any
            System.debug('\n\n### OIT Batch job Exception: ' + e);
        }
        try
        {            
            //Engagement Internal Team.                        
            String eitQuery = HL_PercentageSplitHandler.GetCreatableFieldsSOQL('Engagement_Internal_Team__c');
            eitQuery = eitQuery + ' WHERE Invalid_Office_LOB__c=\'true\'';
            
            SL_Batch_StampInternalTeam batch = new SL_Batch_StampInternalTeam(eitQuery);
            Database.executeBatch(batch, 200);                        
        }
        catch(Exception e)
        {
            //Show exception in debug logs if any
            System.debug('\n\n### EIT Batch job Exception: ' + e);
        }
        
    }
    /* End */
}