force-app/main/default/objects/Activity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As of Winter 16 release, we can now add lookup fields to Events.  This field was added to make it easier to pull in contact details via a lookup.  The WhoId cannot be used as it is a polymorphic lookup field and doesn&apos;t allow you to use it as a true relationship field.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <externalId>true</externalId>
    <label>ParentId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <description>RIVA Custom Object</description>
    <label>Activity (R)</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities (R)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Supplement__c/Activity_Supplement__c.object-meta.xml
<CustomObject>
    <description>Stores related activity fields that cannot be added to the restrictive activity custom fields
- Long Text Area (Over 255 characters)
- Possible Rich Text as a later enhancement</description>
    <label>Activity Supplement</label>
    <nameField>
        <displayFormat>ASN-{00000000}</displayFormat>
        <label>Activity Supplement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Supplements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Supplement__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <description>Activity Record Id</description>
    <externalId>true</externalId>
    <label>Activity</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Activity_Supplement__c/fields/Sync_Description__c.field-meta.xml
<CustomField>
    <fullName>Sync_Description__c</fullName>
    <description>Holds the synch description to be sent to outlook</description>
    <label>Sync Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mentor)</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/classes/HL_ActivitySupplement.cls
public without sharing class HL_ActivitySupplement {
    public Activity_Supplement__c ActivitySupplement {get; set;}
    private Event Event {get; set;}
    private List<Contact> RelatedContacts {get; set;}
    public HL_ActivitySupplement(Event event, List<Contact> relatedContacts) {
        this.ActivitySupplement = new Activity_Supplement__c(Activity__c = event.Id);
        this.Event = event;
        this.RelatedContacts = relatedContacts;

        //Generate the Sync Description
        GenerateSyncDescription();
    }

    private void GenerateSyncDescription(){
        ActivitySupplement.Sync_Description__c = HL_Activity.SYNC_DIVIDER + ('\n'.repeat(2));
        
        for(Contact c : RelatedContacts){
             if(c != null)
                ActivitySupplement.Sync_Description__c += c.Name + (!String.isBlank(c.Email) ? ' - ' + c.Email : '') + '\n';
        }

        //Append Link Back to Record
        ActivitySupplement.Sync_Description__c += ('\n'.repeat(2)) + 'To View the Activity in Salesforce, Use The Link Below:\n' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + Event.Id;
    }

    //Generate or Refresh the Sync Description for the Events
    public static List<Activity_Supplement__c> RefreshSyncDescription(List<Event> eList){
        List<Id> idList = new List<Id>();
        Map<Id, List<Contact>> eventToRelatedContactMap = new Map<Id, List<Contact>>();
        Map<Id, Activity_Supplement__c> existingSupplementMap = new Map<Id, Activity_Supplement__c>();
        List<Activity_Supplement__c> asToUpsert = new List<Activity_Supplement__c>();

        for(Event e: eList)
            idList.add(e.Id);

        //Get the Related Contact Records
        for(Event e : [SELECT ParentId__c, Contact__r.Name, Contact__r.Email, Contact__r.RecordType.DeveloperName FROM Event WHERE ParentId__c IN: idList]){
            Contact c = e.Contact__r;
            if(c != null && c.RecordType.DeveloperName == 'EXTERNAL_CONTACT'){
                if(eventToRelatedContactMap.get(e.ParentId__c) == null)
                    eventToRelatedContactMap.put(e.ParentId__c, new List<Contact> {c});
                else{
                    List<Contact> cList = eventToRelatedContactMap.get(e.ParentId__c);
                    cList.add(c);
                }
            }
        }
        
        //Get the Existing Supplement Records
        for(Activity_Supplement__c s : [SELECT Activity__c, Sync_Description__c FROM Activity_Supplement__c WHERE Activity__c IN: idList])
            existingSupplementMap.put(s.Activity__c, s);
        
        for(Id id : idList){
            Activity_Supplement__c s = existingSupplementMap.get(id);

            if(s == null)
                s = new Activity_Supplement__c(Activity__c = id);

            List<Contact> cList = eventToRelatedContactMap.get(id);
            if(cList != null){
                s.Sync_Description__c = new HL_ActivitySupplement(new Event(Id = id), eventToRelatedContactMap.get(id)).ActivitySupplement.Sync_Description__c;
                asToUpsert.add(s);
            }
        }

        if(asToUpsert.size() > 0)
            upsert asToUpsert;
        
        return new List<Activity_Supplement__c>();
    }
}