force-app/main/default/objects/Activity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>End Date Portion Only</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End Time Portion Only</description>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:15 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>12:45 AM</fullName>
            </value>
            <value>
                <fullName>01:00 AM</fullName>
            </value>
            <value>
                <fullName>01:15 AM</fullName>
            </value>
            <value>
                <fullName>01:30 AM</fullName>
            </value>
            <value>
                <fullName>01:45 AM</fullName>
            </value>
            <value>
                <fullName>02:00 AM</fullName>
            </value>
            <value>
                <fullName>02:15 AM</fullName>
            </value>
            <value>
                <fullName>02:30 AM</fullName>
            </value>
            <value>
                <fullName>02:45 AM</fullName>
            </value>
            <value>
                <fullName>03:00 AM</fullName>
            </value>
            <value>
                <fullName>03:15 AM</fullName>
            </value>
            <value>
                <fullName>03:30 AM</fullName>
            </value>
            <value>
                <fullName>03:45 AM</fullName>
            </value>
            <value>
                <fullName>04:00 AM</fullName>
            </value>
            <value>
                <fullName>04:15 AM</fullName>
            </value>
            <value>
                <fullName>04:30 AM</fullName>
            </value>
            <value>
                <fullName>04:45 AM</fullName>
            </value>
            <value>
                <fullName>05:00 AM</fullName>
            </value>
            <value>
                <fullName>05:15 AM</fullName>
            </value>
            <value>
                <fullName>05:30 AM</fullName>
            </value>
            <value>
                <fullName>05:45 AM</fullName>
            </value>
            <value>
                <fullName>06:00 AM</fullName>
            </value>
            <value>
                <fullName>06:15 AM</fullName>
            </value>
            <value>
                <fullName>06:30 AM</fullName>
            </value>
            <value>
                <fullName>06:45 AM</fullName>
            </value>
            <value>
                <fullName>07:00 AM</fullName>
            </value>
            <value>
                <fullName>07:15 AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Followup_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_End_Date__c</fullName>
    <description>Follow Up Date Portion Only</description>
    <label>Follow-up End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Followup_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Followup_End_Time__c</fullName>
    <description>Follow-up End Time Portion Only</description>
    <label>Follow-up End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>01:00 AM</fullName>
            </value>
            <value>
                <fullName>01:30 AM</fullName>
            </value>
            <value>
                <fullName>02:00 AM</fullName>
            </value>
            <value>
                <fullName>02:30 AM</fullName>
            </value>
            <value>
                <fullName>03:00 AM</fullName>
            </value>
            <value>
                <fullName>03:30 AM</fullName>
            </value>
            <value>
                <fullName>04:00 AM</fullName>
            </value>
            <value>
                <fullName>04:30 AM</fullName>
            </value>
            <value>
                <fullName>05:00 AM</fullName>
            </value>
            <value>
                <fullName>05:30 AM</fullName>
            </value>
            <value>
                <fullName>06:00 AM</fullName>
            </value>
            <value>
                <fullName>06:30 AM</fullName>
            </value>
            <value>
                <fullName>07:00 AM</fullName>
            </value>
            <value>
                <fullName>07:30 AM</fullName>
            </value>
            <value>
                <fullName>08:00 AM</fullName>
                <default>true</default>
                <label>08:00 AM</label>
            </value>
            <value>
                <fullName>08:30 AM</fullName>
            </value>
            <value>
                <fullName>09:00 AM</fullName>
            </value>
            <value>
                <fullName>09:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>01:00 PM</fullName>
            </value>
            <value>
                <fullName>01:30 PM</fullName>
            </value>
            <value>
                <fullName>02:00 PM</fullName>
            </value>
            <value>
                <fullName>02:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Followup_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Start_Date__c</fullName>
    <description>Follow up Start Date Portion Only</description>
    <label>Follow-up Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Followup_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Followup_Start_Time__c</fullName>
    <description>Followup Start Time Only</description>
    <label>Follow-up Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>01:00 AM</fullName>
            </value>
            <value>
                <fullName>01:30 AM</fullName>
            </value>
            <value>
                <fullName>02:00 AM</fullName>
            </value>
            <value>
                <fullName>02:30 AM</fullName>
            </value>
            <value>
                <fullName>03:00 AM</fullName>
            </value>
            <value>
                <fullName>03:30 AM</fullName>
            </value>
            <value>
                <fullName>04:00 AM</fullName>
            </value>
            <value>
                <fullName>04:30 AM</fullName>
            </value>
            <value>
                <fullName>05:00 AM</fullName>
            </value>
            <value>
                <fullName>05:30 AM</fullName>
            </value>
            <value>
                <fullName>06:00 AM</fullName>
            </value>
            <value>
                <fullName>06:30 AM</fullName>
            </value>
            <value>
                <fullName>07:00 AM</fullName>
            </value>
            <value>
                <fullName>07:30 AM</fullName>
            </value>
            <value>
                <fullName>08:00 AM</fullName>
                <default>true</default>
                <label>08:00 AM</label>
            </value>
            <value>
                <fullName>08:30 AM</fullName>
            </value>
            <value>
                <fullName>09:00 AM</fullName>
            </value>
            <value>
                <fullName>09:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>01:00 PM</fullName>
            </value>
            <value>
                <fullName>01:30 PM</fullName>
            </value>
            <value>
                <fullName>02:00 PM</fullName>
            </value>
            <value>
                <fullName>02:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/isFollowUp__c.field-meta.xml
<CustomField>
    <fullName>isFollowUp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To recognize the follow-up activity.</description>
    <label>Schedule Follow-up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Start Date Portion Only</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start Time Portion Only</description>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>01:00 AM</fullName>
            </value>
            <value>
                <fullName>01:30 AM</fullName>
            </value>
            <value>
                <fullName>02:00 AM</fullName>
            </value>
            <value>
                <fullName>02:30 AM</fullName>
            </value>
            <value>
                <fullName>03:00 AM</fullName>
            </value>
            <value>
                <fullName>03:30 AM</fullName>
            </value>
            <value>
                <fullName>04:00 AM</fullName>
            </value>
            <value>
                <fullName>04:30 AM</fullName>
            </value>
            <value>
                <fullName>05:00 AM</fullName>
            </value>
            <value>
                <fullName>05:30 AM</fullName>
            </value>
            <value>
                <fullName>06:00 AM</fullName>
            </value>
            <value>
                <fullName>06:30 AM</fullName>
            </value>
            <value>
                <fullName>07:00 AM</fullName>
            </value>
            <value>
                <fullName>07:30 AM</fullName>
            </value>
            <value>
                <fullName>08:00 AM</fullName>
                <default>true</default>
                <label>08:00 AM</label>
            </value>
            <value>
                <fullName>08:30 AM</fullName>
            </value>
            <value>
                <fullName>09:00 AM</fullName>
            </value>
            <value>
                <fullName>09:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>01:00 PM</fullName>
            </value>
            <value>
                <fullName>01:30 PM</fullName>
            </value>
            <value>
                <fullName>02:00 PM</fullName>
            </value>
            <value>
                <fullName>02:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External_Contact.recordType-meta.xml
<RecordType>
    <fullName>External_Contact</fullName>
    <active>true</active>
    <description>Use for contacts external to Houlihan Lokey.</description>
    <label>External Contact</label>
</RecordType>

force-app/main/default/classes/Test_HL_Activity.cls
@isTest
private class Test_HL_Activity {
    @isTest 
    private static void TestBasicFunctionality(){
        Contact contactRecord = HL_TestFactory.CreateContact(HL_TestFactory.ContactRecordType.External_Contact, false);
        contactRecord.FirstName = 'Test';
        contactRecord.LastName = 'Contact';
        insert contactRecord;
        List<Event> eventList = (List<Event>)HL_TestFactory.CreateSObjectList('Event', false, 2);
        for(Event eventRecord : eventList){
            eventRecord.StartDateTime = System.now();
            eventRecord.EndDateTime = eventRecord.StartDateTime;
            eventRecord.Start_Date__c = System.today();
            eventRecord.Start_Time__c = '12:00 AM';
            eventRecord.End_Date__c = System.today();
            eventRecord.End_Time__c = '12:00 AM';
            eventRecord.DurationInMinutes = 0;
            eventRecord.isFollowup__c = true;
            eventRecord.Followup_Start_Date__c = System.today();
            eventRecord.Followup_Start_Time__c = '12:00 AM';
            eventRecord.Followup_End_Date__c = System.today();
            eventRecord.Followup_End_Time__c = '12:00 AM';
            eventRecord.WhoId = contactRecord.Id;
        }        
        
        Test.startTest();
        
        HL_Activity activity = new HL_Activity();
        
        //Test Properties
        activity.LinkId = eventList[0].Id;
        activity.PrimaryAttendee = contactRecord.Name;
        activity.ModifyAccess = false;
        activity.ViewAccess = false;
        activity.PrimaryContact = contactRecord.Name;
        activity.PrimaryContactId = contactRecord.Id;
        
        //Test Other Class Methods
        activity.Activity = eventList[0];
        activity.Activity.ActivityDate = Date.today();
        String formattedStart = activity.FormattedStart;
        String formattedEnd = activity.FormattedEnd;
        
        //Verify the sort/compare is working
        HL_Activity activityToCompare = new HL_Activity();
        activityToCompare.Activity = activity.Activity;
        activityToCompare.Activity.ActivityDate = activity.Activity.ActivityDate.addDays(1);
        
        Test.stopTest();
        
        //Validate the Properties
        System.assertEquals(contactRecord.Name, activity.PrimaryAttendee);
        System.assertEquals(false, activity.ModifyAccess);
        System.assertEquals(contactRecord.Name, activity.PrimaryContact);
        System.assertEquals(contactRecord.Id, activity.PrimaryContactId);
        System.assertEquals(eventList[0].Id, activity.LinkId);
        System.assertEquals(-1, activity.compareTo(activityToCompare));
    }
}